### ISSUE TITLE
Crash, twice repeated across two weeks. Players timing out before this occured.

### ISSUE THREAD

**Issue by sudofox** [PaperMC/Paper#1003]
# Crash, Stacktrace

Happened last night. Wasn't sure how to be more specific with the title, apologies!

https://gist.github.com/sudofox/5edda6114be9cb3072a32c7285518218

Another happened a week or so ago with similar symptoms:

https://gist.github.com/sudofox/cfbf55f2ec6814f7cce6de129fbaee4f

### Plugin list:

dynmap

### Actions to reproduce (if known):

Unknown. It's a small server running on a VPS (just a few players), with 5000M RAM dedicated to it. It's running on a gigabit ethernet connection in a datacenter.

Did see some players timing out/disconnecting earlier, 'connection timed out.' I know that the internet connection is sound (you'll have to take my word on that one, but I do work at the datacenter it's running in)

Unsure if related, but the Mojang Multiplayer auth servers were having issues last night.

### Paper build number:
git-Paper-1310 (will update soon, unless you want me to try to reproduce something; I see it's a few revisions behind)

### Suggestions

If the server restarts itself with a start.sh or whatnot, don't push it to the background...no good way to access console if that happens.

Maybe dump RAM usage info upon crash so I can see if it ate all the memory or something?

**Comment by electronicboy** [comment]
Your server took too long to tick, if you're having connectivity issues to mojang, I guess that could be related with the skull changes recently, I don't recall what the connection limit is set to around there, but I would suggest keeping your eyes on timings.

"If the server restarts itself with a start.sh or whatnot, don't push it to the background..." - There is nothing we can do about that, the JVM process the server is running in needs to die, otherwise there is no promise that it's safe to start a new server. I don't recommend using the auto restart system, just make your startup script have a loop to restart the server when the process exits.

I also don't agree with dumping out memory information on exit, dumping raw information about memory rarely ever gives a picture as to what is going on and just creates false issues due to misunderstanding around how the JVM handles memory, if you think you're having memory issues, it really boils down to attaching the proper tooling so you can see what is actually going on.
