### ISSUE TITLE
Blocks bug

### ISSUE THREAD

**Issue by masterolos09** [PaperMC/Paper#1018]
Hello.
If the player puts blocks under himself on the autoclicker in the region (event.setCancelled(true)), the blocks under him do not disappe
They disappear on a regular spigot
Why?
Regards.

Version:
1.12.2

Timings:
https://timings.aikar.co/?id=e575d59b20394d21b784ff20fce211f8

The list of plugins is in timings

**Comment by zachbr** [comment]
Please provide some of the information we requested in the template that you deleted.
Version, plugins, timings, clear reproduction method, etc.

**Comment by electronicboy** [comment]
Issue resolved on IRC, Paper makes the packet limiter provided by spigot more configurable, and provides a default value which is more likely to actually trip due to spammy behavior,

`settings.incoming-packet-spam-threshold` can be used to configure this, setting the value to `30` (spigot value), as opposed to the default value of `300`, will make it less likely to trip and not handle the block placement (at the side-effect of it being easier to spam the server)
