### ISSUE TITLE
Server crashes when trying to get a players skull and the mojang servers are down?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1045]
Hi, I've been constantly crashing over the following issue:
https://pastebin.com/q1ub1Ywc

Paperspigot version: git-Paper-1349
ASkyBlock version:  3.0.8.2

I've approached the askyblock developer first and he has told me that he is using a standard bukkit call so this should not be happening so he forwarded me to you guys. Hopefully you have an idea on why this is happening. If you need more information let me know

**Comment by electronicboy** [comment]
His "standard bukkit call" also ends up doing a network request in order to properly fetch the skull texture in the event that it's not cached locally, which is a change done by spigot recently, which the reversal of would restore the broken behavior where setting a skulls owner would not appear to the client until they rejoin/reopen the inventory. To fix, he needs to handle these lookups by populating the inventory async, and then open it to the player once done.

**Comment by tastybento** [comment]
@electronicboy Do you know how can I populate the inventory with heads async? I.e., what method must I use to set a skull to a player's head? I'd genuinely like to know so I can do it.

**Comment by electronicboy** [comment]
You should just be able to create an inventory async and populate it, Spigot has the methods used for this to intentionally block, so an async task which:
- creates the inventory
- places skulls in the inventory (and sets their texture)
- posts back to the main thread to open it (or even, update another inventory)

In general, It really depends how you're handling this, but the only concern would be if mojangs server does go down and this is creating an inventory for players (and opening it once the skulls have been placed in there), it could take a while for it to ever open; If you have a single inventory which stores all of this and you just need to update it periodically, what I'd probably do is to have the main inventory, and then when I wanna update something, do above, and then replace the item in the main inventory.

It's far from ideal, I'm iffy with spigots change, but reverting it is a massive grey area for me (We'd restore the old broken behavior where an inventory might open with skulls missing textures, and as broken, imho, the new unannounced behavioral changes are, we're the ones who get the wrap if X plugin has issues on Paper but not on Spigot because of this), nor can I really see a clean way to expose the sync flag to plugins due to how meta is implemented in CB

**Comment by tastybento** [comment]
Okay, gotcha. My only concern was that the meta.setOwner(playerName) will trip the async catcher, but I just tried it and it doesn't. I already cache heads, so I'll just add an async task to grab them.

**Comment by aikar** [comment]
If your intent is for the skin texture to be static, you would be better off using direct skin textures for the heads btw.

As this avoids a network call, and is more reliable.

With the Paper API, you can do
```java

public static final ItemStack ARROW_UP = createHeadByTextures("Arrow Up", "a8a8e02f-30f7-4b54-ad11-f1fa8f7830ea", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWE4ZWY5MmVmYTE1NjY5ZGY0ODMzMmQxMThhMmY3MDU3NzJhMmEzZmNkMGZiODJhNjFmMjc3Yjg0OWEyYmQ2In19fQ==");

public static ItemStack createHeadByTextures(String name, String id, String textures) {
        ItemStack item = new ItemStack(Material.SKULL_ITEM, 1, (short) 3);
        SkullMeta itemMeta = (SkullMeta) item.getItemMeta();

        PlayerProfile profile = Bukkit.createProfile(UUID.fromString(id), Util.replace(name, Patterns.SPACE, ""));
        Set<ProfileProperty> properties = profile.getProperties();
        properties.add(new ProfileProperty("textures", textures));
        itemMeta.setPlayerProfile(profile);
        itemMeta.setDisplayName(name + " Head");
        item.setItemMeta(itemMeta);
        return item;
}
```

**Comment by tastybento** [comment]
@aikar Wouldn't I have to grab the head texture at some point from Moajng though? Is there a Spigot/Bukkit way of doing that yet? Or just Paper? I'm guessing not...

**Comment by MiniDigger** [comment]
@tastybento what I do is that I fetch skins via mineskin (she has a nice java client) and store them as json files which I ship with the plugin so that I can load the data I need on server start without needing to call mojang. 
generated skin files (I generate them via a ora template so that I can get 0-9A-Z without manual work, upload them to mineskin and save the data): https://github.com/VoxelGamesLib/assets/tree/master/src/main/resources/skulls/generated/skins
loading and applying: https://github.com/VoxelGamesLib/VoxelGamesLibv2/blob/master/VoxelGamesLib/src/main/java/com/voxelgameslib/voxelgameslib/texture/TextureHandler.java#L191-L214

**Comment by aikar** [comment]
@tastybento the payload in my example is the texture URL.

When used in this form, which you can get with the help from sites like this: https://freshcoal.com/maincollection.php

You're storing the payload of what mojangs response returns, so it doesn't even call ever.

This payload is sent to the client, which then the client requests the skin inside of that payload.
