### ISSUE TITLE
Nerf Spawner Mobs not working

### ISSUE THREAD

**Issue by TheTechnologyStudio** [PaperMC/Paper#1059]
### Description of issue:
Nerf-Spawner-Mob: true is not removing the ai from spawner based mobs

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://hastebin.com/oruqobulac.coffeescript - bukkit.yml
https://hastebin.com/edupamumur.coffeescript - Paper.yml
https://hastebin.com/hocoheroco.swift - Spigot.yml
https://hastebin.com/arivatimey.vbs - Server.properties

### Paper build number:
This server is running Paper version git-Paper-1370 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Works fine here.

Are they spawning in with AI or are they already existing in the world and moving about and you would just expect them not to be based on their proximity to the spawner?

Spigot does not write their nerfed status to the entity data. That means if you reboot the server or if the chunk unloads and they haven't despawned, when the are loaded back they will no longer be nerfed. That's just the design choice they made. I have wanted to change this but have not gotten around to it.

Please clarify what you're seeing so we can focus our attention more properly.

**Comment by TheTechnologyStudio** [comment]
they have ai when they spawn. its not even trying to remove the ai. It would be cool if you changed it your self and made a efficient non-spigot one built into the paper code.

**Comment by zachbr** [comment]
So are you actually not running any plugins or did you just not list them in the ticket?
What type of mob/s are you seeing this behavior in.

Because I cannot reproduce this issue.

**Comment by TheTechnologyStudio** [comment]
Mhh, I wonder if its related to plugins. The main ones are Essentials, EpicSpawners, FactionsUUID and MergedMob

**Comment by zachbr** [comment]
My guess would be that its EpicSpawners. I haven't used or looked at it, but if I had to hazard a guess I'd say it probably reimplements the spawning logic on its own end which means that spigot's nerf settings are never used.

Otherwise I suppose it could also be merged mob, but the performance improvements it offers may still outweigh those nerfed spawner mobs offers, depending on the specifics of your server and how its written.

Test without EpicSpawners, if it starts working then you have your culprit. Unfortunately if it is, I am not sure how we could get it working properly with it, and depending on what the plugin tries to do they may not want to support it at all.

**Comment by TheTechnologyStudio** [comment]
i've tested without epicspawners and nothing.

**Comment by electronicboy** [comment]
Have you tested without mergedmobs too, as already asked?

**Comment by electronicboy** [comment]
Closing due to lack of response
