### ISSUE TITLE
TP Command force crash server

### ISSUE THREAD

**Issue by Flavourized** [PaperMC/Paper#1060]
###  Timings or Profile link:

https://timings.aikar.co/?id=2e7caead6c404d919e4c90d017fb2640

### Description of issue:
Server crashes when typing the minecraft:tp command with some arguments

### Plugin list:
See timings.

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/sQhNp91W

### Paper build number:
Paper 1.11.2 b1104

### What behaviour is expected:
Expect server not to crash

### What behaviour is observed:
Server (& client) crashed

### Steps/models to reproduce:
Typing `/tp player 0 0 0` will teleport the player and then hang the server and then crash it. Replace `player` with your player name. 

### Link/paste of stack trace
Stack: https://pastebin.com/0xXkdzY6

**Comment by zachbr** [comment]
Cannot reproduce in 1.12.2

**Comment by electronicboy** [comment]
Nothing here indicates that paper caused the crash, in fact, there is no indication that any form of teleportation occurred beyond the excessive vel. warning caused by citizens. if this only happens on teleportation, I'd suggest either removing plugins in batches, or lowering the timeout value for watchdog in hopes that it might capture your issue.

**Comment by Flavourized** [comment]
The reason I posted it here was because I tried this on spigot 1.11 and there was no crash, then switched to paper and the crash existed. 

I'll do my tests again, but also note that this was 1.11.2

**Comment by zachbr** [comment]
We don't support 1.11.2. If there's a problem with it, you're stuck with it.
