### ISSUE TITLE
Component support in chat events

### ISSUE THREAD

**Issue by Snow-Pyon** [PaperMC/Paper#1097]
# Suggestion

Hey there, I came here to suggest something new for the chat events. It is _just_ adding JSON Component support to the chat event, specifically being able to use components in the setters for chat format and message; in addition to that, also being able to send a message component as the player (basically, a Player#chat method that accepts BaseComponent).

Now, I know this might be a rather troublesome task, and if I get enough time this month I will probably PR it myself but since I can't assure that, I'm putting this here hoping someone else takes it.

I'd also like to thank you all for making such good fork, I really appreciate the effort and time you guys put on this.

**Comment by electronicboy** [comment]
a chat method which accepts a BaseComponent doesn't really make sense as chat doesn't come in as json components, only as a string;

As for the event itself, that really isn't viable without adding additional events to fire after the normal bukkit events; Shamefully there is no way to expose base components in there without breaking how the event works

**Comment by electronicboy** [comment]
I'm feeling somewhat inclined to close this due to lack of commentary on it, having just had a look at the source for this, It would be doable (would require a rework of the existing handling of the chat events), but, the flow would likely have to be something along the lines of
- fire async chat event
- if there are any listeners, fire the sync chat event (and return this event via the waitable, as opposed to dealing with inside of there)
- String.format and convert to ChatComponents
- If there are any listeners on the new event, call them
- send the message

The only real concern is that I can't really see a sane way that would allow us to actually provide a way to manipulate these, bungeecords chat API really isn't designed to be friendly to work with for stuff like this, at least IMHO

The event would likely be something along the lines of
```
AsyncJsonChatEvent (Better name needed!)
- get/setMessage
- getFormat (?) - marginally redundant, but worth passing along still
- get/setChatComponents
```

**Comment by electronicboy** [comment]
Closing in favor of #1144 

We had a discussion on IRC, which basically mirrored a few concerns here and others that I had while looking into this,

Shamefully, while an event would be great for a few things, the chat component API doesn't really foster the ability to modify strings in a clean manner and it leaves many implementation concerns which would likely only cause further issues and hatred around how plugins handle chat.
