### ISSUE TITLE
Config option for endermen being hit with projectiles

### ISSUE THREAD

**Issue by UltraFaceguy** [PaperMC/Paper#1101]
As far as I can tell, there's no way to make endermen actually damageable by projectiles without delving into NMS. This proves to be a hassle on servers with class based systems or a focus on ranged combat. I think this would be a wonderful quality of life change to put into the general configuration, seems like something that would fit right in.

**Comment by aikar** [comment]
I think doing this as an event makes it more flexible, then you can just use a plugin to control it.

**Comment by UltraFaceguy** [comment]
A special event for enderman hit with projectile? It could work, but a config option would still allow you to control it via plugin, as in theory the config change would simply cause the entityDamagedByEntity event to work on endermen when projectiles are involved like other mobs

**Comment by scrayos** [comment]
I would also prefer an event, just for the sake of full flexibility and keeping the config clean. And it wouldn't really make sense to invoke the EntitiyDamageByEntity-Event for this case, as the arrow doesn't actually "damage" the enderman. And it's absolutely contradictory to call `event.setCancelled(true)` to let the arrow inflict damage to the enderman. For this kind of deviant behavior, a separate event would make the intent much clearer, because otherwise the `event.setCancelled()` method would become somewhat "magical", if you ask me.

**Comment by UltraFaceguy** [comment]
I think you have the opposite idea of what I'm pitching. The event.setCancelled() method in this case would... cancel the event and damage. The configuration option is to make the entity damage event work on endermen in the same way it works on other monsters. Currently endermen are immune to projectiles, but when this proposed configuration is true, the intended change is that projectiles would harm them and they are handled like every other entity in the entity damage event.

My idea is to bring in the option for them to work exactly the same as other monsters and make the entityDamageByEntity event LESS magical, as it currently isn't even fired when they take projectile hits.

**Comment by aikar** [comment]
an event lets you only conditionally do this. a plugin can then make it across the board implement your desired behavior.

a config forces it all or nothing. event gives choices.

**Comment by UltraFaceguy** [comment]
What I'm saying is that the exact same effect and more can also be done in this case with the config option, because you'd also be able to cancel the event normally under certain conditions. I agree with you on principle, but remain very fond of the config option is because it would be a setting to normalize the enderman's behavior to be in line with other monsters. In my mind, that makes more sense than a separate event, especially considering you'd still very easily be able to change the behavior.

That being said, I'd still be grateful for an event solution. I just remain unconvinced that it's the best way to go about it 😛

**Comment by electronicboy** [comment]
Normalizing behavior as it appears on the outside and as it's implemented on the inside are two entirely different ballgames

Enderman essentially override all of the existing damage logic to handle their teleportation, before they fall through to even calling the standard damage handling, thus making a config option to make the entity damage by entity event control teleportation is a bit of an icky one due to how this is implemented.

The event isn't called because the entity isn't damaged whatsoever in the event of an indirect attack, the entity teleports without even considering the fact that it was damaged.

While a config option is viable, it's somewhat limiting as in that call site area it would basically have to be a "disable or don't disable random teleportation", making it care about the existing event would be an unviable change. We'd also have to modify this area a little bit, as this is needed, it would make more sense to add an event, and then you could have a trivial plugin to cancel it in the desired state

**Comment by scrayos** [comment]
> My idea is to bring in the option for them to work exactly the same as other monsters and make the entityDamageByEntity event LESS magical, as it currently isn't even fired when they take projectile hits.

The problem here is: They aren't like the other mobs. I'd perfectly understand your point, if endermen would just ignore inflicted damage, and no event would be thrown, but the reason no event is thrown makes sense. They just teleport away. That's an additional behaviour that wouldn't be covered by the EntityDamageByEntityEvent.

That's what I meant with saying, that this makes the events behavior "magical". If you cancel the EntityDamageByEntityEvent for ALL OTHER entities, the damage just isn't inflicted. That's the only difference, in comparison to an event, that wasn't cancelled. But if you cancel the event for an enderman, the enderman would teleport himself away, and the arrow would continue to fly further. That's just a huge difference and destroys the thought behind this event.

And to continue about what I said first: It makes perfect sense, that the EntityDamageByEntityEvent isn't thrown for endermen, as - gameplay-wise - they teleport right before they would be hit by the arrow. I don't know how it is handled in the code, but I guess we should aim for the consistency, that someone who observes what happens ingame, would assume.

**Comment by UltraFaceguy** [comment]
Ah, I hadn't considered the random teleportation angle. Makes sense that the teleport would cause it to 'dodge' damage. 

I'm assuming then that the event would be a... EndermanTeleportEvent or something that lets you cancel based on cause, PROJECTILE, WATER, FIRE, NATURAL? Something like that would definitely work for my purposes.

**Comment by scrayos** [comment]
> I'm assuming then that the event would be a... EndermanTeleportEvent or something that lets you cancel based on cause, PROJECTILE, WATER, FIRE, NATURAL?

I didn't even think about cancelling the other teleportation-aspects of endermen. I think your proposed event is the best way to go about it. It's flexible, groups different cases together (all cases of endermen-teleportation) and offers enough functionality to actually be of some use and justify an own event. I second your proposal.

**Comment by aikar** [comment]
Added EndermanEscapeEvent, you can cancel this event where event.getReason() == Reason.INDIRECT

**Comment by aikar** [comment]
note that a lot of the above discussion was not really relevant for this.

The enderman trying to escape is different code than teleporting due to fire damage.

This event covers the cases of escapes, 
```java

    public enum Reason {
        /**
         * The enderman has stopped attacking and ran away
         */
        RUNAWAY,
        /**
         * The enderman has teleported away due to indirect damage (ranged)
         */
        INDIRECT,
        /**
         * The enderman has teleported away due to a critical hit
         */
        CRITICAL_HIT,
        /**
         * The enderman has teleported away due to the player staring at it during combat
         */
        STARE
    }
```

When the INDIRECT reason is cancelled, it will fall through and do damage like normal.

I'm not sure if there is a critical hit indirect damage, but if there was, you could then also trigger the 2nd reason, but the critical hit escape is AFTER damage is applied.

**Comment by aikar** [comment]
And incase you maybe want to cancel the automatic defensive escape for ranged, and make them teleport after the attack, I've added Enderman.teleportRandomly() in d38e9dc
