### ISSUE TITLE
Timeout due to look up profile properties

### ISSUE THREAD

**Issue by DardBrinza** [PaperMC/Paper#1115]
The server freeze, after which there was an error loading the profile and some players from server disconnecting.

Paper #1387
In server.properties and bungee: online-mode=false

Error:
https://pastebin.com/GnixETwR

**Comment by electronicboy** [comment]
Your issue appears to have been caused by a network issue, not an issue with paper.

**Comment by DardBrinza** [comment]
@electronicboy How do I turn off all these profile checks? I do not need them

**Comment by electronicboy** [comment]
You have a citizen with a skin on it, apparently.

**Comment by DardBrinza** [comment]
@electronicboy Oh, yes, it's true. Is there no solution? At me such freezes happen 1-2 times a week and drop on 50-80 players, as the freeze lasts 20-30 seconds.
P.S. I use OVH Game

**Comment by DardBrinza** [comment]
Maybe you can do throttling for profiles to prevent timeout problems?

**Comment by electronicboy** [comment]
Your issue was caused by a network issue, not the actual lookup of the skin; But you can attempt to disable these lookups by disabling `bungee-online-mode` inside paper.yml.

**Comment by DardBrinza** [comment]
@electronicboy Already `bungee-online-mode: false` in paper.yml
I think throttling of profiles should help even with a bad network: profile though will not loading, but server will not drop players.

**Comment by aikar** [comment]
@DardBrinza the issue is ultimately up to Citizens to fix.

They have a throttle they put in place, however due to how they wrote some of their code, it broke on a paper update.

They then put in a fix to make it work under paper, but it disabled the throttle system.

https://github.com/CitizensDev/Citizens2/commit/c767b6fdc3c9f20f95d1f170983e4f81bd16de0e

I will open a ticket with them on ideas to fix this.
