### ISSUE TITLE
Throttling for look up profile properties

### ISSUE THREAD

**Issue by DardBrinza** [PaperMC/Paper#1116]
Why has throttling not yet been done to obtain profiles from mojang? Sometimes profile may issue a delay and server freezes. I think this throttling would solve all the issues in users by getting a little warning about throttling in the console

**Comment by electronicboy** [comment]
You're completely misunderstanding what the cause of your previous issue is and the implication that intentionally blocking these types of lookups would have. Your issue is 100% down to your network, not an issue with the server software. You can remove these lookups from occuring by:
1) Using the option inside of paper.yml specifically intended to treat the server in offline mode behind bungeecord
2) Removing any plugin which triggers these types of profile lookups.

It's up to plugins to handle their profile lookups off the main thread, otherwise you break the behavior of the APIs these plugins are using.

**Comment by aikar** [comment]
@DardBrinza Resolved in https://github.com/PaperMC/Paper/commit/390f9bb913b9e4238c67f436f5fa0e9312b23131 - build 1416+
