### ISSUE TITLE
Are new patches to spigot automaticly added to newly compiled paperspigot?

### ISSUE THREAD

**Issue by Wqrld** [PaperMC/Paper#1121]
Are new patches to spigot automaticly added to newly compiled paperspigot?
Someone made a patch for me on the spigotmc repo but i want to use paper. Does it automaticly get added?
/
can you pull it now if it isn't?

**Comment by electronicboy** [comment]
If the change was actually commited to spigot then yes, it will be pulled once we do an upstream merge; I currently don't have the ability to due this as my internet is out, but somebody should be able to get to it soon

**Comment by Wqrld** [comment]
Okay, please do that when you have time.

**Comment by electronicboy** [comment]
There are no new commits against spigot since our last upstream merge, if you're trying to use custom patches which aren't actually inside of the official spigot repo, you'll need to add those manually and merge.
How you do that is up to you, however I'd suggest taking a look at something like https://fork.emc.gs/ on how to maintain patches on top of paper, if the spigot fork that has your patches in is going to track the official repo (i.e. it will actually be updated when spigot updates), you could also check out paper and set the upstream spigot repo to that of the fork you're using, you will however be responsible for applying the paper patches on top of that.

**Comment by Wqrld** [comment]
Okay thanks.
