### ISSUE TITLE
disable-teleportation-suffocation-check: true does not cover all teleportation cases

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#1149]
### What behaviour is expected:
`disable-teleportation-suffocation-check: true` should disable all of CB's attempts to teleport the player to a safe location on teleport.

### What behaviour is observed:
As mentioned in #1148, having this setting set to true still does not prevent CB from attempting to safely teleport the player to a safe location upon a nether portal teleport. Additionally, the events do not indicate this "safety teleport," as they continue to show the original location.

### Steps/models to reproduce:
See https://bugs.mojang.com/browse/MC-121098

### Plugin list:
EventDebug

### Paper build number:
1434, 1451

**Comment by BillyGalbreath** [comment]
Did this just start happening recently? If so, I believe the root cause is [this Spigot fix](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/29705a0d4f65440b4d91cba67d63bbac884a833e) for teleporting into the ground when going through portals. I can add the Paper option there, but then it would simply toggle between teleporting into the ground (like in [this case](https://hub.spigotmc.org/jira/browse/SPIGOT-3864)) or teleporting into the nether roof (as in the case here).

Seems the root cause would be unrelated to `disable-teleportation-suffocation-check` and to fix [MC-121098](https://bugs.mojang.com/browse/MC-121098) in `PortalTravelAgent#adjustExit()`'s `ShapeDetector` logic (which is beyond me, tbh).

**Comment by RoboMWM** [comment]
I haven't had issues with people teleporting into The End spawn which is what that spigot ticket seems to be about. Either way, that means CB added a new suffocation check which this config needs to disable.

**Comment by zachbr** [comment]
See commit message

Present in builds 1462+
