### ISSUE TITLE
Menu plug-in lag

### ISSUE THREAD

**Issue by shuiqing2046** [PaperMC/Paper#1164]
I encountered some problems. The game menu plugin opened to delay.（Seriously affect the gaming experience）
The old game version does not contain this error. The plug-in is the latest version, and the normal version is  #1230

Test plug-in：

【ChestCommands 3.1.4.jar】
https://dev.bukkit.org/projects/chest-commands

【DeluxeMenus-1.10.5.jar】
https://www.spigotmc.org/resources/deluxemenus.11734/

Erroneous version（tested）
PaperSpigot 1.12.2（#1300~#1466）

NORMAL VERSION（tested）
PaperSpigot 1.12.2（#1230）

Sorry, my English is not very good (all from Google translation).
![img 20180621160004](https://i.loli.net/2018/06/21/5b2b60d283258.png)
![img 20180621161338](https://user-images.githubusercontent.com/28628358/41706749-242d2862-756f-11e8-9c11-15efc645e6f6.png)

**Comment by electronicboy** [comment]
Spigot modified the server so that skull textures being applied to items are handled sync (i.e. blocking the thread that made the request), as opposed to attempting to perform the lookup async and generally failing to display them properly when an inventory is opened containing them the first time.

Ultimately, it's up to plugins to fix this by caching skulls beforehand.
