### ISSUE TITLE
Entity Addition/Removal Issues

### ISSUE THREAD

**Issue by linsaftw** [PaperMC/Paper#1199]
### What behaviour is expected:
Creating a NPC.

### What behaviour is observed:
The NPC doesnt appear, but the message that you created it appears, no errors.

### Steps/models to reproduce:
1. Do /npc create (Name).
2. Watch the npc not appearing.

### Plugin list:
Provided later - Cant provide rn, mostly the same as old versions that worked fine.

### Paper build number:
1489

### Anything else:
Everything is just broken in latest updates from 1460+ there are lagspikes and entities are bugged (Most of entities are fixed now but there seems to be hard lagspikes and problems with citizens) I dont have the timings anymore, but when i read them everything was red with high usage, the one with most usage was the chunk loading. (Now testing 1490 to check if it is fixed)

**Comment by aikar** [comment]
please let me know of any differences with 1490, as it was meant to fix entity issues (see #1197)

**Comment by aikar** [comment]
if issues still occur, please try 1481

**Comment by linsaftw** [comment]
Citizens seems not fixed in #1490. But entities are working ok.

Tomorrow im going to try #1481.

**Comment by aikar** [comment]
please try 1491, another change reverted.

**Comment by LogGits** [comment]
After testing 1491, all mobs with nametags set, vanished. (except for skeleton horse).

Player reported: Named Horses, villagers, iron golem and llamas vanishing.

Reverting back doesn't replace the mobs.

EDIT: Apparently even unnamed horses and llamas vanished.

**Comment by linsaftw** [comment]
Still not working in latest.

**Comment by electronicboy** [comment]
Just created an NPC without any issues, logged off and waited for chunks to unload, logged back in and it was still there

```
[09:55:51 INFO]: This server is running Paper version git-Paper-"7bb3f45c" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[09:55:51 INFO]: Previous version: git-Paper-"17525cd5" (MC: 1.12.2)
[09:55:51 INFO]: You are running the latest version
```

**Comment by linsaftw** [comment]
(ArenaPvP)

Plugins (47): AAC, AACAdditionPro, AD-NR, AnimatedNames, AntiPearlGlitch, ArrowRemover, AutoRestart, BlockDecay, CancelSounds, ChatGuard, Citizens, ClearAll, CombatLogX, CommandNPC, DeluxeMenus, DisableJoinMessage, EPearlCooldown, Essentials, EssentialsChat, EssentialsMysqlStorage, FastAsyncWorldEdit, FastPot, HCTeamsFreeze, HolographicDisplays, KillCommands, LeaderHeads, LiteBans, LuckPerms, MicroJump, MultiWorld, OldCombatMechanics, PlaceholderAPI, ProtocolLib, ProtocolSupportPotions, qClear, SmoothKnockback, Sopas, StrikePractice, TitleManager, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags

[08:30:21 INFO]: This server is running Paper version git-Paper-1492 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[08:30:21 INFO]: Previous version: git-Paper-1490 (MC: 1.12.2)
[08:30:21 INFO]: Checking version, please wait...
[08:30:22 INFO]: You are running the latest version

Creating a NPC doesnt spawn anything, and the plugin StrikePractice has a pvpbot feature, that isnt spawning anything too.

Btw in arenapvp npcs spawn in X world, but doesnt in Y world. in HCF they doesnt spawn anywhere.

This started happening right after updating paper to the "entity tweaks" version. (So its not a plugin)

**Comment by electronicboy** [comment]
Can you please replicate without plugins, even if it was after our changes, it could be an issue caused with how plugins interact with the server, especially as I couldn't replicate the issue myself without plugins

**Comment by linsaftw** [comment]
Hmmm without plugins it works, but with the plugins i use normally it worked good before. and after the newest update of paper it stopped working.

**Comment by LogGits** [comment]
Is this related to my issue aswell? I went back 1468 because I don't want any other players to have their mobs vanish. Players have been reporting disappearing villagers for a while now and I am assuming its also related to something this updated planned to resolve. 

The mobs that were reported to vanish in update 1491:
- All horses (some named, some tamed)
- Some skeleton horses (some named, tamed)
- Irongolem (named) 
- Villagers (some named)
- Llamas(unnamed, tamed)

There was no word on wolves but I'm sure some also vanished.

**Comment by aikar** [comment]
under what conditions causes them to vanish? players spawned, then what did you do to make then vanish? what plugin addition specifically causes it, just citizens?

**Comment by LogGits** [comment]
Im not sure what causes it, it was just the update to 1491. A player logged in to an unloaded chunk and reported a majority of their mobs missing. I tried to reproduce this on my local machine and have been unsuccessful on version 1491 and 1492 oddly enough.

Only thing in common with the other user is: AAC, Citizens, CommandNPC, DeluxeMenus, Essentials, FastAsyncWorldEdit, HolographicDisplays, LeaderHeads, LiteBans, LuckPerms, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

But wouldn't this be a paper issue, considering it was caused by updating paperspigot to 1491?

**Comment by Drc-DEV** [comment]
Confirmed not to work even with the build 1492. Plugins: Essentials AAC WorldEdit WorldGuard Citizens LuckPerms ProtocolLib

**Comment by electronicboy** [comment]
@DracarysPro plugin list?

Ideally, it would be great if somebody would be able to start pulling plugins one by one until it stops (and I don't have access to one or two plugins which are a reoccurrence), be it an issue with paper or not, some plugin is likely doing something which is causing the server to remove entities from a chunk when it shouldn't, going over the code, I can only see one potential explanation, but I cannot see how this would be possible within the server (outside the realms of some plugin doing something it /really/ shouldn't be doing)

**Comment by aikar** [comment]
its important to note the entity loss would of occurred on the PREVIOUS server running.

So if you were on 1489, then switched to 1491 and saw missing, doesn't mean it was 1491 that caused it, it was likely 1489 that caused it.

what we are looking for is NEW cases of while running on 1491, if new stuff disappears.

To add my own notes, I've been having issues with my holograms disappearing in spawn chunks, that was caused by these issues. So that is something we can ensure to test, is relation to spawn chunks.

I just updated to 1492 last night, so we will see (btw 1492 offers nothing for this issue over 1491)

**Comment by linsaftw** [comment]
Hi, i dont have internet to do testing, but im suspecting of CombatLogX having something to do with this issue. Or maybe is another plugin , i cant really confirm. Maybe it is AAC tho cuz i use it too.

**Comment by Drc-DEV** [comment]
Using build 1492, creating a npc works. The problem is that already created NPCs despawn randomly and reappear after a certain amount of time. You can reproduce this behaviour only with 70-80+ NPCs in my opinion. Everything else seems to work fine, nobody has complained about entities with a custom name despawning yet.

**Comment by aikar** [comment]
err didn't want github to close this until we get confirmation its fixed. Please try 1494 as I now have new fixes in place.

**Comment by linsaftw** [comment]
I've just tested and its fixed, Thanks a lot for the support guys :)

**Comment by amadeusmz** [comment]
I also have entity vanishing issue, fixed it by setting entity tracking range to lower than world's view distance * 4

**Comment by aikar** [comment]
build 1499 includes another fix for entities that go inactive unintendedly

**Comment by aikar** [comment]
at this point issues really should be resolved, so would love feedback confirming it from multiple users so we can mark this closed.

**Comment by aikar** [comment]
and thank you for bearing with us ironing out this new change so we were able to keep it w/o just giving up on it (I was close to just throwing in the towel :()

**Comment by LogGits** [comment]
Hey sorry for the late response I didnt see the email about this. I haven't been able to test build 1499, I will do some testing in the morning and report the results back here 👍

**Comment by Drc-DEV** [comment]
Build 1499 solved the problem for me

**Comment by LogGits** [comment]
@aikar Thanks so much, it seems to have resolved my issue with entities vanishing. If I get any reports about vanishing mobs, I'll make a new issue.

**Comment by zachbr** [comment]
Closing as fixed, thanks for all the reports and interaction on this one. All of us (mostly Aikar since he took point on it) appreciate it!

Edit: Build 1499+ for those who missed it above.

**Comment by aikar** [comment]
Fixed in build 1500. Finally found the source of this final detail while doing the 1.13 update.

**Comment by aikar** [comment]
Some of the issues we were tracking down in this issue was legitly fixed, but one bug causing entity loss is still occuring. Opened as issue #1223 - please subscribe to that issue.
