### ISSUE TITLE
1.13: Readd Generator Settings

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1228]
Removed due to complexity of generation changes
Looking for assistance re-adding

removed/0033-Generator-Settings.patch

**Comment by OtakuMegane** [comment]
Since I've had to root around in the generator code to update my own stuff I've come across most of the things in the generator settings patch so I can at least explain where to look.

 - All (or very near all) decorators and structures are now initialized in the biome classes. Each one is a (long) method call that references individual components to make a composite generator.
 - The floor and ceiling bedrock is still in `ChunkProviderHell.java` in the method: 
`protected void a(IChunkAccess ichunkaccess, Random random)`
 - The emerald ore and monster egg (infested block) generators are still referenced in `BigHillsBiome.java`

Don't know about the Mesa gold but I'd guess it also is done in the classes for those biomes.

**Comment by aikar** [comment]
This would be easiest to reimplement in DefinedStructure.generate, at the top there is a if (!this.a(access) { return false; }

This a(access) method checks "are features enabled for this world" as a "global" flag for ALL features.

We can above this, do if (this instance of EndCity && !generatorSettings.endCity) { return false; } to keep the patch simple
or else add individual checks in every classes override of the a(access) method

**Comment by Fejm** [comment]
What about biome size? Where to look?

**Comment by zachbr** [comment]
Thinking on this, the old system basically just added an extra check to the vanilla world generation code.

So what we ended up with was ``worldSettings.genCaves && world.paperConfig.genCaves``.

Would it be better to instead just use paper's settings to write the default world settings where applicable? It would likely reduce the maintenance burden of the patch going forward. Negative being it would make it harder to change these settings on the fly (unless we also added support for that) but I'm not sure if anyone ever changes these settings for one world.

**Comment by aikar** [comment]
@zachbr last i looked vanilla did not go as granular as us, it was "gen features or not", but not a per-feature type boolean.

so our patch still has value.

**Comment by aikar** [comment]
I think the new version of the patch will also be easier to maintain as it can be done all in one place, unless mojang rewrites worldgen stuff again....

**Comment by baticag** [comment]
Any news about this? Or alternative how it can be done?

**Comment by Proximyst** [comment]
This is no longer necessary with the fact you can override vanilla biomes with data packs as of 1.16.1. For *new* biomes, refer to https://hub.spigotmc.org/jira/browse/SPIGOT-6073 / #4128.
