### ISSUE TITLE
Equality checks between skull items with owners in inventories are incorrect

### ISSUE THREAD

**Issue by stefvanschie** [PaperMC/Paper#1293]
I have an inventory with a skull item in it which has a custom skull owner. When I add an event listener for detecting click events inside this inventory I want to be able to check to see if the clicked item is equal to the item I set in the inventory. However this check will never yield positive results, making it so it's impossible to check between these items.

Here is a small piece of demonstration code I used to test this behavior: https://hastebin.com/kunukugowo.java

I realize that I am using the `setOwner` which is deprecated, however the same issue persists when using the newly introduced method as well.

I'm running git-Paper-1523 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT).

**Comment by electronicboy** [comment]
ItemStack has a method called ensureServerConversions which is designed to deal with the issue you're hitting here, ultimately the snag here is that setOwner doesn't complete the profile on the skull and so the equality check ends up failing

**Comment by stefvanschie** [comment]
I tried calling ensureServerConversions on the item in multiple different spots (after initialization of the item, after putting it in the inventory, after opening the inventory and inside the event listener), but neither one of those calls gave the desired result (e.g. printing "Hi!" in the console).

**Comment by aikar** [comment]
I'm pretty sure your issue is that your obtaining new profiles, which is overall a fundamental flaw with them...

This is a Vanilla level issue, because if you get 2 skulls from 2 different times, they actually have different texture payloads.

These texture payloads contain a timestamp... So using the Mojang API will be difficult to fix this.

See my code here: https://gist.github.com/aikar/9bdf75a3318c1a90bcf43f636049a29d#file-profilelistener-java-L128 
Though I think those profile events are unique to my fork. But i'm not sure this kind of logic belongs in Paper itself....

Your going to need to manipulate the stacks like this to make comparison work. There's nothing much paper can do here to fix that.

**Comment by aikar** [comment]
note using the paper player profile API with static profiles is the recommended approach.
