### ISSUE TITLE
Deep, seemingly undiagnosable performance problems with processQueue

### ISSUE THREAD

**Issue by 501warhead** [PaperMC/Paper#1298]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
Detailed timings before server update:
https://timings.aikar.co/?id=3724079186fb4d538a8a24985194664a
Updated server to 1542, issues have persisted:
https://timings.aikar.co/?id=9cce44a621354b2d92dc6bef4c0d9e23
Upon downgrading to 1430 such problems have not persisted (so far, small sample size):
https://timings.aikar.co/?id=b9d103b3b5354a2997b2ff7480bf49be

### Description of issue:
___If applicable___
Single, unfragmented server of about 140-160 individuals continuously has massive spikes of lag attributed to heavy GC dumps. It's been difficult/impossible to diagnose why it's been stalling out as the timings reports are, from what I can gather, incredibly vague pointing to processQueue, yet processQueue does not report any issues worth note. I am uncertain if I'm reading this wrong, but debugging this has been a nightmare since we run a host of private plugins and finding an issue is a needle in a haystack.

This does not seem to be occurring (as stated) in the 1430 paper build, while such is very old and a lot has changed we're pulling our hair out currently trying to find the source and largely failing.

### Plugin list:
___All plugins running on the server___
Plugins (69): AdvertLog, ArcheCore, AtlasModule, Bard, BetterBooks, BetterTeams, BlocksHub, BossBarAPI, CraftBook, CustomItem, DependencyLoader, DisableJoinMessage, DisguiseCraft, Essentials, EssentialsGeoIP, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit, Fishing, HawkEye, HeadShop, Hookah, HuntLite, InvDez, InventorySearch, iSign, Knockout-Plus, KowaCore, LibsDisguises, LimitedCreative, Lores, LuckPerms, LWC, MinecraftTents, MineWorldGen, MorePlayerModels2, Multiverse-Core, MyPet, Native_Farming, NBTEditor, NoDeathMessage, NoteBlockAPI, Obelisk, PacketWrapper, PlugMan, Polling, ProtocolLib, Refund, ReportRTS, RoadRunSpeed, ShowAndSell, SkeletonHorseNoMore, SkeletonKey, Soulstone, Spit, TabListAPI, TerritoryPartner, TheVoid, TofuCore, TownCandy, TransferVault, Vault, Votifier, VoxelSniper, WarCore, Watcher, WorldEdit, WorldGuard, WorldGuardExtraFlags

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
server.properties
https://hastebin.com/hutuyerumu.ini
bukkit.yml
https://hastebin.com/ivoxoqaduy.coffeescript
spigot.yml
https://hastebin.com/nuqixipewe.coffeescript
paper.yml
https://hastebin.com/woreyafaso.coffeescript

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___
N/A

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
for the majority of this issue: 1514
After update: 1524

Problems persisted in both versions. We downgraded paper to 1430 and the performance issue seems to be gone, but it will require time to see.

**Comment by aikar** [comment]
Well the fun detail about processQueue is that its used by many things...
This is how things that need to "return to main" get processed.

Current things that do this:
async skull lookups such as loading old heads AFTER the heavy stuff is done (unlikely...) 
synchronous chat events, so if the sync chat event had anything done, it would run on main here, but this should show up as sub timings which its not
asynchronously dispatched commands, that paper forces to main, but this has been there for years and would be spamming your log with errors
kicks for illegal chat characters (def not it)
synchronous tab completions (not changed since mentioned build)
Sync player login events, should be sub timing though
timings report done over rcon

None of these things really scream could cause lag, so it is suspicious...
So I am curious what is going on here, but best we could do is add subtimings directly.

If you can get a profiler report during it, that would be helpful.
I am thinking it may be placebo that older builds don't do it, as nothing since 1430 has touched anything with that queue...

So I would suggest keeping up to date, and if you can get more data for us, will try to see if it's something to fix on papers end.

**Comment by 501warhead** [comment]
https://timings.aikar.co/?id=2ea40024829b4b128173c966d0ec412d

As you suspected it was a red herring, the issue is still persisting albeit with much less frequency. We've tried reducing the allocation of RAM to the server (before the testing it was 32GB, we lowered to 24GB) because we had noted the GC likes to be a little silly with excessive memory, it aided but did not resolve the issue either. 

We'll try updating again and seeing if the frequency gets worse or not.

Additional spike: https://timings.aikar.co/?id=f1aab06b35674848b4e152ffdde84f5e

**Comment by aikar** [comment]
It is likely GC as the cause, you have an insane amount of memory.

Try reducing to 16GB, also add this flag: XX:+ParallelRefProcEnabled (this was recently added to my flag research post).

I'm going to close as its not an issue on paper. Please join us on discord for anything new.
