### ISSUE TITLE
Debug Stick Broken

### ISSUE THREAD

**Issue by Zelereth** [PaperMC/Paper#1306]
### What behaviour is expected:
Debug stick should rotate blocks, change water logged states, and several other features. It should also output text above the hotbar when in use.

### What behaviour is observed:
The stick does literally nothing. It acts like the player is left-clicking with a sword in creative (won't break blocks) and does not output any text or rotate blocks. 

### Steps/models to reproduce:
1. Load multiverse at least once. Even after removal the bug persists.
2. /minecraft:give @s minecraft:debug_stick
3. Attempt to use the debug stick.
### Plugin list:
Multiverse

### Paper build number:
1.13 Paper-93

### Anything else:
The debug stick functions as expected in spigot if that helps at all.

**Comment by aikar** [comment]
I cannot reproduce even with multiverse. 
[Multiverse-Core] Version 2.5-b719 (API v20)

If it's an issue with the newer version, please consult with Multiverse.

**Comment by aikar** [comment]
Closing as unable to reproduce and haven't heard anything new. If you find any more information on how to reproduce, please let us know.

**Comment by aikar** [comment]
Also as another person had weird issues, if you are using Bungee, ensure it is up to date.

**Comment by WHiZSTA** [comment]
Just a quick info for anyone who has a similar issue. I too had the issue but it wasn't due to paper or multiverse (current version), it had to do with essentials not having the debugstick.. to correct you have to "  /minecraft:give yourname minecraft:debug_stick 1  "  to make sure you reference the minecraft item, otherwise, the game will report no such item.
