### ISSUE TITLE
Mobs decreased at night

### ISSUE THREAD

**Issue by SuperSaiyanPan** [PaperMC/Paper#1321]
### What behaviour is expected:
Normal mobs. At my area during the night it's usually filled with mobs. Easily 6-10.

### What behaviour is observed:
Extremely decreased mobs to the point of almost none spawning. Maybe 0-3.

### Steps/models to reproduce:
I upgraded my MC Server to paperclip.

### Plugin list:
CoreProtect 2.15.1
BukkitCompat R22A

### Paper build number:
This server is running Paper version git-Paper-112 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Anything else:
My server is 1.13 Vanilla and literally all I did was remove minecraft_server.jar and replace with Paperclip then the mobs drastically decreased.

**Comment by electronicboy** [comment]
By default, spigot has decreased the default spawn radius in spigot.yml
from 8 to 4, for closer to vanilla spawns, I'd suggest reverting that change

**Comment by SuperSaiyanPan** [comment]
Well I am pretty new to hosting a server but I am learning fast. How do I go about editing a .yml file type? Can I open it in notepad?

EDIT: it shows | mob-spawn-range: 6

I will up it to 8 and report back.

**Comment by SuperSaiyanPan** [comment]
It is at 8 and the spawn rate is still really low.

**Comment by aikar** [comment]
I did some testing today, and verified that with a view-distance of 8+ and a mob-spawn range of 8+, the world limit is as desired.

If you lower the mob spawn range, packing the same amount of mobs would lead to high density, so that's why the formula works the way it does.

This is all a numbers balancing game. Tweak your mob-spawn-range for density control, and bukkit.yml mob-spawn limits for volume control.

We have a PR active to redesign the engine to solve other issues with mob spawning to be a better implementation than vanilla, but as it stands I can't see a flaw in paper's spawning compared to vanilla, the numbers line up.

I updated our default to ensure it uses 8+ mob spawn range.

Note spigot does cap upper bounds of mob spawn range to your view distance, so if your view distance is less than 8, you will get less than your mob spawn limit # per player.

If you need any more assistance in configuration, please ask on Discord.
