### ISSUE TITLE
PlayerInventory.removeItem() does not work with things in the OffHand

### ISSUE THREAD

**Issue by Cryptite** [PaperMC/Paper#1360]
### Paper build number:
git-Paper-"ce750d7" (MC: 1.12.2)

Pretty simple. Put a stack of 5 dirt in your OH, run `player.getInventory().removeItem(new ItemStack(Material.DIRT, 5));`

Observe nothingness.

**Comment by BillyGalbreath** [comment]
Does this happen with armor slots as well?

**Comment by zachbr** [comment]
Is this bug also present upstream?

**Comment by Mystiflow** [comment]
@Billy_Galbreath I believe this method is only intended for the main container.

What could be a good idea is a new method ```removeItem(ItemStack, EquipmentSlot[])```

**Comment by LuminousLoreBloom** [comment]
@BillyGalbreath I believe this method is only intended for the main container.

What could be a good idea is a new method ```removeItem(ItemStack, EquipmentSlot[])```

**Comment by Cryptite** [comment]
It does not work on items in your armor slots either, so maybe it sounds like main container storage only. The OH just seems more like your MH than it does another armor slot.

Perhaps a `removeItem(ItemStack, boolean all` that would work on any slot in your inventory?

**Comment by zachbr** [comment]
This is pretty easy to add.
Unfortunately it isn't actually `Inventory#removeItem(ItemStack)`. It's actually `Inventory#removeItem(ItemStack...)` varargs.

So while I can just slap a boolean flag on it, it _has_ to go on the front which I personally think is a terrible place for a flag.
I have an `Inventory#removeItem(boolean, ItemStack...)` written, if that seems tolerable I'll push it, just not thrilled with that. because well I already said...

Maybe instead we just call it something else? Dunno!

**Comment by BillyGalbreath** [comment]
I started working on this but stopped. I was just going to simply override the method, then half way through I realized the way I was doing it would add items to armor slots if they had a full inventory. Easy fix (I think) I just got side tracked

**Comment by zachbr** [comment]
Implemented as a new API so as to not break plugins that may be reliant on _not_ searching the non-storage slots.

`Inventory#removeItemAnySlot(ItemStack...)`

Who knows, maybe in the future the normal API will do the right thing and we can just deprecate this one, but this is a change that could cause obscure discrepancies for plugins expecting the standard CB behavior.

Present in 1.13.1 builds 145+
