### ISSUE TITLE
Entitys lagg [Spigot optimization bug]

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#137]
https://hub.spigotmc.org/jira/browse/SPIGOT-2045

**Comment by Ichbinjoe** [comment]
That issue has nothing specific to really work off of. As the commenters of that issue mentioned,
1. A timings report isn't very descriptive of the actual issue
2. Optimization takes time

If you could get a Java profile that would be great, because at the moment the timings tell us pretty much nothing.

**Comment by zachbr** [comment]
This issue is extremely vague. Yes entities are slower than 1.8, yes they will eventually get better as time goes on. These are common facts of life when it comes to MC updates.
