### ISSUE TITLE
1.13: Anti-xray performance (frame rate)

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1376]
###  Timings or Profile link:
https://timings.aikar.co/?id=481b48cc4bf242eea60d63572ace1ae8

### Description of issue:
Anti-xray enabled with engine mode 2. Frame rate drops considerably when mining.

Disabling anti-xray instantly results in improved frame rates while mining.

### Plugin list:
https://i.imgur.com/iGV4Tpj.png

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Paper build number:
Paper 1.13 build 173 https://destroystokyo.com/ci/view/PaperMC/job/Paper-1.13/173/

**Comment by VADemon** [comment]
I have a very old PC at hand, so I will comment:
P4 3GHz, 2GB RAM, GTS 220 2GB DDR3 GPU

The renderer of Minecraft has become very good, it can sustain 30-45 FPS.
However, chunk/block updates have become much more taxing than in beta, causing a ~1s freeze.

Since AntiXray naturally causes very many block updates, I don't think there's a way around it.
Please test it on 1.12.2 if it causes any FPS drops there, otherwise tune your antixray config.

engine-mode back to 1, so there're potentially less blocks to update
and experimentally 
anti-xray.update-radius=1 (test it yourself if it works correctly). It used to not hide diagonal ores a very very long time ago.

**Comment by prplz** [comment]
This is really just a 1.13 client problem imo. I get really terrible lag when water is spreading for example, even with a decent machine.

**Comment by Puremin0rez** [comment]
^ Same. I'm on an i7-4790k w/ 1080 TI and my performance on 1.13 is abysmal (comparatively), significantly worse then 1.12.

**Comment by aikar** [comment]
took out quote of my comment as its not related to what you are reporting, and Z actually resolved my comment when he merged it. but that only impacted server performance, not client.

**Comment by stonar96** [comment]
Sorry, there is nothing I can do against it. But you can try to reduce the blocks in the hidden-blocks list and set update-radius to 1. Both option also improve the server performance.

**Comment by MatrixTunnel** [comment]
1.13.1 helped fix some of the water spreading lag. Hopefully that helps in this case as well

**Comment by NullCase** [comment]
Update-radius to 1 improves performance by roughly 1/2. (35 frames instead of 15).

Console side, OK. it sounds like 1.13.1 will improve some things in time.

Optifine will probably solve a lot of console problems as well. Gotta love optifine.

OK, @stonar96 Thanks for this update. I'm sending you payment now.

**Comment by NullCase** [comment]
Frames improved twice again in the 1.13.1 version. https://destroystokyo.com/ci/view/PaperMC/job/Paper-1.13/176/

**Comment by aikar** [comment]
there's nothing much that can be done by framerate anyways by paper.
youll have to compromise between xray settings vs begging mojang to fix.
