### ISSUE TITLE
Extreme mob spawn counts

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#138]
Guardian Farms are fucked... I Went to a players Guardian Farm, I Nearly crashed. They crashed and the server tps was at 5 and dropping. 

**The Guardian Farm had over 250 Guardian's in there and just kept spawning...**

How to make this bug, Build a Guardian Farm or just go to a Guardian temple, My server was running 100% fine on spigot, I Updated to Paper today because i was told it will improve my server.... -_-

Proof:

Guardian Farm: https://i.gyazo.com/dbd0c31d7aa4e9d81c127d6f2b0be402.png

TPS: https://i.gyazo.com/c0c948b6d424d9df9cd2da52e89a2fcc.png

**Update: (This is for all spawns, Not just Guardians)**

**Comment by jordanwilliams1** [comment]
Bukkit.yml: http://pastebin.com/J4xFskvw
Spigot.yml: http://pastebin.com/miLMcurL
Paper.yml: http://pastebin.com/VrZ1WFRM

Another screenshot, Tps now 1 :) 
https://i.gyazo.com/592873ec16eeaecb34185cab715b88f3.jpg

**Comment by jordanwilliams1** [comment]
Running latest version of paper ^^

**Comment by andris155** [comment]
Use ClearLag chunk-entity-limiter.

**Comment by jordanwilliams1** [comment]
That's not going to help, Spawns everywhere are fucked, I'm not using paper till this is fixed.... And I do have a chunk entity limiter of 150.. There was over 900 mobs there at one point

**Comment by zachbr** [comment]
I still can't reproduce this despite getting a growing number of reports on it :(

**Comment by UnfixableExploit** [comment]
why not disable Guardian Farms until it can be reproduced or test new builds every week or something on a local - test server to see if its fixed :dancer:  :dancers: :8ball:

**Comment by zachbr** [comment]
Reformatting as general entity spawn issue, as that's the report I keep getting. I don't believe this issue is specific to Guardians.

**Comment by zachbr** [comment]
From GH-150:

"Bukkit: http://pastebin.com/bJATVP17
Spigot: http://pastebin.com/Xy4wumJE
Paper: http://pastebin.com/gt6TLDe6
Timings: http://timings.aikar.co/v2/?id=0337f2b500694c64ad1e8baf5bd9278c
Plugins (49): MobEggSpawnerBlocker, PlugMan, NametagEdit, MineMarket-Universal, ChatColor, AsyncWorldEditInjector, CoreProtect, Deadbolt, SkinsModule, LimitCreative, CreativeNbtControl, ClearLag, ChatControl, Chairs, ProtocolLib, NoCheatPlus, LibsDisguises, AsyncWorldEdit, IPWhitelist, OldGoldSurvival, RedstoneClockDetector, PermissionsEx, Vault, FamoustLottery, FwdMsgChanger, MyCommand, PlayerHeads, WorldEdit, Essentials, PlotMe, Jobs, Auctions, Multiverse-Core, TreasureChest, EssentialsChat, MobArena, WorldGuard, EssentialsGeoIP, LimitedCreative, EssentialsSpawn, PvPManager, RedstoneClockPreventer, TitleManager, iZone, AreaShop, SurvivalGames, CraftBook, ChestShop, MyPet"

**Comment by frash23** [comment]
I'll start a test server with those plugins and see if I can replicate the issue, and hopefully figure out what plugin is causing it.

**Comment by andris155** [comment]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14066858/e0d50f04-f455-11e5-8504-aaf11eda96b5.PNG)

**Comment by frash23** [comment]
Unable to reproduce so far. I'll test some more tomorrow.

**Comment by NullOrNaN** [comment]
I'm only seeing this on a world that's from 1.8.8 might be related.

Edit: Could this be related to Multiverse-Core?

**Comment by hurrgurl** [comment]
Any wild ideas what I can try to look for in order to reproduce it reliably?

Could occasional mass use of `Entity::remove` mess with paper's removing of entities?

@MatthewM 
No Multiverse-Core here, but world was V1.7 > V1.8 > V1.9.

Do you experience no issues with fresh 1.9 as compared to 1.8>1.9 world update?

**Comment by hurrgurl** [comment]
Small update, hopefully I'm going in the right direction.

Standing in one place for ~3 hours (AFK overworld) created 171 entities.
I have monster spawners completely disabled, so that shouldn't add any extra entities.
Not sure if location matters but I was at Y86 Extreme Hills+ biome on top of some mountain.
Paper dispawn ranges are set to 32 and 64, chunk load distance is 5.

My bukkit passive mob limit is set to 10 and 50 hostiles. Water & ambient is set to 1.
That particular world was updated from 1.8 to 1.9. I was AFKing in chunks that have been generated in 1.9 though.

**Comment by ghost** [comment]
Mine isn't as bad as some of the above, but I too am getting way more entities than normal spigot:

WG Report:
http://pastebin.com/e81qT5TF

I have animals limited to 7 and set to spawn every 800 ticks and they are still extremely high.

**Comment by hurrgurl** [comment]
My worldguard wont show entity distribution for some reason. QQ

**Comment by NullOrNaN** [comment]
@hurrgurl yes, 1.9 clean seems to not have the issue. It's something about it going from 1.8->1.9 then I guess

**Comment by ghost** [comment]
Are we just out of luck if we have a 1.8 generated map on 1.9? :/

**Comment by zachbr** [comment]
The bug isn't closed, it is on the todo list.
The issue is that even on 1.8 genned worlds this issue isn't consistent, so we can't reproduce it whenever we like. Which is why it's labelled as such, and as "help-wanted". Feel free to take a look when you get time.

**Comment by RoboMWM** [comment]
> It's something about it going from 1.8->1.9 then I guess

No issues on my end, I've updated my server from 1.8.8 to 1.9.2 with no issues like these as far as I'm aware. My server is in hard mode.

However, I don't use WorldBorder nor a pre-generated world (world is probably 3 years old at this point)

**Comment by Gabscap** [comment]
I have a world generated with 1.9 and I'm also affected by this bug.

**Comment by BestMark** [comment]
Save problem after WorldBorder fill.

**Comment by ghost** [comment]
It's only happening in my world(s) that were generated with WorldBorder's fill command as well ^

**Comment by akarras** [comment]
I too am experiencing this issue in worlds generated by WorldBorder's fill command. Seems like a common theme

**Comment by Brokkonaut** [comment]
We have this problem too - Restarting the server helps for a while but after some time the extreme mobspawning begins again.

**Comment by jordanwilliams1** [comment]
I Would also like to add that my world was generated by world border and I'm currently getting the bug :P

**Comment by RoboMWM** [comment]
I've updated my comment to include the fact that I did not pregenerate my world with WorldBorder (nor do I use it), and am not having this issue afaik.

**Comment by sweepies** [comment]
![2016-04-13_15 56 25](https://cloud.githubusercontent.com/assets/7191851/14507397/78151a8e-0190-11e6-9aa6-b7174e0f9fb2.png)

**Comment by jordanwilliams1** [comment]
Has any progress been made on fixing this bug yet :( ?

**Comment by hurrgurl** [comment]
Having no/next to no issues on clean 1.9 world.

**Comment by NullOrNaN** [comment]
I'm assuming all of us have worldguard.. what version?

**Comment by hurrgurl** [comment]
Why would WG be relevant to this?

Also WG didn't have any big updates for months.

**Comment by NullOrNaN** [comment]
I noticed WorldGuard in the high resource offenders and it trying to deny spawns. I'm updating WorldGuard to [this build](http://builds.enginehub.org/job/worldguard/8790/download/worldguard-legacy-6.1.2-SNAPSHOT-dist.jar) right now.

**Comment by erik1988** [comment]
I also had this problem, I installed paper yesterday and today it was passive mobs everywhere, I did not add any plugins or changed any settings in the meantime. Today I reverted back to normal spigot an the problem seems to be gone. In other words this is defiantly caused by having paper installed, if there is because of paper itself or because of the way it modifies other plugins is unknown to me, but I do know this is not a problem in normal spigot - all things being equal. 

This was my config (and plugins) when paper was installed:
http://timings.aikar.co/v2/?id=a900a03c9cad4c30ac644c4f53904050&section=config

**Comment by dwilley83** [comment]
Did the different build of WG seem to help this issue? I have also switched us back to Spigot after installing Paper because of the passive mob explosion. I installed our world, plugins, and 1.9.2 version of Paper on a test server and afk'd on there for an hour or so and didn't seem to have the issue but hard to tell since there was several players online on our actual server at the time the problem was happening. Also, the test server I made was setup before we switched our 1.8.8 world to 1.9, which was the reason for setting up the test server in the first place. I hadn't done WB fill on the test server because it had been done in 1.8.8 already and didn't think I'd need to. But wb fill has been ran on our actual server since the 1.9 update. I'm all up for trying things to fix this because we liked how the server was performing with Paper installed and are looking to switch back to it once this mob issue is resolved.

**Comment by stevmei** [comment]
@Zbob750 

I've send you my world directory in which I'm getting a lot of passive mobs.
Maybe it is caused by one (or all) of the following aspects:
- (Dirt) Blocks are not checked for air above when trying to spawn mobs, because the only world I am experiencing this is a world that has no underworld, just heigth 0 to 64 dirt
- Some limitations are ignored when spawning mobs
- It takes a whilte to spawn so many mobs, they aren't appearing in an hour. It takes > 10 hours for this:

http://imgur.com/HyTaKAO
http://imgur.com/FY2SLCz

**Comment by dwilley83** [comment]
That makes sense because I had installed Paper on our server at around 5 AM and it ran with it all day and that night me and my co-admin had decided to switch back to Spigot because of all the passive mobs and went on a mass slaughter. It seemed to affect the spawn area worse than anywhere else but we have people going through the spawn area all the time which could have caused that part of it.

**Comment by dwilley83** [comment]
I wish I still had the timings reports we had taken but at this point I feel like all the timings reports are going to pretty much look the same when the problem is happening.

**Comment by zachbr** [comment]
All affected please update to build _681_ or higher. Don't waste our time with outdated versions.
Will re-open if needed
Thanks

EDIT: Use build 681 or newer

**Comment by zachbr** [comment]
Did not fix

**Comment by aikar** [comment]
I found some bad logic issues with spigots changes. Hopefully this resolves it. Let us know and reopen if not.

**Comment by Brokkonaut** [comment]
The change does not fix the bug. I wrote a small plugin to look for the causes of this bug and the cause are negative mob counts in the entityCount Map in the chunks. I don't know why this values can become negative, but somehow they do..

**Comment by Brokkonaut** [comment]
http://pastebin.com/5cZJt1Qj
is the (test-)output of this code:
http://pastebin.com/TrcSP8bs

**Comment by jordanwilliams1** [comment]
So... This isn't fixed, yet its "Closed" -_-

**Comment by aikar** [comment]
@jordanwilliams1 its automatic when we link issues and we think its fixed, so we then reopen them when its found not to be.

Thats a very good find @Brokkonaut 

It is very possible a plugin is using NMS and corrupting the counts.
Will check into it later when home to see if any possible flaw in the counting code (i've got theories on some)

**Comment by TNTUP** [comment]
Server crashed with this: https://hastebin.com/usuhawolov.coffee

I've disabled mob-spawning in **Global** and then enabling in some regions with WorldGuard, I guess it caused this crash, so maybe that's the mob issue? (With WG)

**Comment by RoboMWM** [comment]
> Server crashed with this: https://hastebin.com/usuhawolov.coffee
> 
> I've disabled mob-spawning in Global and then enabling in some regions with WorldGuard, I guess it caused this crash, so maybe that's the mob issue? (With WG)

This seems to be unrelated to the issue.

**Comment by TNTUP** [comment]
Thought it would be, sorry^^

**Comment by Puremin0rez** [comment]
For those having the issue, try the latest build of Paper as of the time of this post. (#684 or higher)

More fixes made in regards to this issue from @aikar

**Comment by dwilley83** [comment]
I ran #682 on my test server tonight and was on there for about 2 1/2 hours and the passive mobs were everywhere so I don't believe it's fixed.

**Comment by Puremin0rez** [comment]
Build 682 does not have the new entity spawn fixes that were made in the past few hours. You need to be using at least #683 to benefit from these newer changes.

**Comment by TNTUP** [comment]
Anyone running with Libs Disguises, unload it and watch your entity count going back to normal! It fixed on my end! But I cannot endorse if it doesn't work or nor you don't have it?

@dwilley83 Any chance you have Libs Disguises installed?

**Comment by Brokkonaut** [comment]
@TNTUP  I don't have LibsDisguises at all on my server, so at least it cannot have been the only source for this bug.
But just update Paper as it is fixed now.

**Comment by TNTUP** [comment]
@Brokkonaut Glad to know! I've updated aswell, without Libs, I'll try it tomorrow or later today!

**Comment by dwilley83** [comment]
Updated to #684 yesterday on my test server and afk'd for about 3 hours and no mobs, passive or hostile, were spawning at all. This morning I have installed #685 and I am trying that one out. So far I've had some hostiles spawn so we'll see how it goes.

**Comment by TNTUP** [comment]
At peak times @dwilley83 ? I'm on the #685 too :)

**Comment by dwilley83** [comment]
My test server only has me logged in on it right now.

**Comment by TNTUP** [comment]
Okay^^

**Comment by dwilley83** [comment]
What is going on with the link to download newer versions? Site seems to be down?

**Comment by zachbr** [comment]
https://twitter.com/PaperPowered/status/722064350685569024

Temporary mirror has been provided [here](https://ci.demonwav.com/viewLog.html?buildId=719&buildTypeId=Paper_Build&tab=artifacts)

**Comment by stevmei** [comment]
Running build 684 since 2 days - no passive mobs spawning (only a few, acceptable amount). Seems this issue is fixed, thanks for all providing informations and many thanks to @aikar  and @Zbob750 for fixing!

I guess this could be closed :)

**Comment by aikar** [comment]
Thought I did close this :P

**Comment by TNTUP** [comment]
Running Libs yesterday, without issues now. Guess now Paper fixed it! You're a hero Aikar!: P

**Comment by Techcable** [comment]
Pretty sure 845090e5704a14e662de109451d62f814c439c2f is the exact commit that fixes the issue.
The problem is apparently plugins messing up mob counts.
Thanks @aikar :p

**Comment by TNTUP** [comment]
Solved on my side, been running since 4 days and no huge TPS drops! Aikar our hero :package:
