### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Sakanas** [PaperMC/Paper#1428]
My server cras crashing, I know it says no and to report here but I do not know where to report I do not know the cause of the problem : / can you help me?

>> https://pastebin.com/MLB3SLKy

### Plugin list:
Plugins (68): AAC, ASkyBlock, AuthMe, BannerMaker, BattleLevels, BetterSleep, BKCommonLib, BlockLocker, BottledExp, bSpawners, ChestShop, Citizens, CMI, CommandNPC, CoreProtect, CrazyCrates, CS-CoreLib, dtlTraders, ExoticGarden, FastAsyncWorldEdit, HackedServer, Heads, JDALibLoaderBukkit, JH_AntiBot, JH_Chain, JH_Shop, Jobs, LagAssist, LibsDisguises, LuckPerms, mcMMO, mcMMOHorse, MinePacks, MobFarmManager, MobHunting, MultiWorldMoney, My_Worlds, MyCommand, MyPet, MythicMobs, PandaWire, PlaceholderAPI, PluginConstructorAPI, PlugMan, ProtocolLib, PvPManager, Reputation, Residence, Revenge, RPGFood, SavageDeathChest, Shopkeepers, SimpleClans, Slimefun, StackMob, TokenManager, TradeMe, TryMe, UltimateChat, UltimateTrash, Vault, VoidSpawn, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, Zenchantments

### Paper build number:
09.09 18:00:15 [Server] INFO --------------------------------------------------
09.09 18:00:15 [Server] INFO CMI plugin version: 8.0.8.1
09.09 18:00:15 [Server] INFO Server version: Paper(1556) 1.12.2-R0.1-SNAPSHOT
09.09 18:00:15 [Server] INFO Vault version: 1.6.10(+)
09.09 18:00:15 [Server] INFO --------------------------------------------------

**Comment by zachbr** [comment]
```me.mrCookieSlime.CSCoreLibPlugin``` is setting skull itemmeta synchronously and the server is having to lookup the profile, resulting in a blocking call out to Mojang.

Mojang is either taking too long to respond, or the plugin is making so many calls, that your server is spending all its time waiting for profile data rather than ticking.

If I remember correctly, the workaround for this is to get the player profiles asynchronously and then take those profiles and set them on the tile entity synchronously using the scheduler or your preferred task chain. You may need to forward that information to the developer.

**Comment by Sakanas** [comment]
the server does not quite turn it off it just kicks all the players, is there any way of it just kicking 1 player, I've always used this plugin with spigot and it never happened that.

**Comment by zachbr** [comment]
It's all going to depend on how long everything is locked up. Sometimes it may be 1, other times it'll be a lot. The linked paste you gave was pretty bad.
