### ISSUE TITLE
Server crashing (For unknown reason)

### ISSUE THREAD

**Issue by archiebakeru1660913** [PaperMC/Paper#1465]
### Link/paste of stack trace

https://pastebin.com/YU9jNAFC

### Plugin list:
![image](https://user-images.githubusercontent.com/42930694/45897658-aa6dc280-bdcf-11e8-8250-89a4daeff2fc.png)

### Actions to reproduce (if known):
Literally no idea, seems to be when chunks are loaded, possibly on join but this is just speculation

### Paper build number:
Version git-Paper-254

**Comment by aikar** [comment]
You got a few contenders here, but ultimately its a plugin

me.vagdedes.spartan.α.β.α(ChatProtection.java:54)
doing file loading on main thread

might be caused by:
nz.co.lolnet.james137137.FactionChat.FactionChatListener.onPlayerCommand(FactionChatListener.java:316)

you'll need to consult those plugins to fix it.
