### ISSUE TITLE
White chat color code is not showing in item display names

### ISSUE THREAD

**Issue by thorlauridsen** [PaperMC/Paper#1484]
### What behaviour is expected:
Items with "§f" or "ChatColor.WHITE" in their displayname should also include the color code when getting the item displayname. All the other color codes are working fine.

### What behaviour is observed:
When you use '.getItemMeta().getDisplayName()' there is no color code included in the displayname.

### Steps/models to reproduce:
Create an item stack with a white chat color code in the beginning of the displayname. Check for that exact same displayname and it won't include the color code. This is a problem because some plugins with custom menus and GUIs check for the specific color codes. Now all menus with items with white chat color, don't work normally.

If you have an item with name "§fDisplay" it will show "Display" when you get the displayname
If you have an item with name "§fDisplay§fname" it will show "Display§fname" when you get the displayname

Very simple code that shows the issue: https://hastebin.com/viyagifoye.java

### Plugin list:
Unnecessary

### Paper build number:
git-Paper-304 (Issue is present)
git-Paper-240 (Issue is not present in this build)

**Comment by BillyGalbreath** [comment]
This is intentional in upstream. The names are now ChatComponents, and the API converts it to a String. This conversion also strips the first character code if it is white:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java#666

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/CraftChatMessage.java#189

md_5's commit for this change:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/94b8708aca2424734417b82a4e872c85740bde16#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java

**Comment by zachbr** [comment]
The change that fixed this was reverted. In fixing this issue, we created new issues for plugins that were updated to support it.

We are looking for a better solution that might allow us to keep both cases but ultimately we are now in line with upstream API.
