### ISSUE TITLE
Villages are removed / Iron Titian

### ISSUE THREAD

**Issue by Foorcee** [PaperMC/Paper#1506]
Villages are partially removed by PaperSpigt from Villages.dat
These were created for iron farms like iron titan.
Everything worked with spigot, but with paper very many are removed. If a world is needed for testing, I can upload this

Iron  Titian: https://www.youtube.com/watch?v=STs4wDJewNw

**Comment by aikar** [comment]
This would be because we don't let villages load chunks, which very intensely melts your servers TPS.

However, I've put in a patch to 1.12 and 1.13 to not remove doors from villages if the door is in an unloaded chunk, so this should fix the overall issue and keep it from breaking.

If that still doesn't work, I have added a config option under game mechanics to allow them to load chunks in 1.13 (did not backport this option to 1.12)

it is EXTREMELY important to try to see if its fixed before changing this config, as turning this back on will make villages destroy server performance.
