### ISSUE TITLE
EAR Improvements

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1529]
If motion is pushed to 'faster than normal', like piston pushing, or falling in air, trigger EAR immunity

this will improve vanilla compat

**Comment by ryantheleach** [comment]
What speed would be considered faster then normal?

Apart from that design decision, this feels like low hanging fruit.

**Comment by lynxplay** [comment]
Closing as a general "This should be good enough" point was reached in my opinion.

https://github.com/PaperMC/Paper/pull/6308 implemented piston push immunity ticks where applicable. 
Beyond that, a bunch of improvements have been made to inactivity checks since the creation of this issue (see https://github.com/PaperMC/Paper/blob/master/patches/server/0349-Entity-Activation-Range-2.0.patch#L518 in regards to falling)

As this issue has been open for a while, I am closing this as it isn't specific enough to realistically "fix" really.

If actual issues against vanilla compatibility due to EAR optimizations come up, the respective specific cases/issues will be used to track progress instead of this generic one.
