### ISSUE TITLE
Implement a "hybrid" view distance

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#1531]
Sorry in advance if this has been suggested before or if this isn't the right place to suggest it.

**Is your feature request related to a problem? Please describe.**
The default view distance on servers is a little short; it's very easy to see the edge of the world. Increasing it, however, can be very bad on server performance.

**Describe the solution you'd like**
The client is sent a higher (configurable) view distance, but only chunks within a smaller radius (again, configurable) are actually "loaded" by the server. Think of it as an entity activation range, but for chunks. So say the server view distance is set to 10, and the new "hybrid" view distance is set to 16. The client sees the full 16 chunk radius, but nothing past 10 chunks is processed at all by the server (other than reading and sending the chunks from the world files), unless those chunks are already loaded by another player's 10 chunk radius.

**Comment by oxycclock** [comment]
For the moment, you only can create a "Per player + Per TPS" view distance plugin. I'd like to see this function inside papermc.

**Comment by electronicboy** [comment]
This issue is interesting, but I'm honestly not sure it really offers much:

1) In order to achieve this, we need to load the chunk up anyways, meaning that we're already doing all of the needed work (outside of potentially dealing with entities, but that's another messy area)

2) This would require a lot of burst memory around anyways, chunks have to be loaded from disk and deserialized into their respective objects, if we're sane, we'd leave them loaded lingering in a cache area, as people are going to walk into these chunks anyways, meaning that we're going to need to load them fully anyways

3) This would be a lot of state to maintain in order to safely deal with the client, we'd also have to introduce a lot of work into ensuring that you can walk into these semi-loaded chunks without any issues, stuff like entities would either have to be hidden in those chunks or respawned to the client which we'd have to handle state around...

4) Craftbukkit already (supposedly) ticks chunks further away from the player less frequently, meaning that we're not really gaining any considerable gains here anyways at the cost of complicating state

I honestly doubt that the gains here would even remotely outshine the effort involved nor that they'd offer much in terms of what you're actually hoping, the heavy costs involved with view distance are the processes of loading chunks (which you'd be keeping, but is async anyways), processing what needs to be sent to clients and sending them (which you'd be keeping), as well as the associated memory involved (This is going to be kept the same, or could even actually be made worse depending on what would be needed for this to work efficiently), reductions in ticking of entities in large view distances can already be handled with EAR

**Comment by zachbr** [comment]
I don't see anyone from the team working on this.
