### ISSUE TITLE
BIG BAGG URGENT.

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#1591]
I found a bug that very much loads the server (Lighting Queue 600% on timings), you need to build a fleet of 100x 100 blocks + - (fleet in 1 block), at a height of + - 200 blocks, and when you break them, then FPS 0, and tps too falls ... (build 1582) (plugins: 0)

**Comment by electronicboy** [comment]
Issue names should be relevant to the actual issue, not generic caps based messages, and with performance issues, should include a link to the timings in question.

if you're triggering a large number of block updates, you're going to trigger a large number of lighting updates, there isn't really anything we can do about that outside of intentionally breaking your worlds; The timings queue should be limited in the time it will spend processing light updates, however, so it being able to take up that much time is somewhat odd, but such is the costs of having to update the world, especially with that many blocks.

FPS is going to be 100% client side, and is going to be down to the same issue: You're expecting a lot of work in a small amount of time.

**Comment by FunnyCraft** [comment]
can you login to my server?  I show you a bug that works even when there are no plugins ... (IP smdest.ru)

**Comment by FunnyCraft** [comment]
When i break this blocks , tps and fps down ...
![image](https://user-images.githubusercontent.com/14358233/47257821-4d7f2e00-d49b-11e8-9489-00feee483ef4.png)

for lag blocks should be  Y above 200 and in one layer

**Comment by electronicboy** [comment]
Could you please clarify if you mean "break a single block" or "remove all of those blocks in a single tick", because if it's the latter, it boils down to "you're expecting the server to deal with a lot of work in a short amount of time", client FPS issues are a client side issue, and is purely down to mojang, TPS issues are ultimatly expecting the server to deal with a lot of work in a short period of time, all of those blocks being removed are going to be triggering light updates, which is not exactly something that's going to be dealt with fast with so many blocks

**Comment by FunnyCraft** [comment]
break a single block

**Comment by FunnyCraft** [comment]
it is more accurate to break 1 block and put it back again then FPS 0, and also the server's TPS drops from these actions too

**Comment by electronicboy** [comment]
There is nothing we can do whatsoever about FPS, TPS being hit is a bit iffy, but the work involved there for updating lighting is far from ideal. Could you please produce a timings report as I asked in my first post?

**Comment by FunnyCraft** [comment]
https://timings.aikar.co/?id=76264e0c915d4529b1ae455e8853b93a#timings

**Comment by electronicboy** [comment]
`Version | git-Paper-1552 (MC: 1.12.2)`
Update, there have been many fixes around the lighting queue.

**Comment by FunnyCraft** [comment]
I understand that nothing can be done with FPS, but I change 1 block (break and place) , this should not cause TPS and  FPS to drop, but still ... The most important thing is the condition that I wrote at the very beginning "need to build a fleet of 100 x 100 blocks +-  (fleet in 1 block) the size may be different, the more the more lags, at a height of + 200 blocks"

**Comment by electronicboy** [comment]
There is nothing we can do to stop the fact that the server needs to update the world, the fixes that have been applied to the server since your current build should help with the TPS

**Comment by FunnyCraft** [comment]
I am sure that this is a bug, maybe we did not understand each other,  do it  and you will understand that this cannot be the norm , he server cannot lag terribly because of 1 block

**Comment by FunnyCraft** [comment]
Version | git-Paper-1552 (MC: 1.12.2)
Update, there have been many fixes around the lighting queue.


On 1582 same lags

**Comment by electronicboy** [comment]
When updating blocks in the world, the server needs to recalculate the lighting; if you break a block floating 200 blocks in the air, it's going to need to update a lot of blocks in order to update this information properly, that takes time, which is why we have the queue

The queue also recently had a few bugs, ex; `The timings queue should be limited in the time it will spend processing light updates, however, so it being able to take up that much time is somewhat odd, but such is the costs of having to update the world, especially with that many blocks.` as per my first post, is in reference to an issue that was fixed several versions ago, and I was, through your original post, under the assumption that you was running a build which had these fixes, your timings however, indicates that you're not running the build with all of those fixes, however, and as adviced, should update to recieve these fixes.

**Comment by FunnyCraft** [comment]
https://timings.aikar.co/?id=ae046d26b7154c4d963db4cdc64dd5ee - 1582

**Comment by FunnyCraft** [comment]
what to do? I myself will not solve this problem

**Comment by electronicboy** [comment]
There is very little that can be done about the fact that updating a lot of blocks is a lot of work, #903  would be the best thing I could recommend to follow, however, that likely isn't going to be done for a while given other commitments and will not see 1.12.2

**Comment by FunnyCraft** [comment]
Processing the illumination of the blocks, as I understand it, not even the platform itself, but under it the server needs to calculate the shadow and the height of the platform complicates it. Solution: turn off the shadow from the blocks. (make the lighting static)
