### ISSUE TITLE
MobSpawner API improvements

### ISSUE THREAD

**Issue by crysis992** [PaperMC/Paper#1611]
I have some suggestions to improve the spawner API, since there are missing some fundamental features.

1) 
Currently it is only possible to set a EntityType, but via command blocks you are able to set itemstacks.
So my first suggestion: 
Allow ItemStacks to be set as a spawn result for spawners.

Following command can be used to spawn a spawner that can spawn ItemStacks (Items)

`/setblock ~1 ~1 ~1 minecraft:spawner{SpawnCount:4,SpawnRange:32,Delay:20,MinSpawnDelay:60,MaxSpawnDelay:100,RequiredPlayerRange:12,SpawnData:{id:"minecraft:item",Item:{id:"minecraft:diamond",Count:5b,tag:{display:{Name:"{\"text\":\"Super Diamond\",\"color\":\"aqua\"}"}}}}} replace`

2)
It is also possible to set a list of "SpawnPotentials" with a defined "Weight" so spawners can spawn random entities from a list with a defined chance. But also this part is missing in the current API. 

Example Command to get this kind of spawner:
`/setblock ~1 ~1 ~1 minecraft:spawner{SpawnCount:4,SpawnRange:32,Delay:20,MinSpawnDelay:60,MaxSpawnDelay:100,RequiredPlayerRange:12,SpawnData:{id:"minecraft:chicken"},SpawnPotentials:[{Weight:50,Entity:{id:"minecraft:chicken"}},{Weight:40,Entity:{id:"minecraft:cow"}},{Weight:3,Entity:{id:"minecraft:bat"}}]} replace`

**Comment by Parozzz** [comment]
I've already asked something similar in #1590 . (You are not setting ItemStacks though, just dropped item entity with a peculiar item stack).
Just for saying, since 1.12 is not possible to spawn Items anymore, only Insentient entities. 
Even more, entities both in the Spawn Data and in the SpawnPotential list (So in the MobSpawnData NMS class) can be further changed by adding relative NBT tags to be loaded in the mob class when spawned.

**Comment by meyden92** [comment]
The command above to spawn an Item Entity spawner is working fine on the latest 1.13 build of paper.
But yes, it is using an Item Entity not an ItemStack to be exact. But api wise it's easier to have a method like spawner.setItem(ItemStack item) next to setEntityType.

**Comment by Parozzz** [comment]
It does work fine on 1.13 again? I remember that functionality broke some time ago.

But, since this is something not viable (You can already set the spawned entity as an item), it would be much more understandable to allow fully configure the mob via NBT tags. Only one problem though, this might take a while to make since every value a mob can have must be re-done here (Not something really doable, unfortunately since every specific entity type has his own data).

**Comment by lynxplay** [comment]
I am going to close this, as this generally will be covered via the property API to allow plugin developers to mutate the data on the stack without having to introduce a bunch of otherwise useless abstractions.

I think there is still need for the easily representable values on the spawner, but the entity part I doubt is nicely done without property API. 

If there is a large demand for this anyway, please post here and I'll happily reopen this!
