### ISSUE TITLE
invisibility-potion-hides-from-all

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [PaperMC/Paper#1632]
Thanks to a vanilla bug, https://bugs.mojang.com/browse/MC-89309, invis potions do not hide players from guardians or elder guardians, and a few select other mobs, like they do from all most mobs.

As this is ambiguous to being a bug or intended vanilla behavior, I propose a config option, something along the lines of "invisibility-potion-hides-from-all: true", to make the invis potions work to hide from all mods unless provoked.

**Comment by kickash32** [comment]
~~What would the expected behaviour be?
Should invisible entities never be targetable?
Targettable when they are within a certain distance?
Become untargetable immediately when they gain invisibility?
Stay targeted if they were already targeted?
Become targetable by another entity if the invisible entity attacks it?
How does equipping items like armour or bows affect it?~~

**Comment by kickash32** [comment]
The vanilla bug seems to have been fixed actually. And invis potions seems to work properly. 

The way mob detection works, its based on a detection radius, and if a player (or another mob) has invisibility, the enemies' detection radius will be reduced 10%-70% of the original radius depending on armour (can be further reduced by sneaking and mob skulls).

So we can either close this issue or we could implement `invisibility-potion-hides-from-all`( or maybe `invisibility-potion-hides-completely`) to change the minimum detection radius reduction.

**Comment by zachbr** [comment]
Closing as a vanilla issue fixed in 1.14.2.
