### ISSUE TITLE
Latest = build 409?

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1638]
I download paper almost every day. The last 2 days, I notice that it states the build 409 is loading.
I made sure I was downloading the latest on the jenkins page. Redownloaded it, But still, it says it is build 409.

Is this false information or am I really just re-downloading an old version?

**Comment by zachbr** [comment]
We recently flipped on a CDN that caches jar links which is nice, but unfortunately due to how the latest links work in Jenkins it hasn’t been playing super nice with them. I’m still poking at it. In the meantime I’d recommend you just use the actual build links.

Alternatively you can grab the build list from Jenkins, parse it with bash or whatever to grab the most recent or highest build number, and use that link.

Which sucks but I’m still poking at it. If you have any other questions, please bug me in the Discord rather than here. Sorry for any inconvenice as we get this sorted.
