### ISSUE TITLE
NBT armor and playerhead

### ISSUE THREAD

**Issue by WindUnwaken** [PaperMC/Paper#1648]
### What behaviour is observed:
skull added damge:3 int or armor type (helmet,legging...) added damage: 0 int after leave server

### Steps/models to reproduce:
get SKULL or DIAMOND_CHESTPLATE , leave server and login,
we can find skull can't stack , because it becomes different item

### Plugin list:
NBTEDITOR

### Anything else:
for rpg server gametype, trading item become different.

**Comment by electronicboy** [comment]
`we can find skull can't stack, because it becomes different item`

Whenever an itemstack passes into vanilla realms of the game, the item will become an itemstack backed by a vanilla implementation, this is an issue for items such as skulls specifically because of their game profile information being stored per skull, information from the profile will be stored on the skull, and due to the nature of the implementation will change over time, skulls need to be handled by checking the skulls owner information manually, Papers api offers an API, called ensureServerConversions(), which will improve the reliability of the checks, but can't deal with issues such as damage differences or skulls game profiles having different info in the game profile for some fields
