### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1657]
removed

**Comment by electronicboy** [comment]
https://en.wikipedia.org/wiki/Responsible_disclosure

**Comment by aikar** [comment]
we will look into this and handle appropropriately. closing to get it off the open issue list.

**Comment by mibby** [comment]
Thanks Aikar. 

> https://en.wikipedia.org/wiki/Responsible_disclosure

🤷‍♂️  The miscellaneous item is serious business I suppose.

**Comment by electronicboy** [comment]
Issues like this tend to expose other behaviour or offer ways to cause harm to servers in some manner when disclosing any issues such as exploits, including duplicating abilities, you should inform the relevant parties in a private manner so that they can have time to look into these issues


I found a serious way in which this could implicate my server (All hail the Turtle Master!)
