### ISSUE TITLE
tab auto-complete disconnects players with error in waterfall

### ISSUE THREAD

**Issue by RealmportalMC** [PaperMC/Paper#1670]
### What behaviour is expected:
for eg pressing rea[tab] to complete to Realmportal

### What behaviour is observed:
i got disconnected from the server.

### Steps/models to reproduce:
Log on to the server type something and press [tab] . it will disconnect you

### Plugin list:
https://timings.aikar.co/?id=6df6287fd46e492391e6c93d11990117#plugins

### Paper build number:
MC:1.12.2 git-Paper-1587

### Anything else:

I am connecting through waterfall (build number 237. Tested without any plugins on waterfall.

error in waterfall console:
https://pastebin.com/uvmYKYwF

No errors on paper console. just says i disconnected

Was working correctly on paper build 1544 (what i was using before updating)

**Comment by electronicboy** [comment]
Shortly after your older build a fix was provided to an issue that was causing tab completion to not be handled properly, and in some cases tab completion wouldn't work for some plugins due to this; Your issue here is now that your server is handling these, but a plugin is doing something which is breaking tab completion packets for some reason and sending invalid data to the proxy, `PremiumVanish` is one such plugin which I've heard of causing this before
