### ISSUE TITLE
Random Crashes on player join

### ISSUE THREAD

**Issue by RiftBladeMc** [PaperMC/Paper#1676]
### Link/paste of stack trace

[https://pastebin.com/RUHfJqeq](https://pastebin.com/RUHfJqeq
)

I know it says Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.
But the server does not resume.

### Plugin list:
BileTools*, CoreProtect, Essentials*, FastAsyncWorldEdit*, InvUtils, OpenInv*, PlaceholderAPI, ProtocolLib*, React*, TAB, WorldEdit

but this has been happening for a while now and started when i had just: Essentials*, and FastAsyncWorldEdit*

### Paper build number:
first seen on like 120 but currently 438

**Comment by electronicboy** [comment]
Your server blows up while trying to get the players scoreboard scores, commonly issues like this are caused due to plugins etc using scoreboards for showing information such as "sidebars" or prefixes/suffixes; The only way in which I could really see it having issues there would be down to your server having a lot of saved scoreboards, maybe consider removing the scoreboard.dat file if you're not relying on scoreboard stuff outside of plugins

**Comment by RiftBladeMc** [comment]
I deleted the scoreboard.dat and that fixed it in the overworld but if I log of in the nether then rejoin in the nether it happens, I have checked and there are no scoreboard.dat files

**Comment by electronicboy** [comment]
Updated crash report? If it's the same, I'd consider replicating without plugins, if your server is getting stuck there without any scoreboards in scoreboard.dat, would probably suggest that a plugin is causing the issues
