### ISSUE TITLE
Suggestion - Grass growth optimization

### ISSUE THREAD

**Issue by oloflarsson** [PaperMC/Paper#168]
**Profiler Screenshot:** [https://i.gyazo.com/f836324fb62f6e39ddc3421bc01f13fa.png](https://i.gyazo.com/f836324fb62f6e39ddc3421bc01f13fa.png)

The profiler screenshot is based off a 90 minute VisualVM sample. It seems grass "growth" alone is using ~5% main thread CPU. There are two main hotspots:
1. Light level fetching
2. Other chunk fetching

In TacoSpigot I saw there was an option to make the grass growth ignore light levels. Maybe that could be added to PaperSpigot itself?

Or maybe the entire issue root issue here is that grass growth triggers synchronous loading of chunks? Perhaps a solution similar to this one is in order: https://github.com/PaperMC/Paper/commit/c09424fd33982123d7ed883cd51bdda1c0b63b55

Maybe grass growth should be blocked when it tries growing into sibiling chunks?

**Comment by zachbr** [comment]
I suspect the primary cause of this issue is that chunk loads in 1.9 are significantly heavier than they were in 1.8.x. Making it ignore light levels entirely is ultimately an ugly band aid, we could probably make it stop loading new chunks and only apply changes to ones that are currently loaded, but this is also something we'll need to experiment with before we know how much it helps.

**Comment by aikar** [comment]
I pushed a patch to make light checks not load chunks today, so this should be fixed in build 620
