### ISSUE TITLE
prevent-moving-into-unloaded-chunks moved player below world?

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#1686]
### What behaviour is expected:
When `prevent-moving-into-unloaded-chunks: true`, rubberband a player flying into unloaded chunks (elytra + rocket) back to safe location.

### What behaviour is observed:
Player experienced what he called "lag" while flying pretty fast, but after the setback he was below bedrock in the overworld.

### Steps/models to reproduce:
That's a tough one. Haven't seen it other than this one time and the server has been running this Paper option since it was released. So...really bad luck. 🤷‍♂️  

I am not certain it's Paper, but this setting seems like the only possible culprit. Only other thing I have messing with setbacks is AAC but I have all teleports and movement checks disabled.

### Plugin list:
AAC is only thing that MIGHT be a culprit, but all movement checks are off.

### Paper build number:
Build 442 (1.13.2)

### Anything else:
- Make sure the player is sent back to their most recent "safe" location, and never below Y=0.

**Comment by aikar** [comment]
plugins is only source I can see, as the code does the vanilla logic that's implemented here to teleport back to last location. so unless that player was below bedrock before, not sure how that feature would of done it.

Ultimately, it's due to a plugin. there's nothing we can change about this code.
