### ISSUE TITLE
mine carts eject player into the block below the mine cart

### ISSUE THREAD

**Issue by Tohya1** [PaperMC/Paper#1702]
### What behaviour is expected:
In paper 446 the player is placed next to the minecart

### What behaviour is observed:
In paper 447+ the player is place in the block below the mine cart. If there is a room below they fall through the floor into that room. If there is a 1 high air gap under the rail they drop into it and suffocate.

### Steps/models to reproduce:
place a rail and minecart on a 1 block thick platform on paper 447+ get in and then exit.

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
I tested pushing a minecart onto bottom slabs and trap doors. With bottom slabs you end up in the slab, with the trapdoor you end up in the block below.

**Comment by BillyGalbreath** [comment]
This effects all dismounts from entities (from vanilla mechanics, to plugin's adding passengers).

Normally there is a small little "jump" when a player dismounts from an entity. This "jump" is the player's location getting updated correctly. For some reason, patch 409 is breaking this logic.

Without that little "jump" up and to the side the player is highly prone to falling through the ground.

I've given @electronicboy quite a few scenarios to easily replicate this issue on Discord over the last few days.

Method 1 (the pig):

* Mount a pig with a saddle
* Dismount the pig
* Watch the player fall straight down (no little "jump" to the side).

Method 2 (the minecart):

* Place a minecart in the world
* Enter the minecart
* Dismount from the minecart
* Watch the player fall straight down **into** the ground block

Method 3 (the untamed horse):

* Mount any untamed horse
* Wait for the horse to buck you off
* Watch as player falls straight down to the ground instead of off to the side

Method 4 (the turtle in Ridables plugin):

* Install the Ridables plugin and set it up so turtles are ridable
* Mount a turtle on land
* Dismount the turtle on land
* Watch as the player glitches inside the ground block directly under the turtle (client tries to place on ground, server tries to make player fall through ground)

I could go on and list all of the scenarios, but they are all the same. Dismounting _any_ entity makes the player fall straight down to the ground, and if the mounted position was low enough (minecarts, turtles, etc) then the player will actually fall _through_ the ground.

My proposed solution remains the same. Revert patch 409. In my own personal server I have reverted that patch and the issue has completely gone away.

Here's a video showing method 1 (the pig).

[![YouTube Video Demonstrating Issue](https://img.youtube.com/vi/57AkB24UsJo/0.jpg)](https://www.youtube.com/watch?v=57AkB24UsJo)

The first part of the video I am running build 458 where the problem persists. Notice when I dismount the pig I fall straight down.

The second part of the video (after relog screen) I am running build 446, where the problem doesnt exist. Notice when I dismount the pig I do a little "jump" up and to the side.

Here's another video showing method 2 (the minecart).

[![YouTube Video Demonstrating Issue](https://img.youtube.com/vi/3693C2HzAXI/0.jpg)](https://www.youtube.com/watch?v=3693C2HzAXI)

Notice when I dismount the minecart I fall straight into the ground block...

Here's another video showing the same minecart method, but with 1 block of air directly under ground, which causes the player to suffocate when they fall through the ground..

[![YouTube Video Demonstrating Issue](https://img.youtube.com/vi/FnbzLqHJ4L4/0.jpg)](https://www.youtube.com/watch?v=FnbzLqHJ4L4)

Here is a video demonstration of what method 2 does on build 446 (correct vanilla behavior).

[![YouTube Video Demonstrating Correct Behavior](https://img.youtube.com/vi/pYH8ZleQ9bA/0.jpg)](https://www.youtube.com/watch?v=pYH8ZleQ9bA)

The problem persists in all builds starting from 447 (the inclusion of patch 409).

**Comment by smmmadden** [comment]
I was also able to reproduce everything @BillyGalbreath mentioned above.  I tested the minecart falling straight down really easily. Place a block in the air or above water where no solid block is below the solid block the rail and cart will be.  Then place a track on that block and then the minecart.  right click to mount the cart and then shift to dismount.  You will fall straight thru the block below you.  Here is  a spectator view where I feel right thru and into the water.
![image](https://user-images.githubusercontent.com/10309346/48980686-4e0e7400-f09a-11e8-95e9-42ac6ade35fc.png)

**Comment by BillyGalbreath** [comment]
Still happens on build 465

**Comment by zachbr** [comment]
Thanks for letting us know.
Should be fixed in builds 469+
