### ISSUE TITLE
[Feature request] Advanced activation range

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1721]
Having an individual activation range for each animal/monster entity type would help with finer performance tuning.

ie:
Settings chickens activation range to very low while letting fish stay at vanilla range.

**Comment by Laarryy** [comment]
After a period of four long years for community input, I shall ask: does anyone (especially you, hurrgurl) still want or need this? 

We have configurable ranges for monsters, animals, etc., but nothing so fine-tuned as what this is asking for. If people could still use this and actively want us to work on it, I'll leave it open. Otherwise it's going to be closed for inactivity.
