### ISSUE TITLE
Losing Trident

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1727]
### What behaviour is expected:
When you throw a trident, it comes back if the trident is enchanted with loyalty

### What behaviour is observed:
When thrown and the player dies shortly after, the trident is lost. Even when the player returns to the death site. Keepinventory = true so no normal items were lost. Arrow-despawn-rate = 600. Maybe a little short, but is sufficient for normal arrows. I could increase the arrow-despawn-rate to, lets say the normal despawn rate of 6000, but this makes all arrows despawn very slow.
The solution could be:
- loyalty makes the trident come back at respawning of the player, or:
- tridents have a separate configurable despawn rate

### Paper build number:
Paper 473

**Comment by zachbr** [comment]
Still seeing this in recent builds?

**Comment by kickash32** [comment]
I tested this in vanilla 1.14.2, and it takes a while longer after respawning to get the trident back.
I think 30s on the despawn timer should be sufficent, however if you still have problems upping it to 1200 (60s) should give players more than enough time.

**Comment by LogGits** [comment]
@zachbr i have this issue on build 225 1.14.4.

The issue is that there is no division of importance. Tridents have a significantly higher value than arrows, especially with the enchantments and level of difficulty to obtain. 

E.g. we use `arrow-despawn-rate: 300`. This works fine for arrows, however, because this applies to tridents, people see their tridents vanish after 15 seconds. 

The only solution (Aside from loyalty) would be to seperate the despawn rates of arrows and tridents.

**Comment by arboriginal** [comment]
I've just seen this while working on a plugin... I'm agree, the best would be to have separate despawn rate, like there is for "non-player-arrow-despawn-rate" and "creative-arrow-despawn-rate" (or why not like "alt-item-despawn-rate").

First, I've tried to rename it in ProjectileHitEvent but even if it display the name, it despawned quickly (same with deprecated method "setPersistent(true)"), I thought it was like named LivingEntity which not despawn but I was wrong...

So, for now I'll use this code until this ticket has been treated, if it can help feel free to reuse it:

```java
@EventHandler
private void onProjectileHit(ProjectileHitEvent e) {
    if (e.getHitBlock() == null || e.getEntityType() != EntityType.TRIDENT) return;
    CraftTrident t = (CraftTrident) e.getEntity();
    if (!(t.getShooter() instanceof Player)) return;
    Location l = t.getLocation();
    t.remove();
    l.getWorld().dropItemNaturally(l, CraftItemStack.asBukkitCopy(t.getHandle().trident));
} // It use NMS classes not to loose enchantments, name, lore, ...
```

It's not perfect because it remove the hammered trident from the block and drop it like classic items, but it prevent players to loose their tridents (I'm using very small values for despawn arrows).

**Edit:** Because it's in Spigot too, I've opened a Jira issue for it and create a plugin to fix it while this is not modified in the server directely:

* Spigot Jira issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5421
* TridentDespawnFix plugin: https://www.spigotmc.org/resources/tridentdespawnfix.73341/
