### ISSUE TITLE
Can't trade with villagers when the input items have NBT

### ISSUE THREAD

**Issue by YanisBft** [PaperMC/Paper#1730]
### What behaviour is expected:
When summoning a villager with NBT on the input items, we should be able to trade with him, the same way we can with input items without NBT.

### What behaviour is observed:
The trades are recognized as valid, as they are shown, but when clicking on the output items, we can't take them. I'm saying the issue comes from the input items because trades work perfectly when the input items don't have NBT, no matter if the output items have NBT or not.

### Steps/models to reproduce:
1. Summon a villager with this command: `/summon minecraft:villager ~ ~1 ~ {Offers:{Recipes:[{buy:{id:emerald,Count:1},sell:{id:diamond,Count:1,tag:{Enchantments:[{id:"minecraft:fortune",lvl:4}]}}}]}}`
2. You can see that the trade works as intended
3. Now summon a villager with this command: `/summon minecraft:villager ~ ~1 ~ {Offers:{Recipes:[{buy:{id:diamond,Count:1,tag:{Enchantments:[{id:"minecraft:fortune",lvl:4}]}},sell:{id:emerald,Count:1}}]}}`
4. You can see that the trade does not work

### Paper build number:
The server is using Paper build 474 (latest at the time I'm writing this)

**Comment by electronicboy** [comment]
Duplicate of #198

**Comment by ISSchuster** [comment]
Please reopen this issue - the problem still exists.

I can confirm the problem in the latest paper-build.

But the problem is NOT a Enchantment NBT Tag - the problem is the StoredEnchantment Tag...

Please test it with this command:

summon villager -1100 70 -150 {Silent:1b,PersistenceRequired:1b,NoAI:1b,Profession:1,CareerLevel:1,Offers:{Recipes:[{maxUses:2147483647,uses:0,buy:{id:"minecraft:enchanted_book",tag:{StoredEnchantments:[
{id:"minecraft:mending",lvl:1}

]},Count:1b},buyB:{id:"minecraft:bow",Count:1b},sell:{id:"minecraft:bow",tag:{Enchantments:[
{id:"minecraft:mending",lvl:1}

]},Count:1b}}]}}

**Comment by mikroskeem** [comment]
It's simply marked as a duplicate, see referenced issue.
