### ISSUE TITLE
Launch Variables for Paper Spigot

### ISSUE THREAD

**Issue by BatteryVoltic** [PaperMC/Paper#1815]
Small question.... Are there any other Launch variables like `-Dpaper.disableChannelLimit=true?` Only reason why i could fine that was search through Github Issues bc modded players could connect to my Servers for the Lobby and Vanilla. If there is other Launch Variables where can i find them?

**Comment by aikar** [comment]
we generally use launch parameters instead of paper.yml for things that most people SHOULD NOT be messing with. Those kind of flags are generally only to be used if a Paper team member tells you to use it to solve a specific problem you are having, and they are generally more fringe.

We do not recommend messing with anything we expose like that unless it's specifically targeted to a problem you have.

General configs that are more open to user tweaking are exposed as paper.yml entries.

If you have any questions, feel free to ask on Discord

**Comment by BatteryVoltic** [comment]
Well any time I have asked a question in discord it generally goes ignored. I figured i would get a response from github faster than i would in discord. 

Players were getting disconnected from my servers with any type of modded client and i didnt see an option in the paper.yml for them to bypass the channel limit. When i did some google research i came across that launch variable and it work flawlessly. I was wondering what other variables i could use to possible optimize more of the performance or do other things.

**Comment by aikar** [comment]
And that's an example of a very fringe problem that we can direct a specific solution for :p 

Performance oriented stuff is nearly always in paper.yml
