### ISSUE TITLE
How to fix this ?

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1816]
How to fix this ?

Server version : http://prntscr.com/mar69i

and problem img : http://prntscr.com/mar6s0
and my player img : https://cdn.discordapp.com/attachments/411564947391119363/537369444976951307/2019-01-22_23.33.27.png

**Comment by mikroskeem** [comment]
USE GODDAMN ISSUE TEMPLATE IT'S NOT THERE FOR NOTHING.

**Comment by successed** [comment]
> USE GODDAMN ISSUE TEMPLATE IT'S NOT THERE FOR NOTHING.

i 'dont understand you for give me.
i have all of player in emty of map img : http://prntscr.com/marjf6 
all players see the free space on the map.
How to fix this ?

**Comment by melinstagibson** [comment]
im having this issue on all my servers since updating today.
chunkswont load and players get stuck in them, it affects all the servers i updated. 

pretty severe issue, im going back to older versions due to this.

**Comment by electronicboy** [comment]
Current suggestion is to switch `chunk-edge-mode` in paper.yml to 2

**Comment by andris155** [comment]
Try update to build 507.

**Comment by andris155** [comment]
Same problem with chunk-edge-mode: 3
![2019-01-24_18 57 24](https://user-images.githubusercontent.com/8324198/51698370-4885c980-200a-11e9-8937-b786a3fec771.png)

**Comment by xiaoyang-sde** [comment]
I met the same problem in the latest version #508. It fixed when I rollback to 1.13.2 #500.

> Same problem with chunk-edge-mode: 3
> ![2019-01-24_18 57 24](https://user-images.githubusercontent.com/8324198/51698370-4885c980-200a-11e9-8937-b786a3fec771.png)

**Comment by electronicboy** [comment]
What's fun is that the issues you guys are seeing on 506+ happens to me on pretty much all builds of paper on what I can only imagine is technically a good day for performance, you see; This is where it gets fun; Right now I can't replicate on either latest or 500, but I feel that's a level of pot (bad) luck that my machines currently running a bit too much for it to maintain peek performance; Running the server on a remote machine pretty much always fixes this (mostly) up for me, however

I was speaking to somebody a bit back and recall entering a discussion which lead to them stating that the client doesn't like it when chunks are sent too fast to it, which is a side effect of 506+ with the change made to the LOAD (3) chunk edge mode (new default, which your config was mitigated over to to prevent complaints over the defaults not working as they expected), will actually start requesting chunks to be loaded (and pretty fast at that), effectively also bypassing the max chunk sends, but the alternative there was to effectively break async chunk loadings performance gains due to the load requests blocking the main thread, 506 turned LOAD into "if async chunks is disabled, load the chunks, if async chunks is enabled, request chunks but wait for them to load on a later tick before sending", which solves the performance issue, but apparently creates other issues;

I believe that the general gist is that async chunks and mode 3 are wholly incompatible with one another, mode 3 honestly seems bad for your server in general if you care about performance and stability, given that no matter what we're loading chunks which will no longer be needed (unless players move into them) a tick later (check your loaded chunk stats and how much they jump around with this mode)

**Comment by BBoyJD10** [comment]
I can also have this problem. Version 500 fixes this.

**Comment by zachbr** [comment]
We've disabled all forms of chunk-edge-mode other than mode 2 (WAIT) as of build 509. That should behave as expected. We'll have to figure out what we're going to do with the rest of them.

**Comment by kashike** [comment]
https://github.com/PaperMC/Paper/commit/f238f3a0f4e86d29f7e9c8c4790705c9b3cb5d6e

**Comment by successed** [comment]
> [f238f3a](https://github.com/PaperMC/Paper/commit/f238f3a0f4e86d29f7e9c8c4790705c9b3cb5d6e)



> We've disabled all forms of chunk-edge-mode other than mode 2 (WAIT) as of build 509. That should behave as expected. We'll have to figure out what we're going to do with the rest of them.

log("Migrating Anti-Xray engine mode to mode 3 (LOAD)");
http://prntscr.com/mcb788

what is this ?

**Comment by kashike** [comment]
That's a removal.

**Comment by successed** [comment]
> That's a removal.

Is the map being checked when loading?
