### ISSUE TITLE
can you fix this ?

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1833]
// redacted

**Comment by MiniDigger** [comment]
~~what are you trying to do? from the looks of it, you are also using some ancient version of minecraft, do you use 1.13?~~

oh wait, you want us to fix the book exploit? then this ticket is a duplicate and you should remove the code....

**Comment by electronicboy** [comment]
In the future, please do not report exploits on the issue tracker, all this does is make the issue more public;

Also, when creating issues, please at least put in the effort to fill in the issue template, we will remove peoples access to the tracker if they refuse to fill in the templates, it makes our life harder as we have to go back and forth with information, if it wasn't for the fact that we know about the issue (and the code itself), there is a good chance anything here would be lost.

I've also got a potential fix for the issue, the person I asked to test it never gave me a response as to if the fix was okay, hence I need to try to find the time myself to test it.

**Comment by successed** [comment]
> In the future, please do not report exploits on the issue tracker, all this does is make the issue more public;
> 
> Also, when creating issues, please at least put in the effort to fill in the issue template, we will remove peoples access to the tracker if they refuse to fill in the templates, it makes our life harder as we have to go back and forth with information, if it wasn't for the fact that we know about the issue (and the code itself), there is a good chance anything here would be lost.
> 
> I've also got a potential fix for the issue, the person I asked to test it never gave me a response as to if the fix was okay, hence I need to try to find the time myself to test it.

i have client.

**Comment by MiniDigger** [comment]
are you willing to test a patched paper jar that @electronicboy might provide to you to confirm that the issue was adressed?

**Comment by successed** [comment]
> are you willing to test a patched paper jar that @electronicboy might provide to you to confirm that the issue was adressed?

yes, Of course I would like to help.

**Comment by successed** [comment]
> In the future, please do not report exploits on the issue tracker, all this does is make the issue more public;
> 
> Also, when creating issues, please at least put in the effort to fill in the issue template, we will remove peoples access to the tracker if they refuse to fill in the templates, it makes our life harder as we have to go back and forth with information, if it wasn't for the fact that we know about the issue (and the code itself), there is a good chance anything here would be lost.
> 
> I've also got a potential fix for the issue, the person I asked to test it never gave me a response as to if the fix was okay, hence I need to try to find the time myself to test it.

i have 1 more

**Comment by Leymooo** [comment]
this only work when ports are open. i think it kick players with `You re logged from another location`

**Comment by zachbr** [comment]
You were just told to provide more information and then to also **stop using this tracker to report security issues** and your response is to try and report one more that may or may not be an issue and then post it here? 

Locking - you can't read.
