### ISSUE TITLE
Door bug

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1845]
http://prntscr.com/mioqi5

the door into the water is placed and the water at the door is cleared.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/52521736-81ad7300-2c73-11e9-86b3-27eedbf5062c.png)

This is vanilla behavior

Also, please stop wasting our time with these no-effort tickets, We've got better things to do than try to piece information together because you didn't wanna fill the template. https://github.com/PaperMC/Paper/issues/new/choose
