### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1854]
###  Timings or Profile link:
https://timings.aikar.co/?id=4c2f2f3526ff48bd85fc09aa26bd5efd

### Description of issue:
The quality of playability is dropping.

### Plugin list:
ActionHealth*, AdvancedAchievements, AngelChest, AntiCurse, AuctionHouse, AuthMe, ChatReaction*, ChestCommands, ChestSort, Citizens, ClearLag*, CombatLogX, CommandCacher*, CommandLogger*, CommandNPC*, CraftDisplay, CratesPlus, Duels, EntityDetection*, Essentials*, EssentialsChat*, EssentialsProtect*, EssentialsSpawn*, FastAsyncWorldEdit*, GriefPrevention, GroupManager, HolographicDisplays, HungerKeeperPlus*, Jobs, MineableSpawners, Multiverse-Core, OreAnnouncer*, PandaWire, Parties, PetBlocks*, PlaceholderAPI, PlayerHeads, PlayerVaults*, PlugMan*, ProtocolLib*, Quests, Rankup, SafeTrade, ShopGUIPlus, Shopkeepers, SkinsRestorer, SkQuery*, Skript, SQLAutoBan*, SuperTrails*, TAB, TimeVote, UltimateTimber, Vault*, Votifier, VotingPlugin, Websend, Wild, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://hastebin.com/usocubayin.coffeescript
spigot.yml : https://hastebin.com/akupelilan.coffeescript
paper.yml : https://hastebin.com/idikinoram.bash

### Other helpful links
tps falls and rising again

### Paper build number:
 This server is running Paper version git-Paper-522 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-521 (MC: 1.13.2)
Checking version, please wait...
You are running the latest version

Please help me, i have the players lose because of this problem.

**Comment by MiniDigger** [comment]
The bug tracker is really not the place to ask such questions. in the future, please use one of the means of communication provided on the community page: https://papermc.io/community (like our discord server).

but since I am replying now anyways I might as well give you a few pointers. this is not an issue with paper but with your setup.
 the first thing I noticed is that your linux kernel is 7 (!) years old. that doesn't sound right. you should look into updating your OS.
the second thing I noticed are your startup arguments. using Xms=1M is rather bad. you want to look at http://mcflags.emc.gs for more info
generally, your CPU seems on the lower end side of things, it you can try to remove the plugin SuperTraits, as that puts a substantial load on your cpu, but if all the options I mentioned now don't help, you want to get better hardware.

if you require more help, consider joining the IRC or discord channels :)

**Comment by NullCase** [comment]
@MiniDigger It seems possible that this problem is wider and has been explored at least since January 4th both https://github.com/PaperMC/Paper/issues/1844 and https://github.com/PaperMC/Paper/issues/1791

It looks like there is a problem with entities ticking, entity removal, activation ranges... I don't know. But I have put cash bounty on solving this problem and wish for other operators to also put up money.

I too have this problem despite using a 6GB server with fewer players and different plugins. Here is an instance with and without lag: https://timings.aikar.co/?id=5dd9acab5fe448549db0db2b8e2c03b9

Yesterday I observed 611.8 million hopper check counts in one hour which became worse as 20% of the loaded hoppers were removed.

**Comment by successed** [comment]
@MiniDigger I'm proving to you that in this video is the absurd way tps fell, 
i need to help. https://youtu.be/Gs0VWgidCgI this problem here!

**Comment by aikar** [comment]
Reduce your entity-activation-range in spigot.yml

You are on the defaults
monsters: 32
animals: 32
tick-inactive-villagers: true
water: 16
misc: 16

Change to something like:

monsters: 20
animals: 12
tick-inactive-villagers: true
water: 12
misc: 8

1.13 has a major regression in entity movement that we cannot fix. 1.14 will fix it.
Your only hope is to reduce entity movement.

You may also reduce max-entity-collisions to like 4 or 6 in spigot.yml

Closing as there isn't a "bug" and we cant improve movement code. Mitigating until 1.14 is only option (Though I recommend those activation ranges regardless of 1.13)

**Comment by totemo** [comment]
@aikar 
It seems like the problem is more than just Mojang's code. Admittedly, I am using a pathological test case, 10 tubes of 50 villagers, `maxEntityCramming 50`, but bear with me here.

PaperSpigot build 525: 
![2019-02-20_17 17 10](https://user-images.githubusercontent.com/1934688/53074495-d3d77980-353a-11e9-953f-9a0eacc846b2.png)

Spigot build 2088:
![2019-02-20_17 27 29](https://user-images.githubusercontent.com/1934688/53074664-42b4d280-353b-11e9-914b-98a9af81cf1f.png)

Setting `max-entity-collisions: 4` (was 8) in `paper.yml` and `spigot.yml` gives about 1 tps improvement on Paper and no change in Spigot.

It looks to me like PaperSpigot is doing something that is exacerbating the problem.

**Comment by ArtNRG** [comment]
@totemo it will be good if you create an additional issue for that, I doubt that the closed issue will be checked or fixed one day.
