### ISSUE TITLE
Items can be taken from the gui menu. 

### ISSUE THREAD

**Issue by myavuzokumus** [PaperMC/Paper#1864]
### What behaviour is expected:
Items can be taken from the gui menu. 
Chestcommands-shopguiplus-tuske.
It can be taken from all of them.

![image](https://user-images.githubusercontent.com/47111280/53150951-e5646400-35c2-11e9-8778-5dfd88c9bdc3.png)

### Plugin list:
![image](https://user-images.githubusercontent.com/47111280/53150918-d2ea2a80-35c2-11e9-82b3-b52bad4d73e5.png)

### Paper build number:
![image](https://user-images.githubusercontent.com/47111280/53150875-b77f1f80-35c2-11e9-882c-3b76d4d1e5fc.png)

**Comment by MiniDigger** [comment]
this is an issue with that plugin, report it to the author.

**Comment by ShaneBeee** [comment]
I could be wrong, but I have a feeling this is caused by ProtocolSupport.

I was tinkering around with a script earlier, and it kept mucking up with GUIs (which worked fine in the past) When I looked at my plugins, i realized I had ProtocolSupport in there (for something I was testing)... I removed that plugin, and the GUIs work totally fine now.
