### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1870]
duplicate

**Comment by LogGits** [comment]
I feel like at that point its probably better to provide a pastebin link

**Comment by ShaneBeee** [comment]
A few things here
1) You have been asked numerous times to use the correct template for bug reports.
When you create a bug report, the template is there, and you are clearly deleting it. Staff have asked you EVERY SINGLE TIME YOU POST SOMETHING HERE to include the template, and properly fill it out.
At this point, since you have absolutely ZERO respect for PaperMC team, don't be too surprised if they ban you from here.

2) The first line of this stack trace LITERALLY says
```
DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-529 (MC: 1.13.2)
```
Could it BE any more clear?

3) As LogGits stated, when you have a stack trace so long, that I have to scroll for what feels like 10 minutes just to get to the comment section, please use a paste service (pastebin, hastebin, gists)

**Comment by aikar** [comment]
please dont open duplicate issues. You already reported this...
