### ISSUE TITLE
Zombies converting to drowned too quickly

### ISSUE THREAD

**Issue by JEFF-BRIDGES99** [PaperMC/Paper#1887]
https://minecraft.gamepedia.com/Zombie#Becoming_drowned

According to the Wiki: 

If a zombie is in water, and not in a boat, for 30 seconds it will begin converting into a drowned. The zombie will start to shake, similar to a zombie villager being cured, and after 15 seconds the zombie will be converted to a drowned. Once this process starts, it cannot be stopped.

Current behavior: 

Zombies that are submerged in water convert immediately into drowned without the intermediate 15 second period. During this time, zombies in the vanilla game can be removed from water while still converting after 15 seconds, so long as the original 30 seconds submerged was met. With this bug, that can no longer occur

**Comment by PseudoKnight** [comment]
Side-note: this bug seems to bypass a separate major dupe exploit. In vanilla if the zombie entity is marked as dead, it can still convert into a drowned during that brief window before the entity no longer exists. However, the zombie drops items upon death AND the resulting drowned holds the items the zombie did. This can be used by players to dupe any items.

I would not fix this bug without addressing the related dupe. The reason people noticed this bug (including me, just today) was because of the dupe videos on youtube from ilmango, docm, etc.

**Comment by zachbr** [comment]
Based on a very precursory review, the dupe fix from months ago doesn't appear related to this in any way.

This still needs testing in vanilla and upstream to see where the issue is introduced, assuming it exists.

**Comment by zachbr** [comment]
Confirmed this has absolutely nothing to do with the dupe fix. It's a result of CB not properly initializing the lastTick value when they moved this process over to wall time rather than directly on the tick.

**Comment by zachbr** [comment]
Fixed in builds 557+

I understand there's a lot of interest in this general area of the code base, but this issue and change aren't related to the dupe fix. I should know, I wrote it. Just for good measure I tested it again, it's still fixed.

**Comment by PseudoKnight** [comment]
Given the nature of the issue, we weren't aware of the dupe fix until now. This just appeared related to the dupe, and I wanted to make sure it was considered before moving forward. Thankfully my concern was unjustified.
