### ISSUE TITLE
Swapped chunks in 1.13.2

### ISSUE THREAD

**Issue by omisacma** [PaperMC/Paper#1888]
### What behaviour is expected:
Chunks in correct place.

### What behaviour is observed:
Swapped chunks and players kicked from server.

### Steps/models to reproduce:
If I knew...

### Plugin list:
BileTools v2
MCJukebox v2.6.2

### Paper build number:
This server is running Paper version git-Paper-553 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
I'm noob programming, but I want learn how to solve this issue, Is too hard to repair it manually because the chunk swapping persists.

[2019-03-05-1.log](https://github.com/PaperMC/Paper/files/2932270/2019-03-05-1.log)

**Comment by electronicboy** [comment]
Your world is corrupted, best suggestion is to restore backups, etc; I have experimental patches in the works for allowing the server to drop corrupted chunks, but really, those are dangerous and stand to break your world even more

"chunk swapping" is another issue we can't fix, if we fix that for you, we break it for somebody else

**Comment by aikar** [comment]
This is not a 'bug'. Your chunk file is corrupt due to the server either running out of harddrive space or being hard shutdown in middle of save.

it is not possible to fix this outside of deleting all corrupt chunks from the region file.

This is not something a beginner can safely solve. Please look into Region Fixer tool.
and I doubt were going to have much time to help here either.

But it would be good for you to attach the ./world/region/r.18.0.mca file, as I'm kinda curious why our auto delete code isnt kicking in

[17:57:52] [PaperChunkGen-world/ERROR]: Invalid chunk: (19, 26) Offset: 547 Invalid Size: 1,073,213,232>4,096 ./world/region/r.18.0.mca

**Comment by omisacma** [comment]
Thanks a lot for you answers. I know how to delete and "re-swap" the chunks, maybe I can export the schematics to save the buildings... I will send you the file region by private @aikar.
@electronicboy Can you explain: "if we fix that for you, we break it for somebody else"?
But I want know what caused the problem. I'm afraid it will happen again.

**Comment by electronicboy** [comment]
The problem is that something caused your region file to not be saved properly, this is often down to the server being closed improperly or the disk being full causing data to not be fully written to disk

The problem here is vanillas logic for "if we try to load a chunk and we find one but it's for a different chunk location", it will move the chunks location to where it belongs; What's happened here is that information is incorrect, likely due to the fact that your region file wasn't saved properly; modifying it to not move chunks would solve chunks being moved when they shouldn't be, but would only break cases when they should be moved

**Comment by omisacma** [comment]
I understand, thanks for the explanation. Maybe Mojang must optimice that logic...

**Comment by omisacma** [comment]
I used Region Fixer and the corruption still continues @electronicboy @aikar 
[Error.txt](https://github.com/PaperMC/Paper/files/2933362/Error.txt)

**Comment by 0-x-2-2** [comment]
>But it would be good for you to attach the ./world/region/r.18.0.mca file, as I'm kinda curious why our auto delete code isnt kicking in

**Comment by electronicboy** [comment]
We determined that, it's only handling the headers, not the actual chunks themselves

It's worth noting that region fixer is pretty "dumb", it doesn't really care to check if chunks are in the correct locations, etc; backups are ultimately your best option here

**Comment by omisacma** [comment]
Ok I tried, thank you a lot @electronicboy :)
