### ISSUE TITLE
Fish vanishing at chunk boundaries. Maybe dying?

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1892]
This is explained poorly. (edit: better)

## What behaviour is expected:
Fish not vanishing when they have a chunk boundary on one side of a water source block.

### What behaviour is observed:
A fish in 1 block space on a claim boundary will occasionally vanish. This tends to happen on the outer side of the chunk.

So, suppose the outside chunk gets unloaded first. If a source block of water is placed on that boundary in the loaded chunk, then a fish in that source block will sometimes vanish... And you're unloading the outside chunk first.

Also, larger bodies of water will also lose fish if there is a chunk boundary through the water.

### Steps/models to reproduce:
Place water source blocks at claim boundaries. Contain fish inside. Move away so the boundary side unloads first (but the source blocks are still loaded). This seems to cause the problem.

### Plugin list:
ChestShop, ChestShopNotifier*, GPRealEstate*, GriefPrevention, PlayerVaults*, Vault

### Paper build number:
Paper version git-Paper-561 (MC: 1.13.2)

### Anything else:

_Speculation: fish in chunk boundaries are being saved in the wrong chunk. then the chunk loads with the fish in the wrong block. if the block is solid, fish eventually dies._

I don't know if it's strictly directional or if unloading any outside chunk can work. water in a loaded chunk against a chunk that unloads seems to trigger this more often.

**Comment by aeonlamb** [comment]
I'm almost certain this is the same bug that I reported a while ago, #1806 . Can you give screenshots of the place where the fish are known to disappear/die? Showing where the chunk boundary is preferably.

**Comment by NullCase** [comment]
I too considered if your issue is related. Here are two screenshots.

In the first one, that empty water source block has lost a fish several times.
![2019-03-08_03 27 35](https://user-images.githubusercontent.com/32785664/54017054-dd73fa80-4152-11e9-8e45-6bbc5b16921c.png)

In the second image, that source block is on the exact same chunk boundary. Same one, but in the other chunk. AFAIK it has never lost a fish. (note the Y coordinates in the image. I'm up one floor in the shop but the style is the same).
![2019-03-08_03 27 48](https://user-images.githubusercontent.com/32785664/54017055-dd73fa80-4152-11e9-9356-78df83454f82.png)

**Comment by aeonlamb** [comment]
Yep, those are the same circumstances to replicate the bug I reported before. The fish would try to pathfind to the water block across the chunk boundary, even though there's a block in the way. Unless I'm missing something I believe this is the same bug. 

The second image the fish probably haven't disappeared because there are people to the west of that area frequently but people don't frequently travel to the east of it. If you travel to the east of that area so that chunk 6, -4 is on the very edge of the currently loaded chunks and just wait for a while or try moving back and forth along that direction I think you will find that the fish will eventually suffocate.

**Comment by Chew** [comment]
Appears to be fixed in the same patch mentioned in #1806. No other discussion has happened here since that response, and no other reports of this have occurred, so I'm going to assume it's fixed. If you are experiencing this on a supported version, feel free to open a new issue. Thank you for the report!
