### ISSUE TITLE
Server Crashes everytime when starting

### ISSUE THREAD

**Issue by ashahir05** [PaperMC/Paper#1916]
Using Paper 1.13.2 584. Here's the log:

https://gist.github.com/DemonWav/629e91f1f0e9d23152bf6f4567a5fe07

**Comment by zachbr** [comment]
It's taking more than 60 seconds to run data conversions from older versions of the game. It's either come across a chunk loaded full of stuff or your server is very slow or even some combination.

There is likely not much we can do about this sort of thing, these data conversions _must_ run in almost all cases, and messing with them is likely to lead to conversion issues.

You can try setting the watchdog timeout very high in spigot.yml and then running the server with the force upgrade option to get it to convert your whole world in one, slow, go. While its doing that you wouldn't be able to have players on however.

**Comment by aikar** [comment]
See if this still occurs on the latest version.

oddly, this is actually not due to converting chunk data.

It seems like it got stuck in initializing the servers data but i'm shocked it took that long.

Look for these log lines:
```
[01:31:21 INFO]: Loading API Data
[01:31:26 INFO]: Loaded API Data (time: 4593ms|dataVersion=1631)
```
if you still crash after those are printed, paste me the logs on Discord (please dont use hastebin)
