### ISSUE TITLE
Placing signs on grass causes NPE

### ISSUE THREAD

**Issue by berwil-1** [PaperMC/Paper#1917]
### What behaviour is expected:
That the sign editor opens without any issues.

### What behaviour is observed:
No sign editor is opened and an error is thrown in the server console.

### Steps/models to reproduce:
In the newest version Paper-584 [e8bbfbf] open a world and place a sign on grass/tall grass (not the solid dirt block with grass texture).

### Plugin list:
None.

### Paper build number:
Paper version git-Paper-584 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
NPE: https://pastebin.com/EApwqrcx

**Comment by BillyGalbreath** [comment]
Sounds like SPIGOT-4678 broke something. Unfortunately no one knows what's going on in that ticket or what it solves because it's private. :(

~~Without digging too deep I'd wager instantiating a default value on `openSign` would fix the NPE. But who knows what else that's going to affect.~~

After digging deep I've determined its caused from using the click action to determine where the sign is placed. When placing a sign on a block it gets the neighbor block, but if its tall grass this is the wrong spot (it should be the tall grass block, not the neighbor block) thus NPE.

**Comment by electronicboy** [comment]
Replaced with https://github.com/PaperMC/Paper/commit/90d8377b5962b729483f3f720de3661cb4abf8f9
Testing the method here, if you have a few blocks standing beside one another, [sign, grass] and place a sign onto the grass while looking at it from the correct angle, it will open the sign that was already placed
