### ISSUE TITLE
Nether damage remains on when set to false.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1939]
version 603. just reporting quickly before anyone else dies & loses their things.

**Comment by zachbr** [comment]
So I changed it to be a height now instead of a boolean.
It's `nether-ceiling-void-damage-height: 0` where the default of 0 means its off.

When I changed it, one build went out (602) where it would migrate people to a value of 128 by default. If you ran 602 during the short intermediate period between then and 603, yours will also be enabled.

Set `nether-ceiling-void-damage-height` to `0` to disable it.

**Comment by zachbr** [comment]
Just went ahead and retested config migrations from pre-change to 603, everything appears to be functioning properly. People who had it set to `false` are getting migrated to `0` (off) successfully, people who had it `true` (on) are getting migrated to `128` successfully, and new config generations are getting `0` (off) correctly.

Looks like you just had the unfortunate luck of hitting a buggy build (602). Thanks for the report nonetheless.

**Comment by NullCase** [comment]
yeah. tested 602 then updated to 603. the 128 height was preserved.

**Comment by zachbr** [comment]
There are no migrations from 602 -> 603. You have to make the change yourself.
