### ISSUE TITLE
Squid Farm + Spawning doesn't work correctly...

### ISSUE THREAD

**Issue by Nikwitz** [PaperMC/Paper#1948]
### What behaviour is expected:
___What you expected to see___

### What behaviour is observed:
Squid Farms + Squid doesn't Spawn naturally in the ocean biomes.

### Steps/models to reproduce:
No Squids is spawning on the server, even with fresh install.

### Plugin list:
No one.

### Paper build number:
This server is running Paper version git-Paper-597 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by ShaneBeee** [comment]
You should try an updated version of paper before doing a bug report.
Paper is currently on 610, you are 13 versions behind.

**Comment by Nikwitz** [comment]
I'm on #614 now but still not working.

**Comment by ShaneBeee** [comment]
Me personally, can not replicate this.

I found an ocean, and there was a squid there.

![](https://i.imgur.com/vxhwSNC.png)

**Comment by WELTEINZ** [comment]
Hi,

same issue here, squids spawn extremly rare in intened bioms (ocean and river).
Tested versions 610 and 624.
I changed the value "count-all-mobs-for-spawning" to see if the problem is related to this parameter, without success.
Squidfarms are completly obsolet on my server.

Thank you for providing PaperMC in general and for your help in advance.

**Comment by kickash32** [comment]
Can you test this again on the latest 1.14.2 build?
