### ISSUE TITLE
use-hopper-check bug

### ISSUE THREAD

**Issue by Cat7373** [PaperMC/Paper#197]
![](http://ww4.sinaimg.cn/large/9103a520jw1f2q8disl4sj20tb0hewk2.jpg)
1. Setting paper.yml the use-hopper-check to true
2. Construction equipment picture above
3. In the upper right corner of the chest put some items
4. Wait a few seconds
5. Open the lower right corner of the chest
6. Wait a few seconds
7. Close the chest GUI
8. You will still see a steady flow of goods to other transmission chest

- Link [0079-Re-add-Spigot-s-hopper-check-feature.patch](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0079-Re-add-Spigot-s-hopper-check-feature.patch)

Version: git-Paper-daab2c8 (MC: 1.9.2)

**Comment by Cat7373** [comment]
I thought of a solution:
Several tick popular stone in the signal disappeared after
Temporarily disable hopper-check

**Comment by Cat7373** [comment]
Alternatively, only the idle time before the use of funnel hopper-check
(No transmission, no red stones after the update tick)

### Example

```
if (flag) {
    this.setCooldown(world.spigotConfig.hopperTransfer); // Spigot
    // Redstone Update I could not find where
    this.hopperCheckCooldown = world.spigotConfig.hopperTransfer;
    this.update();
    return true;
}
this.hopperCheckCooldown--;
if(world.paperConfig.useHopperCheck && !this.o() && this.hopperCheckCooldown <= 0) {
    this.hopperCheckCooldown = 0;
    this.setCooldown(world.spigotConfig.hopperCheck);
}
```

**Comment by Cat7373** [comment]
Incidentally, when the hopper update or reset the cooldown around the funnel

**Comment by RoboMWM** [comment]
There was a reason this was removed upstream - it caused issues like these. But thinking of ideas to solve this is good - although I'm not sure if @Techcable's hopper push method solves this.

**Comment by zachbr** [comment]
From GH-299, for anyone curious on our viewpoint of this setting:

> Can't really say much in terms of a fix. We've known it breaks vanilla behavior for some time, you use it with that risk. We will likely spend time investigating hopper optimizations directly rather than playing with this workaround of a config option.

**Comment by zachbr** [comment]
# From @mibby and GH-299

Paper dev 748

With use-hopper-check enabled, vanilla hopper behavior breaks. Hoppers lose track of items and the direction it should flow in when numerous hoppers are stacked on top of each other in various directions. (i.e. potatoes aren't being sorted at all and are put into the junk chest) As well as had 2 items tick at once rather than one at a time.

Region file for testing. Two different hopper item sorters in the area. Should sort carrots, potatoes, and junk into separate chests.
https://www.dropbox.com/s/5q8z7ifdy3ne1r1/r.-49.-36.mca?dl=0

Coordinates;
-25,042, 70, -18129

Paper config
`use-hopper-check: true`

Spigot config;

```
    ticks-per:
      hopper-transfer: 24
      hopper-check: 24
    hopper-amount: 1
```

Disabling the setting, the hopper sorter works as intended.

Paper config
`use-hopper-check: false`

Spigot config;

```
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
```

**Comment by Techcable** [comment]
@RoboMWM
My hopper patch preserves vanilla behavior.
My patch is based on the observation  that most of the hopper checking lag comes from checking for entities.
Based on my theory it would make sense for @Zbob750 to only throttle the hopper check rate for entities, as block inventories are relatively fast to find and not checing for them may cause bugs like this.
If you want to do it this way, I could contribute a patch, as I'm verry familiar with the hopper code.

**Comment by zachbr** [comment]
Our own support for use-hopper-check will be removed shortly now that we've added @Techcable's patch to improve hopper performance. As such, this issue will no longer exist, as the feature causing it will be removed.
