### ISSUE TITLE
[Feature] Oxygen and respiration drain/recharge rate setting

### ISSUE THREAD

**Issue by UltraFaceguy** [PaperMC/Paper#2005]
The ocean update is cool and all, but I'd like to configure oxygen to work better for custom maps with more/less water. Pretty much in the way that hunger is controlled in Spigot.

Ideally, there would be several configuration settings:
- Oxygen drain while underwater
- Respiration's oxygen drain modifier
- Oxygen recharge rate when out of water

If accepted as a feature, I'll finally realize my dream of (fairly) insta-killing people who run out of air. I mean, I already kill them now, it just isn't fair.

**Comment by kickash32** [comment]
Would these modifiers affect all mobs and players, or just players?

**Comment by uselessknickknacks** [comment]
Both. 
Creatures that die due to being on land is a entirely different issue. So don't touch that.

You could have a general config setting that acts as the default values all entities spawn with.
Then for players, add another tag to their .dat file that is called MaxAir or something like that.

If you want to get really fancy, store air regeneration and air loss rates within the players dat file too and have the priority be the players dat file for what rates to apply, then the config. And finally as a fail safe fallback, minecrafts default rates. This would add plenty of flexibility for coding plugins.
When a player spawns onto the server for the first time, their air loss and air regen rates in their dat file is set to whatever is on the config.

But most important to begin with would be fixing that MaximumAir, as it is right now it's completely pointless, atleast for players.
Yes, maximumair is seemingly tracked for as long as the player is on the server (when you disconnect it's set back to 300 when you rejoin). But it is not a factor in calculations. Minecraft will still regenerate to 300 no matter if you set maximum air lower or higher.
