### ISSUE TITLE
[Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump

### ISSUE THREAD

**Issue by ExploringAussie** [PaperMC/Paper#2043]
Server crashed overnight with this issue, anyone enlighten me on what caused this ? It looks like its pointing towards one plugin by rusketh (comparable hoppers 2), but not sure, and its weird because I have another server running with the exact same plugins and that didnt crash.

Heres a dump report.

https://pastebin.com/uvgiyGvz

**Comment by astei** [comment]
Your server is running quite behind on ticks and you should probably remove that rusketh plugin before you continue. (It's doing I/O in the main thread, a big no-go.)

**Comment by ExploringAussie** [comment]
that is my main plugin, that does everything for me, ive only had this issue since changing to paper, could that be to do with it ?

**Comment by astei** [comment]
Nope, it's not a Paper thing. In fact, Paper is warning you that your server is very slow at making progress.

The correct fix is to report the problem to the plugin author.

**Comment by ExploringAussie** [comment]
Ok thanks, ive shared this page with the author so hopefully he can work out a fix, thanks.

**Comment by electronicboy** [comment]
as noted, paper just includes a set of warnings for when a tick takes too long but doesn't trip the watchdog, there are two sets of performance issues here:
1) Loading chunks - in general, this is bad, but due to the methods used it also means that it's going to load neighboring chunks, causing even more of a hit
2) I/O on the main thread - The plugin is performing sql transactions on the main thread, which is one of those things which is best avoided where possible

**Comment by Emil-D-S** [comment]
1) Backup your world folder in your main server folder.
2) Delete the world folder in your main server folder.
3) Run run.bat.
4) Stop the server.
5) From your backed up "world" folder copy everything except "level.dat" and "level.dat_old" back to your "world" folder in your main server folder and overwrite it.
6) Start server

It worked for me.

**Comment by MiniDigger** [comment]
Please don't bump old tickets
