### ISSUE TITLE
cache folder [question]

### ISSUE THREAD

**Issue by dinfyru** [PaperMC/Paper#2103]
Is there way to clean files in cache folder or paper.jar in main folder?
I'm trying to do docker image, and he turns heavy.
I'm deleted original mojang jar in cache folder and it works. What about other files?
In example spigot has only one file spigot.jar.

**Comment by jacobsandersen** [comment]
So you want to clean the cache folder at an interval?

You can do this with a cron job that runs a `rm` on your cache folder at specified time intervals. I don't think Paper necessarily needs to do this itself as the cache is used to avoid needing to redownload files for patching.

**Comment by mikroskeem** [comment]
>I'm trying to do docker image, and he turns heavy.

Are you storing Paper inside Docker container?  
I suggest you to have server data on separate volume because how frequently new builds come out. Imagine rebuilding container every time when server has an update - it simply wastes your time.

However, please use Discord or IRC for questions like these next time.
