### ISSUE TITLE
1.14.2 world save drop

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2116]
i have latest paperspigot #58

version 1.14.2

i have world save drop.

check this out timings:

https://timings.aikar.co/?id=25f620d7f7164be6beeb7465eb68f7c0

**Comment by successed** [comment]
t,y close.

**Comment by andris155** [comment]
Same problem
https://timings.aikar.co/?id=f1d53e705f774144865ec6069d644f91

**Comment by successed** [comment]
we need fix this..

**Comment by Prof-Bloodstone** [comment]
@successed As it's been said many times - Minecraft 1.14 is not stable. There's a lot of issues, mainly with chunks and entities.
If someone will find time to fix Mojang's code, they will. Noone gets paid to do this, except for Mojang employees. You are welcome to give it a try yourself.
If you want to stay on 1.14, you can increase the time between saving. It'll mean that the lag spikes will be less often, but slightly bigger, with higher RAM usage and in case of a server crash, you can lose more progress.
Some people disable it entirely, but that means that if server crashes, you lose everything you did since last shutdown.
If you have a lot of RAM, you could look into using RAM disks, but it's more complex topic that you'd need to figure out yourself.

**Comment by successed** [comment]
@Prof-Bloodstone i have nwme disk, what you think ? need to collect donations for this problem ?

**Comment by electronicboy** [comment]
World saving performance is a known issue from vanilla, people are working on it in their free time as well as mojang, the fix is to basically have read all the advice and stuck to an earlier version of the software, or wait until the issue is fixed.

**Comment by successed** [comment]
@electronicboy mojang a reported on the problem paper said.
