### ISSUE TITLE
help or go crazy

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#217]
How to disable the messages: Excessive velocity set is detected
It interferes.

**Comment by kashike** [comment]
There is currently no way to disable this warning.

**Comment by FunnyCraft** [comment]
Add this function, please.

**Comment by Gabscap** [comment]
This looks like a client side message. In this case there is no way of disabling it server side. (Except for checking which velocities you send to the client)

EDIT: I misunterstood your issue.

**Comment by FunnyCraft** [comment]
I have to log on every step of it.

**Comment by zachbr** [comment]
Will probably make this check ignore projectiles because they handle large velocities properly, as one would expect, in hindsight

The issue with removing it entirely or putting a toggle on it is that everyone will just turn it off because disabling the message is easier than bugging the developers of these plugins. Then people just start doing it immediately when they make servers, and they can't figure out why their servers are randomly hanging and we're back at square one.

**Comment by FunnyCraft** [comment]
http://pastebin.com/2nppy2BB - This problem remained.
Build latest.
