### ISSUE TITLE
Re-add Bucket Stacking Feature

### ISSUE THREAD

**Issue by ayeelanaa** [PaperMC/Paper#221]
Water, lava and milk buckets are no longer stacking in 1.9.2 version
They are stacked when using the give command but not when placing them in your own inventory.
They are not stacked when filling up with water, lava or milk.

Paper build number:
684

**Comment by zachbr** [comment]
Bucket stacking was removed in 1.9.x because it was not a very reliable mechanic. I've assigned Byteflux who was the original author of that patch. He may get to it, he may not. If someone else wants to take the old patch, update it, and check it against mechanics issues (ie I take a two bucket stack and put it in a furnace what happens? Does it reject them? Use both and return two buckets? etc), feel free to do so.

**Comment by josephworks** [comment]
buckets now stack in 1.12.1. Now that 1.12.1 is out 1.9 is no longer supported.

**Comment by zachbr** [comment]
Empty buckets stack, filled buckets do not; which is what they were asking about.
Please take a minute to read the issue description in full before responding.

**Comment by zachbr** [comment]
I don't see anyone working on this anytime soon. This ticket has little interest from the team and doesn't seem to have much interest from the community at large.

I have been told several times over that there are plugins that simulate this sort of behavior to varying degrees. I would advise you look in that direction if you are still interested.
