### ISSUE TITLE
Citizens2 Crash on server boot.

### ISSUE THREAD

**Issue by Symphonic3** [PaperMC/Paper#2220]
### What behaviour is expected:
The server to start normally with Citizens2 installed.

### What behaviour is observed:
The server crashes on boot when Citizens2 is installed.
### Steps/models to reproduce:
Take latest Citizens2.jar from their Jenkins, and use git-Paper-95.

### Plugin list:
I don't think this is necessary, the issue is with Paper's compatibility with Citizens2

### Paper build number:
git-Paper-95
### Anything else:
I made an issue post on the Citizens2 github, and multiple others stated that they had this issue and we discovered it is an issue with PaperMC. Here is the server thread dump from the crash: https://pastebin.com/AxhsGcG8

Thanks!

**Comment by zachbr** [comment]
All that says is that the server's main thread was blocked too long while loading chunks and was killed.
Citizens is causing chunk lookups, probably not even in any bad or wrong way, and the server can't keep up. This is a known issue with 1.14.x in general and is not related to Paper specifically or even likely Citizens.

There is ongoing work in this area but I'm not going to keep this open because it doesn't really add anything to the conversation. There are plenty of servers not running Citizens with this issue (and others) and there are plenty of servers running Citizens without this issue.

As has been reiterated time and time again, 1.14.x has problems. Don't use it if you can't stomach them.
