### ISSUE TITLE
Return from end, stuck on loading terrain 1.14.3

### ISSUE THREAD

**Issue by ShiftingKill** [PaperMC/Paper#2238]
### What behaviour is expected:
Jump through end gateway on end mainland to get home. The wishing-well looking one.

### What behaviour is observed:
Stuck on "Loading terrain..."

### Steps/models to reproduce:
Go to the end and then beat the dragon and return through the main gateway. At least I was timed out. I log back in to see myself dropping into the portal for a split second and then stuck on loading terrain. Restarted server and still stuck in the portal, also the teleport command went through when I was stuck on loading terrain but it didn't do anything to me although console said it teleported me (also it told me it teleported me in world_the_end, so I assume I'm stuck in the end and not the gateway)

### Plugin list:
WorldEdit
WorldGuard
Dynmap
CoreProtect

### Paper build number:
git-paper-112

### Anything else:
Previous version: git-paper-107

**Comment by PluggedCloud542** [comment]
This problem is still present on version 1.14.4 paper-194, I encountered it recently, the only way I could fix it was with a backup of my characters playerdata as I would sit on the loading screen for a while and then get timed out according to the console.

**Comment by electronicboy** [comment]
194 is considerably outdated; The fact that it's tied to your player data suggests that there is something relevant there specifically vs a general issue, considering the lack of reports on this topic, I'd suggest checking out the area/looking at the contents of the player datafile; Without replication steps, there ain't entirely too much we can do, jstack reports might be handy, but unlikely to produce anything relevant

**Comment by PluggedCloud542** [comment]
When I have the chance later I'll update the server to the latest version to see if the problem is still there, also on how to reproduce it.
It basically happened anytime I went far out into the end and then came back so for me it was 
1. Go far out like where end cities spawn (I usually stayed for a while getting loot but not for too long)
2. Go back and try to leave the end, when you leave the problem will occur.
If you try to leave the moment you go in without going far out it allows you to leave normally
