### ISSUE TITLE
Server crashes with Paper 114 but works with 111

### ISSUE THREAD

**Issue by superfly2000** [PaperMC/Paper#2242]
I know says that I should not report to Paper in the log but this still feels like an issue...I mean...if it works with an older version.

Link to post in Spigot forum with info about my server, from timings paste.

https://www.spigotmc.org/threads/i-am-a-bit-new-at-looking-at-the-paste-from-timings.380009/

**Comment by superfly2000** [comment]
Had 3 crashes in a row withing 10 min. Changed to the 111 jar and now its still running 40 min (**edited**) and more.

**Comment by MiniDigger** [comment]
at least attach the log...

**Comment by superfly2000** [comment]
My log is spammed by one of the plugins I'm using....but ok.

**Comment by superfly2000** [comment]
[latest2.log](https://github.com/PaperMC/Paper/files/3329981/latest2.log)

**Comment by MiniDigger** [comment]
I mean the log when your server crashed...

**Comment by superfly2000** [comment]
Ah, you mean crash-report.

No, there isn't a crash report for this one.

**Comment by kickash32** [comment]
logs are stored in the logs folder, upload latest.log after a crash happens.

**Comment by electronicboy** [comment]
By log he means the log file, if the server crashed due to a bug in paper there will be some form of indication of what happened in the actual log files of the server, there are other reports that much be relevant, e.g. hs_err log files from jvm crashes, etc

I'd also suggest updating your plugins, log files which are flooded with errors is pretty much never a good sign, that plugin is no longer working as intended and might even be creating wider issues than just flooding your logs.

**Comment by superfly2000** [comment]
Works much better with Paper 115 for me now. No crashes so far and low resource usage.

I guess this thread is nearing its closure...

**Comment by 0-x-2-2** [comment]
GreatKits looking a little broken 🤔

**Comment by superfly2000** [comment]
It actually works perfectly :-) It doesn't even lagg the server AFAIK. The **only** problem is the console-spam.

The reason for the console-spam is because its not made for MC v1.14.x yet. At least thats what I find out with my horrible coding skills but decent google skills.
