### ISSUE TITLE
Server crash stacktrace

### ISSUE THREAD

**Issue by f0x48** [PaperMC/Paper#2283]
### Link/paste of stack trace
https://pastebin.com/raw/XMY5m11t

### Plugin list:
`AuthMe, BestViewDistance, Bonuschest, ChangeSkin, ChatCo, CustomHelp, EdwinLogin, NoCheatPlus, OldschoolKill, PermissionsBukkit, PingMOTD, ProtocolLib, RemoveJoinLeaveMessage, SimpleAutoBroadcast, Tablist, TornadoxxDonkey, ViaVersion`

### Paper build number:
`This server is running Paper version git-Paper-1617 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Comment by Chew** [comment]
Link is invalid, and as there has been no discussion on this issue for more than a year on a version we no longer support, I am marking this as stale and closing. If you continue to have whatever the issue was on a supported, feel free to hop on our [Discord server](https://discord.gg/papermc) or open another issue. Have a good day!
