### ISSUE TITLE
BlockGrowEvent wasn't fired on Bamboo growth

### ISSUE THREAD

**Issue by artur9010** [PaperMC/Paper#2291]
### What behaviour is expected:
Fire `BlockGrowEvent` on Bamboo growth. That event was fired on growth of any other plant in the game, but not bamboo.

### What behaviour is observed:
Nothing.

### Steps/models to reproduce:
Write listener that will broadcast material type on growth, like:
```java
    @EventHandler
    void onGrow(BlockGrowEvent event) {
        Bukkit.broadcastMessage(event.getNewState().getType().toString());
}
```
And try to grow bamboo, nothing happens.

### Plugin list:
unnecessary

### Paper build number:
124

**Comment by mikroskeem** [comment]
Smells like upstream issue. Can you check if this works on Spigot?

**Comment by kickash32** [comment]
As noted on the Spigot issue, https://hub.spigotmc.org/jira/browse/SPIGOT-5312, Bamboo/BambooSapling/ChorusFlower/Kelp all use BlockSpreadEvent instead of BlockGrowEvent. Making them all use grow instead of spread seems like it would make the API more consistent, however this would be a breaking change for many plugins. Perhaps paper can add them to the BlockGrowEvent and keep them in the BlockSpreadEvent event until Spigot decides to make the breaking change itself.

**Comment by JuniorJPDJ** [comment]
@kickash32 
It seems like good solution to make it trigger both events, but It still may break some plugins which already take this in account. Some actions could be fired twice for the same event.

**Comment by JuniorJPDJ** [comment]
In any way... It should at least be mentioned in docs

**Comment by Machine-Maker** [comment]
So I would work on implementing this, but if Paper wants to keep the BlockSpreadEvent being called for bamboo (for instance) which order should the events go? Should it be BlockGrowEvent - > BlockSpreadEvent so if BlockGrowEvent is cancelled BlockSpreadEvent is never called? or should the cancellation state of BlockGrowEvent be passed to BlockSpreadEvent, or what would be the best way to do that?
