### ISSUE TITLE
On server restart, the world save is a few minutes behind.

### ISSUE THREAD

**Issue by renorris** [PaperMC/Paper#2323]
### What behaviour is expected:
When the server reboots, the world should be exactly the same as it was right before the reboot (block and item locations)

### What behaviour is observed:
When the server reboots, blocks and items that were placed within a few minutes of  the server rebooting are non-existent.

### Steps/models to reproduce:
Reboot the server.

### Plugin list:
Plugins (15): AFKPlus, ChestSort, CoreProtect, DiscordSRV, dynmap, InventoryRollback, LokisDeathMessages, LuckPerms, OpenInv, OreReplacerPlugin, PingPlayer, ProtocolLib, SuperVanish, WorldEdit, WorldGuard

I try to use only 1.14 supporting and well-known plugins, to avoid weird bugs.

### Paper build number:
git-Paper-129 (MC: 1.14.3)

### Anything else:
not much

**Comment by NobleStrike** [comment]
Do you have a log of the shutdown? It probably got hung up on a plugin and didnt save the maps. By any chance was the restart also a computer restart or just the server?

**Comment by renorris** [comment]
I have a Linux systemctl script that runs save-all before it runs stop.

**Comment by NobleStrike** [comment]
Obviously that isnt working, a server should shut down plugins then save maps. Check your log to see why it was unable to save the maps.

**Comment by sebm253** [comment]
I am experiencing same problem sometimes.

**Comment by electronicboy** [comment]
You guys aren't running with save-off or something?

**Comment by sebm253** [comment]
Nope. I have automatic saving enabled as always and before reboot, I always execute save-all. Sometimes it's same as before and sometimes not.

**Comment by renorris** [comment]
Should I try enabling save-on then remove the manual “save-all” from my script?

**Comment by renorris** [comment]
On the stop command the server will automatically save the map by default correct? (without using save-all)

**Comment by DXUltimate** [comment]
DiscordSRV does this.
Another is WorldGuard.

Make sure they're updated to latest versions.

**Comment by wizjany** [comment]
First I'm hearing about this :thinking:

**Comment by electronicboy** [comment]
There is some concern in that save-all will only run an incremental save currently unless you tell it to flush, but a standard shutdown should work 100% as expected, do you guys have any server logs or anything?

Plugins should also be 100% irrelevant here unless you're deadlocking the server out and having to force-kill it before it tries to save 🤷‍♂

**Comment by DXUltimate** [comment]
All it does is just hang a little bit. Force stopping a server while it is
stuck in this motion causes it to not save chunks. You legitimately need to
wait the small amount of time it takes for the plugins to finish disabling
or else a slight rollback will happen causing some data loss in not only
chunks, but also inventories and whatnot.

This doesn't normally happen with any other plugins, other than
occasionally with older versions of CMI (which updates fix anyways),
DiscordSRV and WG. I'm saying that because I have the same "issue" and
really, it's not even an issue if you just leave it alone for the 10
seconds it needs. Although, on the other hand, plugin makers should
probably consider looking into this though in future releases. I'm 99% sure
this is not a paper issue.

**Comment by Spottedleaf** [comment]
save-all has since been changed to run a full save in later builds, please re-try on latest and see if this occurs again

**Comment by Chew** [comment]
As Spottedleaf has stated, fixes have been done to solve this, and likely many more over the past year. If you are still experiencing this or similar issues, don't hesitate to open a new issue. Have a good day and thanks for the report!
