### ISSUE TITLE
Simple Methods failed..

### ISSUE THREAD

**Issue by DispenserLP** [PaperMC/Paper#2328]
### What behaviour is expected:
The function Bukkit.getServer ().getName() is triggered when called and it will always display "Paper" if this name is given. There is no option to change this name!

### Paper build number:
Paper version git-Paper-132 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**Comment by Spottedleaf** [comment]
that api is no longer in 1.14

**Comment by DispenserLP** [comment]
ok, but how can I still query or determine the server name?

**Comment by electronicboy** [comment]
`getServerName()` no longer exists as it was removed upstream, if you mean `getName()`, then yes, the name of the server software implementation you're running is called Paper

if you want servers to have their own name that you can set, you'd need to handle that yourself, e.g. in a plugin config or using system properties

**Comment by DispenserLP** [comment]
But there is no way to edit system properties or server.properties, because since the last updates, they are not shown an option to edit the name and i don't want to use a config to get a servername.

**Comment by electronicboy** [comment]
The reason why it's no longer in server.properties is that it's not a standard option in there and was only there due to craftbukkit, Spigot decided to remove this in 1.14. There has been some consideration of us restoring that option, but it's pretty much best to be considered dead at this point

System properties can be set using startup flags, not ideal for public plugins and stuff, but for personal use would be fine
