### ISSUE TITLE
tps info/variable that plugins use doesn't work in paperspigot

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#237]
There are various plugins that can use for example {tps} to display current tps in tab, or wherever, but this doesn't work in paperspigot. changing to spigot the various plugins start to report the tps correctly.

some example plugins i tested with:
https://www.spigotmc.org/resources/ctsnc-%E2%98%85-animated-scoreboard-and-tablist-nametag-chat-%E2%98%85-protocol-hack-1-8-1-9.10714/
https://www.spigotmc.org/resources/tab.1448/

build 698
![example](https://cloud.githubusercontent.com/assets/18597710/14761623/e139dddc-0966-11e6-85f6-d05277c5a1f3.png)

**Comment by aikar** [comment]
This is because these plugins use a flawed method of calculating TPS. These "simple" methods that plugins typically use do not play well into how the server does TPS Catchup.

Spigot is using a flawed method of TPS reporting also. Paper uses an accurate TPS algorithm that Spigot refused to accept.

Plugins need to instead use the Paper Bukkit.getTPS() API or Spigot's MinecraftServer.recentTps variable in order to get more accurate readings (again: Spigot is flawed - only Paper can report your servers TPS correctly with /tps and the getTPS API)

If you wish to show correct TPS, please request plugin authors to integrate with Paper's API.

**Comment by ghost** [comment]
thanks, had no idea, but I know how to get it fixed now I guess
