### ISSUE TITLE
Server stopped responding a lot of time

### ISSUE THREAD

**Issue by Elikill58** [PaperMC/Paper#2431]
I'm using Paper-156 and i have a problem.

Event if there is any player on the server, sometimes i receive this message :
`[22:01:44 WARN]: Can't keep up! Is the server overloaded? Running 5054ms or 101 ticks behind`

Then, the server send a lot of stack trace which start with "It's not a bug" but i don't think so ...

https://pastebin.com/kbg4HXMb

(there is 700 lines of this loop ...)

Finally, this is the message that i receive when the server stopped responding :
http://prntscr.com/oq80ek

Just, i haven't ANY plugin, i'm running with default config (except server port and MOTD).
This is the line in run.sh that start the server :
`java -jar -Xms2048M -Xmx4096M -jar ./paper-156.jar`

Good bye

**Comment by successed** [comment]
where is timings ? please paste timings.

**Comment by Elikill58** [comment]
Hello,

I have remove it
This is full error of the loop stack trace:
https://pastebin.com/N5Uq04G1

And this is the full crash log:
https://pastebin.com/YaAKZ6wN

**Comment by Spottedleaf** [comment]
the full crash log should include all of the incremental warnings from the watchdog including the final thread dump made by it

**Comment by Elikill58** [comment]
The full crash log is really full, I paste everything about the final crash.
I want to say that i fix the problem while passing on the basic spigot-1.14.4 but maybe another people will get this error, that's why i don't close this issue.

**Comment by electronicboy** [comment]
Your server was taking too long to tick, spigot "fixes" this by refusing to tick entities after a certain time frame causing its own set of issues, overall you'd need to look into timings/your entity counts, as well as the full set of incremental warnings to see if anything stands out

Spigot also doesn't have incremental warnings, so should you trip the watchdog you would have no real indication of what the server was actually doing in the meantime, hence why we print out information between it taking too long so that there is a breadcrumb of what happened

For further support, please join irc/discord
