### ISSUE TITLE
RFC: Adding an updated anti-xray system to the server

### ISSUE THREAD

**Issue by FabioZumbi12** [PaperMC/Paper#248]
# Suggestion

Hello,
An user maded an Anti Xray for Spigot and is apllyed using built.jar, not a plugin. Is added as patch and to use wee need to run the patch on each update of Spigot.

Can you add this patch to paperclip? heres the patch: 
**EDIT: link to actual patch file**
https://gist.github.com/Zbob750/9dca5c669d00adbe38aab7709164f23d

The owner is: https://www.spigotmc.org/members/stonar96.3981/

**Comment by zachbr** [comment]
There are two extremely important things to keep in mind when considering this PR:
1) Maintainability
This does us no good if we have to scrap it the next time Mojang touches NMS again. In its current form there is significant maintenance cost.
2) Performance
Not everyone uses anti-xray. As such, any performance impact that occurs while this feature is disabled is completely unacceptable.

With those things in mind, we welcome public comment on this request.

Spigot PR, for reference, https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/pull-requests/61/overview

**Comment by 109C** [comment]
@Zbob750 The link is dead, or at least not accessible.

**Comment by Gabscap** [comment]
Its not public. You need to sign Spigots CLA.

**Comment by zachbr** [comment]
@109C The way Spigot/Stash has their PR permissions setup, you must be logged into their Stash server in order to see PRs. Nothing I can do about that

Edit: and yes to get an account there you must have signed SpigotMC's CLA.

**Comment by stonar96** [comment]
@Zbob750 I don't see that much problems with maintainability. There are maybe some field and method renamings required from update to update and if Mojang really discards the whole concept again, just removing this patch would be the worst case scenario. So why not add it as long as it works? I am also sure that there is almost no performance impact if Anti-Xray is disabled except for some boolean checks. Furthermore the performance of the obfuscator is amazing and has low impact even in synchronous mode.

The patch file of my PR on Spigot Stash is outdated and does not contain all features and bug fixes. I don't care about it anymore because it will most likely not be merged as md_5 said to me in a conversation.

I want to add some more comments and do some cleanup in the current patch file. Therefore I will create an own PR for this here to keep things updated, if that's okay.?

Currently I am very busy and I am new to GitHub so I have to get into it first. Therefore it may takes a few days.

**Comment by zachbr** [comment]
Yes that's fine. Don't worry about how long it takes, most of us are extremely busy on the weekdays anyway.

Let us know when you do please. Thanks

**Comment by stonar96** [comment]
@Zbob750 Okay, I will. Thanks.

**Comment by zachbr** [comment]
We can move discussion of this over to the PR when everyone gets time to start with that.

**Comment by intangir** [comment]
i think this guy has been involved in the new 1.9 support for orefubscator, might be helpful to this process @Aleksey-Terzi

**Comment by Techcable** [comment]
I think the performance hit would come form `Lock.waitUntilUnlock()`. We could replace it with a no-op when anti-xray is disabled.

**Comment by zachbr** [comment]
@stonar96 Lose interest in this?

**Comment by FabioZumbi12** [comment]
The plugin Orebfuscator updated to latest build of Minecraft! Then i think embedded anti-xray now is optional, but if you have in mind a optimized and more eficient anti-xray with paper, i still agree :)

**Comment by Postremus** [comment]
Some points I would really like to see addressed in an integrated anti-xray version:
- no performance use, if anti-xray is disabled
- extendibility through plugins (for example, through the service manager)
- ability to completly disable anti-xray for some players without significant performance loss
- timings integration
