### ISSUE TITLE
start.sh missing 

### ISSUE THREAD

**Issue by Thecoolwolf2017** [PaperMC/Paper#2483]
### What behavior is expected:
a server restart

### What behavior is observed:
no restart following message:
Startup script './start.sh' does not exist! Stopping server.
### Steps/models to reproduce:
typing the restart command

### Plugin list:
N/A

### Paper build number:
git-Paper-175

**Comment by Prof-Bloodstone** [comment]
The server doesn't know what it means to restart - i.e. what flags were used. That's why it runs a script that starts it on shutdown when you do `/restart`. The file itself is configurable in `spigot.yml:settings.restart-script`.

You'd need to create such script - that waits for the server to shutdown (port might be still in use etc) and the starts the server with your selected flags.

**Comment by Thecoolwolf2017** [comment]
> 
> 
> The server doesn't know what it means to restart - i.e. what flags were used. That's why it runs a script that starts it on shutdown when you do `/restart`. The file itself is configurable in `spigot.yml:settings.restart-script`.
> 
> You'd need to create such script - that waits for the server to shutdown (port might be still in use etc) and the starts the server with your selected flags.

how do you make one then

**Comment by Prof-Bloodstone** [comment]
It'll greatly depend on how you start your server.

i.e. if you're using screen, you need to make sure it creates the screen if it doesn't exist, it can replace current screen etc. It'll be very specific to how you have your server deployed.

I'd prefer not to give any ready scripts, since they can possibly do harm if not tailored to your needs.

I'd recommend heading over to [Discord server](https://discordapp.com/invite/papermc), you can get better help there. Comments here unnecessarily notifies maintainers.

**Comment by electronicboy** [comment]
The contents of a start.sh file are 100% depenedant on your setup, the usage of start.sh is also discouraged due to some unique issues that it causes which can easily be solved using alternative measures, such as a loop in your startup script.

if you require further assistance around this, please use the discord/irc/forums
