### ISSUE TITLE
Anti-XRay Bypass Permission

### ISSUE THREAD

**Issue by Kitsune42k** [PaperMC/Paper#2492]
We switched to papers own anti-xray on our server and works great so far. Problem is, we need a bypass permission for our server team.

A permission like "paper.antixraybypass" would be nice.

We previously used Orebfuscator but apparently papers own anti-xray seams to be bette performance wise, have i been told.

**Comment by zachbr** [comment]
This has been dismissed in the past because it operates at a packet level where player information is not available. I expect that has not changed, if so this will be closed as a wontfix.
If something has changed where this is now possible without substantial changes to code or performance it can be added.

**Comment by Spottedleaf** [comment]
we still work at a packet level

**Comment by Kitsune42k** [comment]
Correct me, if im wrong, but don't do all efficient anti-xray plugins operate on package level?

**Comment by electronicboy** [comment]
orebfuscator uses protocollib, which means that it's basically forced to see each packet sent to a player as an individual packet if they wanna work on it, meaning that they'll have more work to do in general but are in a much better place to pull these types of changes off

It is theoretically doable, however, the best way I can see to pull that off would be to store a copy of the obfuscated and unobfuscated data so that we can pick which one to send to the player, I'm not really sure if there is a clean way that we can actually get the target player at the level we'd need to implement these changes, however
