### ISSUE TITLE
Damageable.damage with DamageCause

### ISSUE THREAD

**Issue by Dymeth** [PaperMC/Paper#2507]
I did not find a way to inflict fire damage, for example.

Methods
_Damageable.damage (double amount, @Nonnull EntityDamageEvent.DamageCause cause)_
and
_Damageable.damage (double amount, @Nullable Entity source, @Nonnull EntityDamageEvent.DamageCause cause)_
would solve my problem.

I considered some solutions to the problem:
1) Calling _EntityDamageEvent_ on your own plugin. Is a bad way, because then you will have to calculate the motion vectors yourself, calculate armor resists, take advancements criteria to attacking player, and so on.
2) Using NMS: Entity.damageEntity(DamageSource source, float amount)
3) _Map<Entity, DamageCause>_. Before calling _Damageable.damage(...)_ put the value, after calling delete it. Inside the _EntityDamageEvent_, trying to get the reason from this map. If the value is not found, use _event.getCause()_.
The problem is that this will only allow you to determine the cause with your own plugins. Core and third-party plugins define the cause as _DamageCause.CUSTOM_.
4) Using _Entity.setLastDamageCause(...)_ before calling _Damageable.damage(...)_ will cause the same problem.
The problem with determining the cause of other plugins can be solved if you use reflection to set the cause inside the event with hight priority (_org.bukkit.event.EventPriority.LOWEST_).

**Comment by electronicboy** [comment]
This is ultimatly a double edged sword:

Plugins expect to be able to determine the cause of damage properly, be that from fire or plugins; The lack of ability to provide context to the event is an overarching limitation across the entirety of bukkit; At the same point, this is custom damage andnot caused by fire, even if in your context it is

I can see pros for exposing it, I can also see why bukkit didn't
