### ISSUE TITLE
Teleport using Nether dimension breaks with modified Essentials

### ISSUE THREAD

**Issue by BaltimoreCalling** [PaperMC/Paper#2521]
### What behaviour is expected:
Player uses a command to invoke a modified version of Teleport.java. (Commands like /tp, /tpa, /spawn, /home) Player should be teleported to the nether briefly then immediately teleported to their destination. 

### What behaviour is observed:
Player is sent to, and stuck in the nether, unable to remove themselves via said commands.

### Steps/models to reproduce:
Modify the EssentialsX file: Teleport.java
[Pastebin](https://pastebin.com/cVqGJyDx)

### Plugin list:
EssentialsX (Modified Teleport.Java) version: EssentialsX-2.17.1.0.jar

### Paper build number:
Versions: 173-176. The plugin works correctly on versions 172-

### Anything else:
May be an issue with Async Chunk api/io/loading commit. But, we set the 'async-chunks:' Boolean to:
 'enable: false'

All other paper settings are consistent from version to version. 

Our Teleport implementation works under the current version of Spigot: CraftBukkit version git-Spigot-065a373-6ed8a18. 

It also works with paper on versions 172 and below.

**Comment by Spottedleaf** [comment]
If by stuck you mean placed into the nether I'm not surprised. Look at your code, you have not enforced ANY order for the teleport. In fact it's basically guaranteed that if you set the tp's to async, with one of them being some random location, and the other being their current, that the chunk will be loaded for the current location, thus executing before the random location (since the random one will have to load).

So this is not an issue on our side.

**Comment by BaltimoreCalling** [comment]
Thank you for responding. I'll take that info to our development team.
