### ISSUE TITLE
NullPointerException when using Skript commands in command blocks

### ISSUE THREAD

**Issue by RoyCurtis** [PaperMC/Paper#256]
Commands registered by [Skript](https://github.com/bensku/Skript), which are custom written via scripting files, throw a `NullPointerException` when they are used in command blocks. This behavior is observed only on PaperSpigot and not Spigot.

I believe this is due to an [unpopulated `timings` field](http://i.imgur.com/NN8vbxq.png) of the `PluginCommand` instance that [Skript creates and registers for each command](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/command/ScriptCommand.java#L253). In Spigot, [it appears that this field is populated](http://i.imgur.com/XVZZp2k.png), though I am unsure where.
# Details
- `Paper version git-Paper-712 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)`
- [Bensku's fork of Skript dev13d](https://github.com/bensku/Skript/releases/tag/dev13d)
- Default Skript configuration and aliases
- Default server config with `enable-command-block=true` in `server.properties`
# Testing
- Tested with vanilla commands (e.g. `/me`) and other plugin commands (e.g. EssentialsX's `/msg`) - **no issue** 
- Tested Skript commands in-world and in-console - **no issue**
- Local PaperSpigot b712 server with 1 plugin (Skript) - **reproducable**
- Local Spigot server; same configuration and plugins - `CraftBukkit version git-Spigot-e6f93f4-935f18b (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT` - **no issue**
- Public PaperSpigot b706 server - **reproducable**
  - Plugins: dynmap, WorldEdit, Skript, TerrainControl, zPermissions, Chairs, WorldBorder, TicketMaster, WorldGuard, ProtocolLib, Multiverse-Core, WoodCutter, HappyPet, SQLibrary, Multiverse-Portals, Vault, Prism, Essentials, PerWorldInventory, LWC, SignShop, VanishNoPacket, CraftBook, Multiverse-NetherPortals, PurpleIRC
# Reproduction
1. Set up a new PaperSpigot server with Skript and `enable-command-block=true` in `server.properties`
2. After starting server once, go to `plugins/Skript/scripts` and delete all files
3. [Create a new file `commands.sk` with contents from linked gist](https://gist.github.com/RoyCurtis/2bc50d17d13858ed9953ad97f9733c60)
4. In console, execute `sk reload all` to reload Skript
5. In console, op yourself
6. In-world, execute `/gamemode 1` and then `/give @p minecraft:command_block 1`
7. [Place command block somewhere and lever against it](http://vanderprot.gamealition.com/img/891ed.jpg)
8. [Right-click command block and set command to `servertime` (or `stime` or `date` or `/servertime`)](http://vanderprot.gamealition.com/img/10ef6.png)
9. Toggle lever a few times
## Expected

_Based on experience with Spigot 1.8.9 and Spigot 1.9.2_

Command successfully executes; server's real-world date and time is printed on console and in chat
- [Video reproduction](http://vanderprot.gamealition.com/img/48ccb.mp4)
- [Internal state of `/servertime` Skript command in debug-time](http://i.imgur.com/XVZZp2k.png)
## Actual

Command fails to execute and throws exception to console
- [Video reproduction](http://vanderprot.gamealition.com/img/7a9ab.mp4)
- [Stacktrace](https://gist.github.com/RoyCurtis/fa0b4b1db50924760f004fc02dc77e08)
- [Failing code (decompiled `patched_1.9.2.jar`)](http://vanderprot.gamealition.com/img/00f46.png)
- [Internal state of `/servertime` Skript command in debug-time](http://i.imgur.com/NN8vbxq.png)
# Notes

I am unfamiliar with PaperSpigot or its internals, so my assumption that this is a PaperSpigot issue may be incorrect. As far as I could determine, Skript itself never populates or otherwise handles the `timings` field of registered commands.

My rationale for reporting this issue:
- If it is a PaperSpigot caused issue, this is an incompatibility that breaks an existing plugin (Skript)
- It is possible that this is a bug with any plugin that creates/destroys and de/registers commands during runtime

**Comment by zachbr** [comment]
This appears to be because Skript is registering a CommandMap directly to the Command, rather than properly registering via the CommandMap. This bypasses a large amount of logic internally, including our timings registration.

You can see this behavior here:
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/command/ScriptCommand.java#L271

Our Timings v2 system does not account for this (wrong) behavior. And doing so would just break things for people that do it the right way. As such, we cannot fix this on our end directly.

I began working on PRing a fix to Skript, and then I discovered their abomination of a workflow. They use maven for dependencies only, not building. And since I see no reason to go get Eclipse and set up all of that just to build Skript I assumed I could just re-enable the disabled compiler plugin in Skript's pom. Wow was I wrong. (Full rant available [here](https://korobi.io/network/spigot/channel/Paper/logs/2016/04/30/#L377))

This is something they'll have to take care of on their end.
Stop registering CommandMaps directly to the Command, and start registering Commands via the CommandMap, as intended. Shouldn't even be that big of an ordeal for them.

I only hope whoever does it already has their workspace setup, or the patience and/or time to deal with their workflow.

**Comment by zachbr** [comment]
Ugh, rant aside, we can probably add some ugly workaround code for compat's sake.

I still urge Skript to fix this issue (and their workflow)

**Comment by RoyCurtis** [comment]
I was worried this would be a Skript issue; again, I did not know enough about PaperSpigot, so I opted to report here first. Thank you very much for the prompt and informed response!

A workaround would be cool, but if Skript is registering commands incorrectly then I agree this should be fixed. I may attempt to resolve this.

If you are curious, I also opened an issue a while ago on the workflow: https://github.com/bensku/Skript/issues/56 This is also something I am attempting to resolve.

**Comment by zachbr** [comment]
I have just pushed a workaround via 5f98ec08a5aa432c82e6f241cd42df9c50f8ac3b
This is still not the proper way to do command registration and I still urge them to resolve this properly. Hopefully us fixing this does not make them think it unnecessary to do so.

Edit: Build 715 and above will include this workaround.
