### ISSUE TITLE
Insane mob spawning on the ground when player's y-coordinate is too high

### ISSUE THREAD

**Issue by rudde0** [PaperMC/Paper#2598]
mob-spawn-range: 3
view-distance: 4
monster spawn limit(bukkit.yml): 27
monster spawn per tick(bukkit.yml): 4

Mobs are spawning too fast depending on player's y-coordinate

### Paper build number:
1.14.4 build 196

https://youtu.be/a7fc8FKRqxg

https://youtu.be/k_2buwkCdvk

**Comment by ghost** [comment]
This is the mechanics of the game, not a bug.

**Comment by rudde0** [comment]
> This is the mechanics of the game, not a bug.

I already know that but its need to be balanced.

**Comment by Spottedleaf** [comment]
I don't see an issue here

**Comment by rudde0** [comment]
Is Paper released for only bug fixes?

**Comment by Spottedleaf** [comment]
I'm saying I don't see a difference in terms of y level

**Comment by electronicboy** [comment]
This is really down to the core mechanics of how spawning works, there is an option in paper.yml to limit mob spawns per player which can limit some of the potential side effects from this, but, overall; this is really just a case of how vanillas spawning algorithm works, if your player is in an area in which mob spawns are easily viable, many mobs will spawn; Having your view distance so low also implicates this, as on the ground, the actual area in which mobs can spawn is harshly reduced; 

using the per player limits and reducing the mob spawn limits is your only real way to fix this beyond increasing your view distance so that the areas that mobs can spawn in will be 'normal' (i.e. you'll have more mobs while on the ground just like when you're in the air)

edit: I forgot that the y distance was not really considered, but the fact that you're moving around in these videos (pointed out by spotted) is going to have an impact around how the despawning and spawning mechanisms work, your limited view distance is also going to have a play on how mobs are spawned in the world
