### ISSUE TITLE
per-player-mob-spawns: true enables spawns next to other players

### ISSUE THREAD

**Issue by dege16** [PaperMC/Paper#2614]
### What behaviour is expected:
mobs will not spawn within 24 blocks of another player

### What behaviour is observed:
with per-player-mob-spawns: true, mobs will have a chance to spawn within 24 blocks of another player

### Steps/models to reproduce:
set per-player-mob-spawns:true
have 2 players on a server with only 1 mob spawning platform available
have 1 player stand on the platform, have the other player stay more than 24 blocks away
see mobs spawn within under 24 blocks of player 1

### Paper build number:
196

### Anything else:
verify that all players are outside the spawn range of mobs before spawning

**Comment by kickash32** [comment]
That setting only changes which chunks are selected for mob spawning and how many mobs they are allowed to spawn. It does not touch how mobs spawn inside a chunk, like if it should cancel the spawn since it's too close to a player. Unless I see hard proof of this, I'm going to say this is impossible.

**Comment by Brokkonaut** [comment]
I can confirm this bug.

**Comment by ghost** [comment]
You probably didn’t set the "mob-spawn-range" and "despawn-ranges.hard" settings correctly, which is why you got such an error.

Take the number of loaded chunks by the player, subtract 2 and the resulting value is "mob-spawn-range" and "despawn-ranges.hard" to follow the vanilla mechanics.

See: https://minecraft.gamepedia.com/File:Mob_spawning_ranges.png

**Comment by Brokkonaut** [comment]
hu?

I can reproduce this with everything but per-player-mob-spawns set to default values (new generated server config) and no plugins. Just do what daashton said to reproduce it.

**Comment by Brokkonaut** [comment]
This is still an issue.

**Comment by Laarryy** [comment]
I did my very best to reproduce this on 1.19.1, but I can't coax mob spawns within another player's no-spawn range. I'm going to close this, and if it's still a problem that anyone else can reproduce, please open a new issue with detailed steps to do so. Thanks!
