### ISSUE TITLE
Day Resets Itself

### ISSUE THREAD

**Issue by KrNel** [PaperMC/Paper#266]
### Description of issue:

The Day (F3, Local Difficulaty line, last parameter) will reset itself.

I went back to Spigot, and the day is back to 19022, instead of Day 1 last night, and Day 4 this morning. It seems odd that in 8 hours the server only progressed by 3 days on PaperSpigot.
### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit.yml: http://pastebin.com/M5iCxT9c
spigot.yml: http://pastebin.com/eaLixKu3
paper.yml: http://pastebin.com/hQECTZrT
server.properties: http://pastebin.com/KLBz9p2J
### Paper build number:

paperclip-717.jar
I am no longer using this jar, so I can't output the /version. This was the .jar file I was using.
### What behaviour is expected:

Day not resetting.
### What behaviour is observed:

Day is resetting.
### Steps/models to reproduce:

No idea. It just happens.
### Plugin list:

Plugins (18): CoreProtect, dynmap, WorldEdit, WeatherVote, FancyShop, Permission
sEx, Vault, CommandBook, Votifier, UserList, WorldGuard, Admin-Chat-Channel, OnT
ime, CheckMyInventory, ChatEx, Dynmap-WorldGuard, GriefPrevention, JDynmapGriefP
revention

**Comment by Black-Hole** [comment]
This is a workaround for banner waving: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0099-Waving-banner-workaround.patch

On the server the day will progress, it's only send to the client this way. Do you have a use case scenario where the day displayed in the client matters?

**Comment by Gabscap** [comment]
Link to the associated PR: #116

**Comment by zachbr** [comment]
As you can see from the linked patch file and PR. This is a workaround and client-side only.

**Comment by KrNel** [comment]
But I am not the only one having this issue. It's not just my client. Is this going to be fixed in the future for PaperSpigot servers having clients show the correct day on the server? Thanks.

**Comment by MrPowerGamerBR** [comment]
@KrNel does it matter that the client is showing the wrong day?

It only affects the client, not the server.

**Comment by zachbr** [comment]
Clients will show the wrong local time, the actual day/night cycle is controlled by the server and is unaffected.

Because they will show the wrong world time they will also show the wrong local difficulty. This has zero effect on anything other than the text in the f3 menu. It is necessary workaround for banner waving to function, and being that that workaround's only downside is this, and that you're the first to complain, I'd say its working as intended.

For the last time: This is client-side only, has zero effect on anything, and will not be changed unless you can provide a substantive reason other than "but its a problem"
