### ISSUE TITLE
Local Difficulty Too Low

### ISSUE THREAD

**Issue by KrNel** [PaperMC/Paper#267]
### Description of issue:

Local Difficulaty is 2.25-2.27 by default. On Spigot original, it is 3.18-.3.38 by default. This affects spawning of mobs.

Last night on papaerspigot-717 the LD was 2.25, this morning it was 2.27 at spawn. I went back to Spigot, and the Local Difficulty is automatically up by 1 point, from 2.27 to 3.38 at my spawn.
### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit.yml: http://pastebin.com/M5iCxT9c
spigot.yml: http://pastebin.com/eaLixKu3
paper.yml: http://pastebin.com/hQECTZrT
server.properties: http://pastebin.com/KLBz9p2J
### Paper build number:

paperclip-717.jar
I am no longer using this jar, so I can't output the /version. This was the .jar file I was using.
### What behaviour is expected:

Local Difficulty to be higher as it is on Spigot.
### What behaviour is observed:

Local Difficulty is too low.
### Steps/models to reproduce:

Use the paperclip-717.jar compared to spigot-1.9.2,jar.
### Plugin list:

Plugins (18): CoreProtect, dynmap, WorldEdit, WeatherVote, FancyShop, Permission
sEx, Vault, CommandBook, Votifier, UserList, WorldGuard, Admin-Chat-Channel, OnT
ime, CheckMyInventory, ChatEx, Dynmap-WorldGuard, GriefPrevention, JDynmapGriefP
revention

**Comment by zachbr** [comment]
Client-side values are not going to be correct. (Nor do they need to be, client doesn't do anything with that info) because of GH-266.

I will make sure it's being handled properly server side when I get home, but I'm almost 100% sure it's working fine.

Expect this to be closed soon.

**Comment by zachbr** [comment]
See GH-266.

**Comment by KrNel** [comment]
I have tested two times. On paper spigot, the spawn rate is lower in the nether for Withers skels. On regular spigot, with difficulty showing properly, the Wither skels spawn much more frequently. What am I supposed to do with a workaround patch code? Recompile paper spigot myself? LOL.

**Comment by zachbr** [comment]
You are not, listening, reading, etc.

If there is an issue with them spawning it is unrelated to this as we have said several times now. Feel free to get off your high horse and check the code itself instead of constantly arguing about it.

Local difficulty remains sane, the values sent to the client are not what the server actually uses.
Spawn rates are also extremely volatile and depend on a number of factors, so your current anecdotal evidence really isn't helpful.

If you believe there is a separate issue related to spawning, open an issue and follow the template.
If after all of this you still believe the workaround patch, (that again only modifies values client-side), is responsible, please go somewhere else to complain about it.
