### ISSUE TITLE
Fix instant grow farm setting not working

### ISSUE THREAD

**Issue by VizuaaLOG** [PaperMC/Paper#2693]
### What behaviour is expected:
Zero tick farms should start working.

### What behaviour is observed:
Zero tick farms are not working.

### Steps/models to reproduce:
Set the zero tick fix setting to false and then build a zero tick farm.

### Plugin list:
CommandHook
CoreProtect
Gravy
Luck Perms
OpenInv
PluginConstructureApi

### Paper build number:
226

### Anything else:
I've been updating to the latest version just in case it was a known bug but each time players report that the zero tick farms do not work.

**Comment by electronicboy** [comment]
Have you tested this yourself or just relying on word of players? Others have been using this setting without any issues to my knowledge, nor from looking at the code could I see how this would be the case

**Comment by VizuaaLOG** [comment]
Initially, I was just relying on the word for players, just tested myself using one of Ilmango's designs (supposedly still working according to Reddit, I don't really use zero-tick farms). 

[Screenshot of the farm](https://prnt.sc/py8cgs) based on [this design](https://www.youtube.com/watch?v=2wVzDC4bsZk&feature=youtu.be).

Sugar cane doesn't grow, stays placed on the block though. Bamboo just breaks the moment you start the farm (although this could be lighting-related even though I was outside at the time). The sugar cane I believe should grow still though.

**Comment by itsTyrion** [comment]
I can confirm this. 
![grafik](https://user-images.githubusercontent.com/17730120/69918259-42ede100-1470-11ea-8589-812f8a81cb1d.png)

This test design doesn't work on Paper 1.14.4 (226), but it works on Spigot. 
Place a button on the piston that has a block next to it, press the button, the blocks will be pushed, the button pops off, the piston instantly retracts without pulling the blocks. 

On Spigot/Bukkit/Vanilla, after repeating this a hand full of times, the cactus will grow by 1 block and pop off due to the fence block. 

On latest 1.14.4 Paper however, the cactus didn't grow after 20 presses. automating this using a fast clock doesn't work, either.

**Comment by VacantFiend** [comment]
> I can confirm this.
> ![grafik](https://user-images.githubusercontent.com/17730120/69918259-42ede100-1470-11ea-8589-812f8a81cb1d.png)
> 
> This test design doesn't work on Paper 1.14.4 (226), but it works on Spigot.
> Place a button on the piston that has a block next to it, press the button, the blocks will be pushed, the button pops off, the piston instantly retracts without pulling the blocks.
> 
> On Spigot/Bukkit/Vanilla, after repeating this a hand full of times, the cactus will grow by 1 block and pop off due to the fence block.
> 
> On latest 1.14.4 Paper however, the cactus didn't grow after 20 presses. automating this using a fast clock doesn't work, either.

This exact design works fine for me. 16 button pushes in Vanilla/Paper 226 grows the cactus 1 block with `fix-zero-tick-instant-grow-farms: false` in paper.yml

https://streamable.com/qlqe5


Sugarcane takes a few seconds to grow with that design because it has 15 growth stages. I don't see any bonemeal in your inventory in the bamboo screenshot. You need to bonemeal it into an actual shoot before you can zero tick it or it will just pop off.

**Comment by itsTyrion** [comment]
There's an option that disables it by default? oof

**Comment by BillyGalbreath** [comment]
> There's an option that disables it by default? oof

You mean it fixes a bug?

**Comment by VizuaaLOG** [comment]
Have confirmed again that even with `fix-zero-tick-instant-grow-farms: false` the zero tick farms are just not working. [Here's the paper.yml](https://pastebin.com/q0rAn682), just in case I'm putting the config in the wrong place. Currently running build 226.

**Comment by BillyGalbreath** [comment]
> Have confirmed again that even with `fix-zero-tick-instant-grow-farms: false` the zero tick farms are just not working. [Here's the paper.yml](https://pastebin.com/q0rAn682), just in case I'm putting the config in the wrong place. Currently running build 226.

Look at line 63 of your paste. That's the proper spot. Not on line 26 where you put it manually.

**Comment by VizuaaLOG** [comment]
@BillyGalbreath Doh! I did not see that default section! Glad I sent the paste now! Going to quickly run away and pretend I knew that 😛 !

I can confirm it's working now lol. Just a quick question then, any new config added in future builds, does it automatically update that default section?
