### ISSUE TITLE
Server crash (probably light problem)

### ISSUE THREAD

**Issue by Dymeth** [PaperMC/Paper#2744]
### Link/paste of stack trace:
https://pastebin.com/raw/4geBqb8v

### Plugin list:
AuthMe, Brewery, BroadCastMessage*, Chatty*, CoreProtect, FastAsyncWorldEdit, NametagEdit*, PermissionsEx*, PlaceholderAPI, PlugMan, ProtocolLib*, rHideTags*, SerialKey, SimpleJail*, SimpleSit*, SkinsRestorer, StopNetherTrap, TemporalWhitelist*, Vault, WorldEdit

### Actions to reproduce (if known):
No ideas

### Paper build number:
Paper version git-Paper-236 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
`[13:14:12] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 174719ms or 3494 ticks behind`
Your server was overloaded, you'll need to look into your system usage/use tools like yourkit/visualvm to see what is going on when this occurs if you can reproduce it

**Comment by Dymeth** [comment]
> `[13:14:12] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 174719ms or 3494 ticks behind`
> Your server was overloaded, you'll need to look into your system usage/use tools like yourkit/visualvm to see what is going on when this occurs if you can reproduce it

Server overload cannot be the reason for its instant stop? Watchdog did not warn of freezes for 10 seconds or more.
Moreover, there are no mentions of any plugins in the call stack, and the hangs occurred for about 3 minutes of real time, which is unlikely to be the result of performance problems, I think.
My only assumption is that the system time has really changed. But even in this case it is not clear why the server was stopped

**Comment by electronicboy** [comment]
The server stopped because watchdog wasn't ticked in 3 minutes, that's basically how watchdog works; your JVM was in a state where it wasn't able to run the watchdog thread for 3 minutes and when it ran again, it saw that the server hadn't ticked in time and went to stop; This is not within the realms of a paper issue or one that we can even begin to look into as this is more going to be an issue with your environment; Paper itself wouldn't pause the JVM itself
