### ISSUE TITLE
followRange isn't working

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2751]
So i've been trying to change the followRange on mobs but it does not work as it usually does.

Try: /summon zombie ~ ~ ~ {Attributes:[{Name:"generic.followRange", Base:100.0}]}

That should change the follow range of the mob to 100 but it does not. It stays at around 32 blocks. It might be the case that the mob has to be aggroed before it kicks in which isn't normal aswell. 

Thank you for looking into this bug. Our players would very much appreciate it.

**Comment by electronicboy** [comment]
per the discussions on discord,
Have you tested against spigot/craftbukkit?
Are you sure that your entity activation ranges aren't interfering?

**Comment by aikar** [comment]
Im glad it was defaulted off as this was wrong. If you want an entity to target as far as follow, you need to set both. 

These are separate values for a reason. Target controls aggression range, follow controls pursuit range. A monster can follow you to farther distances if it has already targeted you.

Honestly id prefer it to not even be an option, as it's literally just to avoid correctly configuring the entities attributes.

don't really agree with features for user error.

**Comment by wizjany** [comment]
I brought this up but the argument was "it worked this way before 1.14"...

**Comment by aikar** [comment]
It didn't in the past. I do believe I had to restore "Target Range" as an attribute in my fork, so I guess that may be the issue here is I forgot in vanilla mojang removed target range as an attribute....

So i guess its likely not even possible in vanilla due to the removed attribute and people depend on this..

What people actually want is a return of target range too.

**Comment by electronicboy** [comment]
I don't recall there ever being a target range attribute, mc wiki also points to followRange being used for targeting; I mostly pulled this for the reason that there is no configurable way of changing that, I'm more inclined for a target range attribute if we wanna go for that instead of a setting to treat the follow as target/follow

That attribute was added by yourself here: https://github.com/starlis/empirecraft/commit/a2839778251ee9561ddaa248b7c4af0695f1a88e
Unless I gotta go up the history more for that, but that commit is against 1.11
