### ISSUE TITLE
Make server brand configurable

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2788]
Please make the server brand, that appears on the third line of the client debug screen surrounded in quotes, configurable.

Currently it is hardcoded to `Paper`.

Alternatively one has to intercept `PacketPlayOutCustomPayload`, which takes around 225μs on the server thread every time a player connects.

**EDIT:**
Eventually I managed to reduce the time taken to intercept the packet to around 10μs.

**Comment by Draycia** [comment]
not the nanoseconds D:

**Comment by zachbr** [comment]
Declining for the same reason we don’t make the other branded areas of the server configurable.

**Comment by ghost** [comment]
May I know the reason?

**Comment by zachbr** [comment]
There aren’t a lot of advantages to maintaining Paper. We do it because we enjoy it and some of us use it. With that comes hours and hours of work writing code, maintaining code, putting out fires, and trying to keep the community from ripping itself apart.

One of the most positive things we get out of it is the pride in seeing something we worked on, something with our name, used and enjoyed by so many. The minimal branding that 99% of players will never see is part of that. Ultimately, we think that this is a very tiny thing that most people will never mind or care about anyway, and a more than fair trade.

That is why we have constantly resisted when server owners have asked us to make various aspects of the server branding configurable.

I hope you find that answer satisfying. If not, as you’ve said it is quite cheap to change at runtime, or you can just maintain your own fork and do whatever you want with it.

**Comment by ghost** [comment]
Thank you very much. I do not think it's cheap, quite the opposite.

**Comment by zachbr** [comment]
Feel free to fork the project then.
