### ISSUE TITLE
Cobblestone Generator - Water Flow Issue

### ISSUE THREAD

**Issue by crazyspider12** [PaperMC/Paper#2816]
https://www.youtube.com/watch?v=vsWm6F9Ggc4

ISSUE: Water spread speed isn't the same as it would be on a single-player world.
OBSERVATIONS: Upon creating a system for automating the production of cobblestone, when pushed with a piston extruding to an excavator, only the outlines on the pistons are being pushed. This is due to the water not being able to spread fast enough under the lava to turn the middlemost blocks into stone.

Version: git-Paper-29

**Comment by ghost** [comment]
Is there any comment on why this was closed? I happen to have the same issue. I'm fairly certain the issue is not with water but with lava. It spreads when it should not. This is important to that specific design and other things that rely on consistent and 'correct' lava timings. It seems to happen fairly randomly but often. Is it possible lava is getting random ticked evern though this was removed?

**Comment by electronicboy** [comment]
It was closed because the ticket author did not fill in the template and
was missing info
