### ISSUE TITLE
Too many unacked block actions, dropping... START_DESTROY_BLOCK

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#2913]
### What behaviour is expected:
No errors in client console log while breaking blocks.

### What behaviour is observed:
Tested in single player clean vanilla (no mods, no resource packs), vanilla clean server, latest spigot clean server and latest paper clean server. **When breaking blocks in survival,** for example chopping trees, console client log starts spamming [Render thread] Too many unacked block actions, dropping (coordinates), START_DESTROY_BLOCK). **Only happens in Paper server**.

### Steps/models to reproduce:
Start your clean Paper 1.15.2 server. Open your client 1.15.2 (vanilla, MultiMC) and your client console log. Log in and start chopping trees and leaves in **survival mode** (for example, or mining blocks). 

### Plugin list:
None, clean.

### Paper build number:
git-Paper-79 (MC: 1.15.2)

### Anything else:
Video example link:
https://youtu.be/Ahz8ye4dqZ8

Reported to Jira. Moderator told me is a modified server problem... [MC-170438](https://bugs.mojang.com/browse/MC-170438)

Sorry for my bad english,

Thanks!

**Comment by Brokkonaut** [comment]
Maybe this does no longer work in 1.15?
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0394-Fixed-MC-156852.patch

I did not yet have time to test it, but it might be related

EDIT: I did some testing and removing that patch fixes the issue with blocks that should break but do not break. I did not see any negative effects after removing the patch and the mojang bug tracker also says MC-156852 is fixed in 1.15, so i think it should be removed.

**Comment by electronicboy** [comment]
Ah, #BlameMinidigger (jkilybb)

https://github.com/PaperMC/Paper/pull/2396 was restored back here, sending both, during the work for 1.15, it was changed and slipped by and changed to replace, saying that, if the underlying issue is now fixed, that patch can be dropped
