### ISSUE TITLE
Anti-xray doesn't obfuscate blocks touching lava

### ISSUE THREAD

**Issue by kaanakduman** [PaperMC/Paper#2940]
**Is your feature request related to a problem? Please describe.**
X-rayers on my server are able to see hidden-blocks that are touching lava when I would expect Paper's anti-xray to obfuscate them. For example, if a diamond ore is touching lava on one side and covered in stone on all other sides, it isn't obfuscated when it should be.

**Describe the solution you'd like**
Maybe obfuscate hidden-blocks unless the block is touching water or air.

**Comment by BillyGalbreath** [comment]
I believe you are forgetting that lava doesnt always take up a full block. There is a small area at the top of lava that can expose the block next to it.

Pardon my crude drawing skills, but lets pretend purple is stone, blue is diamond ore, and red is lava. That diamond is exposed to air, even though the block directly beside it is lava.

![image](https://user-images.githubusercontent.com/332527/74094379-d1509580-4aa5-11ea-933b-9058c15feaca.png)

Anti XRay only checks the surrounding blocks, not the adjacent ones. Adding a check to the adjacent blocks, too, would just slow down the process even more and isnt worth it, imho.

**Comment by kaanakduman** [comment]
Source lava covers the bottom 14 rows of pixels of neighboring blocks and leaves the top two rows exposed. However, with the default texture pack, the diamond ore texture resembles stone for the top two rows of pixels. So players shouldn't be able to tell if the block is stone or diamond.

**Comment by HexedHero** [comment]
> Source lava covers the bottom 14 rows of pixels of neighboring blocks and leaves the top two rows exposed. However, with the default texture pack, the diamond ore texture resembles stone for the top two rows of pixels. So players shouldn't be able to tell if the block is stone or diamond.

No one cares about the texture of the block, you CAN see the block itself so its shown. Its how it works and isn't going to be changed.

**Comment by ArtNRG** [comment]
Anti xRay will not also obfuscate this block and many of my users are searching the ores near lava with xRay because of this issue.
![uLRjWaw](https://user-images.githubusercontent.com/20762020/74510980-bad38f80-4f26-11ea-8084-64c46a2eaab4.png)

**Comment by electronicboy** [comment]
The code basically checks for solids, I guess excluding lava might be viable, but, water won't be

**Comment by ArtNRG** [comment]
There are no so many water lakes in caves comparing with lava and water is transparent. So yes, excluding only lava will be the ok decision.

**Comment by BillyGalbreath** [comment]
I don't think including lava is a smart move. It's a translucent liquid. Put fire protection on and go swimming, you can still see some blocks when up close. The part that worries me tho, is it flows. So now we gotta start worrying about the level and have a wider update radius to compensate for removing a source block that could potentially be covering an ore that's 4-5 blocks away. Just seems like waaaaaay to much cpu load on am already heavy load :S

There are already lots of scenarios the built in anti-xray doesnt cover. Like obfuscating chests and other TEs. Its just too costly (cpu wise, and maintenance wise) to include these. If you need better coverage than whats included you are free to use the plugin this was all based on, [Orebfuscator](https://www.spigotmc.org/resources/orebfuscator.22818/). There is a team devoted to maintaining it, and [the latest release](https://github.com/TeamWuffy/Orebfuscator/releases) works on 1.15.2. But, I don't think they hide ores behind fluids as well, for the same reasons I've outlined here.

**Comment by ArtNRG** [comment]
The obfuscation behind lava blocks can be optional and be turned on/off in the config if someone wants his players to use potions and dive for the ores, but I don't know any person who does something like then because mined items will burn in lava. The only way is to find ores, place some blocks to make a gap and to dig there.

Is it possible to skip flowing lava blocks and obfuscate only stationary lava? It will be OK because lava lakes are consist of stationary lava. 

By the way, 1.16 presents new block Ancient Debris which will always be covered by lava and/or blocks on all sides. If lava will not hide ores behind it the new block will be too easy to find with Xray.

**Comment by Chasewhip8** [comment]
I don't like the idea as BillyGalbreath mentioned the case where the fluid is transparent. There's no way to do this without breaking things. If you really want it. Fork and add it yourself.

**Comment by ArtNRG** [comment]
I suggest just to add turned off by default obfuscation behind stationary lava blocks. If some server owners like me or @kakd want to use it, they will be able to use it. I don't need a complicated system based on flowing lava with a wider update range, just stationary.

All x-ray cheaters on my server are digging near lava and I can't do anything with it.  At the same time, no one is trying to dive for ores in lava.

**Comment by stonar96** [comment]
Sorry that I didn't notice this issue earlier. However, I'm also not sure if this should be in Paper.

What @BillyGalbreath says is true and I want to add, that it's not even possible to not obfuscate it, if lava is considered as occluding block. This would require checking if the block above the lava is air while obfuscating. But in the way how Anit-Xray is implemented this check isn't even possible without changing the implementation completely. No matter what, if you want that feature, these edge blocks will be obfuscated.

Assuming you are okay with obfuscated blocks at the lava edge (in engine-mode: 2 using only those ores, which have default stone texture on the upper edge for obfuscation), CPU wise it wouldn't make much difference, probably even no difference, except for obfuscating more blocks than it would normally. There is no extra check necessary while obfuscating because Anti-Xray creates [this boolean array](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0384-Anti-Xray.patch#L210-L211) in the constructor, which is used to determine if a block occludes or not. Now you can compile a custom build changing this to:
```
                solidGlobal[i] = blockData.getBlock().isOccluding(blockData, emptyChunk, zeroPos)
                    && blockData.getBlock() != Blocks.SPAWNER && blockData.getBlock() != Blocks.BARRIER && blockData.getBlock() != Blocks.SHULKER_BOX || blockData == Blocks.LAVA.getBlockData();
```
Note that ```blockData``` is compared here for lava and not ```blockData.getBlock()``` because we only want to add "stationary lava".

Of course, if this change once makes it into Paper ~~(which i doubt)~~, this must be a configurable option.

**Comment by ArtNRG** [comment]
https://youtu.be/tS3VNhkW55c
Quick testing of diamonds behind the lava with default textures.
Many server owners including me will be much appreciated if optional obfuscating of ores in this situation will be available in Paper config.

**Comment by stonar96** [comment]
I'm working on a PR.
