### ISSUE TITLE
Tripwire hooks are able to be placed in region-protected areas?

### ISSUE THREAD

**Issue by Dimotai** [PaperMC/Paper#2969]
So recently I discovered that people could place tripwire hooks in areas with protection such as WorldGuard or even in vanilla's default spawn protection area. I then did some process of elimination, ruling out that this is a bug on Paper 1.15.2 (I've only tested this on Paper 1.15.2 build 103 and build 105). Here is my analysis:

- Tripwire hooks, along with any other blocks (unless manually excluded) cannot be placed in WorldGuard protected areas nor any other protected area in PaperSpigot 1.15.1 nor Spigot 1.15.1 (which is normal).
- Tripwire hooks **can** be placed in PaperSpigot 1.15.2 (I've only tested this bug to be working on 
build 103 and build 105) in region-protected areas, including vanilla's built-in spawn protection (thus rules out any plugin intervention issue).

Thanks.

**Comment by Trigary** [comment]
I was able to reproduce this on Paper 102 (too lazy to update, look at my git bash from 2018):

 - you place tripwire hooks on the side of other blocks
 - the block you right click is outside the spawn protection
 - the to-be-placed tripwire hook is inside the spawn protection
 - now you have placed a tripwire hook inside a spawn-protected region
 - you can't break this newly placed tripwire hook since it's covered by vanilla spawn protection
 - by breaking the block on which this tripwire hook was placed you also make the tripwire hook break

Unable to reproduce with trapdoors, buttons, torches, ladders.

**Comment by Trigary** [comment]
What I was able to determine:
 - BlockPlaceEvent is simply not called when tripwire hooks are placed
 - this is because simply nothing gets added to `capturedBlockStates`
 - the block becomes from air to tripwire_hook in the `... = item.a(itemactioncontext);` call (inside `ItemStack#placeItem`)
 - this issue is kinda also present in vanilla Minecraft, but it's not limited to tripwire hooks: you can place literally anything using this method

It would be great if someone could test on Bukkit/Spigot to confirm that this is not a Paper-specific bug.

**Comment by Trigary** [comment]
I believe I have an explanation. Blocks which connect to other blocks modify themselves upon placement, eg. rails rotate themselves to connect to other rails, tripwire hooks enter a "lowered" state if they are connected through tripwire strings to another hook.

Tripwire hooks do this in `Block#postPlace`, which calls `setTypeAndData(..., i=3)`. In that method `iblockdata1` becomes `null` ("//CraftBukkit custom NO_PLACE flag"). This removes the block from `capturedBlockStates`, and since `Block#postPlace` is executed before the collection's contents are checked, no `BlockPlaceEvent` is fired. Rails, on the other hand, use something else that gets called after the event is fired, so they don't have this issue.

PS: this thing rails use is `Block#onPlace`

PS2: client-side visual glitches in connection with `Block#postPlace` and two-block high blocks seem to exist, but they are only client-side luckily

**Comment by Trigary** [comment]
I believe simply moving the code from `BlockTripwireHook#postPlace` to a newly created (overridden) method `#onPlace` would fix all issues. Other blocks that call some sort of `World#setTypeAndData` seem to use this `Block#onPlace` method. I have tested this modification a bit and it seems to work, and frankly, tripwire hooks can't really get more broken than they currently are.

I still haven't tested on CraftBukkit/Spigot, but it's probably present in them as well. What's the next step?

**Comment by Dimotai** [comment]
I just tested them on Spigot 1.15.2, not CraftBukkit though. Tripwire hooks work fine on Spigot 1.15.2 and 1.15.1 (as previously mentioned), so Spigot is out of the picture.

**Comment by HexedHero** [comment]
Can confirm paper 105

**Comment by Trigary** [comment]
@Dimotai Are you sure the issue is not present on Spigot 1.15.2? It very much is for me. What version did you test on? I tested on latest, just now: `This server is running CraftBukkit version git-Spigot-c574e08-37f32da (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Comment by Dimotai** [comment]
I pulled my version off the getbukkit.org Spigot's latest stable release (1/21/2020). Exact version is:
`This server is running CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT`

**Comment by Trigary** [comment]
I have looked over the changes between these two versions and I don't see anything that could have anything to do with this bug. Great...

**Comment by Trigary** [comment]
Issue present: git-Paper-83
Issue not present: git-Paper-81
(There is no version 82)

[This upstream commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6515ea4957c5ebc8b88e3f7581a8a4dbb55fecb1#nms-patches/World.patch) is the culprit because it changed the questionable `capturedBlockStates.remove` method. (Previously that method removed the specific block state instead of the block state at the block position. `ArrayList#add` was overridden, but `ArrayList#remove` wasn't.) I think the correct fix is to only remove the block state from the map if it was added in the same method call, so if the block state present in the map at the block position is the same as the one we have put into it. I still believe that `Block#onPlace` should be used instead of `Block#postPlace` in `BlockTrapwireHook`, but that doesn't cause any issues in itself (currently).

As this is an upstream bug, it would be great if someone who has a virgin child to sacrifice could PR some fix to CraftBukkit or I don't know. I think I will make a PR to Paper in the meantime, I just have to debug some Maven NPE first among other stuff.
