### ISSUE TITLE
Zero Tick Farms

### ISSUE THREAD

**Issue by Quadwheels** [PaperMC/Paper#3018]
Hey so My server uses Paper And I recently tried to re enable the Zero-Tick farms of the server but I noticed they didn't work I went into the paper.yml file and changed the fixer tick thing to false. and yet no response Im hoping I can get some assistance .

**Comment by BillyGalbreath** [comment]
Zero tick farms are a bug and Mojang is actively trying to fix them. They did fix some versions of the bug, but not all. You are apparently using one of the ones that got fixed by Mojang.

My advice: learn to live without zero tick farms now, because Mojang will fix them all eventually and the paper setting to "re-enable" the bug will be gone. ;)

**Comment by Quadwheels** [comment]
I appreciate your input But That is not a fix to the issue I Have. My server has been begging that I get It working again and I want to find a fix for them. And until Mojang Writes it out of their code It can be considered a mechanic.
