### ISSUE TITLE
Entity squid performance issues

### ISSUE THREAD

**Issue by Dagrond** [PaperMC/Paper#3039]
###  Timings or Profile link:
https://timings.aikar.co/?id=6e07e0475f564f41ad424823bd616dca

### Description of issue:

So I noticed that Squid are lagging server... But there is like 3 squids on entire server. 

### Paper build number:
Paper(134) 1.15.2-R0.1-SNAPSHOT

**Comment by pengooin** [comment]
Hi, I think you are having a similar problem as me (Issue #3037). Except instead of squids it is trader llamas. I had only 14 trader llamas, and they were contributing more than half of the time to execute one tick. When I removed these llamas, the time was instead split across other entities, with skeleton horses, sheep, zombies, and more all going up significantly in time.

It appears there is some kind of much larger issue going on with timings. Unfortunatly, I have not found any solution to this problem.

**Comment by Brokkonaut** [comment]
Yes I think its a bug in the timings calculation. I often have that on my server too, where timings say there are hundreds or thousands of a certain entity type ticking while there are just like 10 or so in that world.

**Comment by electronicboy** [comment]
You have deeper issues which means that your timings report is basically invalid
https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/page-20#post-3684550
