### ISSUE TITLE
Server freezes without error message and will not work again until the process is killed and startet again

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3043]
### Link/paste of stack trace
No stack trace, Server simply freezes, all players lose connection, no crash report, will not work again until the process is killed and startet again

### Plugin list:
No installed Plugins

### Actions to reproduce (if known):
not known

### Paper build number:
Paper version git-Paper-142 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
Well giving us the logs at the end is still useful for some context....

This report gives us nothing to look into.

**Comment by ghost** [comment]
`>.... [00:26:32 INFO]: UUID of player RioluKommentiert is 3dfdb866-d676-409c-b682-5c00d77288fb
>.... [00:26:32 INFO]: RioluKommentiert[/77.21.249.82:36951] logged in with entity id 2055 at ([world]5703.644189197739, 80.0, -4577.699999988079)
>.... [00:26:56 INFO]: s1mplexx lost connection: Disconnected
>.... [00:26:56 INFO]: s1mplexx left the game
>.... [00:27:33 INFO]: UUID of player Shrekla is beeac1dc-c254-4459-a66e-9d9dff3fdf24
>.... [00:27:33 INFO]: Shrekla[/91.53.169.48:60372] logged in with entity id 2333 at ([world]5762.299230989631, 72.0, -4454.204859445488)
>.... [00:28:56 WARN]: ff047944-aa23-4abc-8b87-65b05b6a70c6 (vehicle of Darla10) moved wrongly!
>.... [00:29:25 WARN]: EggmanNR1 moved too quickly! -7.276997713108358,3.0,6.671152464656188
>.... [00:29:27 WARN]: Darla10 moved wrongly!
>.... [00:29:52 WARN]: EggmanNR1 moved too quickly! 6.9459373490481084,3.0,-7.682723973717657
>.... [00:30:24 WARN]: EggmanNR1 moved too quickly! -7.923100020883794,-13.0,-3.494915987026161
>.... [00:30:42 INFO]: <Darla10> 6295 75 -4854
>....=>.... [00:30:51 INFO]: This server is running Paper version git-Paper-142 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [00:30:51 INFO]: Checking version, please wait...
>.... [00:30:52 INFO]: Previous version: git-Paper-137 (MC: 1.15.2)
>.... [00:30:52 INFO]: You are running the latest version
>.... [00:31:09 INFO]: Scanning for legacy world dragon fight...
>.... [00:31:09 INFO]: Found that the dragon has been killed in this world already.
>.... [00:31:12 WARN]: EggmanNR1 moved too quickly! -2.2943430919014816,7.0,-6.816980618298377
>.... [00:35:48 WARN]: Darla10 moved wrongly!
>.... [00:36:05 INFO]: EggmanNR1 fell out of the world
>.... [00:37:42 WARN]: EggmanNR1 moved too quickly! 7.558117767575794,2.0,7.942343083601145
>.... [00:38:43 INFO]: EggmanNR1 was slain by Enderman
>.... [00:39:41 INFO]: EggmanNR1 was slain by Enderman
[Pterodactyl Daemon] Server marked as STOPPING`

[Pterodactyl Daemon] Server marked as STOPPING --> User Interaction killing server
I do not understand the behaviour of the server, it just freezes without any error message

**Comment by jdkeke142** [comment]
Got the same problem lately, I would say that the server crashes like 2 times a day, which makes me say that it's potentially not caused by paper, is that often, two servers of my Bungeecord network crash at the same time, both with no errors.

I'm on a recent version of paper but not even on the latest version of paper, so if it's effectively paper-related, it's not from the latest version:

Paper version: `git-Paper-137`

Plugins (37): `AntiAFKPro*, BungeeTabListPlus, Chunkmaster, ColoredSigns*, CrazyCrates, DeltaRedis*, DisplayShops, EntityTrackerFixer, EpicWorldGenerator, GemsEconomy*, IvernyaLoadBalancer*, IvernyaPhysicsTweaks*, IvernyaSomeBungeeTweaks, KeepItems*, LuckPerms, MMOItems, MMOLib, Multiverse-Core, MysqlPlayerDataBridge, NametagEdit*, NoChat*, OreReplacerPlugin, PlaceholderAPI, PlayerParticles, PremiumVanish, ProtocolLib, ProxySuiteBukkit, RandomTeleport, Rankup, ShulkerBox_BackPacks, SomeIvernyaEssentials, spark, StackMob, Vault, VillagerOptimiser, WorldEdit, WorldGuard`

Logs: https://gist.github.com/jdkeke142/31fd57b6120b313b154d06c7549f725c

**Comment by electronicboy** [comment]
>[Pterodactyl Daemon] Server marked as STOPPING --> User Interaction killing server
>I do not understand the behaviour of the server, it just freezes without any error message

That's your control panel, you would need to speak to your hosting provider about that, not much we can do

crashes without errors is also something we can't diagnose, if you're using a hosting provider, you'll potentially wanna speak to them, look for hs_err files, and if you're not on a shared host, check `dmesg` if you're running on *nix
