### ISSUE TITLE
Random chunk-related server lag at 1.15.2

### ISSUE THREAD

**Issue by XXHunter796** [PaperMC/Paper#3052]
### Link/paste of stack trace
https://pastebin.com/KYEK4J74

### Plugin list:
AnimatedMenuPlus, AnimationLib, AuctionHouse, BetterChairs, Citizens, EntityTrackerFixer, Essentials, EssentialsSpawn, HolographicDisplays, Jobs, KillerMoney*, LeaderHeadsRevamped, LimitPillagers, LiteBans, Matrix, PlaceholderAPI, ProtocolLib, Vault*, ViaBackwards, ViaRewind, ViaVersion, VillagerOptimiser, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Unknown.
It happens randomly and many times a day

### Paper build number: git-Paper-142 (MC: 1.15.2)

My world is pre-generated by WorldBorder, prevent-moving-into-unloaded-chunks is set to true
I've tried so many different configurations of paper.yml and spigot.yml without any result.

**Comment by kickash32** [comment]
Such is the state of Minecraft 1.15, chunk loading is just laggy. You will have to bear it just like everyone else...

**Comment by benwoo1110** [comment]
**Things you can try:**
1. Use Protocol Support instead of ViaBackwards (not supported anymore) and unless you need 1.7 support, ViaRewind and ViaVersion is useless.

2. Use AsyncWorldEdit (https://www.spigotmc.org/resources/asyncworldedit.327/). Helps in chunk loading management in worldedit operations, so worldedit of large scale with huge chunk changes have less impact on server.

3. Use Simple Anti-Mob Lag to further manage entity lag. (https://www.spigotmc.org/resources/simple-anti-mob-lag-1-9-1-15.67484/)

4. In paper.yml change config options to 
```
    max-auto-save-chunks-per-tick: 8
    async-chunks:
        enable: true
        load-threads:<Server_cpu_core_count>  # Change number to 75% of your cpu core count (generally)
```

6. For more optimizations: https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/ (But change only if you undestand)
