### ISSUE TITLE
data are deleted

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [PaperMC/Paper#3061]
A critical bug. 

What happened: players ' location and inventory data are deleted. 

How it happens: if a player is on the server and the server's electricity is turned off, the data of players who were online is completely erased (inventory and location). 

What I ask you to do: save data normally from time to time.

**Comment by ghost** [comment]
it is saved manually every 5 minutes

**Comment by TNTUP** [comment]
Is the setting `  save-user-cache-on-stop-only: false` at false? If set true, a warning on the optimise thread on spigotmc

➫ Should the server constantly save user data (false) or delay that task until a stop/restart (true)? This is nice TPS savings on Spigot (less on Paper since it's more efficient).

Note: Take regular backups to avoid data loss in the rare event of a fatal crash.

the last line where is the "Note:", your event of losing electricity would be considered as a fatal crash  thus losing their location/inventory.

**Comment by aikar** [comment]
user cache has nothing to do with it.

This is an impossible thing to solve. If a system loses electricity, then shits bad man.

I did notice in open file handles player data using .tmp files, so i believe mojang is using temporary files to help avoid this.

But the server does auto save.. If you lose power, then yes you're going to lose anything since last save, but nothing can be done there.

Paper can't detect power loss incoming.

**Comment by Envel-Nikita-Gutsenkov** [comment]
This bug is just a result of some kind of incorrect saving of online players. Yes, we solved it, but it is strange to use a kernel that cannot solve an elementary problem that our community classifies as "critical".

**Comment by aikar** [comment]
If you can solve that issue, you will be one of the top programmers in the world.

Mojang does have some changes coming in 1.16 to reduce risk of corruption, but its not going to be 100% and you will still lose latest data on a power loss event.

**Comment by Envel-Nikita-Gutsenkov** [comment]
you may not have fully understood the problem. if the players are online and the power is turned off, the data, then the file is lost COMPLETELY)

**Comment by Envel-Nikita-Gutsenkov** [comment]
that is, it is enough to save data once in a certain period, for some reason when the player online this did not happen

**Comment by C4K3** [comment]
I have also experienced (on 1.15.2) that when the server crashes, region files that are being saved can become corrupt.

> Mojang does have some changes coming in 1.16 to reduce risk of corruption, but its not going to be 100% and you will still lose latest data on a power loss event.

I'm assuming you mean

> Region files are now opened in synchronous mode to increase prevent data loss and corruption after a crash.

from the 1.16 changelog.

Normally to solve this problem you would write into a temporary file, and then when that's complete move the temporary file into the original file (with fsync in between.) Similar to what it does with level.dat (and apparently now also player .dat files?) But as far as I can tell it doesn't do anything like that for region files. Having it do it to region files as well would be a nice feature to prevent world corruption.

**Comment by VADemon** [comment]
> Region files are now opened in synchronous mode to increase prevent data loss and corruption after a crash.

1.12.2 (Forge) client SSP:
> CreateFile	\region\r.-1.-1.mca	SUCCESS	Desired Access: Generic Read/Write, Disposition: OpenIf, **Options: Synchronous IO Non-Alert**, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0, OpenResult: Opened

1.16.1 Vanilla SSP:
> 20:55:08,8878193	javaw.exe	5036	CreateFile	\region\r.-1.0.mca	SUCCESS	Desired Access: Generic Read/Write, Disposition: OpenIf, Options: **Write Through, Synchronous IO Non-Alert**, Non-Directory File, Attributes: N, ShareMode: Read, Write, Delete, AllocationSize: 0, OpenResult: Opened

> **FILE_WRITE_THROUGH**: Applications that write data to the file must actually transfer the data into the file before any          requested write operation is considered complete. This flag is automatically set if the CreateOptions flag **FILE_NO_INTERMEDIATE _BUFFERING** is set.

https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile

Moejang disables buffering ✔

There must be the effect of the journaling filesystem (ext4, NTFS, ...) rolling back the changes, even though through further investigation leaves me puzzled:

Paper b101 does an indirect playerdata save:

1. Save to temp file `<uuid>-<nonce>.dat` (Generic R/W, Disposition: OverwriteIf)
2. Rename `<uuid>.dat` to `<uuid>.dat_old` (ReadAttr, Disposition: Open)
3. Rename `<uuid>-<nonce>.dat` to `<uuid>.dat` (ReadAttr, Disposition: Open)

This process happens within 20ms on my machine (means overwriteIf files don't stay unflushed for a long time). However these don't have `FILE_NO_INTERMEDIATE _BUFFERING`.

I can't see how a journaling FS can have the following state:

- `uuid.dat` missing/empty
- yet the correct `uuid.dat_old` of last save exists

It should at least rollback correctly?

Either way it leaves the question: **How does MC manage to load an empty playerdata when there's (presumably) always the `_old.dat` present?**

**Comment by Clouddii** [comment]
Nikita were you able to yo get your stuff back?

**Comment by ProblemsSender** [comment]
It seems the problem is worse than the looks of it, the issues suggest that even periodically saving from Paper or Bukkit isn't enough to prevent data loss in case of power loss even if it was saved recently. If this were the case backups would be more reliable when they cost similar performance while having the backup separated from the source...
