### ISSUE TITLE
Unable to join server with weird stacktrace

### ISSUE THREAD

**Issue by EnvyingGolem47** [PaperMC/Paper#3127]
### Link/paste of stack trace
I have two stacktraces because I believe that both are important to this problem

randomly appears in console: https://pastebin.com/f2cErWVj

When a user tries to join: https://pastebin.com/NsgmKSEm

### Plugin list:
BetterConcrete, BetterRTP, ClearLag, ClickSortLite, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastLeafDecay, Harbor, InfinityMendingUnnerf, LuckPerms, NoEndermanGrief, TreeCapitator, Vault, VoxelSniper, WorldEdit, WorldGuard

### Actions to reproduce (if known):
It just happened... I started up the server and it just started happening. I didn't change anything.

### Paper build number:
git-paper-167 (MC: 1.15.2)

**Comment by aikar** [comment]
Seems like your java is configured to use a socks proxy, and somethings wrong with it....
Also please update paper, that build has a bad bug.

But consult with your host on if they are doing anything with socks proxy

**Comment by EnvyingGolem47** [comment]
So I updated paper but the problem still persists. I have contacted the owners but they have not been able to fix the problem so far. Do you know of a way to fix this problem?

**Comment by electronicboy** [comment]
you would need to look at the full logs and see if there is an earlier error which might have more information

**Comment by aikar** [comment]
Everything I can find on this is related to outdated java 7, which you clearly can't be on for MC 1.15, or security manager stuff.

The stack trace is clearly trying to create a SOCKS proxy socket.

Running a timings report can help identify what startup flags are being used in case your host is doing something there, but can't find any potential for this to be a Paper issue.

Either host is doing something to it to enable socks, or enacting a security manager, doing something to block metrics, or java itself is corrupt and missing class files.

Hop on discord with a Timings report and we can analyze if it seems the host is injecting flags, but going to close as an issue since not anything we can do to help on code side.

**Comment by EnvyingGolem47** [comment]
I think it must have been something wrong with our java 8 because all I did was update java to java 11 and now everything seems to be working fine. Thanks for the quick replies and help!
