### ISSUE TITLE
High amount of ChunkLoadEvent/ChunkUnloadEvent calls

### ISSUE THREAD

**Issue by Wirlie** [PaperMC/Paper#3135]
###  Timings or Profile link:
https://timings.aikar.co/?id=2fda7eebcc654d78aa5d1931dac8861b

### Description of issue:
After updating to the last version (build 176), when my server have more than 30+ players I have noticed that the chunks events (load and unload) are called too fast and the TPS of my server are around between 3.5 and 4.

I have made a plugin that listen the ChunkLoadEvent and send me a report with the times that the event have been executed in the last 30 seconds.

With old Paper version, with 30 players I have this results:
[15:41:19 INFO]: >> ========= ChunkLoadEvent last 30s ===========
[16:04:36 INFO]: >> world - 847 times
[16:04:36 INFO]: >> world_nether - 150 times
[16:04:36 INFO]: >> estructuras - 2 times

With the recent version of Paper - build 176:
[15:41:19 INFO]: >> ========= ChunkLoadEvent last 30s ===========
[15:41:19 INFO]: >> world_the_end - 238 times
[15:41:19 INFO]: >> world - 40800 times
[15:41:19 INFO]: >> world_nether - 150 times
[15:41:19 INFO]: >> estructuras - 282 times

### Plugin list:
https://gist.github.com/Wirlie/f65e9e843e699fca145542a720348f15

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml
https://gist.github.com/Wirlie/e49b837f2c3cbfa1fb8bebcd203db631

spigot.yml
https://gist.github.com/Wirlie/fbc150bd6184f8c9a1a40970152615bd

paper.yml
https://gist.github.com/Wirlie/74e0e8748d284dda329fa243d9b4182e

### Paper build number:
This server is running Paper version git-Paper-176 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
This is intentional actually. Looking at your timings, it seems your chunk counts are still pretty stable?

Before, the server could queue up a lot of chunk loads, and wouldn't finish loading them until end of the tick, but if the server was lagging, those would end up not processed until end of tick, and only some of them.

This resulted in slow loading chunks especially noticeable to the client.

We've optimized that to process the pending chunk queue faster...

Notably, this processing is worked queued to be done - it's got to be done at some point.

Loads in this sense are either necessary for a generation, or necessary for players. If you delay this, either generation is delayed, or the user's visible chunks are delayed, and if they move into an unloaded chunk, server lag will occur as this will force a sync chunk load, which forces all this pending work to be 'flushed' anyways.

Additionally, if any of these chunks are short lived, ie only for generation, holding them back will increase pressure on the garbage collector as the chunk data will stay in memory longer.

-----------
Now for your specific lag. My assumption is you have something extreme generating chunk loads that then expire, IE a plugin.

Looking at the timing "mid tick chunk tasks" (use filter box), at the start when you were not lagging, you can see it did 221 per tick. which is around the "per tick cap" the feature has. 

But as your server started lagging, it dropped to .5 of a tick. It's written in a way it stops doing the work soon as it's lagging.
which is ultimately what Vanilla does...

What appears to be the issue here is UltimateStacker.
 We strongly recommend to not use plugins like this - they destroy your performance.

UltimateStacker at end of your timings is causing serious lag. This is likely the source of triggering a lot of chunk requests too...

So your plugin yes identified lots of loads are occurring faster than before, but that doesn't appear to be the real root cause of whats going on here.

Please remove Ult stacker and see how things go.

**Comment by Wirlie** [comment]
Hello, thank you, I appreciate your detailed explanation!

I have removed UltimateStacker and for now it seems to be stable with TPS between 19 and 20 with 25 players, I will keep testing this change today to check the server performance when more players arrives.

Thanks for the help, I believe that this issue can be closed, but I will keep this open in case that you need my feedback of the performance result.

**Comment by Wirlie** [comment]
Awesome! UltimateStacker was the problem, thanks for the help, the problem has been fixed 💯 and now the TPS are stable.
