### ISSUE TITLE
Make flying entities immune to activation range rule

### ISSUE THREAD

**Issue by i0xHeX** [PaperMC/Paper#3175]
**Problem:**
It's so weird to see flying entities, such as **Phantom** or **Ghast** freezing in the air / spot they spawned when they out of entity activation range (EAR). This in some way breaks general expected behavior and difficulty level when fighting them. Very often travelling in the nether I see frozen ghasts that even don't target me. Only few times when come too close they start moving & target me. I don't remember such problems in 1.14.4, ghasts were always a problem for building etc.

**Solution:**
Make flying entities immune to EAR rules.

Ghasts:
[https://i.imgur.com/MKeub6I.png](https://i.imgur.com/MKeub6I.png)
[https://i.imgur.com/RDVqqlR.png](https://i.imgur.com/RDVqqlR.png)

Phantoms:
[https://youtu.be/kwkn1buJ_pQ](https://youtu.be/kwkn1buJ_pQ)

**Comment by JavierKasunic** [comment]
I'd rather have a separate AR for flying entities rather than making them immune to it, and to be fair, without zooming in, you might not even be able to notice it

**Comment by aikar** [comment]
sep range is better, thats my general idea, because if its > 32 blocks from you its likely not aggro'ing anyways.

the main maybe here is if you're not paying attention and it normally would move near you.

I am looking at making a temporary wakeup period for ear in general, could help here, as well as brand new mobs start with a temporary immunity too

**Comment by aikar** [comment]
This was resolved in EAR 2.0
