### ISSUE TITLE
Async I/O questions

### ISSUE THREAD

**Issue by Sataniel98** [PaperMC/Paper#3179]
This is not a bug report, but I'd like to ask a few questions since I am worried Paper behaves differently from Spigot in some cases, or at least that the exact behavior isn't defined at all in the API.

## Bukkit#unloadWorld(World, boolean)
Does this happen asynchronously? Can I safely delete the world folder in the same tick after calling the method? Does saving the map have any influence on whether this works or not?

## Can I copy folders of loaded worlds?
Is it possible that (asynchronous) chunk I/O leaves the world in an "illegal" state when it's not unloaded before?

Thanks for the help.

**Comment by electronicboy** [comment]
discord is often a better place for discussions, due to the whole chat thing;

1) the world is unloaded and data is flushed here, so, should be safe, but I would not sure I'd rely on this too well

2) No, even without async IO this is never safe unless you disable world-saving and flush the IO queue, that applies to even vanilla
