### ISSUE TITLE
Automate the process of EULA acceptance, or at least make it quicker

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3206]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when upon initial startup I have to first start, then accept the EULA then start again.

**Describe the solution you'd like**
I had several ideas on how to fix that, I just listed then:
1) Prompt the user upon initial boot to accept the EULA using a simple Y/N response.
    1.1) Upon prompting the user, open a text file containing the EULA and the user just needs to close it and press either Y/N.
    1.2) Just contain in the prompt a link to the EULA itself and again, prompt for a Y/N response.

In both scenarios, after the prompt is answered, the `eula.txt` file is updated according to the response captured from the user, `true (Y)` or `false (N)`.

**Describe alternatives you've considered**
I don't have any in mind, if anybody wishes to suggest them here I'd be happy to list them.

**Additional context**
None, currently.

**Comment by Proximyst** [comment]
To be quite frank, this isn't strictly necessary IMO.

You can always do `echo eula=true>eula.txt` before starting it, perhaps even incorporating it into your start script.

**Comment by electronicboy** [comment]
You'd imagine that this would be simple, but it's actually a massive pain in the arse and really unviable to actually pull off properly, I know that FML tried to do something similar for dangerous actions, e.g. running the server with missing blocks, but they had to add a system property to this because many hosting providers control panels broke this feature somehow.

There is also no sane cross-platform manner to open a text file, not to mention the number of headless environments

The effort involved for a one time operation, not to mention how easy it is to just throw a file onto the disk or the system property that already exists for the eula, it's not really worth it

**Comment by MiniDigger** [comment]
I mean, paper does have something like this :D
https://github.com/PaperMC/Paper/blob/bc8fafb206675c5489e5b1cf5320f30169a01a74/scripts/testServer.sh#L50

**Comment by BillyGalbreath** [comment]
Spigot added a flag for it

```
java -Dcom.mojang.eula.agree=true -jar server.jar
```

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0075-Add-CommandLine-EULA-Flag.patch#20

**Comment by ghost** [comment]
> Spigot added a flag for it
> 
> ```
> java -Dcom.mojang.eula.agree=true -jar server.jar
> ```
> 
> https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0075-Add-CommandLine-EULA-Flag.patch#20

Seems like an alternative to what I was looking for, thank you.
