### ISSUE TITLE
Entities movement a bit slower or less fluid than vanilla

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3228]
### What behaviour is expected:
Entities should move at the same speed and fluidity than vanilla behaviour.

### What behaviour is observed:
Well, this is very weird. I have noticed that entities movement (I just test it with animals and villagers) in Spigot and Paper is different than vanilla. Movement is a bit slow and not fluid at all. Here you have three videos I recorded for show you, vanilla, Spigot and Paper.

**· Vanilla:** https://youtu.be/i_i48bQQ7k8
**· Spigot:** https://youtu.be/Z4T0dmdjwOg
**· Paper:** https://youtu.be/1TFrVYBw1bY

### Steps/models to reproduce:
Summon a pig (for example) and see how it moves.

### Plugin list:
None, fresh install.

### Paper build number:
Latest, build-226.

### Anything else:
Tested in vanilla server, latest Spigot and Paper.

**Comment by aikar** [comment]
I think this ultimately was a game of luck. In your paper video, the entities head was clearly looking in ways to have pathfinding failures a lot. 
The vanilla video was lucky that the pigs randomly chose really good pathfinder targets.

Try an unpenned area instead. Because even from your video, i don't see an issue here. When the pigs did pick a good path, they seemed pretty normal to me.

**Comment by lordrius** [comment]
Hi Aikar, thanks for your time!

I just recorded two new videos with cows, please look at the cow's body when it moves. In vanilla is soft, fluid. In Spigot/Paper is like laggy, a bit slow... I don't know how to explain, can't find the right word...

**· Vanilla:** https://youtu.be/hrNyo5umzhQ
**· Paper:** https://youtu.be/WGnpSBhcklA

Thank you.
