### ISSUE TITLE
Remaining issues with fix cannons/tnt

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#329]
I dont really know too much about cannons/redstone whatever so here is a video explaining what is still messed up

https://www.youtube.com/watch?v=faxYVx2ao_E

Heres some issues:

- [ ] TNT seems to have an extra block AoE, in versions 1.9 and above it it's a 9 block radius where as in 1.8.8 and lower its 8.
https://i.imgur.com/dG6EqjT.gifv

- [ ] Maybe a visual glitch but some strange behavior:
http://i.imgur.com/JEdIUCk.gifv
Does not do that if the slab is not there....

- [ ] Sand magically disappears when a piston moves below it to turn it into an entity....
https://gfycat.com/SimplisticScarceAlpaca

- [ ] Sand somehow moves back to its old position after being pushed by a web:
https://www.youtube.com/watch?v=6OkBK4Id2yg&feature=youtu.be
four pushes of a piston is how much it would take to push sand out of a web pre 1.9

- [ ] TNT doesn't seem to be shooting tnt in the same block with it left or right even though the TNT is aligned right or left...
https://www.youtube.com/watch?v=uEK9KC5aXLs&feature=youtu.be
In the video TNT should be shooting to the left since the left side tnt goes off first.

- [ ] ??????? east/west glitch or something else?
https://gfycat.com/PlumpNaturalAmericanmarten

- [ ] When using a TNT sand stacker cannon several sand should stack per shot, and sand should not be destroyed
Even though TNT Cannon mechanics fixes are all enabled, sand stacking does not work, it fires the sand and the sand hits the wall but when falling down to the bottom it will only stack 1 and destroy the others. https://www.youtube.com/watch?v=tm4gb4HvqNA&t=3s if you build this cannon and try using it it wont stack more then 1 sand

Edit: Using for tracking

**Comment by PaulGaming** [comment]
Bump

**Comment by zachbr** [comment]
If you want it resolved faster, PR it. Bumping won't help.

**Comment by imaBASKET** [comment]
Heres some issues:
- TNT seems to have an extra block AoE, in versions 1.9 and above it it's a 9 block radius where as in 1.8.8 and lower its 8.
  https://i.imgur.com/dG6EqjT.gifv
- Maybe a visual glitch but some strange behavior:
  http://i.imgur.com/JEdIUCk.gifv
  Does not do that if the slab is not there....
- Sand magically disappears when a piston moves below it to turn it into an entity....
  https://gfycat.com/SimplisticScarceAlpaca
- Sand somehow moves back to its old position after being pushed by a web:
  https://www.youtube.com/watch?v=6OkBK4Id2yg&feature=youtu.be
  four pushes of a piston is how much it would take to push sand out of a web pre 1.9
- TNT doesn't seem to be shooting tnt in the same block with it left or right even though the TNT is aligned right or left...
  https://www.youtube.com/watch?v=uEK9KC5aXLs&feature=youtu.be
  In the video TNT should be shooting to the left since the left side tnt goes off first.
- ??????? east/west glitch or something else?
  https://gfycat.com/PlumpNaturalAmericanmarten

**Comment by imaBASKET** [comment]
Been a few months and this still has not been addressed.

**Comment by zachbr** [comment]
PRs welcome.

**Comment by Techcable** [comment]
This is a critical bug, causing my brain to rot, plz fix.
The Heart-bleed vulnerability was nothing compared to this, and it it'll have disastrous, irreversible consequences like the Y2K bug!!!!!!

**Comment by zachbr** [comment]
No one currently active on the team runs a cannon server of any sort. These fixes were originally contributed by multiple people who were. It is unlikely we will ever directly fix many of these issues. If someone with cannon experience would like to submit PRs for any of the tracked issues listed in this ticket, feel free. We will accept them. Outside of that, I wouldn't expect much progress on this front.

Ever since we added the patch it has been a source of large maintenance burden, and given how few cannon users are even up-to-date, it's harder and harder to justify our time towards this goal. Especially since, as I mentioned, none of us are cannon users.

**Comment by imaBASKET** [comment]
About a year later since this issue was opened.

I ended up fixing a load of the problems for 1.12 on pre5.

https://www.youtube.com/watch?v=2W2bfTyOwwQ&lc

Still working on some things.

**Comment by PhanaticD** [comment]
:o someones actually working on this?

**Comment by PhanaticD** [comment]
@imaBASKET are your changes public anywhere

**Comment by josephworks** [comment]
there is a setting fore old tnt cannons

**Comment by zachbr** [comment]
No longer a priority for the project.

**Comment by PhanaticD** [comment]
WHY

**Comment by mikroskeem** [comment]
It was stated that nobody active on the team runs a server dealing with cannons, so that is not a priority.

And seems like the guy who made some progress is not willing to share his modifications and/or just disappeared.
