### ISSUE TITLE
Offline-mode server whitelist.txt/banlist convertion issue

### ISSUE THREAD

**Issue by sgdc3** [PaperMC/Paper#334]
When a CraftBukkit server tries to convert a whitelist/banlist with the old pre-uuid .txt format it uses always the online-mode uuid lookup method, as result the new .json file contains online UUIDs and it's useless. It would be amazing if Paper could fix this annoying issue. ;)

**Comment by sgdc3** [comment]
Found the issue:

net\minecraft\server\NameReferencingFileConverter.java L68

`if (minecraftserver.getOnlineMode() || org.spigotmc.SpigotConfig.bungee) { // Spigot: bungee = online mode, for now.`

**Comment by zachbr** [comment]
So this one is a little trickier to resolve. Because there's no way for us to get any info from bungeecord on whether or not the proxy is in online mode or offline mode, and obviously if it's in online mode it's pretty important the server still convert to online mode UUIDs.

So if you have bungee set to true, the server will always assume online mode. I can't think of any amazing solution to this issue without having some way for the two to talk or introducing another config entry, which doesn't sound all that great.

Workaround would be to just disable bungee in spigot.yml and force conversions with a plugin.

**Comment by sgdc3** [comment]
At least, could you add a warning in the console?

**Comment by zachbr** [comment]
Fixed as of above linked PR being added

**Comment by sgdc3** [comment]
Sorry forgot about this :/
