### ISSUE TITLE
Sand disappearing after falling through end portal

### ISSUE THREAD

**Issue by imnotdax** [PaperMC/Paper#3344]
### What behaviour is expected:
___After placing 10 sand on top of an end portal, and it falling through and teleporting, it should place 1 block in the end and drop 9 blocks.___

### What behaviour is observed:
___No block is placed, and only 8 blocks are dropped, effectively losing 2 blocks of sand.___

### Steps/models to reproduce:
___Drop 10 sand above an end portal, and let it fall through.___

### Plugin list:
___N/A___

### Paper build number:
___280___

### Anything else:
___When you place 2 sand, both sand disappear, but when you place >2 sand the amount of sand dropped in the end is amount of sand placed - 2.___

**Comment by i0xHeX** [comment]
Also can add few details:
- Reproduced this on b255 (and as author said in discord issue first detected in b213)
- Chunks in the end are not loaded by other players

**Comment by aikar** [comment]
It would of been 216 not 213 that likely caused it.

**Comment by imnotdax** [comment]
> It would of been 216 not 213 that likely caused it.

I first found this on b213, and then tested on b280 which also had it.
This is the output of /version on a server with the same bug.

> This server is running Paper version git-Paper-213 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
Well the likelihood of figuring that out just dropped 99% then....

Going to require someone else to find the cause then, as I honestly can't justify spending the time unless it's an easy one.
Too much else to work on

**Comment by MiniDigger** [comment]
basically, if somebody can try bisecting paper builds to find the exact one that caused this, it would be greatly appreachiated.

**Comment by Chew** [comment]
My adventures with trying to find this:
Every time, I put 11 blocks on top of an End Portal and break the bottom block. I also have no plugins loaded.
Paper-1.15.2 build 213 - Bug occurs
Paper-1.15.2 build 200 - Bug occurs
Paper-1.15.2build  150 - Bug occurs
Paper-1.15.2 build 100 - Bug occurs
Minecraft Vanilla 1.15.2 (Just to find intended behavior) - Obviously bug doesn't occur
Tested with Latest Spigot - Bug occurs!

It appears this is an underlying issue with Spigot itself.

**Comment by i0xHeX** [comment]
Found build where bug first appears:
https://papermc.io/ci/job/Paper-1.14/83/
(MC 1.14.2)

**Comment by Chew** [comment]
Not sure if this is fixed yet. It still likely isn't, but if it is, we can close this.

**Comment by Trigary** [comment]
"Transferring" falling sand through the end dimension end portal into the overworld seems to mimic vanilla mechanics - it's working fine. The opposite direction does not though: neither falling sand blocks, nor falling sand items appeared for me on Paper, but they did in vanilla. So this bug is still not fixed, but it might have changed a bit compared to the original bug description.

**Comment by Trigary** [comment]
The end "spawn" (portal area with the obsidian floor and air above it) gets reset (blocks get overridden) whenever someone/something enters it. In Vanilla falling block entities stay falling block entities until you also appear. In Spigot/Paper they become blocks. Why? Maybe Spigot/Paper loads the chunk, whenever any entity enters the portal; I don't really know. But why does this matter? As I said, whenever someone/something enters the portal, it resets itself, potentially removing blocks. If falling blocks become real blocks and you enter the portal after they have already become real blocks they will be set to air. This is what this GitHub issue is about.

You can observe this portal area reset in Vanilla by freefalling into the portal and placing sand blocks above you as you descend: they will enter the portal after you. You can see that all sand blocks except the last one will get removed by the portal reset feature.

So frankly, I think the Vanilla feature/mechanic this "bug" broke is actually just a broken and fragile Vanilla side-effect. I don't think PaperMC would want to support this Vanilla "feature". Again, this "feature" breaks if the chunk is loaded eg. because another player is in the end.

What about item drops? Sometimes falling blocks just disappear, something they drop as items. They drop as items when multiple falling blocks enter the portal in the same tick: in that scenario, the falling blocks try to become real blocks in the same tick, therefore no "portal area reset" can be triggered between them. Because of this, a single real block is able to be present and the rest of the falling blocks drop as items since their space is occupied.

If there's a broken Vanilla feature, shouldn't Paper try to make it less broken, more reliable? I guess yeah, but what exactly does that mean here? Should we completely deviate from Vanilla mechanics and always break blocks naturally when resetting the portal area instead of just removing the blocks "silently"? Sounds like a bad idea if you ask me. What other options are there?

**Comment by spnda** [comment]
From my testing for my issue #5153, I discovered that on git-Paper-457 all of the blocks falling through were disappearing, no matter how many or when they were dropped through. Items seemed fine to me but I only tested that vaguely. This issue is also present on latest Spigot.
Also for my personal suggestion to @Trigary's last comment: At best, keep the current vanilla mechanic and don't change it, or try to find the best possible place for the player to spawn, before resetting any blocks (to prevent the loss of any valuables) and/or only reset the obsidian platform.

**Comment by GrimEpp** [comment]
In singleplayer they create a "queue" for entities. When the player enters the portal it first clears the 3*3*3 box and then spawns the entities in. This is a problem when multiple people are on the same server:

Some tests that need to be ran is:
On singleplayer open lan one player on the platform and another dropping a sand into the portal. Does it appear?
Same test need to be ran on vanilla server and spigot

If the block appears does it disappear when the other player join?
Maybe making a queue for when players join the portal does the then block disappear?

On a big server this will be complicated if two players enters the portal at the same time.

A solution is that the entities are tied to one portal and queued with the portal only loading when the player joins the portal. Vanilla multiplayer has this solved. 

Going to vanilla mechanics will solve this for now until a better solution can be found

**Comment by GrimEpp** [comment]
I have opend a issue in Jira spigot and will be commentating here about the issue forward on.

**Comment by Trigary** [comment]
> A solution is that the entities are tied to one portal and queued with the portal only loading when the player joins the portal. Vanilla multiplayer has this solved.
@GrimEpp 

First of all, Vanilla multiplayer does not work like that. If the portal spawn area in the end is loaded, then Vanilla functions the same as Paper: dropping the dragon egg (as a falling block) and then jumping in after the egg will cause the egg to disappear.

Secondly, that is not a solution. We do not know whether or not a player (or any other entity) will jump into the portal after entities have entered it. So we must spawn the entities in the portal spawn area as soon as possible (as soon as the chunk is loaded). Therefore queueing them is not an option.

**Comment by GrimEpp** [comment]
> First of all, Vanilla multiplayer does not work like that. If the portal spawn area in the end is loaded, then Vanilla functions the same as Paper: dropping the dragon egg (as a falling block) and then jumping in after the egg will cause the egg to disappear.

Woops sorry thought it did. I'll try to do some testing for example dropping a egg in then stopping the server. Have a alt already in the end.

**Comment by Owen1212055** [comment]
Can't reproduce as of paper 1.19, 1 sand is placed and 9 sand items are dropped.
![image](https://user-images.githubusercontent.com/23108066/176006759-fe2d3ab4-4cfe-467b-848f-c43411347226.png)

**Comment by aurorasmiles** [comment]
Since Owen was not able to replicate this in a current version I'll be closing this issue for now.
