### ISSUE TITLE
Hide an entity; Difference between paper and spigot

### ISSUE THREAD

**Issue by DerbanTC** [PaperMC/Paper#3453]
### What behaviour is expected:
Useing the mec `hide_from_players` from the plugin `Denizen` should hide an entity for all players until this mec is removed. 

### What behaviour is observed:
On spigot 1708-REL it works fine .On the paper build 318 it doesn't hide the entity until the player rejoins in the server.

### Steps/models to reproduce:
Install `Denizen` on paper and spigot and test it via 
`/ex adjust <player.precise_target> hide_from_players` when looking at an entity.

### Plugin list:
`Denizen: 1.1.4-SNAPSHOT (build 4821-DEV)`
### Paper build number:
`Paper 318 (1.15.2)`
`Spigot 1708-REL`

**Comment by DerbanTC** [comment]
I tested some random old versions of paper and noted that the mec from denizen are broken on paper since `paper build 247`
https://papermc.io/ci/job/Paper-1.15/247/

**Comment by mcmonkey4eva** [comment]
Copy/pasting my post from Discord to here for relevance:


`PlayerChunkMap.EntityTracker#clear(EntityPlayer)` is called, which calls `EntityTrackerEntry#a(EntityPlayer)` which in turn calls `EntityPlayer#c(Entity)`  which performs `removeQueue.add(entity.getId());` ... `EntityPlayer#tick` then sends the destroy packet for all entities in the removeQueue list. The only part of this Paper changes (that I can see) is that removeQueue became a Deque instead of a List, but otherwise operates the same. I've verified that `PlayerChunkMap.EntityTracker#trackedPlayers` does indeed contain the relevant player, so the one if statement present in that logic chain is still the same.
What am I missing?


The thing that's breaking is the `hide_entity` mechanism, ie a thing that makes an entity disappear for certain clients, it uses that relevant `EntityTracker#clear` call to achieve the immediate entity removal/hide part, which works fine on Spigot but doesn't work on Paper (ie the entity remains visible)
