### ISSUE TITLE
Make 'enable-treasure-maps: false' disable more than just cartographers

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3480]
**Is your feature request related to a problem? Please describe.**
Yes, shipwreck maps are causing huge amounts of server lag, 20+ second lagspikes

**Describe the solution you'd like**
If enable-treasure-maps is false in the config, do not have treasure maps in shipwreck chests

**Describe alternatives you've considered**
datapack to remove treasure maps?

**Additional context**
Image of lagspikes: (97% server tick) https://imgur.com/a/5LCweKT

**Comment by JRoy** [comment]
care to post the actual spark and timings not a screenshot

**Comment by Phoenix616** [comment]
Actual profile report was shared in the paper discord before: https://spark.lucko.me/#2O1zfw0paM

**Comment by ghost** [comment]
Update: removing treasure maps from loottables using a datapack did not fix the issue, server is still experiencing huge lagspikes for the same reason.

**Comment by aikar** [comment]
I'm going to leave this open as the feature is valid ,the config SHOULD work for all, however this is less needed now as I just pushed fix for making the treasure maps not load chunks and instead compute biome by seed.

**Comment by Techcable** [comment]
This should be much less of an issue now that Aikar changed the code to quickly compute biomes instead of loading chunks.

However, this is also related to #3536. When chunks are loading async, there could be lock contention with the biome computations. Working on a fix for that :) After that, I should be able to expand the config to work for shipwreck chests.
