### ISSUE TITLE
Hoppers no longer transferring items to chest minecarts

### ISSUE THREAD

**Issue by Intelli** [PaperMC/Paper#354]
Chest minecarts are no longer being filled by hoppers above them. Hopper minecarts are still working.

This issue started occurring in Paper 787, presumably due to this commit: https://github.com/PaperMC/Paper/commit/bf40dd5557f81a36162c9d0e6302073814992654

The issue does not exist in earlier Paper builds. I've also verified that it's still occurring in Paper 805.

All testing was done on a clean install with no plugins.

**Comment by zachbr** [comment]
Temporary workaround for the time being: set `hoppers: push-based` to `false` in the paper.yml configuration file, then restart the server.

**Comment by Techcable** [comment]
Dang, looks like I have to refractor to have minecarts push into hoppers up and down.
The root of the issue is this: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0159-Make-entities-look-for-hoppers.patch#L281
Thats where hoppers look for minecarts and inventories to push into, I disable the expensive minecart searching.
However the chests don't actually search for hoppers (like the optimization does for items and hopper minecarts), so it doesn't work right.

There are two solutions to this:
1) Revert back to the old behavior and take the performance hit
  - It still won't be as slow as vanilla since it goes from 3 bounding box lookups -> 1
2) Add a config option on weather to keep the old behavior (default off)
  - Let server owners make the decision
3) Add a proper fix to make chests search for hoppers like we do with items and hopper minecarts

I say we should stick with 2 for now, to provide a quick-fix until I (or someone else) implements a proper fix.

**Comment by FatherWh0** [comment]
Verified bug is still present in paper 818

**Comment by PseudoKnight** [comment]
Bug still exists in build 820, after the "Push based hoppers cleanup" commit.

**Comment by ChanceSD** [comment]
Still an issue btw. Build 968

**Comment by BlackBeltPanda** [comment]
Is this something that can/will be fixed? I can't disable push-based hoppers without introducing a lot of lag on my server due to the large number of giant hopper arrays players have been building. =/

**Comment by josephworks** [comment]
try taco spigot or maby it was fixed in the past few 100's of builds

**Comment by lululombard** [comment]
Still an issue on 1226.

**Comment by electronicboy** [comment]
to be honest, my recommendation is to disable push-based hoppers, while the patch can do a good amount of performance improvements, as it stands right now, there are a few issues within the patch that are causing odd behavior on the server, e.g. #763 

Looking into the patch properly is on my todo list, however the very nature of the patch and the fact that /all/ of the code here is obfuscated makes dealing with it much more effort ontop of the unexpected behavior I was seeing inside, which is why some part of me is really considering waiting on the MCP branch in order to look into this.

**Comment by lululombard** [comment]
Yeah that's what I've done. Thanks !

**Comment by Trigary** [comment]
Unable to reproduce, version: git-Paper-210 (MC: 1.13.1)

**Comment by zachbr** [comment]
This was a bug in a patch that fundamentally altered how hoppers work. It was not ever confirmed to be present in the base game with that altered hopper functionality disabled.

That patch has been dropped entirely as of 1.13 and is unlikely to come back. Closing as such.
