### ISSUE TITLE
Block#setBlockData with applyPhysics=false doesn't properly update lights anymore

### ISSUE THREAD

**Issue by CrushedPixel** [PaperMC/Paper#3542]
Between Paper#327 and Paper#348, the behaviour of lighting updates when setting blocks without applying physics has changed negatively.

In [MCC](https://mcchampionship.com)'s mini-game Sands of Time, we're placing a bunch of dungeons in the world that are copied together from room templates that are located in the same world. To avoid redstone contraptions from breaking, these dungeons are placed via `Block#setBlockData` with the `applyPhysics` parameter set to `false`.

This is what the placed dungeons look like in Paper#327:
![2020-06-11_22 57 45](https://user-images.githubusercontent.com/10288753/84439196-0af20280-ac38-11ea-9cfb-4cb14c51010a.png)

This is what they look like in Paper#348:
![2020-06-11_22 52 25](https://user-images.githubusercontent.com/10288753/84439211-13e2d400-ac38-11ea-8f27-8d918fcc4029.png)

Very notably, the time it takes to place the dungeon in the world went down from over a minute to about 15 seconds, so the performance improvement is immense, but we can't upgrade because we require the lighting to be correct.

**Comment by aikar** [comment]
I think you may have something else at play here, because the light optimizations did not have that much of an impact to .setType

.setType does not actually care about the physics flag for light updates. Light will be queued regardless of that flag.

Additionally, unless you're running with the server thread pool disabled, which we did do for a while on single core CPU's, light should not be hitting main thread, so it's just the case of enqueueing the updates.

Are you on a single core cpu? If so that would explain the performance difference, as you went from doing light on main thread vs thread pool.

However I just tested with worldedit, i made a box, copied it, pasted it elsewhere, and light updated.
I then tested with //fast lighting off and it then did not render light.

Are you loading the chunks with the .setType call by chance? can you paste how your setting the blocks?

**Comment by CrushedPixel** [comment]
Strangely, I can't reproduce this issue anymore with the exact same setup - dungeons placed now seem to have correct lighting! Seems like some sort of race condition to me (knowing vanilla MC's code, I wouldn't be surprised by anything).

Our CPU has 12 virtual cores, so we're definitely not in a single-core environment.

The source chunks are probably loaded before the copying is done, as we first iterate over all blocks in the entire area of room templates to analyze them.

The target chunks are definitely loaded only with the `setType` call, should I pre-load the chunks to ensure this issue can't occur?

This is the function we use to copy blocks, we don't really do anything special:
```
    public static void copyBlocks(World world, RectArea source, Vector target, HorizontalRotationKeepingOrigin transform) {
        var size = source.getSize();
        for (int z = 0; z < size.getBlockZ(); z++) {
            for (int x = 0; x < size.getBlockX(); x++) {
                for (int y = 0; y < size.getBlockY(); y++) {
                    var posRelative = new Vector(x, y, z);

                    var sourceBlock = source.getMinCorner().add(posRelative).toLocation(world).getBlock();

                    var blockData = transform.apply(sourceBlock.getBlockData());

                    var targetPos = transform.apply(posRelative).add(target);
                    var targetBlock = targetPos.toLocation(world).getBlock();
                    targetBlock.setBlockData(blockData, false);

                    // copy over tile entities
                    TileEntityUtils.copyTileEntity(sourceBlock, targetBlock);
                }
            }
        }
    }
```

**Comment by CrushedPixel** [comment]
Update: it's happened again in a playtest yesterday. The old version has never had that issue, while the new version has it sometimes (unreliably).
