### ISSUE TITLE
Server crash on build 371

### ISSUE THREAD

**Issue by Elric02** [PaperMC/Paper#3618]
### What behaviour is observed:
Server crashed today, I upgraded to build 371 this night

### Steps/models to reproduce:
No idea

### Plugin list:
AdvancedAchievements, Chunkmaster, Citizens,CoreProtect, CrazyEnchantments, EntityDetection, EntityTrackerFixer, Essentials,FastAsyncWorldEdit, Jobs, LibsDisguises, LimitPillagers, LuckPerms, Multiverse-Core, MythicMobs, NBTAPI, PlaceholderAPI, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Paper build number:
Build 371

### Anything else:
When the crash happened, console was spammed by this : https://pastebin.com/xcKNTPXG
After a restart, got this error spammed on the console : https://pastebin.com/dqKGrMmg

**Comment by electronicboy** [comment]
Your world is mangled

**Comment by Elric02** [comment]
What does that mean ?

**Comment by electronicboy** [comment]
It means that your world has invalid data inside of it, generally down to external tools, worldpainter type stuff, or, bad plugins

**Comment by chickeneer** [comment]
Extra note. The error you are getting is caused by invalid entities in your world files. It appears at least a villager (may be others). Likely some plugin injected bad data in a format the 1.15.2 server doesn't recognize. Since the issue was not caused by the server. It is out of scope for Paper to fix data that shouldn't exist.
