### ISSUE TITLE
Server crashes/console error when shutting down the server normally

### ISSUE THREAD

**Issue by MCHalfAssed** [PaperMC/Paper#3668]
### Link/paste of stack trace

https://hasteb.in/aqesanes.pl

Edit* Full log : https://hasteb.in/qomowiqu.md

### Plugin list:
AdvancedNMotd*, AsyncWorldEdit, BetterSleeping3, ChargedCreeper*, Chunkmaster, CommandSigns, CoreProtect, CraftBook, DeathMessagesPrime, DMPMonitorCompat, DMPWorldGuard, DragonEggDrop, EntityTrackerFixer, Essentials, EssentialsProtect, EssentialsSpawn, GPAccruals*, GriefPrevention, HolographicDisplays, HolographicExtension, HopperFilter, IllegalStack, ItemEdit, JoinMessagePlus*, LaggRemover, LightAPI*, NametagEdit*, NBTAPI*, OpenInv, PacketLimiter, PermissionsEx*, PlaceholderAPI, PlayerHeads, ProtocolLib, pvparena, PvPManager, PvPToggle, RandomTeleport, SAML, SimplePets, spark, StatisticEditor, StopNetherTrap, SuperTrails*, TAB, TopSurvivor, UltimateKits, VarLight, Vault, VentureChat, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
Shutting down the server using the console GUI normally

### Paper build number:
This server is running Paper version git-Paper-10 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by BomBardyGamer** [comment]
I could not see the full stack trace in the bin link you sent, there should at least be an error that looks something like:
`com.example.ExampleException: This is an example of the exception you should see`

Followed by a "caused by" clause that looks a bit like:

`caused by: com.example.ExampleException: This is an example of the caused by clause you should see`

If you are able to pull up the full log (probably in logs/latest.log or logs/date.log.gz if older), please paste that to your chosen paste service (I personally recommend https://bin.bardy.me but the choice is ultimately yours).

**Comment by MCHalfAssed** [comment]
https://hasteb.in/mijafevo.pl

Here's what I have for now, going to get the full log in a sec

**Comment by MCHalfAssed** [comment]
Here's a full log;

https://hasteb.in/qomowiqu.md

**Comment by BomBardyGamer** [comment]
Looks like a Vanilla bug to me, since it doesn't call any Paper methods. Have you tried reproducing on the latest build? (git-Paper-12)

**Comment by kennytv** [comment]
> Looks like a Vanilla bug to me, since it doesn't call any Paper methods. Have you tried reproducing on the latest build? (git-Paper-12)

Paper patches the server; just because it doesn't call any paper api or specific impl, doesn't mean it might not be caused by methods changed by paper ( ﾉ ﾟｰﾟ)ﾉ

**Comment by MCHalfAssed** [comment]
Just updated to Paper-12, the error still persists.

**Comment by BomBardyGamer** [comment]
True @KennyTV , my bad. Let me attempt to reproduce this without any plugins.

**Comment by MCHalfAssed** [comment]
I removed all plugins and didn't get the error - Well, time to start troubleshooting. Any guesses as to which one might be causing the issue?

**Comment by BomBardyGamer** [comment]
Yeah I was unable to reproduce after multiple times without any plugins. Sorry, I'm not sure which plugin could be causing it, I suggest just removing all your plugins, and then adding them back one by one until you get an error.

**Comment by MCHalfAssed** [comment]
I narrowed this issue down to Varlight. Is this due to an issue with Paper/Varlight like this issue here? @flori-schwa 

Running most recent version, 1.12 

https://github.com/PaperMC/Paper/issues/3524

**Comment by aikar** [comment]
Something is causing the server to reload resources constantly which is really bad, likely due to an NMS plugin that's not been updated correctly to 1.16.

This is likely destroying your server performance.

But I have fixed this in latest builds to at least identify when its running on the wrong thread during shutdown and avoid calling the method, so update, but def want to remove any nms plugins that have not explicitly updated.

@flori-schwa if it is varlight, it seems the issue is that the server is triggering a reload of the resource manager constantly, as thats the code blowing up, and I'm suspicious why someone would be spamming /minecraft:reload

**Comment by MCHalfAssed** [comment]
The server performance is fine, actually. This is just a test server. It's only when I send the server a 'stop' command that I get this error. When I disable VarLight and run a stop command, the error is gone and the server shuts down normally.

**Comment by flori-schwa** [comment]
Sorry that I keep causing trouble for you guys. I just published VarLight 1.12.1 which should fix this: https://github.com/flori-schwa/VarLight/releases/tag/1.12.1
