### ISSUE TITLE
push-based hoppers

### ISSUE THREAD

**Issue by melinstagibson** [PaperMC/Paper#372]
The push-based hopper option makes it impossible to fill chest-carts with hoppers.
eventually even more downsides i didnt have time to test but i had to turn it off on my server

i know the description said this option might break stuff but this seems sort of not-minor, so you might want to disable it by default atleast.

just a suggestion (build 819)

**Comment by zachbr** [comment]
Duplicate of GH-354

**Comment by dwilley83** [comment]
This is also sort of an issue with hopper minecart unloaders and it present in CraftBukkit 1.10.2, Spigot 1.10.2, and Paper #858. A couple of items will transfer to hopper in unloader from the hopper minecart but the comparator will not turn the powered rail off to unload the chest before items are no longer detected in the unloading hopper. I have pushed based hopper set to false. Not sure if this is a related matter to what the push-based hopper setting was supposed to fix but it was not present in earlier versions of Paper and it is not present in a 100% vanilla server. I can probably give more details but the problem is not hard to duplicate. 

https://www.youtube.com/watch?v=FeTHFokfJY4

Build this minecart unloader or variant of it as described in this video and with items in the hopper minecart, you will notice that the hopper will not stop even though a couple items drop into the unloader hopper and are not detected by the circuitry.
