### ISSUE TITLE
1.16.1-v27: Structure generating still not working

### ISSUE THREAD

**Issue by PauerBanane** [PaperMC/Paper#3720]
### What behaviour is expected:
Structure generating in 1.16.1 Nether worlds

### What behaviour is observed:
No structures are generated, checked with /locate and the same map on SP

### Steps/models to reproduce:
Generate a Nether world and look for structures

### Plugin list:
Tested without plugins

### Paper build number:
Build 27

**Comment by JRoy** [comment]
Cannot reproduce on build 27 (latest). Used `/locate` command to successfully find a fortress, nether fossil, and bastion remnant.

EDIT: Make sure your configs are default. If not, share them

**Comment by PauerBanane** [comment]
This only seems to appear when running it with the velocity enabled in paper.yml.
I ran the same setup without velocity and structures where generating directly. After enabling velocity support it was broken again.

EDIT: Using Velocity 1.1.0 Build 150

EDIT EDIT: Not caused by velocity option, see my next post.

**Comment by TekExplorer** [comment]
im using build 34 (latest rn) and fortresses and bastions dont generate. ruined portals and fossils appear to generate fine.
using waterfall, in case that has an effect

**Comment by PauerBanane** [comment]
Okay final solutuion here:
It got a problem with my 1.15 spawn map. I first thought, it couldn't handle that i changed the 'level-name' to anything else than world.
But the only problem is, that my old main world is set as the main world.
Renaming the world didn't change anything, only setting another world as main world fixed this issue.
Should I load the world up here?

**Comment by BillyGalbreath** [comment]
Y'all probably just have bad RNG or something. They're working fine for me.

![image](https://user-images.githubusercontent.com/332527/86293828-04143b00-bbb9-11ea-98ea-c98c99c53277.png)

**Comment by Plaudible** [comment]
I too am experiencing this issue, using a custom world made from 1.15 presently on 1.16.1. 
![image](http://puu.sh/G2EKY/4de53fec41.jpg)

**Comment by HexedHero** [comment]
![2020-07-01_23 35 47](https://user-images.githubusercontent.com/6012891/86297579-a05b3380-bbf3-11ea-8463-b787012682bf.png)
Fine here

**Comment by TekExplorer** [comment]
Fixed mine! It was something to do with the world file. (Nothing to do with the nether file) something something generation option? Idk the world was a void world I downloaded. Regenerating it and copying over the region files fixed it

Nether only server with a datapack to make it work :D

**Comment by PauerBanane** [comment]
Worked for me as well!

I created a new world in SP and copied the region files and playerdata from my old world to the new one.
Structures are now generating! :D

But still a weird bug.

EDIT: My old world was created with worldpainter, if that would cause any issues?

**Comment by deaphuz** [comment]
I've found a solution for this problem.

You must edit a level.dat file of Nether (or another world, I've noticed same problem with Overworld) using NBTExplorer or similar program.

Find option "WorldGenSettings" in level.dat file, double-click it and change value "generate_features" from 0 to 1. Then just replace file in your world folder with a modified one.

Sorry for my bad English :)

I hope you understand me

**Comment by aikar** [comment]
its possible world painter saved the level.dat with that value as 0.

**Comment by TekExplorer** [comment]
I almost garuntee this was the problem. I'm glad I could help someone at least

Edit: seeing my solution working for others makes me unnaturally giddy. Is this normal?

**Comment by nicegamer7** [comment]
I think this might have to do with worlds that are not the main-worlds. See Multiverse/Multiverse-Core#2310 for more details.

**Comment by NobleStrike** [comment]
I posted a ticket explaining this bug in much more detail.
https://github.com/PaperMC/Paper/issues/3864

Also setting the main world level.dat world gen settings to enable structures (0 to 1) causes a nasty crash when going through other worlds, even if it fixes the issue. It seems sub worlds level.dat structure setting is entirely ignored. This issue was also brought up with spigot and the devs of multiverse core.

**Comment by nicegamer7** [comment]
This is an upstream issue, see https://hub.spigotmc.org/jira/browse/SPIGOT-5901.

**Comment by NobleStrike** [comment]
It appears that ticket was declared as solved on spigot and is now being ignored even though they didn't actually patch the issue. Which is really unfortunate. I could open my own ticket with them but they will most likely not be happy about a duplicate ticket. I found a loophole work around for the issue so I dont have to wait for them to figure out the ticket status should be reopened. For those interested in my fix, I just edited the level.dat in a couple places to allow structures and it applies it to all worlds.

**Comment by TekExplorer** [comment]
That's unfortunate...

For anyone in the future, the final solution/workaround appears to be regenerating or editing level.dat in the main world folder, multiverse or no multiverse.

I suspect this has to do with Minecraft's new custom dimensions interfering in some way. (Not a dev, just a guess)

**Comment by NobleStrike** [comment]
Yeah its seems it's not exactly a bug, more like a change in how worlds work. Last I checked single player saves merge all 3 maps into one folder with one level.dat to control them all, it even has settings on both single and servers in the main world for each dimension under the world folder, while servers have separate folders for each world it seems that one controls all behavior was carried on. Maybe we should talk to the multiverse dev about adding a new feature to control them independently if this was a behavior change rather than a bug.

**Comment by nicegamer7** [comment]
This problem should be fixed as of build 93. Could someone please confirm?

**Comment by dirkniblick** [comment]
I was using build 93 and updated to 98 and no worlds generated with structures with either one. A /locate would give me coordinates to somewhere which had nothing. Creating any world in the Minecraft java app with structures enabled has loads of structures.

**Comment by Prof-Bloodstone** [comment]
Are you guys using VarLight?
https://github.com/PaperMC/Paper/issues/3900#issuecomment-659536684

**Comment by NobleStrike** [comment]
A true test would be manually setting another world to the opposite setting of the main world and see if it is able to maintain it. Many of us used multiverse to import custom flatworlds with structures disabled, in their nbt data they had it disabled for the end and nether but that only seemed to matter as of 1.16, so again someone needs to test if every world follows it's own level.dat file rather than draw from the main worlds settings for structures. It may help to have someone heavily experienced with how worlds function and link together to drop in and provide accurate information, as I'm getting the feeling world mechanics in general changed with 1.16 and we are just experiencing the side effects of a behavior change rather than a true bug here. Maybe I'm wrong, but it sure seems that way.

**Comment by dirkniblick** [comment]
Success. I am using Multiverse and had a world with structures disabled as my "home world". Per the suggestion from @TekExplorer, I found a way to [edit the world](https://www.reddit.com/r/Minecraft/comments/6d9opk/how_to_turn_generate_structures_back_on_after_the/) to re-enable structures, restarted my server, and successfully generated a world with structures.

**Comment by TekExplorer** [comment]
That's good. Btw for already explored chunks, worldedit's //regen command should regenerate the chunks, this regenerating the structures. Somebody verify this please (//chunk then //regen)

**Comment by james-d-elliott** [comment]
@TekExplorer  I used WorldEdit to mark the chunks for deletion and restarted. Worked perfectly.
