### ISSUE TITLE
Player Collision disable not working

### ISSUE THREAD

**Issue by Phreag** [PaperMC/Paper#376]
My paper.yml has this line:
enable-player-collisions: false

But players can still push each other...

[00:32:20 INFO]: This server is running Paper version git-Paper-821 (MC: 1.10.2) (Implementing API v
ersion 1.10.2-R0.1-SNAPSHOT)
[00:32:20 INFO]: Checking version, please wait...
[00:32:21 INFO]: You are running the latest version

**Comment by zachbr** [comment]
If I remember correctly players need to be on some sort of scoreboard or team for that to work right now.

**Comment by sgdc3** [comment]
What abou entity.setCollodable(false) on join?

**Comment by sgdc3** [comment]
Same for entities on spawn

**Comment by Phreag** [comment]
I know about all those Options, but Paper has added a Patch to make it easily configurable.
And this specific patch does not work.

[https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0127-Configurable-Player-Collision.patch](url)

**Comment by zachbr** [comment]
Because we don't just automatically add users to teams. Which would likely just create even more problems.

Once the players are on teams it works fine. We may change this later but for now that's just how it is.

**Comment by sgdc3** [comment]
@Zbob750 so we just need to add players to the same team on join, right?

**Comment by Black-Hole** [comment]
Same or different team doesn't matter, just any team.

**Comment by sgdc3** [comment]
@Zbob750 What about this: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/LivingEntity.html#setCollidable(boolean)

**Comment by zachbr** [comment]
Sets collision server side. As of 1.10 clients will also handle it client-side by moving if they detect they're inside another entity. The client treats this as any other move, and there's no great way to detect and cancel it.

Which is why we have to do all this nonsense with scoreboards, because we have to inform the client to knock it off.

What was wrong with the older, server-side collision only system from a few versions ago, I don't know.  But the new one is absolute crap and this is how we have to deal with it until Mojang comes to its senses.

**Comment by aikar** [comment]
@Zbob750 that's actually starting 1.9.

The server no longer controls player collision. The players client simply sends move packets when it detects collision.

Meaning, even with servers with collisions on, cheat clients can force it back off :/

**Comment by sgdc3** [comment]
@aikar So the setCollidable method is 100% useless, right?

**Comment by zachbr** [comment]
I would advise you still use it, for backwards (and forwards??? _wink_ _wink_) compatibility. Then additionally use scoreboards as needed for affected versions.

I have some plans that may or may not pan out around this issue. But there's also the case mojang just fixes it anyway in the next version, so best to just leave it in.

EDIT: and no, it's useless setting it on players, because they handle it client-side for now. Still fully working for other entities and other versions.

**Comment by Phreag** [comment]
Means the Config option enable-player-collisions: false is also useless?
Should be removed...

**Comment by zachbr** [comment]
... As we just covered, it works so long as they're on a team. So no, not useless.

**Comment by zachbr** [comment]
Builds 825+ will send the client a scoreboard packet with a fake team to initialize this setting (if needed). Should resolve any drama remaining.
