### ISSUE TITLE
Whitelist isn't working!

### ISSUE THREAD

**Issue by iMot4k** [PaperMC/Paper#3774]
### What behaviour is expected:
People that aren't in the whitelist shouldn't be able to join

### What behaviour is observed:
People that aren't in the whitelist can join the server

### Steps/models to reproduce:
Just enable the whitelist and see

### Plugin list:
None

### Paper build number:
44

**Comment by kickash32** [comment]
Can not reproduce

**Comment by iMot4k** [comment]
> Can not reproduce

When you've never been whitelisted, you can't join, but as long as you're whitelisted once, even if you remove the name from the whitelist you still can join

Here is an example : [https://youtu.be/JvH22CGHI3E](url)

**Comment by Machine-Maker** [comment]
If you are operator on that server, you bypass the whitelist. I just discovered that for myself when testing.

**Comment by Chew** [comment]
Hello, this error may or not be related to #4150 because the whitelist is a bit wonky, but this error seems like user error to me. Not enough information is given, so if you can give some more specific steps (i.e. everything you do from brand new server to error), feel free to open a new issue. There are just too many variables and this error is too vague to be able to handle properly.
As Machine-Maker stated, operators bypass whitelist, so this may be the issue you're running into, or not, you never responded.
Feel free to let us know if this still happens on latest paper 1.16.2 and we'll be happy to look into it further. Have a good day!
