### ISSUE TITLE
Yaml-serialized items have different lore to their counterparts

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3852]
### What behaviour is expected:
2 items, a normal item and the same item serialized to yaml and back being able to stack

### What behaviour is observed:
each line of the item serialized in yamls lore has the prefix {"extra":[ and suffix ],"text":""}

### Steps/models to reproduce:
https://imgur.com/a/cS1E2Y4

### Paper build number:
git-paper-75 1.16.1

### Anything else:
Players on my server cannot trade normal items with villagers whos items are from yaml

**Comment by aikar** [comment]
where are players acquiring the 'normal items', its more so your normal item needs to be the same as the yaml one, not the other way around.

your ultimately going to have to update your source item. Bukkit doesnt serialize as simple components, it has a wrapper component and due to 1.16's changes, we're kinda stuck with it now.

**Comment by ghost** [comment]
normal items, in chests/inventory from 1.15.2

**Comment by ghost** [comment]
Same issue as the display name but for lore it seems

**Comment by weaondara** [comment]
I'm experiencing the same issue. i used a function to generate an item (returns always the same item), let's call it A(); == denotes isSimilar() function of ItemStack
comparing A() == A() = true
comparing A() == deserialize(serialize(A())) = false
comparing A() to 1.15.2 chest to 1.16 map conversion == A() = false

this exists for display name and lore

**Comment by electronicboy** [comment]
The issue here is that bukkit doesn't support components at all and basically relies on wrapping stuff into another component as aikar said, the problem here is that the checks are working perfectly fine, those items are not equal; /ideally/, bukkit would support components and we'd be able to start using them properly instead of relying on the broken legacy parsing, but, given that upstream has blatantly stated that they have 0 intent to actually fix this, it's that huge massive corner of "we have to break something"

**Comment by weaondara** [comment]
also CraftItemStack and ItemStack use different implementations of isSimilar()
ItemStack compares the properties of itself while CraftItemStack compares the tag compound of the NMSItemStack where the lore and displayname are stored as serialized string. the serialized strings may have the properties in a different order
is it possible that the entries in a serialized tag compound are ordered in a predicable way, so that comparing CraftItemStacks could be possible?

**Comment by electronicboy** [comment]
The ordering of properties is not the issue here, those are essentially set in stone due to the nature of serialization, issue here is that bukkit mangles json components, not really much more to it here

**Comment by ghost** [comment]
@electronicboy @aikar how do I data-fix my items via plugin so that they stack again and will not break again in the future.

**Comment by Protonull** [comment]
We recently updated our server from 1.14 to 1.16 and in doing so have come up against this same issue. Our plugins are unable to match the new lore data with the old, but this appears to be a more pervasive issue than just YAML parsing. We know this because some of our plugins create new items with set display names and lore which has this new data in the NBT.. and this is checking immediately using NBT tooltip mods and inspecting `.dat` files directly using external parsers like http://varscript.ru/NBT/

The new structure:

    {"extra":[{"text":"hello, world!"}],"text":""}

The old structure:

    {"text":"hello, world!"}

The new data structure wouldn't necessarily be a problem if it weren't for the fact that any item that existed prior to the update still have the old data structures, so they don't match nor stack with newer items. Matching the items is difficult since `ItemStack.isSimilar()` is doing an NBT comparison, so the different data structures get in the way, so in order to match them, you need to go through the ItemMeta API and specifically match display names and lore because those getters deserialise.

**Comment by Protonull** [comment]
After some digging, this issue isn't specific to PaperMC; it originates from Spigot. I just checked on a Mojang server by naming a pickaxe and that has the old format. Therefore this issue probably originates from the switch over to `IChatBaseComponent` under the hood for lore and display names to support hex colours, and that for some reason the transformer interprets a standard string as an extra of itself.

**Comment by Protonull** [comment]
Relevant: https://hub.spigotmc.org/jira/browse/SPIGOT-5964

**Comment by chickeneer** [comment]
I believe there is an issue with the isSimilar method (which I have found). I do not know if it is what motivated this issue ticket - but I will be PRing a fix within the day.
