### ISSUE TITLE
[1.16.1] Moving blocks do not get destroyed by explosions

### ISSUE THREAD

**Issue by DragonOfMath** [PaperMC/Paper#3853]
Before 1.16(.1), blocks being pushed by pistons during an explosion would be destroyed and drop as items. Example: cobblestone farms using TNT and timing mechanisms.

In 1.16(.1), blocks do get pushed at the moment of explosion, but do not get destroyed or dropped as items. This does not happen in singleplayer vanilla.

You can reproduce this with a sticky piston pushing and pulling a cobblestone block repeatedly until TNT explodes nearby. Neither the block nor the piston are destroyed in explosion. This happens regardless of settings for redstone optimization, piston duplication, explosion optimization, and whether TNT can destroy blocks at all.

No plugins, just Paper 1.16.1 #79. 

![screenshot](https://user-images.githubusercontent.com/34234739/86879559-e2cbb700-c0b0-11ea-86f0-9f3174c6339f.png) The moment of explosion shows no blocks were destroyed. If the timing were even one tick later or earlier, then some blocks would be destroyed, but not enough to clear the column for the next cycle. This is because they are solid blocks at those times so their explosion calculation occurs with their natural blast resistance. As before, moving blocks would have a blast resistance of 0 making them crucial for a TNT-based block farm. Now I suspect that they are ignored entirely during explosion calculations.

**Comment by aikar** [comment]
see paper.yml unsupported section, enable piston duping to resolve this.

**Comment by binary-dragon** [comment]
Piston duping does let the blocks break but doesn't break as many as in standard vanilla MC.

**Comment by aikar** [comment]
you may also need to enable permanent block breaking, but other than that, should be no difference to vanilla.

**Comment by binary-dragon** [comment]
I've enabled that too. Still not getting parody.

**Comment by binary-dragon** [comment]
would setting optimizing explosions to true help?

**Comment by aeonlamb** [comment]
This affects 1.15.2 build 378 as well, just confirmed this on my server using the settings: `allow-perm-block-break-exploits: false` and `allow-piston-duplication: false`.

IMO, this should definitely be considered a bug by paper, because you should expect that the tnt should actually be able to blow up the blocks. Even if it is a vanilla bug that the blocks being exploded get treated as if they were blast resistance 0, and you hope to fix that with both these patches, the expected behavior is still that the blocks get blown up, even if it is at their normal blast resistance. As it stands, they currently do not blow up _at all_. And that seems like a bug to me.
