### ISSUE TITLE
Lore Deleting After Restart

### ISSUE THREAD

**Issue by Ergenta** [PaperMC/Paper#3869]
### What behaviour is expected:
The lore to stay

### What behaviour is observed:
The removed itself

### Steps/models to reproduce:
step 1. Make an items with a third party plugin using a command block command with a lore
step2. Restart the server and look at the lore
step3. restart the server again if the lore is still present after the first restart. 

### Plugin list:
This has been replicated on two different servers using both paper spigot build 77 and 81 on both servers after plugins were removed. I used bosshsoppro and cratesreloadedpro 

### Paper build number:
paperspigot 1.16.1 77 and 81

### Anything else:
It seems as if this problem can't can't be reproduced with a command itself and only possible via third party 

This bug doesn't seem to be effected using normal 1.16.1 spigot build 
<img width="328" alt="Annotation 2020-07-09 013414" src="https://user-images.githubusercontent.com/25316276/87014531-e5eaa400-c191-11ea-80f0-ede739dd2576.png">

<img width="326" alt="Annotation 2020-07-09 013429" src="https://user-images.githubusercontent.com/25316276/87014541-e71bd100-c191-11ea-98a4-ae87181973b1.png">

This is for the plugin bossshoppro [here](https://www.spigotmc.org/resources/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin.222/)
[a_test.zip](https://github.com/PaperMC/Paper/files/4895395/a_test.zip)
do /bs test and click on the 6 heads and place some in a chest and keep some in your inventory. Restart the server and if the lores are still present, restart again and they should be gone. Like I said above this doesn't happen with normal spigot 1.16.1 build

**Comment by Ergenta** [comment]
the command I used was this:

`minecraft:player_head{display:{Name:"{\"text\":\"&aVelocity &8orb\"}",Lore:["{\"text\":\"&8&m-&7&l&m>&8&m----------&7&l&m<&8&m-\"}","{\"text\":\"&7Tier: &8Champion&n§p&f&l\"}","{\"text\":\"&8&m-&7&l&m>&8&m----------&7&l&m<&8&m-\"}"]},AttributeModifiers:[{AttributeName:"generic.movement_speed",Name:"generic.movement_speed",Amount:0.1,Operation:0,UUID:[I;1396740064,-1399963022,-1597927901,1853048206],Slot:"offhand"}],SkullOwner:{Id:[I;506271496,-186691926,-1902844364,1414935678],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM2YmFjZDM2ZWQ2MGY1MzMxMzhlNzU5YzQyNTk0NjIyMmI3OGVkYTZiNjE2MjE2ZjZkY2MwOGU5MGQzM2UifX19"}]}}} 1'`

and this:
`minecraft:diamond_axe{display:{Name:"\"name\"",Lore:["\"&8&m-&7&l&m>&8&m----------&7&l&m<&8&m-\"","\"&7Tier: &8Champion&n§p&f&l\""]}} 1`

**Comment by Ergenta** [comment]
I think I figured out what's causing it: It's the colored text. Both of these never lose their lore but if I add color codes to it via third party plugin, the lore gets removed after several server restarts. 
<img width="356" alt="Annotation 2020-07-09 033545" src="https://user-images.githubusercontent.com/25316276/87017212-52b36d80-c195-11ea-8ddb-6f236df226b7.png">
<img width="143" alt="Annotation 2020-07-09 033556" src="https://user-images.githubusercontent.com/25316276/87017215-534c0400-c195-11ea-8109-8a0550ec9934.png">

---------------------------------------------------------------------------------
^Turns out this was partially true. However, it seems like paper has problem with legacy formatting as the newer chat components do not get deleted upon multiple restarts. Example: `player_head{display:{Lore:['{"text":"lore","color":"gold"}']}} 1` instead of using legacy formatting such as with & or § which

**Comment by Hexicube** [comment]
Can confirm this, actually came here because I had the issue independently. The following simple command in a command block triggers the issue:

`give @s stick{display: {Name: '"\\u00A7rLore Test"', Lore: ['{"text":"\\u00A7t\\u00A7r\\u00A72This Changes Each Relog"}']}}`

Vanilla handles this fine, it never messes with the Lore tag. Paper does the following:

If the item is _never_ moved around in the inventory, nothing happens and the lore works fine. A save-load cycle maintains the unicode character declaration, likely as it was never parsed:
`{display: {Name: '"\\u00A7rLore Test"', Lore: ['{"text":"\\u00A7t\\u00A7r\\u00A72This Changes Each Relog"}']}}`

As soon as you move the item, \\u00A7 is replaced with a section sign, which is reasonable even if vanilla does not do this:
`{display: {Name: '{"text":"§rLore Test"}', Lore: ['{"text":"§t§r§2This Changes Each Relog"}']}}`

After this replacing, leaving and rejoining will convert the NBT to this, which is invisible to the player, but again is reasonable (but inefficient):
`{display: {Name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"Lore Test"}],"text":""}', Lore: ['{"extra":[{"text":"§t"},{"italic":false,"color":"dark_green","text":"This Changes Each Relog"}],"text":""}']}}`

A _second_ leave and rejoin will then do this, rendering the line blank:
`{display: {Name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"Lore Test"}],"text":""}', Lore: ['{"text":""}']}}`

Note: The NBT data was acquired via `data get entity <yourname> SelectedItem` in the console.

From what I can tell, everything before the last step is _entirely fine_ as it has no visible effect and looks like old to new format conversion stuff. However, what I think is happening is that paper then decides on the next data load that, because the "text" tag is blank, there is no lore so it can drop the "extra" tag. A reasonable, and wrong, assumption.

**Comment by Hexicube** [comment]
Forgot to mention: I did this on paper-83 (newest at the time), with zero plugins, after first reproducing the issue with the plugin Brewery which is affected by this bug.

Ideally it should not convert lore with section signs to the new format as Brewery actually uses it to identify its own lore lines, but that's an issue for the plugin to resolve.

**Comment by Hexicube** [comment]
This is a regression between paperclip-24 and paperclip-52, I'm hunting down the specific version change now.

**Comment by Prof-Bloodstone** [comment]
Nice find Hexicube!
Did you have a chance to test any other versions/Spigot?

I suspect it's this patch: https://github.com/PaperMC/Paper/commit/8bb002728a98aa84ac262d9f1d2617caf7b4c8e2
Released under version 51: https://papermc.io/ci/job/Paper-1.16/51/

**Comment by Hexicube** [comment]
I have not personally tried spigot, but the server I play on switched from spigot to paper and this issue was not apparent on spigot. We did have an issue with a lore line not being removed by the plugin but I can't pin that on spigot.

**Comment by Hexicube** [comment]
Good find with that patch by the way, it would be nice if this was a setting so that you could disable converting legacy lore, that would solve the issues in the meantime and grant better backwards-compatibility with plugins.

**Comment by BillyGalbreath** [comment]
> Ideally it should not convert lore with section signs to the new format as Brewery actually uses it to identify its own lore lines, but that's an issue for the plugin to resolve.

This is actually intended design to better aid backwards compatibility. See https://github.com/PaperMC/Paper/issues/3740 for more information. Legacy text doesn't work in components anymore, so they get converted into proper components now.

**Comment by Prof-Bloodstone** [comment]
@Hexicube Did you manage to confirm that 51 is the build that indeed introduces the bug (as you commented in the other issue)?

I've started playing with it in an attempt to fix it, but I'm not 100% convinced this patch is the cause of the bug - it might've just uncovered the bug in the other converters.

**Comment by Hexicube** [comment]
I have not messed around to find out which patch causes the main issue, I just know that I have a lore issue as a result of 51.

**Comment by zizmax** [comment]
Haven't done specific testing, but after being plagued by this issue, I tried build 50 and it appears to work as expected. Lore doesn't disappear on login.

**Comment by Hexicube** [comment]
It's difficult to find which version has a regression, attempting to spawn in an item with the appropriate NBT either results in it keeping the section signs (when using the original data) or immediately removing the section signs and not breaking (when using data with signs and full declarations).

I tried this on paperclip-30.

**Comment by Ergenta** [comment]
So I just spent the last fews hrs trying to figure out how to do the chat componets and converting all my items into that. Turns out, the lores also delete themselves with that as well 
<img width="325" alt="Annotation 2020-07-09 160242" src="https://user-images.githubusercontent.com/25316276/87090453-a5287480-c1fd-11ea-9335-b52444eb8d5c.png">

`    - minecraft:give %player% minecraft:player_head{display:{Name:'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Besiege "},{"italic":false,"color":"dark_gray","text":"orb"}],"text":""}',Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":true,"obfuscated":false,"color":"dark_gray","text":"-"},{"bold":true,"italic":false,"strikethrough":true,"color":"gray","text":">"},{"bold":false,"italic":false,"strikethrough":true,"color":"dark_gray","text":"----------"},{"bold":true,"italic":false,"strikethrough":true,"color":"gray","text":"<"},{"bold":false,"italic":false,"strikethrough":true,"color":"dark_gray","text":"-"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Tier:"},{"italic":false,"color":"dark_gray","text":"Champion§n§p§f§l"},{"italic":false,"underlined":true,"color":"dark_gray","text":""},{"bold":true,"italic":false,"underlined":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":true,"obfuscated":false,"color":"dark_gray","text":"-"},{"bold":true,"italic":false,"strikethrough":true,"color":"gray","text":">"},{"bold":false,"italic":false,"strikethrough":true,"color":"dark_gray","text":"----------"},{"bold":true,"italic":false,"strikethrough":true,"color":"gray","text":"<"},{"bold":false,"italic":false,"strikethrough":true,"color":"dark_gray","text":"-"}],"text":""}']},AttributeModifiers:[{Name:"generic.attack_damage",AttributeName:"minecraft:generic.attack_damage",Operation:0,UUID:[I;1396740064,-1399963022,-1597927901,1853048206],Slot:"offhand",Amount:7.0d}],SkullOwner:{Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzM2ODdlMjVjNjMyYmNlOGFhNjFlMGQ2NGMyNGU2OTRjM2VlYTYyOWVhOTQ0ZjRjZjMwZGNmYjRmYmNlMDcxIn19fQ=="}]},Id:[I;506271496,-186691926,-1902844364,1414935678]}}`

**Comment by Prof-Bloodstone** [comment]
So, I think I've narrowed it down.

I've added following debug messages:
```diff
     private NBTTagString convert(String json) {
+        System.out.println(String.format("CONVERT(%s)", json));
         IChatBaseComponent component = IChatBaseComponent.ChatSerializer.jsonToComponent(json);
         if (component != null) {
+            System.out.println(String.format("COMPONENT not null: %s ### %s",component.getText(), component.getString()));
             component = org.bukkit.craftbukkit.util.CraftChatMessage.fromString(component.getText())[0];
+            System.out.println(String.format("COMPONENT converted: %s ### %s",component.getText(), component.getString()));
         }
         return NBTTagString.create(org.bukkit.craftbukkit.util.CraftChatMessage.toJSON(component));
     }
```
And got following logs on last pass:
```
[23:56:06 INFO]: CONVERT({"extra":[{"text":"§t"},{"italic":false,"color":"dark_green","text":"This Changes Each Relog"}],"text":""})
[23:56:06 INFO]: COMPONENT not null:  ### §tThis Changes Each Relog
[23:56:06 INFO]: COMPONENT converted:  ### 
```
Notice how before conversion, `getText()` returns empty string on the component, but `getString()` returns what is expected - but it shouldn't be parsed! Since only `getText()` is used, the content is lost, as the text field is empty.

Looks like the issue is that the issue is that, after first pass, the everything is put into simple component with only `"text"` field present (this is before I added `getString()` to output):
```
[23:53:10 INFO]: CONVERT({"text":"\u00A7t\u00A7r\u00A72This Changes Each Relog"})
[23:53:10 INFO]: COMPONENT not null: §tThis Changes Each Relog
[23:53:10 INFO]: COMPONENT converted:
```
Next time it converts, this is split into extra components - which this logic ignores.

I'm not sure what is a good fix - leaving it here in case @BillyGalbreath or someone else picks it up while I sleep, though I'd love to finally make my first contribution to Paper code :).

**Comment by Hexicube** [comment]
`component = org.bukkit.craftbukkit.util.CraftChatMessage.fromString(component.getText())[0];`

This looks like it's outright dropping parts of the result, since it only gets the first value returned.
Surely it should be concatenating the resulting list?

**Comment by aikar** [comment]
The [1]+ deals with new lines only. the issue is that the code should only be operating on lines with the legacy. should be pretty easy to fix.
