### ISSUE TITLE
1.16.1 Crash by Async chunk loading

### ISSUE THREAD

**Issue by Tim269** [PaperMC/Paper#3896]
### Link/paste of stack trace
https://paste.enginehub.org/gs7hhmiCi

### Actions to reproduce (if known):
Once I turned async-chunks.enabled to off in paper.yml, the server no longer crashed or had issues with loading chunks.

### Paper build number:
git-Paper-89 (MC: 1.16.1)

**Comment by aikar** [comment]
Please turn async chunks back on, that setting had nothing to do with it.

You simply had a player teleport and the server got behind on light data.

async chunks has nothing to do with those things. I'm going to be removing that config here soon because of situations like this people thinking turning it off helps when it's doing nothing
