### ISSUE TITLE
[1.16.1] Squid movement desync?

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3912]
### What behaviour is expected:
Squids moves as usual.

### What behaviour is observed:
Squids start moving but return to their original position.

### Steps/models to reproduce:
Find some squids and look at them. I don't know if it's related to the separation distance.

### Plugin list:
None, fresh Paper setup.

### Paper build number:
Paper build 91

### Anything else:
Attached demonstration video: https://youtu.be/yNaqduyVcxg

**Comment by kickash32** [comment]
Please post paper.yml and any other config changes you made.

**Comment by aikar** [comment]
I saw this before, but it appears the client is making squids move when the server isn't actually moving them so they snap back.

This would be due to EAR making inactive entities not move. 

unless someone finds some other source, not sure we can fix this, as letting squids move is a silly idea.

**Comment by calumari** [comment]
Reproducible in vanilla singleplayer.

https://streamable.com/chg7oh (using OptiFine in video but I've also tested on a vanilla client).

**Comment by VADemon** [comment]
Squids have had their movement extrapolation since the dawn of time, back when the sun used to update chunks.
This indeed looks like EAR to me, with the coarse update timer for deactivated entities:

1. Squid is outside AR, not moving
2. Ticks for one tick, player receives updated movement packet: Squid EITHER moves in a direction or rotates still in place
3. goto 1

There's a packet for [entity velocity](https://wiki.vg/Protocol#Entity_Velocity), but entity head rotation is always a hard set (I've not found a "rotation speed" delta-packet). So I don't think it can be solved by just **not** sending some packets - probably extrapolated by client.

Important to note that squids appear to NOT change pos at all server-side (compare left squid at 0:00 and 0:35). So either squids need to stop pretending to move when triggered by wake up EAR calls or send a second packet nullifying their velocity/speed change (and keeping head/view rotation so they don't appear static).

I don't have my tool to inspect packet flow in 1.16. If someone feels like it to play with [log4j](https://wiki.vg/Debugging), they're welcome.

**Comment by lordrius** [comment]
Hi! Sorry for reopening this issue but any new ideas of how to fix this? Maybe making squids stand still like fishes when you are far enough from them? Still happening in 1.17.1...

Greetings and keep up your good work!

Many thanks!

**Comment by electronicboy** [comment]
It's done by the client, outside of making squids always tick, there is pretty much nothing we can do here
