### ISSUE TITLE
[Paper Async Chunk Task Thread #0/ERROR]: Unknown tag: minecraft:doors

### ISSUE THREAD

**Issue by ArkadSt** [PaperMC/Paper#3933]
I noticed these error messages in my server log. The log is attached. There was no crash, the playing process was smooth.
[latest.log](https://github.com/PaperMC/Paper/files/4940647/latest.log)

**Comment by pop4959** [comment]
I've gotten this error while pre-generating chunks in a world, so can confirm it happens :)

**Comment by ofunny** [comment]
Can confirm it, happend also several times while pre generating a 10000 squared block world.
For 10000² blocks only 20 times "[Paper Async Chunk Task Thread #0/ERROR]: Unknown tag: minecraft:doors" in a world with type normal. So I have no clue in witch kind of structure it might happen, since only 20 times.

**Comment by Tencryn** [comment]
Any update on this? It too happened to me and I'm wondering whether a village bugged during generation and generated without doors.

**Comment by ZakShearman** [comment]
Happened to me just after restarting my server.

**Comment by electronicboy** [comment]
Mojang removed some features from the game but didn't pull their data during upgrades, this is essentially harmless albeit annoying
