### ISSUE TITLE
Inventory cleared when teleporting across worlds

### ISSUE THREAD

**Issue by calumari** [PaperMC/Paper#3934]
### What behaviour is expected:
Teleporting with my inventory intact on arrival.

### What behaviour is observed:
My inventory is cleared on arrival in creative.
My inventory is hidden(?) in survival, clicking a previously occupied inventory slot returns the items.

### Steps/models to reproduce:
1. Give yourself items.
2. Teleport to another world:
`/execute in minecraft:the_end run teleport 0 70 0`

### Plugin list:
None.

### Paper build number:
98 (1.16.1)

### Anything else:
A chat error message is thrown with the command posted above: https://i.imgur.com/IuNuDgI.png
Fresh install, newly generated world with default config.

**Comment by calumari** [comment]
Reproducible on 97, and not on 93.

**Comment by Krisud** [comment]
Also affecting on multiversecore. Doesnt work as intended. mvc thinks you are still in the world when you jump to world_nether. had to downgrade to build 91

**Comment by WonderDave** [comment]
I'm also having this problem.  Errors are generated whenever my plugin calls the Player "teleport" method.  The teleport succeeds, but due to the the error, the player inventories are lost.  And I can confirm that build 93 is fine, but build 97 has the problem.

The errors generated in the console:  https://pastebin.com/ct0aiGbq
