### ISSUE TITLE
Piston bugs when it's powered from above

### ISSUE THREAD

**Issue by armagidon-exception** [PaperMC/Paper#3976]
### What behaviour is expected:
When you power a piston it should be extended and when power it off retracted.

### What behaviour is observed:
It just stay extended even without power til you update block near it.

### Steps/models to reproduce:
https://youtu.be/KxvcCs-ju30

### Plugin list:
My plugins: 
![image](https://user-images.githubusercontent.com/42355119/88182530-f93d4b00-cc38-11ea-9548-ea9cb62dbda2.png)

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/42355119/88182780-44eff480-cc39-11ea-8ef7-d3494766f090.png)

### Anything else:
Check new redstone mechanics, i think mojang messed up when they were updating redstone.

**Comment by Prof-Bloodstone** [comment]
The video you linked is private - should be unlisted if you want us to see it.
Are you sure it's not QC which has been in game for years?

**Comment by armagidon-exception** [comment]
Opened the video! Checked 1.12.2 vanilla, has the same thing. Just wonder, why it just powered until i update block near it.
UPD: QC works with lamps, but lamps isnt bugged.

**Comment by Proximyst** [comment]
Please share a schematic of the redstone contraption so we don't have to recreate it from a video.

**Comment by Prof-Bloodstone** [comment]
That's normal QC. Replace stone blocks with upper slabs - this should fix it for you.

**Comment by armagidon-exception** [comment]
![2020-07-22_17 01 23](https://user-images.githubusercontent.com/42355119/88185791-09572980-cc3d-11ea-944b-f65e31b2b265.png)
UPD: needed to place 2 upper slabs to fix it

**Comment by Prof-Bloodstone** [comment]
Explanation on WHY it happens.
Minecraft redstone sends update to all touching blocks. And if they change state - they do the same.
Now, the last redstone dust (right above piston) gets unpowered, causing the block between it and the piston to also get unpowered. This in turn sends update to the piston - but it is still powered by other stone block, so it doesn't retract.
Now, when the next redstone wire gets unpowered, it updates the block next to it - but since this block is not touching piston, the piston doesn't get updated.

If you replace the other block with slab, piston will not see it as powered (since non full blocks can't be powered), and thus will retract after getting update from the wire right above it.

(this is somewhat a simplification, but should give you a general idea).

**Comment by armagidon-exception** [comment]
thanks. you can close the issue
