### ISSUE TITLE
Skull ItemStack Creation Causes a Blocking Network Call

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#4004]
###  Timings or Profile link:
https://spark.lucko.me/#W67OANpY46

### Description of issue:
Even when set with setOwningPlayer and provided an offline player the performance of skull itemstack generation is really really bad.

There should be a way to generate skulls using existing on disk information, and/or prebake this information asynchronously so that the hit isn't on the main thread.

### Paper build number:
Paper 113

**Comment by electronicboy** [comment]
This is a spigot change to ensure that skulls are populated on items properly, otherwise they won't update to the client; Paper also provides events such as the profile lookup event to handle caching yourself, https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/profile/package-frame.html

You can also just do it off the main thread, just, make sure to cache stuff properly otherwise you'll overload mojangs API, which can cause issues for users logging in, etc

**Comment by DarkArc** [comment]
One of the things I wanted to work around this actually existed, updating this in case someone stumbles across it.

You can get a player profile by using `Bukkit.createPlayerProfile(UUID)` using the player's `UUID`, then call `PlayerProfile::complete` on another thread, then switch back to the main thread and use `SkullMeta::setPlayerProfile` with the completed profile.

**Comment by aikar** [comment]
your free to even set the item stacks owning player in the other thread too, just dont add the item to an inventory until back on main.

but ultimately, for GUI uses, strongly recommended to manually create profiles with textures already supplied so no network is needed.

Youd only need to do a network call for "Give me players current skin", and if you want an online players skin, player.getPlayerProfile can give you that too.
