### ISSUE TITLE
[1.16.1][paper130]The track doesn't copy properly

### ISSUE THREAD

**Issue by Espboxx** [PaperMC/Paper#4039]
paper 130 The track doesn't copy properly .Downgrading to lower version 113 and normal replication

**Comment by schoentoon** [comment]
Track and copy makes me believe you're looking after rail duplication, in which case please read #3724 and #3854

**Comment by aikar** [comment]
Paper does not support item duplication.

**Comment by Espboxx** [comment]
> 跟踪和复制让我相信你正在照顾铁路复制， 在这种情况下， 请阅读[#3724#3854](https://github.com/PaperMC/Paper/issues/3854)
oh on ， TNT can replicate normally, yml file Already on，but Only rails can't be copied

**Comment by Espboxx** [comment]
> Paper does not support item duplication.

no ，The lower version of paper can copy the track normally, but the higher version can't

**Comment by Espboxx** [comment]
> Paper does not support item duplication.

I am currently using version 113, because version 130 cannot be copied. The configuration file has been set to true

**Comment by aikar** [comment]
If rails no longer works with that config then I'm excited about that. We never wanted rails to have a config, it only originally had one due to it being the same bug as tnt.

However other improvements were made to rails that must have fixed the problem, and if so, that's awesome...

Paper will not be adding support for rail duplication.
