### ISSUE TITLE
Zombie entering minecart behaves differently from vanilla

### ISSUE THREAD

**Issue by bleuthoot-sven** [PaperMC/Paper#4052]
### What behaviour is expected:

Zombie Villager enters the Minecart

(See example video below)

### What behaviour is observed:

The Zombie Villager doesn't enter the minecart

### Steps/models to reproduce:

I've used a slightly modified version of [this villager killer](https://youtu.be/5a7zTWpkS94) for making trades cheaper. 

### Plugin list:

No plugins installed

### Paper build number:

```
> ver
[17:06:07 INFO]: This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[17:06:07 INFO]: Checking version, please wait...
[17:06:07 INFO]: You are running the latest version
```

### Anything else:

Example video's

[Vanilla](https://i.imgur.com/nbEht4L.mp4)
[PaperMC](https://i.imgur.com/00uf6x5.mp4)

This issue doesn't occur on Spigot and behaves the same as Vanilla

**Comment by 4daze** [comment]
Also villagers will not accept workstations while inside a Minecraft, and this does work on vanilla.

**Comment by bleuthoot-sven** [comment]
> 
> 
> Also villagers will not accept workstations while inside a Minecraft, and this does work on vanilla.

I haven't had any issue with it, the Villager station I showed in the example video's all has villagers in minecarts.

But I don't think that is related to this issue.

**Comment by aikar** [comment]
re villagers not taking workstations, That does not work on Vanilla, because that was a very direct and intentional change that they CAN'T take workstations unless they can move to it, and minecarts restrict movement.

aS for the OP's issue, not really sure. Only thing I can figure is Activation Range kicking in and disabling a tick or something. IF that's the case, it'll be very hit or miss based on timing.

What happened is the zombie moved out of the minecarts range fast enough to not get pulled back in and then collided to stop the movement.
