### ISSUE TITLE
Add a permission node for /paper fixlight

### ISSUE THREAD

**Issue by jwosty** [PaperMC/Paper#4066]
**Describe the solution you'd like**
It would be handy to have a permission node for the ``/paper fixlight`` subcommand so that, for example, server moderators could be given access to just that part of the ``/paper`` command. ``/paper fixlight`` has been very useful to me as of late and has been fixing a lot of problems.

**Describe alternatives you've considered**
The only other option that I know of, really, is to grant permissions for the whole ``/paper`` command, which contains many utility functions.

**Comment by HexedHero** [comment]
If you really wanted to, couldn't you just listen for command event. If /paper fixlight and player has "some.custom.perm" it'll be allowed or give them the /paper permission for that tick?

**Comment by 20BBrown14** [comment]
I would like to see this too. I'd to give my players permissions to fix lights without given them permissions for everything else paper has.

**Comment by Brokkonaut** [comment]
A maybe better solution would be to add an api to relight a chunk. so it would be much more flexible.

**Comment by Machine-Maker** [comment]
Is this a serious feature still? I thought it was discussed in the discord and determined that adding a permission would just encourage its use in the wrong situations.

**Comment by Malfrador** [comment]
I did not participate in the discussion in paper discord, but I would really like a permission node for that.

We occasionally have some lighting issue, mainly caused by WorldEdits //perf options. As fixing them by hand is really annoying (and not doable at a certain size), I gave our builder rank the /paper permission. The WE //fixlight command does a far worse job compared to the paper command.

I do trust my builders completely as they are in our team since years, so I don't worry about the other /paper commands too much. But for bigger server teams or just additional safety, a extra permission just for the fixlight subcommand would be great.

I also really don't see the risk for using it in wrong situations. This would always be a permission you give to team members, not every player.

**Comment by jwosty** [comment]
Plus, other plugins don't work nearly as well as this command. This really is the best option I've been able to find.

**Comment by aikar** [comment]
Yes this is desirable, as theres some stuff under paper that you dont want to give to all staff but do want to allow fixlight.

It's just tricky to do this without changing the root paper permission node then assigning each subcommand its own.
