### ISSUE TITLE
1.15.2 Skeletons and illusioners move extremely fast on certain blocks

### ISSUE THREAD

**Issue by piotrskibapl** [PaperMC/Paper#4137]
### What behaviour is expected:
The skeletons and illusioners movement speed should be consistent and should not be affected by the block they are walking on.

### What behaviour is observed:
The skeletons and illusioners move extremely fast when on certain blocks (like any slabs).

### Steps/models to reproduce:
1. Build a platform using any slabs (I used acacia)
2. Spawn a skeleton using the skeleton spawning egg
3. Make sure you are on a survival gamemode and attack the skeleton
4. The skeleton is moving extremely fast

### Plugin list:
none

### Paper build number:
385

### Anything else:
I know that this bug actually exists in the Minecraft itself, but maybe it's possible to be fixed server-side as it is very annoying on some servers like skyblock where players use a lot of slabs to build. This issue is fixed in Minecraft 1.16, but it's still present on 1.15.2.
Mojang ticket: https://bugs.mojang.com/browse/MC-104900

**Comment by Chew** [comment]
Hello, you are correct in that it was mostly fixed in [MC-104900](https://https://bugs.mojang.com/browse/MC-104900) (though still seems to be lingering in [MC-174500](https://bugs.mojang.com/browse/MC-174500)), so as a result this is not in the team's interest to fix themselves. If someone wants to implement this backport themselves, you are more than welcome, but with 1.15.2 support dropping soon with the release of a stable 1.16.1 build, it may just be time to upgrade.
