### ISSUE TITLE
De-opping kicks players not on whitelist

### ISSUE THREAD

**Issue by silverwolfg11** [PaperMC/Paper#4150]
### What behaviour is expected:
When I de-op myself, I expect players to remain online.

### What behaviour is observed:
When I de-oped myself, I noticed that players got kicked for "You are not whitelisted on this server". However, whitelist was not enabled.

### Steps/models to reproduce:
1. Create a whitelist with some players on it. 
2. Make sure `enforce-whitelist` is set to `true`
3. Disable whitelist (`/whitelist off`)
4. Op yourself or another player
5. Deop yourself or another player

### Plugin list:
I believe they are irrelevant for the current issue, but will be happy to provide if necessary.

### Paper build number:
Paper 1.16.1 #136

### Anything else:
I was looking at the source code for this and it seems like vanilla only checks if the `enforce-whitelist` property is enabled, but not if whitelist is actually enabled. So adding that check may resolve the issue. I don't know if this is intended behavior, but it definitely seems weird to me that it doesn't even check if whitelist is enabled.

**Comment by danny6167** [comment]
This is https://bugs.mojang.com/browse/MC-145260
Original paper bug here - https://github.com/PaperMC/Paper/issues/1880
But was apparently patched. Was the patch dropped ?

**Comment by danny6167** [comment]
Patch appears to still be in, so I guess someone needs to take a look at why it's not working anymore.
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0338-MC-145260-Fix-Whitelist-On-Off-inconsistency.patch

**Comment by ann4belle** [comment]
Edit: The problem(?) seems to be that `enforce-whitelist` is taking priority over the `/whitelist` command. Not sure if that's intended behavior or not, but my gut says it is since `enforce-whitelist` can only be set by the server owner, while `/whitelist` is a command usable by all OPs. However, running `/whitelist off` when `enforce-whitelist` is true does misleadingly state that the whitelist is off, when it is in fact on.

Original comment:

I can't seem to reproduce this. Are you certain you don't have the whitelist enabled?

Steps I took (on a test server spun up on docker):

1. Create and start new server.
2. Whitelist my account.
3. Stop server.
4. Set `enforce-whitelist`.
5. Restart the server, connect, op and deop myself.

Running "whitelist off" says the whitelist is *already* turned off.

**Comment by jaylawl** [comment]
This also happened to me last night. Running git-Paper-128 (1.16.1)

**Comment by Chew** [comment]
Last night? On an old build? Try latest (1.16.3)
