### ISSUE TITLE
1.15.2 TRAP Firework crash

### ISSUE THREAD

**Issue by HexedHero** [PaperMC/Paper#4162]
https://paste.gg/p/anonymous/07a13f8f7afe4822ba7513ad7dddf6e1/files/6aafdf22805145a495aa252b1d505df8/raw

### Paper build number:
[17:30:32 INFO]: This server is running Paper version git-Paper-385 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[17:30:33 INFO]: You are running the latest version

**Comment by electronicboy** [comment]
The issue here is a plugin is modifying an item in an unexpected state for the server, closing as a duplicate as there are many reports of this issue in many different areas, general stance from upstream is that plugins should fix this, adding all the checks to all the areas where this would be needed is very eer
