### ISSUE TITLE
Portal Blocks Spawn In Wrong Spot, End Portal 1.12.2

### ISSUE THREAD

**Issue by IWentPro** [PaperMC/Paper#4183]
Whenever I create an end portal with the frames, it either doesn't spawn in or the portal blocks spawn outside the frames instead of between them. I've tried this with and without plugins and the issue is still persistent throughout both trials. How do I fix this?

**Comment by MiniDigger** [comment]
Screenshot?

**Comment by IWentPro** [comment]
I can't get the portal glitch to recreate itself, but it just won't spawn at all now.
![2020-08-23_12 19 05](https://user-images.githubusercontent.com/35195656/90983334-44e65b80-e53b-11ea-9a5b-378ff6fcef62.png)

**Comment by IWentPro** [comment]
Nvm got it.
![2020-08-23_12 23 47](https://user-images.githubusercontent.com/35195656/90983359-87a83380-e53b-11ea-95fc-676b63343944.png)

**Comment by kennytv** [comment]
Support for 1.12 has been long gone

**Comment by IWentPro** [comment]
What's the best version to use pre-1.14 cause I hate the new update mechanics. And I don't want people to dupe and stuff

**Comment by kennytv** [comment]
Paper should have fixes for all sorts of dupes even in the latest stable version. ;) But if you really don't like it, you can either try 1.13.2 or you're out of luck

**Comment by IWentPro** [comment]
I'll try upgrading to 1.13 and see if that fixes the portal issue.

**Comment by Chew** [comment]
Unfortunately we do not support any version below 1.15.2. You are free to use any version you want, but if it's not on our download site, then we don't support it. If this issue happens to also be on 1.15 or 1.16, feel free to open a new issue, and also ensure you're following the template as well. Thanks for the report, and have a good day!

P.S. If you want to support older versions, try ViaBackwards. A lot of dupes are fixed in later versions but still exist in older, so you'd likely have LESS ways to dupe if that's what your concern is.
