### ISSUE TITLE
Unexpected crash.

### ISSUE THREAD

**Issue by AlexisWiiu** [PaperMC/Paper#42]
http://hastebin.com/ayutukuvat.vbs

Saw this type of crash 14 months ago when running Spigot. After 1 day of Paper this happened, so I'm assuming either it or it + another plugin is the cause. Just posting it here for reference, will update if the issue reoccurs.

**Comment by TitanicFreak** [comment]
First of all, that seems outdated, unless you of course used papertools which you shouldn't.

And secondly it seems like ServerListPlus is causing your issues, mainly because of this,

[22:33:44] [Craft Scheduler Thread - 691/INFO]: [ServerListPlus] [Core] Saving player identities...

As after that, no commands are processed.

Just my 2 cents on it.

**Comment by Techcable** [comment]
Does this happen alot?
Looks like its spending too much time saving players.
As @TitanicFreak suggested, it looks like it is caused by ServerListPlus 'saving player identities'.

**Comment by zachbr** [comment]
We do not currently have plans to support 1.8.8 unless there's some severe issue that pops up.
Thanks anyway :)
