### ISSUE TITLE
Compatibility with InventoryTweaks

### ISSUE THREAD

**Issue by Platinteufel** [PaperMC/Paper#420]
Latest PaperSpigot, 0 Plugins, default configs. 
**Related video:** https://youtu.be/Q6KHmAMkYuQ
**Related issue:** https://github.com/Inventory-Tweaks/inventory-tweaks/issues/390

If I try to sort chests on my server (latest PaperSpigot 1.10.2) with InventoryTweaks I'll get ghost items into my inventory/hand. 
It works fine on vanilla servers, seems like it's related to spigots item movement handling.

**Comment by zachbr** [comment]
Uber low priority. Absolutely no ETA.

Any fix must remain compatible with existing plugin behavior. Needs quite a bit of investigation, confirmation, and testing.

**Comment by DenWav** [comment]
Not enough tacos.

**Comment by AlfieC** [comment]
we must go deeper

**Comment by Brokkonaut** [comment]
https://github.com/PaperMC/Paper/commit/c02c01b2c531384dfe8f2d1d721113bada4892cb

Could you please make it disableable? And also make interact limiting disableable again? We have huge problems on our worlds since this update. Lots of ghost blocks in the world with interact limit and lots of ghost items in the inventory...

(Our creative server is sometimes a bit overloaded and laggy - Without interact limit it was no big problem, but now its nearly unusable)

EDIT: Ok found out that use limiter is disableable by setting the play-in-use-item-spam-threshold to 0. some setting like this for interacts would be really helpful.

**Comment by DenWav** [comment]
@Brokkonaut this is an issue regarding InventoryTweaks (hence the title), not that change. Create a new issue instead.

**Comment by Brokkonaut** [comment]
That change causes the problems with InventoryTweaks..

**Comment by zachbr** [comment]
No, it doesn't.

**Comment by Brokkonaut** [comment]
Ok, I'm sorry, I was wrong

**Comment by zachbr** [comment]
@Brokkonaut no biggy, and the setting now handles both as of 2b244fb51ecaf4dc9be99ba797a174fbee34bc28

As such it was renamed to the more generic `incoming-packet-spam-threshold`, though it should pull the old setting automatically.

**Comment by Platinteufel** [comment]
Seems like you need to go even deeper. ☕️ 🍩 ^^

**Comment by Combustible** [comment]
This behavior is the same with vanilla and Spigot. I've actually spent a *lot* of time investigating this issue - here is what I have learned: 

The problem is actually not inventory tweaks - but something inventory tweaks does triggers the actual bug. The problem is that for custom items (i.e. with custom enchantments, display name, lore, attributes, etc.) minecraft's system which tests for item equality is inconsistent. In some places, items are considered "equal" when their stats match - and in others, they are only equal if the NBT data is in *exactly* the same order. 

The weird part is - there is some kind of "magic" order for NBT to be in. Inventorytweaks' sorting system actually causes the items to be reordered into the "correct" order. When you click the sort button on a chest, it puts an "incorrectly" ordered item into your mouse - and a "correctly" ordered item is moved to your inventory. That item that was moved to your inventory has correctly sorted NBT data. You can actually "fix" (reorder) item data using this - basically click the sort button a bunch of times on a chest and shuffle the items that get moved into your inventory into a new chest. This new chest, when sorted, will never exhibit this behavior. 

This is confusing as hell, but I believe that if the upstream code was patched to consider equal-but-different-ordered NBT data to be "equal", then inventory tweaks sorting would be fixed. It would also fix villagers occasionally not accepting trades for custom items (because they are "the same" but differently ordered)
