### ISSUE TITLE
InventoryClickEvent#getAction method always returning PLACE_ALL in creative menu

### ISSUE THREAD

**Issue by Archy-X** [PaperMC/Paper#4246]
### What behaviour is expected:
InventoryClickEvent.getAction() should return the correct action type

### What behaviour is observed:
In the creative menu InventoryClickEvent.getAction() always returns PLACE_ALL no matter what action type was actually performed.

### Steps/models to reproduce:
1. Write an InventoryClickEvent event to print out what is returned with the getAction() method
`
@EventHandler
public void onClick(InventoryClickEvent event) {
     Bukkit.broadcastMessage(event.getAction().toString());
}`
2. Register the event
3. Go into creative mode and open the creative inventory (press e)
3. Click to pick up, place, or move around items in the HOTBAR or Survival Inventory tab
4. Check console or chat, PLACE_ALL will be the only thing that is printed

### Plugin list:
No plugins except the plugin used to test the bug.

### Paper version:
[16:06:46 INFO]: This server is running Paper version git-Paper-161 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[16:06:46 INFO]: Previous version: git-Paper-"dccaf59a0" (MC: 1.16.2)
[16:06:46 INFO]: You are running the latest version

### Anything else:
This bug works on Paper 1.12, Paper 1.16.1 and probably any version

**Comment by chickeneer** [comment]
For the InventoryCreativeEvent (which is what is happening), it will only ever return the action PLACE_ALL by design. 

The simple explanation, is that the client tells the server which item to create, and then triggers the event. Creative mode does not track items in the cursor in the creative menu. Hence there is no concept of where the items are coming from.

Put another way. It is like the creative mode player runs `Inventory#setItem` on their own inventory.

This inventory click events are kind of jank with how they relate to each other, ideally - there wouldn't be a action type for the creative event. But since it extends the base click event... It just inherits it.
