### ISSUE TITLE
Scoreboard performance semi leak

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Paper#4260]
###  Timings or Profile link:
**Before:** https://timings.aikar.co/?id=3e60f03df39441cd9d57d6a9b45190f9#timings
**After:** https://timings.aikar.co/?id=d9b5b0c85af34fd6b2bd2c96746b9eb1#timings

### Description of issue:
I believe I've figured out why scoreboards are causing so many performance issues. Whenever a scoreboard is created it's stored in a weak collection, however it seems to take a while for the scoreboard to be removed even when there are no references to it. Some plugins (mine at least) create many scoreboards and just rely on the scoreboard to be garbage collected. This results in basically a memory leak, but not in the sense you will run out of memory (scoreboards don't take up a lot of memory). There's just so many scoreboards in the collection it takes a very long time to search through the collection and find the score of a scoreboard. The only way I've figured out to fix this is to use reflection and remove the scoreboard from the collection after I'm done with the scoreboard. I listed the results before & after I did this change above.

I'm not really sure what you would do to fix this, maybe add a method to the API to unregister the scoreboard? Just thought I'd bring it to the attention of the developers.

### Paper version:
Observed and tested on: git-Tuinity-"ae2d7fc" (Latest 1.15.2 Tuinity) however it affects paper as well.

**Comment by Chew** [comment]
Please provide timings and report your findings on Paper. Otherwise, toss this up to the Tuinity issue tracker at https://github.com/Spottedleaf/Tuinity and close it here. We do not support forks.

**Comment by AoElite** [comment]
This applies to paper as well, maybe try reading what I said first?

**Comment by AoElite** [comment]
The issue applies to paper as well. The scoreboard code I'm referring to is the exact same.

**Comment by JRoy** [comment]
That's great that it applies to paper too! That means you are able to reproduce it on Paper and not a fork! In which case please provide a spark profiler report and timings while on Paper. Software changes on Tunity can cause debugging the exact problem on Paper a nightmare. Maybe try applying common sense before you act snippy?

**Comment by jacobsandersen** [comment]
I'll try to repro tomorrow.

**Comment by jacobsandersen** [comment]
Apparently paper doesn't time scoreboards, so what I'll do is make a minimal plugin that does what the OP describes (as best as I can) and then get a spark profile. Maybe we can try to get that patch in to paper? Seems useful to time those

**Comment by electronicboy** [comment]
CB stores plugin created scoreboards in a weak collection, this is usually not an issue as GC is able to clean these out, the issue is really when plugins, etc, are churning scoreboards. 

Having an unregister method would be ideal to allow plugins to pull their stuff out, but it's really not going to fix the issue as it stands

**Comment by jacobsandersen** [comment]
MWE: https://github.com/simpleauthority/paper4260mwe

Download [from my fileserver](https://drop.jacobandersen.dev/minecraft/paper/issue/4260/paper4260mwe-1.0.0.jar) or from the release tag on the above repo. The MWE is very simple, it just churns new scoreboards for every connected player every tick with the current time in seconds.

Spark Profile: https://spark.lucko.me/#LiaVrhcV0B

I don't quite see where the issue is here. I am not including a timings report as it likely won't show anything of interest but if requested I will get one to include.

The profiler ran for around 15-20 minutes. Maybe needs to be tested with more connected players or something.

**Comment by MrPowerGamerBR** [comment]
Can confirm that this issue happens, the problem is that it looks like the list is only emptied when a Full GC happens.

If you are running with a large heap while having a lot of free memory, a Full GC won't ever run and the scoreboard collection will never be emptied. (my server always has ~8GB memory free)

This does not happen if the "the issue is really when plugins, etc, are churning scoreboards.", even if you only create one scoreboard per player on join you are bound to hit this issue sooner or later, requiring a restart OR a Full GC to be triggered.

Would be nice to implement a auto clean up task on Paper to avoid this issue.

How I found out that this only happened when a Full GC happens? Well, I thought that maybe one of the plugins was holding references to the scoreboard object, so I decided to do a heap dump of my server... and that triggered a "Pause Full (Heap Dump Initiated GC)", which magically cleaned up the scoreboard list.

Here's the source code of my scoreboard plugin: https://github.com/SparklyPower/SparklyPower/blob/master/DreamScoreboard/src/main/kotlin/net/perfectdreams/dreamscoreboard/DreamScoreboard.kt#L36

Here's the source code of the scoreboard thingy via teams: https://github.com/SparklyPower/SparklyPower/blob/master/DreamCore/src/main/java/net/perfectdreams/dreamcore/utils/PhoenixScoreboard.kt#L16

Here's my server timings (using Tuinity, but Tuinity *was* the reason I was able to track down why it was lagging, since Paper does NOT track scoreboard score search): https://timings.aikar.co/?id=a870bb44647b4de8990f50f537bda2e3

Here's my server spark sample showing that the scoreboard *does* lag: https://spark.lucko.me/#TU1UVhG5YH

I've implemented this code
```kotlin
                val playerScoresMethod = (Bukkit.getScoreboardManager() as CraftScoreboardManager)::class.java.getDeclaredField("scoreboards")
                playerScoresMethod.isAccessible = true
                val map = playerScoresMethod.get(Bukkit.getScoreboardManager())
                println(map as WeakCollection<*>)
                println(map.size)
```

And the result was 3696 scoreboards (!). The `playerScores` only had ~40 (which was the current player count), so it is certainly a leak that should be fixed.

For now I created my own clean up code on my plugin, cleaning up any scoreboard that is not used by any player
```kotlin
		// Needs to be fixed: https://github.com/PaperMC/Paper/issues/4260
		scheduler().schedule(this, SynchronizationContext.SYNC) {
			while (true) {
				val scoreboardsField = (Bukkit.getScoreboardManager() as CraftScoreboardManager)::class.java.getDeclaredField("scoreboards")
				scoreboardsField.isAccessible = true
				val weakCollection = scoreboardsField.get(Bukkit.getScoreboardManager()) as WeakCollection<CraftScoreboard>

				logger.info("Weak Collection before clean up size is ${weakCollection.size}")

				val playerBoardsField = (Bukkit.getScoreboardManager() as CraftScoreboardManager)::class.java.getDeclaredField("playerBoards")
				playerBoardsField.isAccessible = true
				val playerBoards = playerBoardsField.get(Bukkit.getScoreboardManager()) as Map<CraftPlayer, CraftScoreboard>

				weakCollection.removeAll(weakCollection - playerBoards.values)

				logger.info("Weak Collection after clean up size is ${weakCollection.size}")

				waitFor(20 * 60) // 1 minute
			}
		}
```

Of course, that code *won't work* if you use scoreboards that are not bound to players, if you prefer to clean up yourself, here's a small method that does the clean up process:
```kotlin
	val scoreboardsField = (Bukkit.getScoreboardManager() as CraftScoreboardManager)::class.java.getDeclaredField("scoreboards").apply {
		this.isAccessible = true
	}
	val playerBoardsField = (Bukkit.getScoreboardManager() as CraftScoreboardManager)::class.java.getDeclaredField("playerBoards").apply {
		this.isAccessible = true
	}

	fun cleanUp(scoreboard: Scoreboard) {
		// Needs to be fixed: https://github.com/PaperMC/Paper/issues/4260
		val scoreboards = scoreboardsField.get(Bukkit.getScoreboardManager()) as WeakCollection<Scoreboard>
		scoreboards.remove(scoreboard)
	}
```

**Comment by PaulBGD** [comment]
The spark shows the scoreboard lookup sitting at 0.20% of tick usage.. I don't think that's very important, given a more loaded server that does GCs more often and will empty the map. As well I don't think 4k scoreboards is huge at all, compared to Paper with no plugins making 500k allocations a second. I wouldn't be surprised if that scheduler ends up being slower than the "leak" itself, especially on an actually loaded server.

**Comment by MrPowerGamerBR** [comment]
> 
> 
> The spark shows the scoreboard lookup sitting at 0.20% of tick usage.. I don't think that's very important, given a more loaded server that does GCs more often and will empty the map. As well I don't think 4k scoreboards is huge at all, compared to Paper with no plugins making 500k allocations a second. I wouldn't be surprised if that scheduler ends up being slower than the "leak" itself, especially on an actually loaded server.

Sorry, my mistake, I pasted the wrong Spark profiler URL, check this one out: https://spark.lucko.me/#TU1UVhG5YH

Also, Tuinity's timings doesn't lie, they do show that a considerable amount of ticks are used just for scoreboard score search. The lag magically vanished after the Full GC (triggered by the heap dump) happened. This issue can be timed in Paper by... well, forking Paper and copying Tuinity's scoreboard score search timings code. Also, as @AoElite said, the scoreboard code is identical in Paper as well. (the only difference is the timings part)

The problem is that scoreboards are not being evicted if you have a large heap dump that never triggers a Full GC, causing CPU issues.

And it is huge, because *every time* a player ticks, it loops *all the scoreboards in the server* to get *all the scores*, this uses A LOT of CPU. After I cleaned up the collection and implemented my own clean up methods, the TPS is now 20 and is not dropping anymore.

**Comment by MrPowerGamerBR** [comment]
And before anyone pulls the "omg u are using tuinity reproduce in paper pls" card:

I created a plugin that creates 50 scoreboards every tick and attaches every single created scoreboard to the online player:

```kotlin
			scheduler().schedule(this, SynchronizationContext.SYNC) {
				while (true) {
					// create dummy scoreboard
					repeat(50) {
						val scoreboard = Bukkit.getScoreboardManager().newScoreboard

						Bukkit.getOnlinePlayers().firstOrNull()?.scoreboard = scoreboard
					}

					val scoreboards = scoreboardsField.get(Bukkit.getScoreboardManager()) as WeakCollection<Scoreboard>
					println("Weak Collection Scoreboard Count: ${scoreboards.size}")

					waitFor(1L)
				}
			}
```

CPU usage results: https://spark.lucko.me/#ptas2yf9PI

9,34% CPU usage on the `CraftScoreboardManager.getScoreboardScores` method with only one player online! 60k unused scoreboards were in the list until GC was executed. Because this method is called for every online player, if we had 50 online players we would *theorically* use 100%+ CPU usage!

To reproduce this issue, please lower your server view-distance (to avoid high memory usage) and use this flags:
```
java -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -jar paperclip.jar nogui
```

`[16:45:44 INFO]: This server is running Paper version git-Paper-209 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`

I think @simpleauthority wasn't able to reproduce the bug because they were running their server with a low heap, so GC was being executed every time before the issue became apparent.

**Comment by astei** [comment]
This issue should be fixed now. Plugin scoreboards are no longer registered with the server by default until a non-dummy objective is added. This should fix the issue for good. In addition this will also deliver a performance improvement by reducing scoreboard lookups in general.
