### ISSUE TITLE
CPU usage for each plugin

### ISSUE THREAD

**Issue by ohAleee** [PaperMC/Paper#4273]
**Is your feature request related to a problem? Please describe.**
How many times do people complain about high CPU and don't understand the problem? For this it would be very convenient to have a way to see CPU usage for plugins.

**Describe the solution you'd like**
A trivial command (example: / cpu <plugin>) which returns you a message with the use of the cpu of per plugin in the last minute. Some plugins already do this but are old and out of date. A plugin that has this features is TAB on spigotmc.org

**Describe alternatives you've considered**
A more refined alternative would be to use a gui (in addition to the command).

**Additional context**

Example of the TAB plugin

![2020-09-02_11 10 03](https://user-images.githubusercontent.com/36593455/91962526-eecca180-ed0c-11ea-89f0-2963d488c540.png)

**Comment by Proximyst** [comment]
Not only can you not accurately measure how much CPU time every single plugin uses, it also adds issues with integration. What happens if a plugin, CoolPlugin, calls Essentials stuff?

This will most definitely not be implemented. Timings already exist to help diagnose stuff like this (with time per tick) too. Not the best solution, but it was doable.
