### ISSUE TITLE
Problem with colored names.

### ISSUE THREAD

**Issue by wallxq** [PaperMC/Paper#4305]
I noticed a problem, I reported it to both developers but I have the impression that it may be the fault of the engine itself.
The first problem is with optifine. When I use a colored name in CIT armor, optifine reads the item correctly. However, after re-entering the server, the CIT no longer works on the same item.

The second problem is with MythicMobs. When spawning an item with a colored name that stacks up, it doesn't read by SKRIPT via:
 "if player has 2 iron ingot named "&6&lBiała Wstęga +" with custom model data 81:"

However, again after re-entering the server this item is suddenly visible by SKRIPT and after re-spawning by MythicMobs it does not stack with the item before re-entering the server as if it were a different item even though it has the same NBT.
The problem does not occur if I do not use colors. I use the latest 1.16.2 paperspigot from today and MythicMobs as well as Optifine and Skript.

**Comment by Chew** [comment]
IF this problem can not be reproduced without ANY of the mods or plugins you mentioned above, then this is not our issue. It is up to them.

By the way, we are called Paper now.

**Comment by Chew** [comment]
Upstream issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5063

**Comment by SaltyPotata** [comment]
Still no info?

**Comment by wallxq** [comment]
> Still no info?

Spigot doesn't seem to care about the problem.  I don't see anyone taking care of it there, except for the person who reported and probably solved why.  Comment here https://hub.spigotmc.org/jira/browse/SPIGOT-5063?focusedCommentId=37231&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-37231

**Comment by Shevchik** [comment]
Essentially you just don't do stuff with custom names which include color codes, and that's it (or you strip the color codes beforehand). If you need to put some data in itemstack, you can and should use PDC.
The legacy color code -> json chat -> legacy color code can't really return the original result in all cases (Because of reset code not existing in json chat components, so you can only guess where it was in original string for example. Also you can't restore the same order of format style codes, because json style modifier has no order for formats, so it isn't really worth attempting to do that.

**Comment by wallxq** [comment]
Nothing change? 🙄

**Comment by Chew** [comment]
As this is a Spigot issue, you're free to sign their CLA and fix this issue if you want a change. We may fix this if we have time, but, since we are all volunteers, this is all done in our free time. If the issue is open, there is no change. Saying "no change" isn't going to do anything outside of you looking impatient.

**Comment by Jenzimi** [comment]
I think spigot fixed it https://hub.spigotmc.org/jira/browse/SPIGOT-5063

**Comment by Chew** [comment]
It would've been https://github.com/PaperMC/Paper/commit/9f61759d9048f4322d98c524ebaeda00444c648f
Please let us know if this problem persists on the latest build by opening a new issue.
