### ISSUE TITLE
the special rails are cut off when the sticky piston pulls back

### ISSUE THREAD

**Issue by graycat27** [PaperMC/Paper#4335]
### What behaviour is expected:
when the sticky piston pulls back the special rails...
(special rails ::= powered rail, detector rail, activator rail )
the rails are still connected with both beside.

photos taken in 1.16.3 vanilla
STEP1 set rails on the blocks
![2020-09-17_19 27 57](https://user-images.githubusercontent.com/64903817/93463303-88599d00-f922-11ea-984c-6ba09415fc53.png)
STEP2 push up the rail with the sticky piston
![2020-09-17_19 28 07](https://user-images.githubusercontent.com/64903817/93463342-96a7b900-f922-11ea-9072-7a89caab2d77.png)
STEP3 pull back the rail
![2020-09-17_19 28 14](https://user-images.githubusercontent.com/64903817/93463739-22214a00-f923-11ea-917f-277469104981.png)
all rails are connected

### What behavior is observed:
in paper server, at STEP3 written above,
special rails placed beside are broken.
![2020-09-17_19 29 38](https://user-images.githubusercontent.com/64903817/93464196-bee3e780-f923-11ea-831c-0309644ccb86.png)

### Steps/models to reproduce:
see the 3steps written in "What behaviour is expected:"

### Plugin list:
nothing

### Paper version:
Paper version `git-Paper-197 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`

### Anything else:
I tested the behavior in vanilla and also spigot`git-Spigot-2740d5a-890130b (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`
Both seems works as I wrote in "is expected"

**Comment by graycat27** [comment]
add information to reproduce
- It doesn't matter the direction
- Caused by the special rail pulling back by the sticky piston

STEP1 first place blocks and rails as see..
![image](https://user-images.githubusercontent.com/64903817/93478327-b9dc6380-f936-11ea-8fd0-1bc10b4c5111.png)
STEP2 push up
![image](https://user-images.githubusercontent.com/64903817/93478616-ccef3380-f936-11ea-8a1a-8f5ec2c4186a.png)
STEP3 pull back
![image](https://user-images.githubusercontent.com/64903817/93478793-d7a9c880-f936-11ea-9e2a-08b67f119536.png)
the rails which placed besides are broken when the special rails pulling back.

**Comment by aikar** [comment]
Try enabling TNT duplication option in unsupported options in paper.yml
It's possible this behavior is dependent on a piston bug.

**Comment by graycat27** [comment]
thanks @aikar 
it worked well!

changed just this yml config, from false to true:
`settings:
  unsupported-settings:
    allow-piston-duplication: true` 
then, all types of rails stay connected!

**Comment by chickeneer** [comment]
I have created a short video to demonstrate a vanilla rail mechanic which appears to be somewhat consistent with the behavior seen on Paper.
https://youtu.be/VY_2PHm7k1c

To explain in my own words, it is consistent with vanilla for the ascending shaped rails to break when the supporting block is no longer there. This is shown in the first example.
The second example demonstrates what happens when the supporting block becomes a rail and the upper one drops due to no lower supporting block - which looks like the paper mechanic.

My only point in bringing this up is to normalize that rails drop quite frequently (when sticky pistons are not involved).
I think the vanilla mechanic shown is unexpected in context of all of the ways that rails break.
Yes it is inconsistent with vanilla. But the behavior of rails are not generally friendly to reshaping... this issue would not keep me up at night.

I would either want Mojang to implement a fix to the piston duping issue so the Paper behavior is normal AND/OR Mojang to make rails less prone to breaking in general - just more reshaping. Both of which would be for Mojang to do, not Paper.
(assuming it is not feasible to solve this issue in the blocking piston duplication patch).

**Comment by aikar** [comment]
what chicken said, but regardless, any unknown side effects of stuff depending on the dupe bug will be (Won't Fix) and people will have to decide if that behavior is worth letting people duplicate things.
