### ISSUE TITLE
Wither Skeletons not spawning on wither roses

### ISSUE THREAD

**Issue by Kooramah** [PaperMC/Paper#4583]
Hi,

There is a bug that has been fixed on 1.16 that Wither Skeletons were not able to spawn on wither roses: https://bugs.mojang.com/browse/MC-182743

I am on Paper-206 1.16.3. I made a Wither Farm similar to found on MC-182743 and I cant seem to get Wither Skeletons to spawn on top of wither roses.

### What behaviour is expected:
Wither Skeletons should be spawning on top of wither roses

### What behaviour is observed:
Wither Skeletons are not spawning on wither roses

### Steps/models to reproduce:
Tried something similar to: https://www.youtube.com/watch?v=le_tTlKEbyw

**Comment by Prof-Bloodstone** [comment]
Do wither skeletons spawn when there's no wither roses? Maybe, as mentioned in the ticket you linked, it was caused by another bug: https://bugs.mojang.com/browse/MC-184740

**Comment by Kooramah** [comment]
Yes, they happen to spawn when there are no wither roses.

**Comment by BolongL** [comment]
Yes, I'm having the same issue, pretty this is not caused by this bug https://bugs.mojang.com/browse/MC-184740
because wither skeletons can spawn in neither fortresses but not on wither roses. 
We just updated to paper 249 and still experiencing the issue.

**Comment by ixayy** [comment]
I am also experiencing this issue, wither skeletons spawning perfectly in fortresses but not on top of wither roses

**Comment by rrvk** [comment]
I have also build that farm with the wither roses and my farm works and the wither skelletons spawn on the wither roses
Try to build it in a clean server without any plugins?

**Comment by BillyGalbreath** [comment]
I believe I found the root cause of this issue, but it's in vanilla code. Are ya'll 100% certain this _only_ effects Paper, and it works as intended in Spigot and vanilla?

Technical details of what I've found: If you look at the method `SpawnerCreature#a(IBlockAccess, BlockPosition, IBlockData, Fluid, EntityTypes<?>)` (known as `SpawnHelper#isClearForSpawn` in yarn mappings) you will see that it is checking the `PREVENT_MOB_SPAWNING_INSIDE` block tag (which contains wither roses) which says its not allowed to spawn inside wither roses _before_ it checks the `EntityTypes#a(IBlockData)` method (known as `EntityType#isInvalidSpawn` in yarn) which says its _okay_ to spawn inside wither roses. The checks are just in the wrong order, so its denying the spawn before it can be allowed.

**Comment by ScreaminMonk** [comment]
I’m on a multiplayer Java 1.16.4 server running Paper #395 and have no problems with wither skellys spawning on a platform of netherrack and wither roses. We have a handful of plugins and DPs running. 

Adding that it pays to double check that you are putting the platform actually inside the bounding box of the fortress crossroads area and that it helps to make everything else around non-spawnable.

**Comment by e-im** [comment]
I haven't been able to reproduce this issue, spawning on wither roses seems to work the exact same way that it does in vanilla and the linked world download works as intended. If you are still experiencing this on 1.17.1, leave a comment.

**Comment by ghost** [comment]
> I haven't been able to reproduce this issue, spawning on wither roses seems to work the exact same way that it does in vanilla and the linked world download works as intended. If you are still experiencing this on 1.17.1, leave a comment.

I play in Vanila 1.17.1 Minecraft, and im too facing the same issue, no Wither Skeletons are spawning on Wither Rose

**Comment by e-im** [comment]
Still can't reproduce almost a year later. If anyone is still having problems with this in 1.19.1 without any plugins, datapacks, or other modifications, leave a comment.

**Comment by RickertvD** [comment]
Playing on 1.20 and encountering this issue on java. Made the world in 1.19 and it didn't work back then either.
