### ISSUE TITLE
Patrols not spawning in Paper 1.16.3

### ISSUE THREAD

**Issue by christofin** [PaperMC/Paper#4589]
### What behaviour is expected:

disable-pillager-patrols is set to false in paper.yml, and there isn't a setting in bukkit.yml or spigot.yml that would affect patrols. However, even with disable-pillager-patrols set to false, patrols still aren't spawning. I also double checked the gamerule for doPatrolSpawning and it's set to true. 

### What behaviour is observed:

Patrols are not spawning. 

### Steps/models to reproduce:

I'm not sure the best way to reproduce the issue -- patrols simply aren't spawning. Just play the game long enough and you'll notice the lack of patrol spawns. 

### Plugin list:

Plugins (10): AutomaticInventory, CustomJoinLeaveMessage, DiscordSRV, dynmap*, Harbor, Lasso, LuckPerms, PluginConstructorAPI, Vivecraft-Spigot-Extensions, WorldBorder

### Paper version:

[Tue, 29. Sep 2020 11:52:57 EDT INFO] This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[Tue, 29. Sep 2020 11:52:57 EDT INFO] Checking version, please wait...
[Tue, 29. Sep 2020 11:52:58 EDT INFO] Previous version: git-Paper-204 (MC: 1.16.3)
[Tue, 29. Sep 2020 11:52:58 EDT INFO] You are running the latest version

### Anything else:

I don't think that this is a Paper 1.16 specific bug, as I've noticed that Patrols haven't spawned for a long time now -- possibly as far back as one of the 1.15 or 1.14 builds.

**Comment by Chew** [comment]
Can you reproduce this without plugins? I think there's been some issues with this before and it was some random plugin messing with it.

**Comment by AceChickenLouie** [comment]
I was discussing this issue with @christofin on a [reddit post](https://www.reddit.com/r/admincraft/comments/j1o9b1/i_updated_my_vanilla_server_to_paper_and_pillager/), with the same observations about a lack of patrols spawning. They suggested I also submit my setup information here:
### Paper version:
This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
### Plugin List:
Plugins (5): dynmap*, LuckPerms, MyPet, PickupArrows, VillageInfo

**Comment by electronicboy** [comment]
The only changes we really have to patrol spawning is the option for per-player timers, best off the top things are going to be to check the patrol gamerule (Some people have had issues with gamerules resetting somehow, however, this was fixed upstream)

**Comment by christofin** [comment]
Hi, I've disabled my plugins and still haven't seen a patrol in the 5 days I've had plugins disabled. I did manually set the gamerule for patrol spawning to true, just in case if the gamerule was edited (I haven't ever touched it, but did this based on electronic's previous comment). 

I'm not sure the best way to test this at this point, since it's something as intermittent as infrequent mob spawning.

**Comment by DXUltimate** [comment]
I have 54 plugins on my server and patrols still spawn. They're just incredibly rare, as they're intended to be. They're not suppose to spawn as "rapidly" as 1.15 did. =3

**Comment by schoentoon** [comment]
As far as I understood it 1.16 also added the requirement that the player should not be too close to a villager for a patrol to spawn, although I am not sure what the exact range for this is. May want to check if that's the case here.

**Comment by AceChickenLouie** [comment]
I think @schoentoon might be on to something with this. Looking at the [Mojang issue tracker](https://bugs.mojang.com/browse/MCPE-72851?jql=project%20in%20(MC%2C%20MCPE)%20and%20(resolution%20is%20empty%20or%20resolution%20in%20(1%2C%202%2C%206))%20and%20(summary%20~%20%22patrol%22%20or%20summary%20~%20%22pillager%20patrol%22%20or%20summary%20~%20%22illager%20patrol%22)%20order%20by%20resolution%20desc) there are multiple comments regarding patrols not spawning as frequently since 1.16. The only patch note I can find comes from the wiki, and I suspect these are all changes working as intended but just not communicated clearly.
### Patrols

- Patrols no longer spawn when the player is close to any intact village.

I haven't come across any more technical information, as to how the distance to the village is calculated or what the limit is. But in my own case, **this is almost certainly it**; I moved a villager from afar right next to my main play area right around the time I updated to 1.16 and vanilla to paper.

I will post any additional observations if any players report finding a patrol while exploring further away from the base/village.

**Comment by schoentoon** [comment]
Had to dive into the source for it. It looks like it's a 48 block range from the player to the closest villager.

**Comment by aikar** [comment]
so my gist of the conversation is this is working as designed?
