### ISSUE TITLE
spam messages [WARN]

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#465]
http://pastebin.com/97JrQRRS

paperspigot build 910

**Comment by zachbr** [comment]
Please don't just dump random crap on us.

Had you bothered to look into this issue you'd have very quickly found out that the boat is moving faster than it should be, and as boats and other vehicles are now handled client side this could be a malicious player, or caused by server TPS or network lag issues.

And yet again you didn't even bother to follow the issue template.
This question belongs on the forums, not here. Figure out how we handle things or be blocked from creating new issues here. You are a repeat offender of this type of behavior.
