### ISSUE TITLE
paper chunk ban

### ISSUE THREAD

**Issue by Sulferix** [PaperMC/Paper#4748]
fill up a shulker with illegal stacked 32ks, and place and mine the shulker in surivival. this will cause a chunk ban until the item despawns.(you dont need to pick up the item) for some reason, if breaking the shulker in creative, this isnt an issue. 

heres the error, happens right after mining the shulker and whenever attempting to login: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException; Tried to read NBT tag that was too big; tried to allocate 2097180bytes where max allowed: 2097152

running paper spigot 262

**Comment by LaurenceBarnes** [comment]
This issue is still a thing though, and can be a severe problem for creative servers out there.

**Comment by sudofox** [comment]
Trying to find a solution to this. The particular stacktrace from the crash can be found here:

https://gist.github.com/sudofox/534b9cbd76af1a7724b3000795e21fb2

It has to deal with the NBT data on the shulker item being too big, causing an instant crash on launch.

Same behavior exhibited by an unmodified client, it's just that I accidentally overwrote my own latest.log so I had a friend who was similarly chunkbanned send me the stacktrace from his.

Server version:

> _This server is running Paper version git-Paper-547 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)_

Downloaded today

**Comment by LaurenceBarnes** [comment]
I want to add that this issue is a 1.13+ issue, something was different in 1.12.2 that prevented this from happening without disabling those 32k values completely. I wonder if it could be found out what has been changed.

**Comment by sudofox** [comment]
I have a hypothesis. For us it seems to happen with shulker boxes containing stacked armor (produced with a different exploit)

I think what might be happening when you break it is that it tries to re-serialize the shulker contents into an NBT tag and maybe unstacks the stacked armor, causing the length to overflow. This doesn't happen when you drop it from your inventory, only when you convert it from a tile entity to an item entity by breaking it.

I hacked around a little bit with my client to try to reproduce it without crashing, with a slightly less full shulker. Same version of Paper used. It ended up unstacking the stacked armor and actually making it so that some of the items were no longer accessible through the shulker interface

**Comment by electronicboy** [comment]
Theres two issues here)
1) Vanilla can create oversized stacks, this is technically not possible to fix, best we could do is prevent metadata being sent in cases where it overloads, this would work for entitys with large stacks
2) The logic for oversized TEs is generally flawed, technically we could mitigate this somewhat by reducing the TE limit, but, being frank, I wanted to modify the network code to actually consider the length of data, but, this introduces some performance impact, but, this should only be on the network thread, so, maybe worth it, but, not too sure

**Comment by LaurenceBarnes** [comment]
So a trace I might've found through reading and writing with people is that shulkers apparently attempt to unstack items when broken in survival, but don't do that in creative. Might that be a cause?

EDIT: @sudofox kinda mentioned that

**Comment by LaurenceBarnes** [comment]
If it is the cause the implementation of the suggestion in issue #5140 would fix that, and there is other reasoning behind wanting to keep unstackable items in shulkers stacked

**Comment by sudofox** [comment]
By doing a little digging around and using an old util I made ages ago, I was able to produce the nbt of the chunk itself containing a floating "chunkban" item. It's a shulker that contains a whopping 1,728 items.

Attached both the region file as well as the specific chunk file as a .zip as GitHub doesn't like .nbt file extension.

Full region file:
[r.711.492.zip](https://github.com/PaperMC/Paper/files/6144842/r.711.492.zip)

The actual chunk, extracted [with this tool I wrote](https://github.com/sudofox/minecraft-utils/blob/master/region-parser/region-parser.sh)
[421.zip](https://github.com/PaperMC/Paper/files/6144841/421.zip)

The .nbt can be opened with this web-based tool: http://irath96.github.io/webNBT/

If one of these buggers made it into someone's inventory, they'd have a pretty bad day. I think there should be some discussion as to a better way to handle a shulker containing more than 27 item entries.

This issue is directly caused by unstacking the shulker contents. We wrote a plugin that would intercept the item block break/drop event and recreate the item's nbt from the block data to work around it. Does not solve the problem of existing ones that are in the world but it's a start

**Comment by LaurenceBarnes** [comment]
Well if I understand correctly, it is not necessarily that the shulker uses more slots than possible, but that it is unstacked, and purely that. 
One of the actual experts here might correct me, but stacks are saved as one full item instead of each individually; if you unstack all those, they are much larger, especially with some nbt tags added to this. It probably doesn't even need to be the largest possible amount of tags.

**Comment by sudofox** [comment]
**Workaround (preventing new ones) plugin**
We uploaded the workaround plugin. It won't fix existing glitch shulkers, but it will keep the items from getting unstacked when a shulker is broken in survival, preventing the creation of the glitch shulker the first place.

I worked with a friend of mine, @NickM13 to create it -- he did the programming, I was mostly along for the ride haha.
Plugin is targeted at MC 1.16.5, not tested for earlier versions. If you need previous version support ask him.

https://github.com/NickM13/ShulkerFix/releases

**Comment by LaurenceBarnes** [comment]
For old ones, there's a way to fix it by deleting it via a command, this is how we fixed it beforehand when someone broke one in survival.
Could that workaround/fix be implemented into paper, or a similar solution?

**Comment by LaurenceBarnes** [comment]
hey, is there any info on an implementation of the fix as in #5140 or the plugin mentioned in the comments under this? :D
