### ISSUE TITLE
IronGolem Farm Crash

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#4749]
### Link/paste of stack trace

https://pastebin.com/eZdcJCZt

### Plugin list:
AdvancedAchievements, AntiAFK, BanFromClaim, Barrels, BetterRTP, BungeeTabListPlus, CartographerCrashFix, ChatColor, ChatControl, Clans, Clans-Spigot-Part, ClearLag, CMI, CMIPaperLib, CoreProtect, CS-CoreLib, DeluxeMenus, DisableJoinMessage*, DiscordSRV, DyedBackpacks, EcoPower, ExoticGarden, ExtraHeads, FriendsAPIForPartyAndFriends, GemsEconomy*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, IllegalStack, LangUtils, LessPillagers, LiteXpansion, LuckPerms, MarketPlace, MaSuiteCore, MaSuiteHomes, MaSuiteTeleports, MaSuiteWarps, MobCapturer, MobLimiter*, Multiverse-Core, MysqlPlayerDataBridge, NametagEdit*, PartyAndFriendsGUI, PlaceholderAPI, PlayerWarps, PluginConstructorAPI, PlugMan, ProCosmetics, ProtocolLib, PvPInvite, SAML, ShowItem, Slimefun, SlimeLabTweak, SoundMuffler, Spartan, TradeMe, Vault, VaultChatFormatter*, VillagerOptimiser, VoidGenerator, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Build a lot of iron golem farms and wait.
I believe that it happened when a iron golem fall into water in a specific angle or velocity that cause somewhere in NMS could not handle it well.

### Paper version:
Paper-253 (MC: 1.16.3)

**Comment by Nezz202** [comment]
Hey,

I've been searching around because I have been having the same looking issues.
https://pastebin.com/dfffyPJ1

This timings report is one I have whilst the server was on, however I could not get one close to the crash/lockup, however it might help somewhat, I don't know (Yes, I know its laggy :P) https://timings.aikar.co/?id=5e0ea065f5bc43a0b3644ef9f1baebfd

I am on Paper-348 (1.16.4) with the plugins:
ArmorStandEditor, AuctionHouse, BannerBoard*, BlockParticles, BossShopPro, BuycraftX, ChatControl, ChatReaction, Citizens, ClueScrolls, CommandSigns, ContainerPassthrough, Core, CoreProtect, CrateReloaded, CustomEnderChest, DiceFurniture, DiscordSRV, dynmap*, EditableSign, EffectLib*, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts, FarmLimiter, FeatherBoard*, FurnitureLib, GoldenEnchants, GSit, Harbor, HeadDatabase, HolographicDisplays, HolographicExtension, ImageOnMap, InventoryRollback, ItemShops*, Lands, LeaderHeadsRevamped, LibsDisguises, LimitedUses*, LiteBans, Lottery, LuckPerms, mcMMO, MineableSpawners, Multiverse-Core, MVdWPlaceholderAPI*, NexEngine, OpenAudioMc, OpenInv, ParagonAdvent, ParagonAnchors, ParagonArena, ParagonBanners, ParagonBillboards, ParagonChatBattle, ParagonCoreSpigot, ParagonEvents, ParagonFinishTheLyrics, ParagonGodItems, ParagonItemFrameFixer, ParagonItemOfTheDay, ParagonLaunchPads, ParagonMarriage, ParagonMathBattle, ParagonMuseum, ParagonNetherAndEnd, ParagonNPCUpdater, ParagonPerms, ParagonPermsLocal, ParagonPlayTimePAPI, ParagonRestarts, ParagonShadyMerchant, ParagonTags, ParagonTemplates, ParagonTutorial, ParagonUpdater*, ParagonWild, ParagonXP, PartyAndFriendsGUI, PlaceholderAPI, PlayerParticles, PlayerWarps, PlugMan, PocketGames, ProtectionLib*, ProtocolLib, QuickShop, SellStick, SimplePets, Spartan, SurvivalInvisiframes, TAB, TitleManager, TradePlus, Vault, Vehicles, VehiclesFlags, VillagerLobotomizatorNator, VoteParty, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

A player has a multi tiered Iron Golem farm which drops them down, similar to what you reported too, and its usually when he is around his base/afking that this happens.

Hope this helps a bit, and might assist in trying to see whats causing this and how to fix :)

**Comment by HexedHero** [comment]
> Hey,
> 
> I've been searching around because I have been having the same looking issues.
> https://pastebin.com/dfffyPJ1
> 
> This timings report is one I have whilst the server was on, however I could not get one close to the crash/lockup, however it might help somewhat, I don't know (Yes, I know its laggy :P) https://timings.aikar.co/?id=5e0ea065f5bc43a0b3644ef9f1baebfd
> 
> I am on Paper-348 (1.16.4) with the plugins:
> ArmorStandEditor, AuctionHouse, BannerBoard*, BlockParticles, BossShopPro, BuycraftX, ChatControl, ChatReaction, Citizens, ClueScrolls, CommandSigns, ContainerPassthrough, Core, CoreProtect, CrateReloaded, CustomEnderChest, DiceFurniture, DiscordSRV, dynmap*, EditableSign, EffectLib*, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts, FarmLimiter, FeatherBoard*, FurnitureLib, GoldenEnchants, GSit, Harbor, HeadDatabase, HolographicDisplays, HolographicExtension, ImageOnMap, InventoryRollback, ItemShops*, Lands, LeaderHeadsRevamped, LibsDisguises, LimitedUses*, LiteBans, Lottery, LuckPerms, mcMMO, MineableSpawners, Multiverse-Core, MVdWPlaceholderAPI*, NexEngine, OpenAudioMc, OpenInv, ParagonAdvent, ParagonAnchors, ParagonArena, ParagonBanners, ParagonBillboards, ParagonChatBattle, ParagonCoreSpigot, ParagonEvents, ParagonFinishTheLyrics, ParagonGodItems, ParagonItemFrameFixer, ParagonItemOfTheDay, ParagonLaunchPads, ParagonMarriage, ParagonMathBattle, ParagonMuseum, ParagonNetherAndEnd, ParagonNPCUpdater, ParagonPerms, ParagonPermsLocal, ParagonPlayTimePAPI, ParagonRestarts, ParagonShadyMerchant, ParagonTags, ParagonTemplates, ParagonTutorial, ParagonUpdater*, ParagonWild, ParagonXP, PartyAndFriendsGUI, PlaceholderAPI, PlayerParticles, PlayerWarps, PlugMan, PocketGames, ProtectionLib*, ProtocolLib, QuickShop, SellStick, SimplePets, Spartan, SurvivalInvisiframes, TAB, TitleManager, TradePlus, Vault, Vehicles, VehiclesFlags, VillagerLobotomizatorNator, VoteParty, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
> 
> A player has a multi tiered Iron Golem farm which drops them down, similar to what you reported too, and its usually when he is around his base/afking that this happens.
> 
> Hope this helps a bit, and might assist in trying to see whats causing this and how to fix :)

Your issue is nothing to do with Iron golems at all, your server is just overloaded mostly from Hoppers

**Comment by e-im** [comment]
This more just looks like a generally overloaded server and not anything specific with iron golems, but regardless, major changes have been made here and 1.16.3 is no longer supported. If you are still experiencing this on 1.17.1, leave a comment.
