### ISSUE TITLE
Loading vanilla world with paper resets player positions

### ISSUE THREAD

**Issue by ZillyHuhn** [PaperMC/Paper#4797]
### What behaviour is expected:
Spawn at last logout position when switching from vanilla to paper

### What behaviour is observed:
Teleport all accounts to spawn once when loading vanilla 1.16.4 generated world with paper.
Inventory is not cleared.

### Steps/models to reproduce:
Generate a fresh world with official vanilla 1.16.4 server.
Walk to a position you remember.
Stop vanilla server and run paper.
Reconnect and check if login postion equals last logout position.

### Paper version:
https://github.com/PaperMC/Paper/commit/821ce25d95ef5aa33a7134c640258e239769fdac

**Comment by Camotoy** [comment]
I can confirm that this issue still persists with Paper 1.16.5 build 449.

**Comment by larwood** [comment]
Issue still present with paper-1.16.5-570

**Comment by larwood** [comment]
Issue resolved for me.  It was either:

1. I finally crafted a bed in Vanilla and slept thereby setting my spawn point or
2. Migrated from Vanilla again but this time with paper-1.16.5-576.jar

**Comment by Owen1212055** [comment]
I cannot reproduce this issue anymore as of 1.19.1.
I created a survival world on vanilla then opened the world on paper and I was still in the same location.

According to Larwood, it seems this issue was also resolved for them too.
However, if you still are able to reproduce this, feel free to comment on this issue and it can be reopened. 😄
