### ISSUE TITLE
Shulker box loses contents and name

### ISSUE THREAD

**Issue by oroJefe** [PaperMC/Paper#494]
Annoyingly, I've very little information to provide here, but I did just lose the entire contents of a shulker box. Curiously, the box also lost its custom name and reverted to 'shulker box'.

This was during a period of brief TPS drop due to some players chunk loading on elytras. Some players mentioned general lag events like epearl and mining lag at the time. I don't know how the mechanics of shulkers work, but its almost like the process that saves their state just failed when we had that lag spike; one minute I was working with the box just fine, the next, it had reverted to a plain old shulker box.  

The box in question had previously been dyed red, it did not lose this state.  Other shulker boxes are completely fine on the server, including my own, and other players. It was just this one box I was actively working with during a lag spike.

Using Paper build 924 with plugins: world guard, world edit, core protect, protocol lib, trophy heads, slack, essentials x, dynmap, automessage, mcmmo, creative gates/massive core, pex.  Timings report from the last hour, I dount this is helpful, but you can see the period in the timeline where we had the lag: https://timings.aikar.co/v2/?id=32cc8b33e71140afb67cfcf6927eefa9

**Comment by zachbr** [comment]
Anything in the logs when this happened?

**Comment by oroJefe** [comment]
I'm sure it took me a minute or two to spot the failure.  Going back through the logs now, the only thing that really stands out in that time frame is:

[Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:red_shulker_box

This does seem to be in the logs at various points through the day though so I suspect its not related.

**Comment by zachbr** [comment]
please let us know if it happens again, and if that message accompanies it. For the time being I believe they are separate, but if they aren't it'd be good to know. Thanks

GH-489 is tracking the cause of that warning message.

**Comment by guccihub** [comment]
-edit-

Looks like a problem on my end, will update again if I find a way to reproduce.

**Comment by Black-Hole** [comment]
I tested it exactly like in the video and cannot reproduce it with Paper or with single player.

**Comment by oroJefe** [comment]
What plugins are you using guccihub?

**Comment by zedwick** [comment]
A player on my server has also experienced this with 5 of his shulker boxes. They were stored in his ender chest, he took them out to find a specific item and started placing them, finding it empty, moving on placing the next. He realised he could see the tooltip showing the contents, but once placed had no items in it. One box had been named and lost its name once placed. All boxes were cyan_shulker_box.

Accompanying this, I saw the following in the console around about that time (but cannot confirm it directly coincided with placing the boxes): https://pste.me/#/85XYj

I have not been able to reproduce this myself.

Other details probably not important: using iron pickaxe, believes he placed them against the wall rather than on the ground. all 5 were placed in relatively short time span, subsequent boxes placed were fine and no other boxes were wiped.

**Comment by zedwick** [comment]
After seeing #483 I have been able to reproduce this by placing shulker box against the side of another shulker box. Still not reliably reproducing, however.

Following in console the moment I placed the shulker, which was both filled and named but empty and unnamed after placing: https://pste.me/#/aSLw7

**Comment by Black-Hole** [comment]
Seems to be fixed upstream: https://hub.spigotmc.org/jira/browse/SPIGOT-2833

Merge please. 😃
