### ISSUE TITLE
Comparator not updating in certain conditions

### ISSUE THREAD

**Issue by lululombard** [PaperMC/Paper#505]
# Incompatibility (Bug)

### What behaviour is expected:
Comparators should update the output state when an item is received in it's container
### What behaviour is observed:
Comparators will not if you push an item into a container with a dropper
### Steps/models to reproduce:
Push an item into a hopper, and lock the hopper.
The comparator will not update with Paper, but will with Spigot.
![bug1](https://cloud.githubusercontent.com/assets/2182934/20578532/0f19a976-b1c8-11e6-92f9-39324a28906b.png)
![bug2](https://cloud.githubusercontent.com/assets/2182934/20578533/0f1b06cc-b1c8-11e6-891b-57f77416377b.png)

### Plugin list:
None

### Paper build number:
932

**Comment by lululombard** [comment]
As a video explains a lot more than 2 pictures :
https://www.youtube.com/watch?v=28qTzWOdDJU

**Comment by Black-Hole** [comment]
I tested this and was able to reproduce it. It also happens if a hopper sucks in items with "hopper.push-based" set to true.

updateAdjacentComparators() isn't called. So if you force a block update on the comparator (like placing a block beside it) it will check the hopper inventory again.

It's caused by this patch:
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0131-Improve-Minecraft-Hopper-Performance.patch

**Comment by lululombard** [comment]
When will this be fixed ? It's game breaking for a lot of players.
