### ISSUE TITLE
Support for Nether Portals at bedrock

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#5052]
**Is your feature request related to a problem? Please describe.**
I think no.

**Describe the solution you'd like**
If you can then add support to teleport player above the bedrock if the portal default is broken and do not create it again in the Nether.

**Describe alternatives you've considered**
When game create a portal in the Nether and player destroy it and place a new one above the bedrock there should be a support to teleport this player to it, and not enable Minecraft to create his own portal.

**Additional context**
If player is far away from the bedrock portal then allow Minecraft create his own portal.

**Comment by Chew** [comment]
I do not exactly understand what you're saying...

**Comment by electronicboy** [comment]
We are not modifying portal mechanics, I'd rather have a PR/suggestion to allow plugins to mess with this logic more if needed rather than this, which seems unviable anyways, portals don't record if they create a portal on the other side, so there is no way to see if they previously created a portal without going on a roundabout trip which would be better suited for plugins
