### ISSUE TITLE
Reputation/discount for player resets if another player cures the same villager twice

### ISSUE THREAD

**Issue by ChiboYen** [PaperMC/Paper#5104]
### What behaviour is expected:
Player A zombified and cures a villager, Player B zombified the same villager and cured it. Both players have discounts currently from the villager. When Player A cures the villager again, player B should have their discount unaffected.

### What behaviour is observed:
Player A zombified and cures a villager, Player B zombified the same villager and cured it. Both players have discounts currently from the villager. When Player A cures the villager again, player B has their discount/reputation completely removed like they never cured the villager in the first place.

### Steps/models to reproduce:
Have two accounts/players and one villager. Have Player A zombify and cure a villager. Have Player B zombify it and cure it. Both players should have discounts now. Player A will then zombify the villager again, and upon curing it, Player B will have lost their discount.

### Plugin list:
None, tested on server with no plugins

### Paper version:
[23:37:31 INFO]: This server is running Paper version git-Paper-439 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
`fix-curing-zombie-villager-discount-exploit: false`, so this patch shouldn't affect the behavior of villagers.

Please let me know if you have any questions

**Edit:** I've gotten asked this question a lot of times, bug has not been able to be reproduced upstream in spigot, this is a Paper specific issue.

**Edit 2:** Upon further testing, paper-405 does not have this issue. The cause seems to be isolated to [patch-648](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0648-Fix-villager-boat-exploit.patch)

**Comment by EuanM199** [comment]
paper pls fix 👍 

This has already happened on my server once, this is server economy ruining.

**Comment by ryderbelserion** [comment]
+1

**Comment by facundogaidano** [comment]
+1

**Comment by electronicboy** [comment]
Please don't bump tickets, you bumping tickets does not magically resolve my health issues or make others suddenly able to drop their commitments elsewhere, failing that, submit a PR.

**Comment by ChiboYen** [comment]
I did some further testing, it would seem that if I follow the instructions I initially mentioned but instead of using paper-406, rather paper-405, this issue isn't present. The cause seems to be isolated to patch-674

**Comment by DelanoPreston** [comment]
I am seeing this same problem on paper-455

**Comment by BillyGalbreath** [comment]
This is an intentional bug fix for an exploit of stacking discounts. If you don't like the behavior you are free to disable the option.

```yaml
fix-curing-zombie-villager-discount-exploit: false
```

As shown in the code, the reputation is _not_ touched if the option is disabled: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch

As for mentioning build 405 working and 406 not working, the commit for 406 doesn't touch reputation behavior in the slightest (https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0648-Fix-villager-boat-exploit.patch) which leaves me to believe you either have the builds wrong, or are not describing the issue correctly.

**Comment by Chew** [comment]
If anyone can reproduce this without plugins, on the latest build, with the above setting, please reply to this or open a new issue. My assumption is everyone is missing the config part and is falling victim to normal Paper mechanics. As stated above, there doesn't seem to be any changes. Else, it might be an upstream bug.

**Comment by Arcanious** [comment]
My understanding of the report is that another players single cure should not be affected when another player attempts to cure the villager twice. While I understand the multi cure villagers are fixed with the above option enabled, it should not affect another players single cure on that same villager. This pull even attempted to fix the issue described.
https://github.com/PaperMC/Paper/pull/5054

**Comment by electronicboy** [comment]
that patch is 100% irrelevant when the configuration option is configured to not use the fix, there are 0 changes to behavior when that option is disabled

**Comment by BillyGalbreath** [comment]
> My understanding of the report is that another players single cure should not be affected when another player attempts to cure the villager twice. While I understand the multi cure villagers are fixed with the above option enabled, it should not affect another players single cure on that same villager.

Your understanding is correct, and when the option is set to false that doesn't happen but this report incorrectly claims it does still.

> This pull even attempted to fix the issue described. #5054

That PR fixes the patch in question that was erroneously resetting _all_ stats for _all_ players. #5054 fixes it by _only_ resetting the reputation.

**Comment by DelanoPreston** [comment]
We are updating our server to the most recent paper version today. I will update this thread or open a new one if the issue persists.
