### ISSUE TITLE
Paper Massive Packet Increase

### ISSUE THREAD

**Issue by MonzterDev** [PaperMC/Paper#5173]
### Description of issue:
I recently discovered that Paper seems to be causing a massive increase of Packets when I respawn or teleport to certain locations. The amount of packets sent to client exceeds 1,000 and causes my ping to jump to 1000 for a few seconds. I determined this is Paper specific, because when testing with the Spigot Jar, the packets do not exceed 200.

I've recorded a video of it here: https://cdn.discordapp.com/attachments/289587909051416579/807476472193351691/OkFumidehi.gif
I've also recorded a video with Spigot Jar here:
https://cdn.discordapp.com/attachments/289587909051416579/807476655730982953/3gxtFeDKaq.gif

### bukkit.yml, spigot.yml, paper.yml, server.properties
[Paper.yml](https://pastebin.com/kMn7uc5k)
[Spigot.yml](https://pastebin.com/jWdafF8b)
[Bukkit.yml](https://pastebin.com/nn4itxxX)
[server. properties](https://pastebin.com/7mdb6N9C)

### Other helpful links
I did some Packet Debugging, here are 
Spigot's Packets: https://pastebin.com/TGBFax7q
Paper's Packets https://pastebin.com/rfa6Ng0k
### Paper version:
Paper(d4dcc1a2e) 1.16.5-R0.1-SNAPSHOT

**Comment by MonzterDev** [comment]
zzzCat recommended I try "clone the repo, delete the patch, ./paper b, pray 0483-Workaround-for-Client-Lag-Spikes-MC-162253.patch" which I did, and sadly no noticeable difference.

**Comment by LaurenceBarnes** [comment]
I can confirm that this issue exists.

**Comment by ChiboYen** [comment]
Can confirm, happens on paper 465

**Comment by Strahilchu** [comment]
Happens to me even after I went to PurPur and now Airplane lol can someone fix this?

**Comment by LaurenceBarnes** [comment]
well paper gotta fix that though, the other forks would then fix it by patching that in.

However I believe that this issue is quite critical, as it affects every kind of server (even survival due to nether/end portal teleporting)

**Comment by aikar** [comment]
I do not see 1000's of packets in your logs there? 

This change has been there for months with no reports like this (only occasional reports it didn't fully fix the issue)

However, in what way is it actually impacting gameplay? Yeah I do see the ping increase, but a short burst in that number jumping high will not have any meaningful impact on gameplay. 

How is your plugin reporting that number? it doesnt seem to update often. I suspect its not as bad as you think it is and it bursts up for a short time only.

**Comment by Cryptite** [comment]
It's anecdotal, but several of our players do report big lagspikes due to effectively packet spam on world switches as well. I thought this might've been more of a 1.15+ problem where both the quantity, and probably also the size of the packets has gone up a lot.

**Comment by LaurenceBarnes** [comment]
No, it bursts up for quite a few seconds, and I noticed that quite recently since it causes command executions and other actions to have some serious delay time. It slowly goes down then.
Also if it doesn't happen on spigot, why should it happen on paper and all its forks?

**Comment by EternalWolf16** [comment]
I’m having the same issue.

I have this issue when teleporting and when players login. I have been doing some test as I just got my test server setup, I have tried swapping from spigot to paper and had the issue on both, also updating to 1.16.5 and that did nothing. Recently removed all my plugins to test that and that’s not changed anything so I don’t think it’s a plugin issue, we also tried adding Chunky and that helped a little, but not a lot. It’s worse at my spawn as you only really full out the world when at spawn now, but players ping still goes crazy when they teleport and some can’t even join because of it. Im not sure what the issue is or where it’s come from, but it’s very odd and I hoping someone has some other ideas. (Gonna try moving back to 1.16.1 and testing that)

Very confused why it is only happening to some of us as a lot of servers are running fine.

**Comment by electronicboy** [comment]
PPS is a hard metric to follow, and the reason why the PPS is often so low on, say, vanilla or upstream, is due to how slow they do things like load chunks. Chunks in paper can often load fast enough to swamp slower connections down, this is why we had things like the maximum chunk sends config which shamefully broke in some changes in the past few versions, as well as varying other patches like those trying to send more light updates out to prevent the client from freezing as much

beyond that, we'd need to know exactly what the packets are and what the amounts compare to, say, spigot; as I think we easily know what the issues are and it a muuuuuuuch easier issue to solve than just saying it should be fixed

**Comment by MonzterDev** [comment]
> I do not see 1000's of packets in your logs there?
> 
> This change has been there for months with no reports like this (only occasional reports it didn't fully fix the issue)
> 
> However, in what way is it actually impacting gameplay? Yeah I do see the ping increase, but a short burst in that number jumping high will not have any meaningful impact on gameplay.
> 
> How is your plugin reporting that number? it doesnt seem to update often. I suspect its not as bad as you think it is and it bursts up for a short time only.
So by 1,000 packets, I'm referring to the Gif I included where is displays "rx" (debug from F3) in the middle of the screen. You can see the number next to rx shoots up to about 1,000 for Paper, but not above 200 on Spigot.

I included a short sample of my logs because it's gigantic the amount of packets which are generated. I can upload the entire logs file if that'd be further useful. I wasn't sure it if maybe required, but I can grab one from Spigot & Paper to compare.

The impact on gameplay is about a 10 second delay every single time you respawn, which can become very annoying. I get it doesn't affect direct gameplay, but it's pretty annoying to be forced waiting up to 10 seconds each death to be able to get back to normal gameplay. 
This impact isn't only on death, but also Warping or Teleporting to different areas around the map, and when joining the server. 


If there is anything else I can do to help further debug this, I'd love to, please let me know! I really appreciate and enjoy using the Forks, which is why I'd love to get this fixed, so I can continue to.

**Comment by Joshinn-io** [comment]
I am having the same issue on several servers running Paper/Paper forks (can trace it back to starting at paper), teleporting often causes extremely slow load times for a few seconds and then it all catches up in an instant. Really annoying. It happens on login as well depending on the server.

**Comment by LaurenceBarnes** [comment]
I'd say it can affect gameplay if one joins into nether and gets into a heated situation or vice versa. Might be an unlikely case, but definitely possible in multiplayer

**Comment by MonzterDev** [comment]
Here is the log example which includes as soon as I join in the Server, then warp to the area I did the tests in with the included Gifs, then /suicide multiple times. Just to clarify, the packets (client side lag? & high ping) occur upon **Joining**, **Teleporting**, and **Respawning**.  I'm also surprised by how large the Paper Log (3,477KB) is compared to the Spigot Log (821KB)

[Paper Log Short.log](https://github.com/PaperMC/Paper/files/5947810/Paper.Log.Short.log)
[Spigot Log Short.log](https://github.com/PaperMC/Paper/files/5947815/Spigot.Log.Short.log)

Anyways, please let me know if there is anything else I can do to improve upon debugging. I have no experience with debugging packets, but trying to provide the most information I can gather as possible!

**Comment by RoloRotMG** [comment]
Can confirm, thought it was just minecraft until i switched back to spigot

**Comment by EternalWolf16** [comment]
I was doing a couple test today and yesterday and as I wasnt having this issue on spigot 1.16.1 (I believe) I updated to paper 1.16.2 and started to get this issue so I tired to fix it by moving to paper 1.16.4 and then 1.16.5 after and still had no luck. I have recently move my server to a test server to go deeper into this issue and moving to paper 1.16.1 and spigot 1.16.4/1.16.1 and had no luck there. Removing all my plugin also didn’t help. I also had a issue with my tps going down all the time in the past when using spigot and could barley hold more then 7 players that stopped after moving to paper so not sure if that has anything to do with it.

I heard someone say “might move back to spigot” was everyone here using spigot at some point and moved to paper as maybe they are clashing, but unlikely. I also just removed my server from my bungee server before this issue happened as I didn’t wanna use bungee anymore. I just trying to figure out what it could be even if it makes no sense as I just want us all to fix this issue. I don’t understand why it’s happening to a couple of us and not everyone, like what are we doing different. If anyone has tested anything else please let me know and I hope we can find a fix for this issue.

I currently have 12 GB of Ram on my server and running on paper 1.16.5

**Comment by EternalWolf16** [comment]
Just ran another test. I added all my plugins back and reset the world and the issue is still a thing even on a fresh vanilla world, I have also tested this without my plugins and with and a fresh work and the same thing happens :/

**Comment by aikar** [comment]
Thinking we should just drop that patch if its making things worse for many vs fixing for the few that had the original issue, and maybe mojang has improved it in 1.16.4 anyways.

**Comment by electronicboy** [comment]
yea, been thinking the same too, it seems to marginally help maybe in some cases but the issue afaik is bad lighting data and how the client deals with it, such fun

**Comment by RoloRotMG** [comment]
I think it effects everyone, it’s just scales with how far you are from the
server. If you are testing it on a home server you won’t notice it I think.
If you are testing it on a server located far from you then you will notice
it a lot more depending on distance (I think)

**Comment by RoloRotMG** [comment]
I'm sure me and some others are happy to test it

**Comment by MonzterDev** [comment]
I have refreshed this page at least once an hour for 12 hours each day.

**Comment by electronicboy** [comment]
There is no need to pointlessly bump the ticket, this is far from a simple issue and will require somebody to actually spend some time looking over it.

**Comment by MonzterDev** [comment]
My deepest apologizes for sharing my excitement!

**Comment by MonzterDev** [comment]
Any progress being made on this?

**Comment by Chew** [comment]
> There is no need to pointlessly bump the [issue]

**Comment by EternalWolf16** [comment]
I have actually fixed this issue. After days and day of testing stuff out over and over is the only thing that actually works for me. I grab a empty server and just started running paper again and creating a whole new server, then replacing the new generated world and plugins folder with mine and starting that server. Obviously do this at your own risk as I very much did, but I also did a lot of testing on a test server and had backups in case anything went wrong, but yes my server has been running really smooth ever since. I hope this helps a lot of people as I know this issue was a pain (also remember to edit all your other stuff again and transfer banned data and etc. Any questions feel free to ask.

**Comment by MonzterDev** [comment]
Bump

**Comment by HexedHero** [comment]
"Bumping" won't magically do anything.

**Comment by ChiboYen** [comment]
@Dancull47 You never pasted your `spigot.yml` or `bukkit.yml` or `server.properties`, can you tell me what your network compression threshold is set to in `server.properties`? 

I used to experience this issue a while ago, but it was set to `network-compression-threshold=512` for me, setting it to 64 helped out with ping spikes a lot, even fixing them. This will incur extra CPU cost, but it is multithreaded so 2+ threaded servers should be fine.

**Comment by Chew** [comment]
@Dancull47 Bump ^ (sorry for ping, and bumping)

**Comment by MonzterDev** [comment]
> @Dancull47 You never pasted your `spigot.yml` or `bukkit.yml` or `server.properties`, can you tell me what your network compression threshold is set to in `server.properties`?
> 
> I used to experience this issue a while ago, but it was set to `network-compression-threshold=512` for me, setting it to 64 helped out with ping spikes a lot, even fixing them. This will incur extra CPU cost, but it is multithreaded so 2+ threaded servers should be fine.

Thanks for the responses! My apologies for failing to post those files, I've updated the original post with them, but I'll leave them here as well!

[Spigot.yml](https://pastebin.com/jWdafF8b)
[Bukkit.yml](https://pastebin.com/nn4itxxX)
[server. properties](https://pastebin.com/7mdb6N9C)

I also changed my network compression threshold as you suggested from **256** > **64**, but saw no impact with this actual issue at all. Thank you for the suggestion though!

**Comment by ghost** [comment]
I have randomly inherited this error a few days ago and have been trying to figure out how to go about it.

For some background, I self host my main Towny server and proxy the connections through a proxy server hosted by OVH (about 17 miles from my house with a 1.5ms ping)

Whenever a player joins the server, for a brief few seconds, only their ping is increased incredibly high. The same occurs when they teleport between anywhere. I believe it is starting to boil down to something with chunks.

Here is what I have done so far with no good solutions.
- I've tried fresh configurations all around.
- I set my network compression threshold to 64, 256, 512, 1024 and disabling it with -1
- I've physically replaced all the cable between my ISP's fiber ONT to my networking switches (even changed the switches, bought factory made cat5 and cat6 to test)
- Called out my ISP and they did a quality check on my fiber line and it passed with flying colors.
- I've set my view distance to minimum.

I decided to load up a network monitor and watch the load in Mbps between incoming and outgoing. The amount of outgoing is incredibly high when the latter occurs.

This issue is becoming a plague right before we are about to release a new Towny server on the hardware. Hopefully something can be done about it. 

I am 0xBit#1312 on discord and you can find me at discord.gg/nebulamc or in the Purpur Discord!

I am also willing to let a reputable dev ssh access to dig around and diagnose

**Comment by Iaiao** [comment]
I've reset my paper.yml to default and unusable 6000 ping for 30 seconds turned into a small 1-2s lag, which is acceptable for most servers. The reason was `no-tick-view-distance` set to 12 in my configuration. I've set it to -1 and it worked!

**Comment by electronicboy** [comment]
One of the major patches contributing to this was removed in 1.17, beyond that, it's all down to packet flooding from stuff like joins, tuinity merge should pull in a patch which limits this iirc

**Comment by Iaiao** [comment]
> One of the major patches contributing to this was removed in 1.17, beyond that, it's all down to packet flooding from stuff like joins, tuinity merge should pull in a patch which limits this iirc

I had the same issue 5 hours ago on 1.17.1-202, I couldn't test if it's related to packets (I tried, but it's a bit hard to filter out hundreds/thousands of packets per second, maybe I should've looked at PPS, but joining takes about 30 seconds on my server), but it seems to be related to this because of the same symptoms: high ping on join, respawn and teleport. It's probably because the server tries to load 31x31 chunk area (no-tick-view-distance: 15 in Dancull47's paper.yml) and it takes some time and produces much more packets. After all no-tick chunks are loaded, they don't produce new packets, so it looks like packet flooding from stuff like joins.

**Comment by ChristopherHaws** [comment]
Users on my server are having this issue as well. My server can easily handle a view-distance of 32 with a simulation distance of 10 (MSPT never goes above 30 since we only have around 8 players on the server), however I have had to lower the view-distance to 16 since players who are physically farther from the server (overseas) simply cant join. I see no issues when I join (i have very low ping to the server), but the further away players are from the server the worse they are affected. They report that they fall through the void for minutes at a time until the server simply disconnects them. With the view distance set to 10 they still fall through the void but after about 30 seconds it corrects itself so they can keep playing. Even myself with a ping of less than 10ms have this issue when going through portals (albeit it fixes itself within about 1s vs 30s).

Some interesting observations I have had while testing with my players:
- Even though I have `autoconfig-send-distance` set to true, players have the issue even if their client chunk distance is set as low as possible
- Increasing `max-concurrent-sends` seems to make the issue worse for high ping users but better for low ping users
- When `view-distance` is set too high, high ping users get disconnected after the configured `paper.playerconnection.keepalive` timeout (there is no affect on low ping users)
- Even with a server running on my local network I sometimes get up to 200 ping when going through portals. Once the world finishes loading it goes back down to 0 or 1 ping.
- Even though players report they are falling through the void, when I spectate them while they are logging in, their player is actually on the ground and not moving at all
- This even happens when users are logging in and their player is in the spawn chunks (which I have paper set to keep 16 chunks loaded at spawn)

The relevant settings I have tried adjusting are:

`Paper Startup Arguments`
```
paper.playerconnection.keepalive=60
```

`server.properties`
```ini
network-compression-threshold=64
view-distance=18
simulation-distance=10
```

`paper.yml`
```yml
chunk-loading:
  min-load-radius: 2
  max-concurrent-sends: 2
  autoconfig-send-distance: true
  target-player-chunk-send-rate: 100.0
  global-max-chunk-send-rate: -1.0
  enable-frustum-priority: false
  global-max-chunk-load-rate: -1.0
  player-max-concurrent-loads: 4.0
  global-max-concurrent-loads: 500.0
```

I am willing to be a gunnie pig for settings changes if anyone has thoughts. Feel free to contact me on discord (Chaws)

**Comment by electronicboy** [comment]
Closing this issue, the patch which was causing the original massive increase of packets, etc, has been removed and in 1.17 packet rate sending has been implemented through the tuinity merge, this patch is known missing in 1.18 but will be tracked elsewhere

players falling through the world on join, etc, is pretty much the defacto norm since mojang modified the chunk system a few versions back to it no longer just waiting for X amount of chunks before joining, tuning view distances, etc, can help, but those with high latency/bad connections/machines are generally always gonna have these types of issues (and this is not the place to diagnose those)
