### ISSUE TITLE
PluginReloadEvent for inter-plugin communication

### ISSUE THREAD

**Issue by jaylawl** [PaperMC/Paper#5187]
```
public class PluginReloadEvent extends PluginEvent {

    public PluginReloadEvent(@NotNull Plugin plugin) {
        super(plugin);
    }

}
```

A nice and simple event for inter-plugin communication. Useful for plugin's that depend on each other. Supposed to be called when a plugin completes it's own internal reload process; for example when server staff is using `/myplugin reload`.
Just a simple idea. Maybe some of you guys have some useful ideas what kind of useful data could be passed along with this event.

**Comment by JRoy** [comment]
This is definitely something that should be handled on a per plugin level. There's absolutely nothing in the Bukkit API which would dictate how this is fired. The idea that plug-in should just fire this event "whenever they feel like it" is just poor API design.

**Comment by Machine-Maker** [comment]
JRoy, weren’t you working on a new plugin lifecycle? I assume that would include an event like this. If not, I think an event like this would be more appropriate if Bukkit had a plugin reload api for config files, etc.

**Comment by JRoy** [comment]
> JRoy, weren’t you working on a new plugin lifecycle? I assume that would include an event like this. If not, I think an event like this would be more appropriate if Bukkit had a plugin reload api for config files, etc. 

Just the fact that you were able to misunderstand the purpose of the event is exactly why I'm opposed to adding this to paper. The OP doesn't want the event to dictate an actual plug-in reload cycle but rather something like a config reload (ex `/essentials reload`).

**Comment by Malfrador** [comment]
A lot, if not nearly all, Bukkit plugins that offer an API have such an event for plugins that use the API. Having a central, server-event instead of each plugin providing a new event (that, in the worst case, also shares the name with the same event from a different plugin) seems pretty useful to me. I am assuming its for full reloads of the plugin, not just config reloads - a event for those seems unnecessary to me. 

Depending on how the plugin in question reloads it might be possible to use the PluginDisableEvent to listen for reloads using the Bukkit-API, but that is certainly not what the event is intended for. 

In my opinion such an event would even encourage better (or at least more standardized) plugin design and it would be a really small change. I don't think there is more useful data that should be passed along, other than of course the plugin in question. Yes, it would be up to the plugin when to call the event, but as its something that is entirely different for every plugin, I see no other way for this.

**Comment by JRoy** [comment]
> that, in the worst case, also shares the name with the same event from a different plugin

This is what fully qualified imports are for :)

> In my opinion such an event would even encourage better (or at least more standardized) plugin design and it would be a really small change. I don't think there is more useful data that should be passed along, other than of course the plugin in question. Yes, it would be up to the plugin when to call the event, but as its something that is entirely different for every plugin, I see no other way for this.
In an ideal world, plugin reloading would be done by the server (and would actually work reliable with all plugins) and would use a onReload() method, similar to how disabling and enabling works, but thats a pretty big change.

This is not good API design. Any plug-in can call this for a different use case than other plug-in and unless you know specifically which plugin you're using this against it's not reliable to use nor is there any really use case for it. since you're already going to need to be accessing that plug-ins internals anyway it's just better for the plugins to handle it and perhaps even give specific methods within the event to access the data being "reloaded". Bukkit doesn't support plugin config "reloads" so would make no sense for it to maintain an event for it.

**Comment by Malfrador** [comment]
> This is what fully qualified imports are for :)
>>
Of course. But not needing to use those is easier and means there is less chance that you accidentally import the wrong event.

**Comment by kashike** [comment]
See @JRoy's response.
