### ISSUE TITLE
Scaffolding Bug

### ISSUE THREAD

**Issue by JustJP2K** [PaperMC/Paper#5198]
Spamming Scaffolding generates a floating scaffold, which you can continue to scaffold forward on.

**Comment by HexedHero** [comment]
Isn't this intended or am I missing something?

**Comment by rrvk** [comment]
I think he is talking about something like this? 
https://youtu.be/a8ds6SnOGow?t=1104

**Comment by JustJP2K** [comment]
Yeah, i mean its a fun thing, but its lagging out the server since the anticheat is freaking out.

**Comment by Malfrador** [comment]
It is a bug (MC-148795), not intended. However it's probably like all similar ghost block issues not really fixable by Paper, but would need client networking changes as well.

And if your anti cheat creates lag because of that, it's the anti cheats fault, not Papers. Without anti "cheat" plugins, placing floating scaffolding does not create any (lag) issues.

**Comment by Chew** [comment]
As stated, this appears to be a plugin issue. Additionally, the template is missing, so not much we can do with the information we've been given. If you can reproduce on latest without plugins, please open a new issue (without removing the template...)
