### ISSUE TITLE
Drowned does not spawn (1.16.5)

### ISSUE THREAD

**Issue by chesskuo** [PaperMC/Paper#5215]
### What behaviour is expected:
Drowned spawning rate will be normal.

### What behaviour is observed:
When only one user at here, drowned spawning rate in seems normal.
When multi users at the other place which will spawn others mobs, deep ocean's drowned will not spawn anymore(also river biome).

### Steps/models to reproduce:
1. only one user in the server and then in the deep ocean biome
  - spawning rate will be normal
2. multi users in the server and then include spawning others mobs
  - drowned will not spawn

### Plugin list:
- SkinRestorer
- WorldEdit

### Paper version:
- `git-Paper-472 (MC: 1.16.5)`

**Comment by e-im** [comment]
I haven't been able to reproduce this behaviour on the 1.17.1 build 351, and a mitigation for the flaw of multiplayer spawning expressed here (`per-player-mob-spawns`) has since been defaulted to true.

If you are still experiencing this issue on 1.17.1 with per-player enabled, first come by our [discords](https://discord.gg/papermc) `#paper-help` channel and then leave a comment here.
