### ISSUE TITLE
"Adventure" Chat issues. 

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#5216]
### What behaviour is expected: 
I expected no changes to chat formatting.

### What behaviour is observed:
Opped players now have 2 :'s after their username. Essentials Social Spy now is written in the color of the players nickname.
![image](https://user-images.githubusercontent.com/8680731/108697749-27e71100-74fb-11eb-9732-111b95a0dd51.png)

### Steps/models to reproduce:
All I did was update paper about 7 versions. 

### Plugin list:
![image](https://user-images.githubusercontent.com/8680731/108697843-48af6680-74fb-11eb-96b2-48006d6b0b6f.png)

### Paper version:
![image](https://user-images.githubusercontent.com/8680731/108697892-59f87300-74fb-11eb-9c76-005928cbe7ef.png)

**Comment by kashike** [comment]
What plugins do you use to handle chat? You have a big list and it would save time if you told us (configuration files would also be helpful).

**Comment by slvlr** [comment]
> What plugins do you use to handle chat? You have a big list and it would save time if you told us (configuration files would also be helpful).

Towny Chat:
https://pastebin.com/FZzcQBCk

Essentials Chat:
https://pastebin.com/XBcsdSvW

**Comment by ghost** [comment]
plugin ChatItemDisplay: https://www.spigotmc.org/resources/chatitemdisplay.77177/ also doesn't work correct

**Comment by electronicboy** [comment]
can you provide more info around "doesn't work correct"?, reproducing issues with every single plugin in existence is somewhat of a non-starter, so providing info would help a ton

**Comment by ghost** [comment]
> can you provide more info around "doesn't work correct"?, reproducing issues with every single plugin in existence is somewhat of a non-starter, so providing info would help a ton

![image](https://user-images.githubusercontent.com/75625135/108753060-8be1f780-7544-11eb-929e-c204d438ad96.png)
after use [i] on the chat (the plugin displays on the chat the player's item/inventory /ender chest)
I'am using paper #483

**Comment by Proximyst** [comment]
Here's a proper image for good measure:
![https://girlsare.life/4W2L1Bd.png](https://girlsare.life/4W2L1Bd.png)

There is nothing logged to the console.

The plugin requires ProtocolLib, so I'd assume this issue is caused by that.

**Comment by ghost** [comment]
> Oto właściwy obraz dla dobrej miary:
> ![https://girlsare.life/4W2L1Bd.png](https://camo.githubusercontent.com/64ca2abab0728cf0e0673ab2225e80d5976300fc64bd210223f578375a293611/68747470733a2f2f6769726c736172652e6c6966652f3457324c3142642e706e67)
> 
> Nic nie jest rejestrowane w konsoli.
> 
> Wtyczka wymaga protokołu ProtocolLib, więc zakładam, że ten problem jest spowodowany tym.

I have protocollib, and after upgrading to the latest version of paper # 483, it just started happening

**Comment by mibby** [comment]
Also getting reports from players about HEX color codes not working properly in EssentialsX ``/nick`` naming & BungeeTabListPlus tab menu / TAB player nametag showing their displayname incorrectly. As well as the vanilla MC message seems to use the displayname instead of being all yellow when you force restart the server & auto-reconnect players. 

![link](https://i.imgur.com/U8qkCt8.png)

How his name normally looks with correct HEX.
![l2](https://cdn.discordapp.com/attachments/496445433229344769/813883932844097667/unknown.png)

How it now looks with Adventure, using same HEX.
![l3](https://cdn.discordapp.com/attachments/496445433229344769/813883985796923412/unknown.png)

The player used the same HEX code but the shade/color matching is different. Like it's matching to the closest in-game vanilla colors instead of using actual HEX.
```/nick &#841f13L&#CE2503o&#E05404r&#FCC713d&eo```

>  I use #841f13 #CE2503 #E05404  and #FCC713 (and just &e for the last letter)

Reverting to pre-adventure implementation, all is fine.

**Comment by slvlr** [comment]
![image](https://user-images.githubusercontent.com/8680731/109002822-9dd7ad80-769e-11eb-86cb-a803f78a9a56.png)
The above still does not work on build 496 in case this needed testing.

This is my TownyChat settings:
channel_formats:
  global: '{townformatted}{deluxetags_tag}{modplayername}&f:{msgcolour} {msg}'
  town: '{channelTag} {townycolor}{townyprefix}{playername}&f:{msgcolour} {msg}'
  nation: '{channelTag}{towntagoverride}{townycolor}{townyprefix}{playername}&f:{msgcolour} {msg}'
  alliance: '{channelTag} {towntagoverride}{townycolor}{permprefix}{townyprefix}{playername}{townypostfix}{permsuffix}&f:{msgcolour} {msg}'

  default: '{modplayername}&f:{msgcolour} {msg}'
  
  If I have 1 colon :  it displays 2 in the chat. And if I remove the colon, it displays 0. Very strange... 
![image](https://user-images.githubusercontent.com/8680731/109003568-82b96d80-769f-11eb-9c09-7baf7200701b.png)

**Comment by s1h4d0w** [comment]
Plugin item2chat is also very similar and not working, instead of seeing **Diamond sword x1** they see [item] and their name.
![image](https://user-images.githubusercontent.com/5654654/109326361-5cd6c900-7857-11eb-8d5d-bef378397b8a.png)

Works fine under build 472, which will probably fix anyone's issues here until there's a proper fix or people update their plugins.

**Comment by kashike** [comment]
I cannot reproduce this using build 506 of Paper 1.16.5 using your provided configurations.

If this is still an issue for you, please reply and I will reopen this issue.

**Comment by kashike** [comment]
Apparently this only happens when *not* in a town.

**Comment by slvlr** [comment]
I got this message in an email, but cannot see it here:
"I cannot reproduce this using build 506 of Paper 1.16.5 using your provided configurations.
If this is still an issue for you, please reply and I will reopen this issue."

The issue seems to still be open, please confirm if I need to test build 506?
