### ISSUE TITLE
Server being killed randomly with no error

### ISSUE THREAD

**Issue by HyplexMC** [PaperMC/Paper#5243]
### Plugin list:
CMI, CMILib
CoreProtect
DeluxeHub3
DiscordSRV, DiscordSRV Staff Chat
HeadDatabase
LuckPerms
NameTagEdit
PlaceholderAPI
Plan
ProtocalLib
UltraCustomizer
UltraRegions
Vault (optimized for CMI)
WorldEdit

### Actions to reproduce (if known):
The kills have been happening randomly some days it happens twice and some days it doesnt happen at all

### Paper version:
> [INFO] .... This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
>[INFO] .... Previous version: git-Paper-495 (MC: 1.16.5)
>[INFO] .... You are running the latest version

### Latest Log:
This is my latest log of the kill
[2021-02-24-2.log](https://github.com/PaperMC/Paper/files/6039538/2021-02-24-2.log)

**Comment by electronicboy** [comment]
99% of cases like these are due to the host running out of memory, if self hosting on Linux, check dmesg, failing that, if shared hosting, speak to your hosting provider; crashes like this are always on the JVM or the host itself and there's very little we can do to aid diagnose these types of issues, and that's more suited to the discord/forums
