### ISSUE TITLE
get performance improvement

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5349]
![unknown](https://user-images.githubusercontent.com/66251951/110944406-1730fa80-8345-11eb-9d6e-3dceccb666a7.png)
 performance improvement?
 
move to spigot! (best answer)
when paper will be less of garbage things like vanilla patch, jvm checkers, etc. etc. etc. etc. you Can, (CAN) move back to paper

**Comment by electronicboy** [comment]
Please refrain from creating troll issues on the tracker, assuming by "vanilla patch", we've been fixing bugs for years and it is part of what we advertise, if bug fixes are not something you want, a platform that prides itself on bug fixes for issues is probably not for you.

if by checker you mean the java version warning, that's there to encourage people to update so that they don't get caught out, if you mean the info logs, those are for debugging purposes and are harmless.

Further abuse of the tracker will result in revocation of your access.
