### ISSUE TITLE
Server shuts down automatically for no reason

### ISSUE THREAD

**Issue by DorrD** [PaperMC/Paper#5381]
Hi there.
First of all, sorry for my English. :)

I've been experiencing a very annoying error on my server for a week. Since every 10 minutes the server restarts automatically. Looking at the logs I don't see anything strange.

I leave you my log: [2021-03-18-2.log](https://pastebin.com/PSyjGKN3)

**Comment by jpenilla** [comment]
enable debug in `server.properties` and upload the new log please

**Comment by chickeneer** [comment]
Closing due to lack of information in the logs to help us provide further support. You can either reply back with more information (and we will re-open the issue). Or you can also ask for support in Discord.

Specifically. The logs provided are not stating the source of what is triggering the shutdown. The debug in server.properties. As suggested. Is a fair place to start.
