### ISSUE TITLE
Ender dragon takes no knockback from exploding beds

### ISSUE THREAD

**Issue by Blumbo** [PaperMC/Paper#5415]
### Expected behavior

When the ender dragon is perching in a dragon fight, it should go a few blocks up when a bed is exploded below it. That's how it is in singleplayer and in vanilla host

### Observed/Actual behavior

Dragon does not mind the beds at all, keeps going down and breaks the next placed bed.

### Steps/models to reproduce

How it should work (vanilla server): https://drive.google.com/file/d/1eWu46BHeAf3efbf9hWYzCEbF-FrUASqL/view?usp=sharing

Paper server: https://drive.google.com/file/d/1NGUl6SnVSo1C6h2wPl7Ry-6zW4Dl5ewS/view?usp=sharing

### Plugin list

None while testing

### Paper version

[10:26:03 INFO]: This server is running Paper version git-Paper-570 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

**Comment by embeddedt** [comment]
I am suspicious that the Spigot changes referred to in #5435 may be responsible for or at least related to this problem.

**Comment by lynxplay** [comment]
> I am suspicious that the Spigot changes referred to in #5435 may be responsible for or at least related to this problem.

Seems to be the case. The ender dragon does not return `true` from the `damageEntity` call when damaged.

**Comment by embeddedt** [comment]
@lynxplay It is indeed the culprit. As a quick hack I added `|| entity instanceof EntityEnderDragon` to your patch and one-cycling now works as expected. I am pretty sure this is not the right solution; I just used it as a quick test.

**Comment by lynxplay** [comment]
Yeah, I'd expect the ender dragon to return `true` when damaged, so either we are currently having a wrong understanding of the return value of the `damageEntity` method or the ender dragon is simply returning something false.

EDIT.1: `EntityEnderDragon:l578` returns what seems to be a boolean indicating if the dragon was actually damaged. This boolean however is completely ignored. Forward that boolean to the caller of `damageEntity` might solve this issue ?

EDIT.2: `EntityEnderDragon` seems to work fine concerning its return value, as the damageEntity method called on its own should not cause any damage (as the ender dragon entity can only be damaged through the complex parts of the dragon).
The quick "hack" proposed earlier may hence actually be our best way forward to allow ender dragon velocity changed due to explosions as any alternative would have to implement specific logic on the dragons complex parts and forward the motion change to the owner.

**Comment by e-im** [comment]
Although this isn't the exact same, closing in favour of https://github.com/PaperMC/Paper/issues/5429 as that has had more activity and stems from the same root cause.
