### ISSUE TITLE
Faster Random Numbers

### ISSUE THREAD

**Issue by xThunderCodex** [PaperMC/Paper#5433]
### Is your feature request related to a problem?

Right now Paper/NMS utilizes "java.util.Random" to generate lots of random numbers for several purposes (e.g. MathHelper.java, RandomPositionGenerator.java). While this is not a major issue it is not the most efficient way to generate random numbers.

### Describe the solution you'd like.

Because of this it would make sense to replace the classic "Random" with the newer and more efficient "SplittableRandom" which speeds up random number generation by 50%+. In most cases this might not be a huge gain in peformance but may add up in the end.

### Describe alternatives you've considered.

/

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by PaulBGD** [comment]
If you profile with an async profiler and filter by callstack, you'll quickly notice that randoms aren't that big of a deal (partially due to Paper already using ThreadUnsafeRandom.) The one spot that they do impact performance is in the chunk ticking, and you can basically [reduce the random calls to so few](https://github.com/TECHNOVE/Airplane/blob/master/patches/server/0012-Optimize-random-calls-in-chunk-ticking.patch) that a replacement isn't needed.
