### ISSUE TITLE
TPS Drop and weird thing called Minecraft::world - tracker stage 1.

### ISSUE THREAD

**Issue by Dolzur** [PaperMC/Paper#548]
###  Timings or Profile link:
https://timings.aikar.co/v2/?id=348cbe84056f46d796bd9611fb583d48

### Description of issue:
Good afternoon. A few days ago I've done some timings due to the TPS drop.
Here's what I've found. Seems something weird causes lag, but noone knows what is Minecraft::world - tracker stage 1.

### Plugin list:	
# KeepItems
# PlaceholderAPI
# PlugMan
# BetterChairs
# MyItems
# SkinsRestorer
# AutoMessagePlus
# SuperTrails
# GameParty
# MelooonCensor
# X-TimePass
# AsyncWorldEditInjector
# TTA
# WorldEdit
# LoginSecurity
# ClearLag
# ChatControl
# WorldBorder
# CustomJoin
# ProtocolLib
# Multiverse-Core
# AsyncWorldEdit
# PermissionsEx
# MCDonate
# RandomBox
# CustomJoinItems
# Multiverse-Portals
# MineResetLite
# Vault
# ServerListPlus
# HolographicDisplays
# Marriage
# WorldGuard
# SkyWars
# ChestCommands
# LeakParkour
# Essentials
# WGFix
# BuildingGame
# Jobs
# ActionHealth
# Citizens
# AdvancedAchievements
# EssentialsChat
# ShopChest
# UltimateArena
# NoFlyZone
# BetonQuest
# ServerSigns
# EssentialsSpawn
# MyPet
# MyPet-NPC
# CTSNC
# CTSNC_Scoreboard
# CTSNC_Tablist

### bukkit.yml, spigot.yml, paper.yml, server.properties
Spigot.yml
http://pastebin.com/2VwAKWFn

Bukkit.yml
http://pastebin.com/KrKSBek3

Paper.yml
http://pastebin.com/wzwY1WU6

### Paper build number:
git-paper-899

### Subscription :D
I can't even google what could cause such lags. Help, please!

Thank you in advance!

**Comment by aikar** [comment]
Lag here is typically due to too many players. However you don't even have many on.

Investigating your timings report raw data, it does appear you are using a low end system on a VPS.

It's most likely that your system just got overloaded and resulted in bad tps (it is only 2 cores, so if that 2nd core is used up by OS, mc is going to suffer)

There is not a 'bug' that's the cause of the low performance. I suggest also checking out my MC Flag guide: https://mcflags.emc.gs
 and review the other performance optimization guides listed there.

And finally, update to the latest paper.
