### ISSUE TITLE
Obfuscate water (anti-xray)

### ISSUE THREAD

**Issue by Philosoap** [PaperMC/Paper#5489]
### Is your feature request related to a problem?

Paper's anti-xray has two modes: engine-mode 1 and engine-mode 2. Both are useful in preventing xrayers, but servers that need to save on performance are likely to choose engine-mode 1. On my server, engine-mode 1 works well besides the issue that small pockets of **water and lava** are included in underground generation. This causes ores which are nearby the water/lava pockets to be seen because they are exposed to air.

There is currently a 'lava-obscures' option in the config, so that ores next to lava are hidden. This results in partial protection:
![2021-04-13_09 54 23](https://user-images.githubusercontent.com/77870215/114579011-74251680-9c4b-11eb-8c0e-5f33ec035dd2.png)

As you can see, ores next to lava are hidden, but ores next to water are not. Since there are so many water pockets included underground, xrayers can still find lots of ore veins.

### Describe the solution you'd like.

A simple solution would be to make a 'water-obscures' option. It would have the same effect and result of the 'lava-obscures' option, only for water.

### Describe alternatives you've considered.

Alternative solutions would be for my server to enable engine-mode 2 or find another anti-xray solution. Engine-mode 2 is easily overkill when engine-mode 1 is doing its job (outside of water pockets). Engine-mode 2 would likely decrease our server's performance and impact our players' fps. From what I've heard, paper has the most efficient anti-xray available. I'm hesitant to use another option that would decrease performance, cost money, or both.

### Agreements

I have searched for and ensured there isn't already an open issue regarding this.
I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
Issue is that, if you obfuscate ores adjacent to water, people are gonna see mangled as all shit ores by water when they mine down there, as with many of these types of things, am not really sure that there is a solution here which allows for anti-xray to remain efficient and not create oddball issues like rivers lined with fake ores...

**Comment by stonar96** [comment]
What you are describing is a general issue of engine-mode 1 (blocks exposed to air or transparent blocks cannot be obfuscated) and in principle it's also an issue of engine-mode 2 because more clever hacks could also just show only the blocks that are exposed to air or transparent blocks. One way to make this harder to bypass in engine-mode 2 is to add air to hidden-blocks (see [my gist](https://gist.github.com/stonar96/ba18568bd91e5afd590e8038d14e245e)), however, even this could be bypassed with even more clever hacks that detect fake air blocks and distinguish them from real caves.

Treating transparent blocks, such as air or water as occluding blocks isn't a solution of the problem because this means that ores that should be visible to a player would be hidden in engine-mode 1 and in engine-mode 2 you would see lots of fake ores. What you are suggesting doesn't make sense to me. Note that lava shouldn't be treated as occluding either. (You can see adjacent blocks on the upper edge of lava blocks on the surface. See [this comment](https://github.com/PaperMC/Paper/issues/2940#issuecomment-583793212). The only reason why the option for lava exists is because lava is kind of almost occluding.)

Thus I don't think that there should be an option for water in general, because it doesn't make sense. If you still want this feature you can easily implement this in the same way that it's implemented for lava in [this line](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0363-Anti-Xray.patch#L250).
