### ISSUE TITLE
LogPrinter

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#5514]
### Expected behavior

The LogPrinter should be terminated last (when the server is shut down).

### Observed/Actual behavior

**Sometimes** not all logs are output completely when the server is shut down.
The log simply stops at plugins even though there are others that need to be terminated.

### Steps/models to reproduce

It is too rendom to create an accurate guide.

### Plugin and/or Server Log

incorrect:
https://pastebin.com/aeUhx3s4

successful:
https://pastebin.com/fSmE7CBa

### Paper version

This server is running Paper version git-Paper-592 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by BomBardyGamer** [comment]
I remember having this issue in an application I made. The reason why this occurs is due to the fact that the order in which shutdown hooks are executed is never guaranteed, and that the server may spend more time shutting down than how long the Log4J shutdown hook takes to shut down.

The reason we don't see it happen every time is due to that aforementioned no guarantees for order of execution of shutdown hooks, essentially creating a race condition.

Thee way we solve this is by disabling Log4J's own shutdown hook and shutting down Log4J manually. This can be done by calling `LogManager.shutdown()` manually as the last thing before shutdown.

I'll see if I can implement this myself, and I'll PR it over.

Example: [config](https://github.com/KryptonMC/Krypton/blob/411b71919e4a7136369279f98bdf7fa1a89294bf/server/src/main/resources/log4j2.xml#L2), [code](https://github.com/KryptonMC/Krypton/blob/411b71919e4a7136369279f98bdf7fa1a89294bf/server/src/main/kotlin/org/kryptonmc/krypton/KryptonServer.kt#L242)

**Comment by electronicboy** [comment]
shutdown order looks generally correct unless I'm missing something, how are you stopping the server?

**Comment by seema84** [comment]
> 
> 
> shutdown order looks generally correct unless I'm missing something, how are you stopping the server?

I can't see that exactly with my hoster. I think quite normal with stop.

**Comment by electronicboy** [comment]
The place where it stops makes 0 sense, to a degree I wonder if there is some plugin interference here
Your logs are stopping before paper even touches the log stuff to close it, this honestly screams something external is going on;

"Stopping server" is printed
plugins are disabled
async tasks are stopped
server connection is closed
"saving players" is printed

and some stuff after that, the fact that your logging stops where it does makes 0 sense and screams that it might not even be a paper thing here

**Comment by seema84** [comment]
you think it is because of dynmap?

**Comment by electronicboy** [comment]
I mean, it's the last thing to stop, so it's either gonna be that or whatever sneaks in right after it, which is somewhat of a "fun" issue to debug

**Comment by e-im** [comment]
Closing as cannot reproduce, if you are still experiencing this on 1.17.1 leave a comment.
