### ISSUE TITLE
Multiverse-Core unable to generate nether worlds

### ISSUE THREAD

**Issue by aclare92** [PaperMC/Paper#5568]
### Expected behavior

A generated nether world with the correct nether atmosphere with the red hue

### Observed/Actual behavior

A generated nether world with the overworld atmosphere and the world pitch black

### Steps/models to reproduce

- Create a new fresh folder
- Add PaperMC version 1.16.5-642
- Start server
- Stop server
- Add multiverse-core, multiverse-netherportals and multiverse-inventories
- Start server
- Create a nether portal and go to nether, correctly loads [world_nether]
- Go back through nether portal, back to [world]
- Run "/mv create creative normal"
- Run /mv tp creative
- Correctly in [creative]
- Run "/mv create creative_nether nether"
- Create a nether portal and go to nether, world is a nether world but the world type is normal
- Fly (spectator mode) above the nether roof and see "overworld daylight" in screenshot attached

![2021-05-03_14 16 17](https://user-images.githubusercontent.com/6871661/116883802-e7ec8a80-ac1d-11eb-91ce-6b5ef925c0b1.png)

### Plugin list

- Multiverse-Core-4.2.2
- Multiverse-Inventories-4.2.2
- Multiverse-NetherPortals-4.2.1

### Paper version

This server is running Paper version git-Paper-642 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Thank you for the correctly filled out and very detailed issue report! But please see the multiverse support/issue tracker. This issue tracker is only for issues directly with paper.

**Comment by nicegamer7** [comment]
Hi @sulu5890, please see the following issue which led to the creation of this one, Multiverse/Multiverse-Core#2627.

**Comment by benwoo1110** [comment]
Want to just highlight that the issue author mentioned that this error did not occur on spigot in his report to MV.

**Comment by HexedHero** [comment]
I cannot reproduce, using MV Core, Netherportals and Inventories and Paper b642
/mv create test nether
/mvtp test
works fine.

https://i.imgur.com/72IDuyJ.mp4 (Sorry for lag spike at the start)

**Comment by aclare92** [comment]
If this helps any more, I have attached the link used, the startup command I am running, system information and a video replicating the previous video showing "cannot reproduce" but with an added "/mv info 2" to show that the world type is "NORMAL" and not "NETHER"

- https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/642/downloads/paper-1.16.5-642.jar
- java -Xms4G -Xmx4G -jar paper-1.16.5-642.jar --nogui
- System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.291-b10) Host: Windows 10 10.0 (amd64)

[https://imgur.com/a/XpiqYIp](url)

**Comment by e-im** [comment]
I also wasn't able to reproduce. Attached is a video of the steps I took for both paper and spigot (paper first, spigot second) following your instructions. While for both it does say `World Type: NORMAL`, it still shows as the nether. What you are looking for is the environment, not type. In this context type would be normal/flat/amplified etc. Would you be able to try on the vanilla client? It looks as if you may have a modded client in your video. Also do let me know if I have done anything wrong.

[https://youtu.be/tnMluWObLPY?t=8](https://youtu.be/tnMluWObLPY?t=8)

[Spigot multiverse version](https://paste.gg/p/anonymous/1acbde7a8e4e4d3792a52d969348ec54)
[Paper multiverse version](https://paste.gg/p/anonymous/cd137f962c364ab3b0257311d287f06d)

**Comment by aclare92** [comment]
Hi all, sorry for the lack of replies, I'll pick this back up tomorrow night (5th May 2021, 8pm BST) and go over the repro steps in the video and also check my client mods. I am running Optifine with a shader pack and will have a play with those to see what I can find out

**Comment by aclare92** [comment]
Yeah, that nailed it, thanks all. Seems to be an issue with the shader pack. Moving from Optifine+Sildur's Shaders to Vanilla, shows up fine, move to Optifine, still fine, add the shaders back in, "broken".

My best guess is that, as it is reporting the world as "normal", that the shader's also identifies the world type using that same stat, therefore rendering the overworld _system_. So, yeah, I will have a go with a few other shader packs or just disable them really 😃 

Again, thanks all for the help/investigation, this one can be closed, or left as "the world type is being reported incorrectly" 👍🏼

**Comment by e-im** [comment]
Thanks for following up with this-

I haven't seen a difference between how paper and spigot report this, and in both multiverse will report that the [style/type is normal](https://gist.github.com/sulu5890/d06e90ad352553189fd2572ced9afd19#file-spigot-worlds-yml-L101) (what you were looking at when running `/mv info`), however, this is not what you are looking for. On my test server, the possible types were `NORMAL`, `FLAT`, or `LARGEBIOMES`. What you are looking for is the environment, which is both saved in the config, as well as reported to the client correctly in both [spigot](https://gist.github.com/sulu5890/d06e90ad352553189fd2572ced9afd19#file-spigot-worlds-yml-L138) and [paper](https://gist.github.com/sulu5890/d06e90ad352553189fd2572ced9afd19#file-paper-worlds-yml-L138). The possible values from my server were `NORMAL`, `NETHER`, and `END`.

I also attempted this with `Sildurs Vibrant Shaders v1.29 Lite`, and wasn't able to reproduce the behaviour. Due to the dimension being reported to the client correctly for both paper and spigot, I am not sure why on spigot this worked correctly for you but on paper it didn't.

Because of this, I'm going to close this for the time being.
