### ISSUE TITLE
PlayerInteractEvent possible issue

### ISSUE THREAD

**Issue by Hivane060** [PaperMC/Paper#5602]
### Expected behavior

When I aim the target/entity by also being on sight of the block behind it, when I left click, I should be able to detect him as a target.

### Observed/Actual behavior

When I'm aiming to the entity/target which has also a block behind it that can be broken by me, it won't be detected:

(Image 1) Here I am aiming the wither skeleton, that has also a gold block that can be reached (and therefore broken) by me. This is the situation where the target is not detected
![2021-05-09_01 05 41](https://user-images.githubusercontent.com/83833914/117567322-18b83e00-b0bc-11eb-83f5-993277243d00.png)

Here are shown situations when the issue doesn't occur:
As it can be noticed here the code works fine, due to the message (that tells the type of the target) showing up

(Image 2) In this image I'm aiming the wither skeleton + the crosshair doesn't encounter any block
![2021-05-09_01 26 33](https://user-images.githubusercontent.com/83833914/117567331-22da3c80-b0bc-11eb-84a3-cfd0394b7c6d.png)

(Image 3) In the second image I'm really far from the target (and therefore from the blocks behind it)
![2021-05-09_01 24 59](https://user-images.githubusercontent.com/83833914/117567337-279ef080-b0bc-11eb-964e-977b6fbfeb7d.png)

### Steps/models to reproduce

To replicate this issue:

make a skript with this code: https://pastebin.com/MLJdKD33
Summon a mob and put a block behind it
Left click when you are close enough to be able to break that block behind the "target"
You will notice that the message that says the type of the target won't show up

### Plugin list

Skript

### Paper version

1.16.5 ; Build 649

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I already made a report similar to this in the Skript's github page, and they told me that this is related to the PlayerInteractEvent (The left click one), which is only called when there's a block in line of sight.

Therefore, is the behaviour I occured into an expected one?

**Comment by electronicboy** [comment]
The type of interaction that is fired depends on what the client sends us, entity interaction occurs within a specific range, beyond that, there is ray tracing methods in the server which are generally used, this is basically a misunderstanding of how the client interacts and what the API does, if you want to target an entity outside of the typical client interaction range, you'll explicitly need to look for that

On that note, we can't provide support around abstraction layers, based on what you're saying it sounds like it's relying on the entity interaction directly rather than actually checking if you're looking at an entity, these are two entirely different concepts; If there is an issue in the API, a test case with java would need to be provided, there is 0 interest trying to rip apart some abstraction layer to diagnose where the issue is
