### ISSUE TITLE
"PortalCreateEvent" Can't be cancelled for End Portal

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5645]
### Expected behavior

When cancel the event, cant create a End Portal

### Observed/Actual behavior

The portal creates normally

### Steps/models to reproduce

Cancel the "PortalCreateEvent" Event

### Plugin list

really needs?

### Paper version

1,16,5 #667 (Actually the latest)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by ghost** [comment]
Note: Nether portal is cancelled, only the end portal is not.

**Comment by Chew** [comment]
Duplicate of #5547

**Comment by Machine-Maker** [comment]
@danielzinh Can you give more specific reproduction behavior, and more specific expected behavior, what **exactly** do you want to cancel? The generation of the obsidian platform in the end? There are [currently only 3 reasons](https://papermc.io/javadocs/paper/1.16/org/bukkit/event/world/PortalCreateEvent.CreateReason.html) for this event to be fired. This may not be a duplicate, depending.
