### ISSUE TITLE
Build #1012 or #1013 Causes Items to Disappear from Inventory

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#567]
# Incompatibility (Bug)

### What behaviour is expected:
Essentials /worth should check what the player is holding and send a message in chat telling them what the item is worth in the economy.
### What behaviour is observed:
Using builds 1013 - 1019 result in the item being removed from the player's inventory. Build 1011 does not have this issue.
### Steps/models to reproduce:
Start a server with EssentialsX and any build of Paper after 1011. Try to do /worth while holding an item that is configured in Essential's worth.yml
### Plugin list:
EssentialsX

**Comment by NachtRaben** [comment]
https://github.com/drtshock/essentials/commit/ca28d8aa84010ce97f6e534cd78982df3be8aeca

Potentially fixed on the plugin side?

**Comment by zachbr** [comment]
This was caused by https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/5715b3a6d98848d39c1e6bc6b0be6ba0ef8e2b76

As this change was made by CB and plugins are already updating to handle it, it doesn't seem all that wise for us to alter it and create a new unknown behavior. You can update EssX to resolve this.

Thanks @Spottedleaf @SupaHam
