### ISSUE TITLE
Add option do delete unused chunks

### ISSUE THREAD

**Issue by maxkraft7** [PaperMC/Paper#5720]
### Is your feature request related to a problem?

Yes, if players scavenge the end it generates a lot of chunks that then often aren't used for anything which bloats up the world size more than necessary. This increases deployment time, time to backup and in general just takes up a lot of ressources.

### Describe the solution you'd like.

If a player remains in a chunk for a very short time (<1 Minute for example) and isn't placing or removing any blocks in it, it can be deleted again. If someone else enters it again, it gets generated again. 

### Describe alternatives you've considered.

I found this tool: https://github.com/Querz/mcaselector which I find really cool, but it requires too much manual interaction for such a task I think. Just adding some options to automatically remove these junks would be way easier. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Prof-Bloodstone** [comment]
This doesn't feel like Paper territory. There's so many things you would potentially want to filter through that it's not feasible as an addition. Either use a plugin or previously mentioned mcaselector.

Also, simply deleting chunks is not a good idea - you'll have to regenerate them again and again (what if someone keeps moving between 2 chunks), as well as there's no reliable way to recreate a chunk (since it uses up information from neighbor chunks that is destroyed during the generation).
