### ISSUE TITLE
[Suggestion] Auto update?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#576]
Is it possible to do an AutoUpdate, automatically compile the jar and replace the previous jar?

I don't know if there would be more useful. (not to be downloading all the time the paperclip, etc)

**Comment by ghost** [comment]
I made a plugin, which automatically downloads the paper clip, and starts the server.

More, it would be very useful a function that implemented directly in paperspigot.

**Comment by MrPowerGamerBR** [comment]
Why couldn't you just create a script which downloads the latest Paper version when the server starts up?

Auto updating on a Minecraft Server can be a mess, 1.11.3 released? Paper would auto update to 1.11.3, breaking NMS changes? breaking API changes on a commit? Whoops, there goes your server.

This shouldn't be added, and, if it gets added, it should be a opt-in feature, not opt-out.

**Comment by ghost** [comment]
I did a command that automatically downloads.

If I do in onLoad would give several errors.

It's just I get /version, if you have missing version I download the jar again.

~Skript~

**Comment by MrPowerGamerBR** [comment]
> Why couldn't you just create a script which downloads the latest Paper version when the server starts up?

You know how to read, right? Why can't you create a script to ```wget https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/artifact/paperclip.jar``` every time the server starts up?

You are trying to over complicate something so simple.

Anyway, this shouldn't be added due to the reasons I said above.

And, if you are using Multicraft (or any other server wrapper that doesn't allow you to edit the startup script), then that's isn't my fault. You can also download wget for Windows if you need that.

EDIT: And it is kind of obvious that you can't swap the server JAR while the server is running, doing that is asking for "hey JVM, can you crash the server for me? thanks, I know that I'm dumb"

**Comment by ghost** [comment]
Who said what I'm going to change the server's jar when low?

I give Shutdown on the server, and then change.

**Comment by MrPowerGamerBR** [comment]
@Kurimatzu if you are replacing the JAR while the server is running (doesn't matter if you are doing it on onDisable()), it will crash. (and even it doesn't crash, why not download the new JAR when the server starts instead of doing your plugin workaround?)

**Comment by DenWav** [comment]
We are not going to implement auto update, ever, period.
