### ISSUE TITLE
Paper 1.17 ETA??????

### ISSUE THREAD

**Issue by Leonoell** [PaperMC/Paper#5834]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like.

Release 1.17 support for paper

### Describe alternatives you've considered.

TELL ME.. THE FREAKING… ETA..!!!!

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Why isn’t paper in 1.17 yet??!! Please tell me the ETA!!!

**Comment by HexedHero** [comment]
Now delayed since you asked 😂

**Comment by Esophose** [comment]
should be done with a few thousand years

**Comment by Chew** [comment]
I'm not actively working on Paper so replying won't be affecting development, however it is still a waste of my time. Not only did you waste my time having to deal with this issue, you lied about it being a issue at all. Your impatience is not our problem. We are under no obligation to give you any information regarding when we'll be done, even if we had any. Instead of making an issue, check out the development branch to see how we're doing. Hop on discord voice chat to listen in to the development (assuming you haven't been banned for being annoying there as well). Please do not use our issue tracker for your impatience. Thanks!

**Comment by Leonoell** [comment]
> I'm not actively working on Paper so replying won't be affecting development, however it is still a waste of my time. Not only did you waste my time having to deal with this issue, you lied about it being a issue at all. Your impatience is not our problem. We are under no obligation to give you any information regarding when we'll be done, even if we had any. Instead of making an issue, check out the development branch to see how we're doing. Hop on discord voice chat to listen in to the development (assuming you haven't been banned for being annoying there as well). Please do not use our issue tracker for your impatience. Thanks!

I’m so sorry for the inconvenience but sadly I have a… a.. LIFE! (Which must be unheard of from the papermc devs) You did not need to respond to this question nor do you have to respond to any question posted on this GitHub. Thanks!! (I attached a selfie to hopefully make this conversation seem more life like in these troubling times.)
![53D37AC4-46E8-4243-B154-6569C7D44034](https://user-images.githubusercontent.com/83191185/121980536-1b145480-cd5a-11eb-9050-8a4600281cee.jpeg)
