### ISSUE TITLE
Issue with nametag edit tags disappearing with mcmmo + paperspigot anti-pushing

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#585]
I am not sure who's fault this issue is, so posting here in case https://github.com/sgtcaze/NametagEdit/issues/130

**Comment by andris155** [comment]
Same problem. :(

**Comment by zachbr** [comment]
Paper's anti-push system is relatively invasive due to the way the server and client handle collision movement. It does only assign users to a team if they aren't already on one however. So you could work around this for certain users by adding them to your own team and setting everything up. Or you could just disable Paper's blanket system for a more specific one setup for your needs.

Though I am still unsure that Paper is even responsible for this, given that someone else commented on that ticket and says they have the same problem on Spigot. That being said, there's not a ton we could do even if it was.
