### ISSUE TITLE
/locate does not always give correct location for structure, Paper 1.17

### ISSUE THREAD

**Issue by Slimerblue22** [PaperMC/Paper#5852]
### Expected behavior

/locate command should always give me the correct cords for the structure location.

### Observed/Actual behavior

Sometimes the correct cords are given and sometimes incorrect cords are given.

### Steps/models to reproduce

Video showing bug here: https://www.youtube.com/watch?v=bPVbxvQzgdQ

### Plugin list

None

### Paper version

 This server is running Paper version git-Paper-"3740db0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
 
 *Directly underneath the version output was this message "Error obtaining version information"* 

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I have tested this on the same seed and different seeds with Vanilla and Spigot and have not seen this issue on either of them.

**Comment by Proximyst** [comment]
That should be due to: https://github.com/PaperMC/Paper/blob/dev/1.17/patches/server/0552-Seed-based-feature-search.patch

**Comment by Drathaar** [comment]
slimey wimey

**Comment by kickash32** [comment]
Did you test with a new world or an upgraded world?

**Comment by Slimerblue22** [comment]
> 
> 
> Did you test with a new world or an upgraded world?

New world.

**Comment by kennytv** [comment]
Pretty sure this is broken in 1.16 already, we recently merged a pr changing its behavior there

**Comment by Chew** [comment]
I had this issue in very early 1.16, but it was due to VarLight or something. Never looked too deeper into it.

**Comment by electronicboy** [comment]
if you enable the option to allow them to load chunks, it should work, I think that part of the issue here si that structure gen is not guaranteed to happen in a place the seed says it may, vanilla actually causes the chunk to generate however to actually see that it does;

to my understanding, back in the past we used to have more visibility of this as the code was more "open" to us, so we could reduce this case, now we can only see pre-gen that something might or might not be there, you actually have to gen the chunk to know if it actually is in fact there AND exactly where it is

**Comment by kennytv** [comment]
Set `seed-based-feature-search-loads-chunks` to `true` in your Paper config; the defaults will be changed now tho, see cat's definitely very coherent message for why
