### ISSUE TITLE
[1.17] Putting " as a message puts out a blank line

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5870]
### Expected behavior

when `no-permission:` is set to " it should output nothing.

### Observed/Actual behavior

Instead a blank line finds it way in chat.

### Steps/models to reproduce

Put the value to ".

### Plugin list

Plugins (6): CMI, CMILib, LuckPerms, TAB, Vault, WorldEdit

### Paper version

Latest 1.17 build found in the discord. Paper-1.17-R0.1-EXPERIMENTAL-3.jar.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Malfrador** [comment]
Can confirm. Happens on 1.16.5 builds as well and is not plugin related, I tried it without any.

**Comment by Machine-Maker** [comment]
Was the behavior ever different from this? (Not saying it's not smth that should be changed, but I'm wondering if before, it also sent a blank message instead of nothing)

**Comment by ghost** [comment]
I thought it did before but I'm not certain of that. Regardless it exists on 1.16.5 as Malfrador pointed out so I would assume this has been standard behaviour.

**Comment by robog-two** [comment]
IIRC a lot of bukkit stuff requires you to use null and not '' for it to send nothing, so I think this might be intended behavior. However, it's impossible to set a property to null, since Paper thinks it doesn't exist and sets it to it's default. I assume there is a way to check if a property exists and is set to null vs if it's not configured, but I'm not sure.
