### ISSUE TITLE
[1.17] Maps on frame clearing after restarting 

### ISSUE THREAD

**Issue by hapeshiva** [PaperMC/Paper#5878]
### Expected behavior

Maps will be saved.

### Observed/Actual behavior

The cards on the frames are cleared after restart, but when press the middle mouse button they are restored

### Steps/models to reproduce

1. Restart
2. ![image](https://user-images.githubusercontent.com/59057758/122642118-38fb0400-d122-11eb-9ab4-6ff09eae5a4b.png)
3. Click middle button in creative
4. ![image](https://user-images.githubusercontent.com/59057758/122642138-5039f180-d122-11eb-8d1d-df184c82a036.png)

### Plugin list

![image](https://user-images.githubusercontent.com/59057758/122642168-75c6fb00-d122-11eb-8bf3-4d3298668c50.png)

### Paper version

This server is running Paper version git-Paper-"d76f8e0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Paper-753 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by kennytv** [comment]
There's a 1.17 client bug preventing map data to be cleared on server switches, also unable to override the old data, not sure if that's related here.

**Comment by kennytv** [comment]
... tho I can't reproduce this specific issue.

**Comment by Foorcee** [comment]
https://bugs.mojang.com/browse/MC-229520

**Comment by DeSinc** [comment]
could this be related to ImageOnMap? I also have this issue with all item frame custom images made with that plugin after server restarts. with me however, I don't see that little blue green box in the corner, I just see an empty but "filled" item frame (larger than usual frame to indicate there is an item in it) but with no picture showing up.

regular maps seem to be fine though.

**Comment by hapeshiva** [comment]
> there is an item in it) but with no picture showing up.
> 
> regular maps seem to

yes

**Comment by Machine-Maker** [comment]
I can't reproduce it on paper 1.18.1 with no plugins. Additionally the possibly linked Mojira issue has been resolved. Closing as cannot reproduce, if someone has reliable reproduction instructions, this may be reopened.

**Comment by yannicklamprecht** [comment]
I had that problem multiple times after major upgrades. Everytime for image on map map walls only.

The screenshot seems to be a image on map generated map wall.

**Comment by DeSinc** [comment]
EDIT: confirming this is FIXED on latest 1.18.1 paper jar and with latest imageonmap 1.18 jar

~~_it definitely still happens on the latest paper 1.17.1 jar because I literally just switched back from tuinity (which it didn't happen on) to paper for the log4j fix, because tuinity merged back to paper, and the issue has come back to plague me yet again. Yet again I am delegated to going around middle clicking my 25x25 damn images for my friend's house :(_~~

**Comment by DeSinc** [comment]
EDIT: confirming this is FIXED on latest 1.18.1 paper jar and with latest imageonmap 1.18 jar

> ~~I can't reproduce it on paper 1.18.1 with no plugins. Additionally the possibly linked Mojira issue has been resolved. Closing as cannot reproduce, if someone has reliable reproduction instructions, this may be reopened.~~

~~just making sure you realise that the issue is for image-on-map images, which is a plugin that puts png or jpg whatever images on maps to make a big image. the problem isn't for vanilla map walls. this doesn't happen on tuinity, for reference. it's only broken on paper.~~ edit: it's fixed on latest versions of both anyway (just updated my server so had chance to test it)

**Comment by DeSinc** [comment]
confirming this is FIXED on latest 1.18.1 paper jar and with latest imageonmap 1.18 jar
