### ISSUE TITLE
Exception ticking world Crash Paper 1.11

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#588]
Crash: https://1drv.ms/t/s!Au0_fNq_9GA4gcEnV2czuWS_ed4wRA
Timings: https://timings.aikar.co/?id=dcb4084c4d49415fa1f4977873a0351b
Plugins:  Vehicles, MobEggSpawnerBlocker, PlugMan, PlayerWarp, BetterChairs, NametagEdit, MineMarket-Universal, EntityDetection, SkinsRestorer, ViaVersion, Stats, AsyncWorldEditInjector, Deadbolt, OpenInv, LimitCreative, CreativeNbtControl, XRayDetector, ClearLag, AutoMessage, ChatControl, WorldBorder, Votifier, ProtocolLib, weeTrade, AsyncWorldEdit, RedstoneClockDetector, PermissionsEx, Lottery, mcMMO, Vault, GAListener, AuctionHouse, MyCommand, WorldEdit, Essentials, PlotMe, CompatNoCheatPlus, NoCheatPlus, TreasureChest, EssentialsChat, PlotMe-DefaultGenerator, WorldGuard, myZone, EssentialsGeoIP, RandomTeleport, PvPManager, EssentialsSpawn, TitleManager, Multiverse-Core, Shopkeepers, CraftBook, ChestShop, MobArena, LimitedCreative, AreaShop, SurvivalGames, MyPet
Version: git-Paper-976 (MC: 1.11)

**Comment by zachbr** [comment]
Looks like something is modifying the world's nextTickList asynchronously. Not sure how else this could happen. I'm not familiar with many of the plugins you're using as well, so my only suggestion would be to start going through them.

**Comment by Brokkonaut** [comment]
Sometimes we have crashes with exactly the same exception and i'm sure we have no plugins with async world access/modification.

The first of them happened on 20 february 2016 and since then we hat a total of 4 of this crashes (on 20 servers) - it was so rare i did not report it.

~~Maybe the cause is that NextTickListEntry.compareTo()  is not consistent to NextTickListEntry.equals() and HashTreeSet requires them to be consistent. So the HashSet and the TreeSet in the HashTreeSet might desync (but i did not check that)~~ (EDIT: Checked that, I think its safe)

If it's a server bug, it's definitely an upstream bug:
https://hub.spigotmc.org/jira/browse/SPIGOT-2473
https://www.spigotmc.org/threads/server-crash-error.138010/

**Comment by zachbr** [comment]
Has anyone seen this on builds 1052+ ?

**Comment by andris155** [comment]
fixed
