### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by Wazez** [PaperMC/Paper#59]
Hey got a few suggestions for paper:
- like slime mobs, add an option to make it so that mushroom cows can spawn in any biome
- option to make invisibility potion effects hide the player name above head. (this is when you drink/splash an invis potion)
- world generation suggestion: removespawners option - would generate the world without natural mob spawners (useful for spawner based economies)

keep up the good work

**Comment by Ichbinjoe** [comment]
I feel like all 3 can (and should) be handled by plugins. We try not to add things that can be achieved by using plugins. Thanks for the suggestions, but I feel like this is out of the scope of this project.

**Comment by RoboMWM** [comment]
- I thought mooshrooms spawn based on biome, not chunk. Could use a plugin to have a chance to spawn a mooshroom instead of a cow.
- This is possible via Scoreboard teams via a plugin
- Possible via plugins by watching chunkLoadEvent, and seeing if it's new, then scan and remove mob spawners.

**Comment by Wazez** [comment]
Thanks guys, i meant biome not chunk sorry.

And I know these are possible via plugins but its more for the public and servers without devs. like the stuff already in paper e.g the flat bedrock feature, stackable buckets etc

feel free to close the ticket, i was just suggesting

**Comment by RoboMWM** [comment]
tbh you can do some of this with already existing plugins, e.g. MobManager for the mooshrooms suggestion.

**Comment by zachbr** [comment]
- like slime mobs, add an option to make it so that mushroom cows can spawn in any biome

I feel like @RoboMWM's answer was the most sane here because just letting them spawn wherever would be ridiculous, iirc they spawn a lot a lot a lot. So a plugin would be the best fit, along with being far more customizable than we could provide.
- option to make invisibility potion effects hide the player name above head. (this is when you drink/splash an invis potion)

Wait wait wait, an invisibility potion doesn't hide your nametag? Just close-up right? What is the point of invisibility potions otherwise? I would like a bit more clarification on this item.
- world generation suggestion: removespawners option - would generate the world without natural mob spawners (useful for spawner based economies)

This may be a sane thing for us to add to our existing generator changes patch just because making a worldgen plugin in Bukkit sucks because you have to reimplement the existing logic. And while yes, a plugin could loop through all the blocks and remove it on load, that's really not any better than us just putting a toggle in.

**Comment by Wazez** [comment]
Thanks for the reply mr Zach sir !
With invis potions, it doesn't hide the name tag of some with the invis
potion effect.

**Comment by RoboMWM** [comment]
@Wazez Are you using plugins that mess with the scoreboard (e.g. HealthBar, AnimatedNames, or anything else that gives you a prefix or suffix on your nametag)?

**Comment by Wazez** [comment]
Ah hmm. Ok I'm at uni at the moment but I will test this in detail when I
get home. Yes we do have some plugins that modify name tags like mcmmo and
one of our own plugins that showcases user ranks.

So is this not a minecraft thing/feature but a something on my end? I
thought a update (1.7) made it so that name tags are visible when drinking
invis

**Comment by Puremin0rez** [comment]
Nametags still showing while Invisible was a bug in 1.8, it was fixed for 1.9 (according to the official bug for it)

https://bugs.mojang.com/browse/MC-48730

If you're still having the issue, then one of your plugins that touch teams/nametags must be doing something wrong.

**Comment by zachbr** [comment]
@Wazez is there some reason you don't just disable dungeon generation in the generator settings in paper.yml?

**Comment by Wazez** [comment]
What I didn't know that would remove the spawners... hm thank you.

**Comment by zachbr** [comment]
Guess that's everything then?
