### ISSUE TITLE
Potential chunk unloading issues

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#597]
There is something going on with version 1045 and beyond that makes every single thing about the server lag. In timings everything appears to be using huge amounts of %, and tps drops down to 2 after less than an hour. Running version 1044 and server runs fine - solid at 20 tps after 48 hours of uptime. Another issue is running /stop when using version 1045 or beyond for a longer amount of time, it takes a very very long time to save all the worlds, took 10 minutes of waiting just now (on paper 1046).

**Comment by mikroskeem** [comment]
More information could be useful, for example what plugins you are using. Or perhaps timings link?

**Comment by zachbr** [comment]
Spigot has been making changes to the way the chunk unload queue is managed, specifically, they are delaying it and breaking out the work over multiple ticks. It appears that the way this was being done, could make the chunk unload queue flush very very slowly on servers that are in a constant state of TPS loss, or are always running very close to it.

They've added a ratio so that a certain number of chunks always get flushed from the queue regardless of the TPS, which should help alleviate the issue. This is now present in builds 1047+ please give them a try.

**Comment by ghost** [comment]
Tested running it for about 6 hours, it seemed to have improved in the first hour of running, but after that the issues came back. Timings are the same, everything appears to use a lot of tick which I guess is because of chunks unloading slower than before. Especially fire tick time in nether used a ridiculous value, as if a huge amount of nether chunks were loaded and active. Back to 1044 for now which runs fine.

**Comment by AlfieC** [comment]
From your description, it appears your server is running close to 50ms full tick and your players do a lot of teleporting - perhaps we could add in a toggle for this new feature?

**Comment by Brokkonaut** [comment]
Can confirm the problem.. once there are too many chunks loaded and it starts lagging a bit more, too few chunks unload and there are constantly loading more chunks than unloading up to some very high value.. we had to downgrade to 1044 (from 1052) because our servers lag extremely in the more recent versions.
i would recommend to revert to the old unloading logic.

**Comment by ghost** [comment]
I have tested 1051 and 1052 with near default configs (all auto save and chunk related config values default) and removed many unneeded plugins especially ones that appear to do chunk related things, and the issue would remain. The server would run okay the first hour, and after that it would drop below 20 tps and continue going down forever until a restart was made. It would go as low as 3 tps, and more than half of the lag was from nether chunks. the mobSpawn and fire tick value in nether was extremely high, mobSpawn could reach 50% with spawn range of 2 and spawn tick per set to 4.

**Comment by Brokkonaut** [comment]
The new unloading logic is just wrong. Currently it is

Many chunks loaded -> Tick time at its limit -> Less chunk unloading -> more chunks stay loaded -> tick time even more at its limit -> ...

This just cannot work. If the server is overloaded it has to unload chunks as soon as possible to reduce load in the long term, but now it does exactly the opposite...

**Comment by zachbr** [comment]
This change has been removed in builds 1054 and above.
