### ISSUE TITLE
chunk task prioritisation scheduling stall

### ISSUE THREAD

**Issue by Primorior** [PaperMC/Paper#5980]
### Stack trace

```
https://paste.gg/p/anonymous/07b1a81ebef5480fa54cfe14e65078c7
```

### Plugin list

AutoMessage, ChestShop, CMILib, CoreProtect, DiscordSRV, EssentialsX, FarmLimiter, Fe, GroupManager, Jobs, LandLord, Multiverse-Core, Multiverse-Nether-Portals, NerfPhantoms, NuVotifier, Paintball, Protocollib, SetMotd, SilkSpawners, SimpleVoteListener, SkQuery, Skript, Vault, VoidGenerator, WDLCompanion, WorldEdit, WorldGuard

### Actions to reproduce (if known)

Just logged in and this happend.. switched back to Spigot and had no issues.

### Paper version

Paper 46

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Stabrinai** [comment]
+1,
[Chunk Bug](https://github.com/PaperMC/Paper/issues/5910) Not fixed yet...
I also encountered the same situation.

**Comment by supertakeru** [comment]
also still a problem for me

**Comment by electronicboy** [comment]
Trace may look similar but it's not the same bug, need the full log, but, spigot won't warn you about incremental stalls, so, generally hard to say on this stuff, if you can, provide timings, etc

**Comment by Primorior** [comment]
Happened directly after logging in after start, so there are no timings :/

**Comment by electronicboy** [comment]
if the server is still ticking, you can wait a few minutes to run it, ideally, give it a moment before trying to join, JIT warmup is still in process can can have massive impacts on performance, otherwise, need full logs

**Comment by Primorior** [comment]
https://paste.gg/p/anonymous/dc6f764010284fc69c22c5469e6ae026 full crash until I killed the java process

**Comment by Primorior** [comment]
full log here too https://paste.gg/p/anonymous/1cdfbdfb74964f3b96de5bfedc2689ba

**Comment by electronicboy** [comment]
Yea, seperate issue entirely, gen thread stalled because catto

**Comment by TauCubed** [comment]
having the same issue, appears to be deadlock on serverconnection#c() sync block?
I can't reproduce this locally myself so I can't be sure.

**Comment by kennytv** [comment]
We still have been unable to reproduce this, so it would be great if you could give us a timings report on the setup you get this issue (so we can get the configuration setup and some other info timings provides).
Also, does this actually hard lockup your server, or does your server tick/log normal messages again at some point after the first 10 second watchdog warning appears (do you see entities moving, can you drop an item or hear place sounds, aka does it "just" lag a lot or fully crash immediately)?

**Comment by Primorior** [comment]
I'm going to take timings later and post them. After logging in, it kicked us after seconds of falling down into the void.

**Comment by Primorior** [comment]
https://timings.aikar.co/?id=f7915fc37afa4820aab1a00a65ad9fa3 Timings, updated to Paper 48, logged in after taking the timings and it doesn't crash anymore.

**Comment by Primorior** [comment]
Happened again, server was running fine, one of my players said he was flying in the farmworld with elytra and then ported back home (alot of hoppers, chests and villagers there), maybe helps.. Full log of it: https://paste.gg/p/anonymous/314dc98a9a7d4d0287091d285f33adcc

**Comment by TauCu** [comment]
do you use pterodactyl?

if so try setting the memory of the container 1 or 2 GB higher than that of the server.
solved similar problem for us.

**Comment by Primorior** [comment]
Nope, I don't use it

**Comment by radekklima21** [comment]
I have these errors everyday. Sometimes, when someone teleports or just join the server, then whole server freeze for 5-10 seconds and sometimes I have these errors: https://paste.gg/p/anonymous/82459c80a99b4486b2ecaa1edec9e5b1

As you can see, someone typed /home before it. I can give you a timings too: https://timings.aikar.co/?id=6b0271daa8c4413ca923f25d08092ea3#timings

I dont know what can I do, it is happening 6-20 times per 24hours. This is not usual laggs, it is just freeze, stuck. The TPS-meters shows nothing (stable 20TPS)

**Comment by SnickoDeadMC** [comment]
Had this error yesterday with Paper-68. Huge amount of errors with a crash that didn't restart the server until I killed the process and had to manually start again.

https://pastebin.com/AuMj0Pk0

**Comment by ScuroK** [comment]
updated to 1.17 today. server crashes nonstop. i tried everything but could not fix it.

**Comment by Brokkonaut** [comment]
> updated to 1.17 today. server crashes nonstop. i tried everything but could not fix it.

Without giving enough information (at least server log file, plugin list) nobody will be able to help you.

**Comment by radekklima21** [comment]
I know how to reproduce this issue. You must have 50-60 players playing on your server and typeing a lot of teleportation commands such as /tpa /rtp /home. After a moment your server will be freezed and crashed due to chunks loading

**Comment by Primorior** [comment]
> 
> 
> I know how to reproduce this issue. You must have 50-60 players playing on your server and typeing a lot of teleportation commands such as /tpa /rtp /home. After a moment your server will be freezed and crashed due to chunks loading

Around 3 players can do the same. All 3 used rtp and used the elytra with fireworks. Took only seconds to kill the server

**Comment by Brokkonaut** [comment]
It looks like an error in this patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch where it schedules chunk priority updates while updating them and so go into an endless loop

**Comment by NobleStrike** [comment]
Issue is happening to me now too. Server basically stopped then wont start after that, even before anyone logs in.
https://pastebin.com/fXqwvT7g

Hopefully its a quick fix and not some sort of map corruption/damage.

I was on build # 71 ver 1.17 when it happened. Even after going to build # 75 the issue continued. 

> It looks like an error in this patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch where it schedules chunk priority updates while updating them and so go into an endless loop

It only affects my older maps it appears which makes sense.

**Comment by Primorior** [comment]
> It only affects my older maps it appears which makes sense.

The worlds in which this issue happend were all generated in 1.17 for me

**Comment by Ricardo11v** [comment]
***@***.***

**Comment by Ricardo11v** [comment]
ece0b19c59c98df5dda540e612b71fcc1c688f66

**Comment by ravegergame** [comment]
same problem, using random spawn on join
https://paste.gg/p/anonymous/b05cb75a1b304107a49073f03debcce6#pastefile1-l902

**Comment by Primorior** [comment]
Issue still a problem in 1.17.1 :/
Edit: Updated to paper 95 and updated EssentialsX to newest dev, seems like it doesn't happen anymore

**Comment by NobleStrike** [comment]
Is this still an issue? I'm stuck on spigot unfortunately until it's patched.

**Comment by Machine-Maker** [comment]
I still haven't been able to replicate it. If there were some solid repo instructions with a world download, or just anything that could cause it to be reliably reproducible by someone else it'd probably help.

**Comment by NobleStrike** [comment]
Well ill try some of the latest builds and see if this was upstream or some other issue. If the server boots then I'll fly around some old and new worlds, some of the older worlds. I'll find out very fast if this is patched.

**Comment by DarkKingKaan** [comment]
Having a similar issue, it was mentioned above. I'm also not quite sure how to reproduce it. The server keeps crashing after updating from 1.16.5 generated world to 1.17 (Then loading some chunks with newer generation).

**Comment by RapidGravy** [comment]
Having similar crashes and not sure how to trace it down until finding this. I'll try and get a timings of my latest crash.

**Comment by ChimpGamer** [comment]
I've had similar crashes as well on three different servers. This is my server log which includes the upgrade process from 1.16.5 to 1.17.1 https://paste.gg/p/anonymous/25c6153e124e4f4d91ea29ce5e3bcdf4 (some plugins printed exceptions because they need reconfiguration nothing that causes this or these errors)

**Comment by hotspuraz** [comment]
Having to run spigot because Paper just crashes after 5 minutes x.x

**Comment by richardhyy** [comment]
Same issue.

But, strangely, after I turned the verbose mode on (`paper.yml` -> `verbose: true`), it no longer crashes.

(Paper-151, 1.17.1) https://paste.gg/p/anonymous/df8c96da9dc145578eef4be386efbf2e

**Comment by RapidGravy** [comment]
It's hard to get a timing report at the time it happens because it seems to happen randomly for me. But heres the log of it crashing: https://pastebin.com/RXMBZKH1

**Comment by h316098438** [comment]
this problem still exists. tt is useless to upgrade to the latest paper and essX

**Comment by NobleStrike** [comment]
> this problem still exists. tt is useless to upgrade to the latest paper and essX

Can you link the error with the version of paper so the Devs can bring attention back to this? I've been running spigot since July 5th waiting for this to be patched.

If it has something to do with essentials then that needs exposed so we can figure out what the heck is causing these crashes.

**Comment by h316098438** [comment]
I don't think it has anything to do with essentialsX, because I've already upgraded and the problem still exists.i suspect it has something to do with running maps, which seems to cause this problem every time someone uses elytra to fly an unloaded map on the server




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaperMC/Paper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaperMC/Paper] chunk task prioritisation scheduling stall (#5980)





  
this problem still exists. tt is useless to upgrade to the latest paper and essX
  
Can you link the error with the version of paper so the Devs can bring attention back to this? I've been running spigot since July 5th waiting for this to be patched.
 
If it has something to do with essentials then that needs exposed so we can figure out what the heck is causing these crashes.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hotspuraz** [comment]
It is exactly what the title says, nothing to do with essentialsx. 
I don't run essentials and it crashes my server. The crashes are most frequent when players are moving into new chunks using commands like /rtp but it will also crash when players are stood afk at mob farms.

**Comment by h316098438** [comment]
Yeah, so I suspect there's something wrong with the loading algorithm for the new chunk. This can happen when the player is logging in and out of an unloaded chunk, or tp, or flying, anything that involves an unloaded chunk, especially one that the server has not saved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaperMC/Paper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaperMC/Paper] chunk task prioritisation scheduling stall (#5980)





 
It is exactly what the title says, nothing to do with essentialsx.
 I don't run essentials and it crashes my server. The crashes are most frequent when players are moving into new chunks using commands like /rtp but it will also crash when players are stood afk at mob farms.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MeowRay** [comment]
Use Spigot before Paper fixes it
This is the only solution

**Comment by h316098438** [comment]
But they weren't ready to fix it and didn't even think it was a paper&nbsp;problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaperMC/Paper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月14日(星期六) 中午1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaperMC/Paper] chunk task prioritisation scheduling stall (#5980)





 
Use Spigot before Paper fixes it
 This is the only solution
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by electronicboy** [comment]
We've seen reports of this crash on spigot, looks like the mechanism for managing tickets is backing up or something but we've not been able to reproduce it, I'd imagine that as people see this less on spigot it's likely down to the speed improvements elsewhere causing a stall here as we often see with other parts of the server, there was some theories on it but nothing concrete and diagnosing this stuff when we can't really reproduce it is often *fun*

**Comment by h316098438** [comment]
I used spigot1.17, which did not have this problem, but started to appear after I migrated to Paper1.17.170, and now I am in a dilemma




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaperMC/Paper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月14日(星期六) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaperMC/Paper] chunk task prioritisation scheduling stall (#5980)





 
We've seen reports of this crash on spigot, looks like the mechanism for managing tickets is backing up or something but we've not been able to reproduce it, I'd imagine that as people see this less on spigot it's likely down to the speed improvements elsewhere causing a stall here as we often see with other parts of the server, there was some theories on it but nothing concrete and diagnosing this stuff when we can't really reproduce it is often fun
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by electronicboy** [comment]
Please actually read what I've said.

**Comment by h316098438** [comment]
never mind , I go back to spigot.&nbsp;MCBBS told me to go back to Spigot, and I'm here trying to find a solution. It's my fault




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaperMC/Paper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月14日(星期六) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaperMC/Paper] chunk task prioritisation scheduling stall (#5980)





 
We've seen reports of this crash on spigot, looks like the mechanism for managing tickets is backing up or something but we've not been able to reproduce it, I'd imagine that as people see this less on spigot it's likely down to the speed improvements elsewhere causing a stall here as we often see with other parts of the server, there was some theories on it but nothing concrete and diagnosing this stuff when we can't really reproduce it is often fun
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by electronicboy** [comment]
Can somebody reproduce this on the latest version of paper and provide a profiler sampling and watchdog reports, (if possible to reproduce on paper without any plugins, please try a non remapped jar, just because it aids with debugging given the proper mappings)


-------- 
Due to the response given while writing the above;

We're trying to work on a solution, we cannot however reproduce the issue in our own environment and the useless commentary just spams peoples emails for no reason, if you have something productive to add, please, provide info, but, we don't need the same set of information consistently rehashed in our inboxes. I've gone over this logic a few times and while not in the best health, I cannot see any changes here between 1.16 and 1.17 in terms of logic

**Comment by tildearrow** [comment]
> We've seen reports of this crash on spigot, looks like the mechanism for managing tickets is backing up or something but we've not been able to reproduce it, I'd imagine that as people see this less on spigot it's likely down to the speed improvements elsewhere causing a stall here as we often see with other parts of the server, there was some theories on it but nothing concrete and diagnosing this stuff when we can't really reproduce it is often _fun_

You are assuming that the bug is not on Paper, but on Spigot. However, nearly every thread dump that has been reported regarding this issue points to `setNeighborPriority`/`recalcNeighborPriority` which only exists on Paper. This is definitely a Paper bug.
Are you using an SSD (solid-state drive)? Try reproducing on an HDD (hard disk drive). Due to longer read times it may have a much higher chance of triggering the issue.
I have tried removing `patches/server/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch` and building Paper myself. After that the server does not hang anymore, even after flying at great speeds on new chunks and /rtp'ing.

**Comment by electronicboy** [comment]
I'm not making assumptions anywhere, I'm just saying that this seems to be wider of scope than people are assuming around the basis that this logic does not seem to have changed at all between 1.16 and 1.17, maybe there is a logical change elsewhere which we're missing, but, there are a lot of questions and especially as to why this is not a much wider issue

The logical paths here at the same between paper and spigot bar this extra branch of logic which creates a lot of naunces, if that patch is indeed causing it, which seems to be a high potential, that helps reduce the amount of work we need to look at, but the question here ofc is why is this an issue on 1.17 and not 1.16, is this just hitting people on weaker hardware and the "do stuff fast" here is hurting harder than before for some reason?

Theres a lot of stuff we need to look into here, I've not said that this is a spigot issue, I've said that we've seen similar reports on spigot, just rare, so heck, it's pretty justifiable that the system is crapping itself and racing in there is making it worse for some people

**Comment by h316098438** [comment]
My hardware configuration : AMD5900X，8G of memory，SSD，Only about 10 players。When spigot is used, the CPU usage is 50% and TPS is 20. Using paper takes up 40% of the CPU, but crash every few hours.I don't think my hardware is good enough

**Comment by h316098438** [comment]
> > 我们已经看到了关于 spigot 崩溃的报告，看起来管理票的机制正在备份或其他东西，但我们无法重现它，我想，随着人们在 spigot 上看到的更少，它可能归结为正如我们经常在服务器的其他部分看到的那样，其他地方的速度改进导致这里停顿，有一些理论，但没有具体的东西，当我们无法真正重现它时诊断这些东西通常_很有趣_
> 
> 您假设错误不在纸上，而是在 Spigot 上。然而，已经就这个问题点，报道几乎每一个线程转储`setNeighborPriority`/`recalcNeighborPriority`只存在于纸上。这绝对是一个纸虫。
> 您使用的是 SSD（固态硬盘）吗？尝试在 HDD（硬盘驱动器）上再现。由于读取时间较长，它可能有更高的机会触发该问题。
> 我尝试过`patches/server/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch`自己移除和构建 Paper。之后服务器不再挂起，即使在新块和 /rtp'ing 上以极快的速度飞行之后也是如此。

Do you have a solution, Can you teach me pls

**Comment by kirin-3** [comment]
Hello, so I have reported before on this issue but I am doing it again just because I might have some new info.

So, this is the error I get whenever my server is booting up:
[https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf)

Just so you know my server does not crash.
Plugins List: Plugins (70): AdvancedAchievements, AdvancedEnchantments, AdvancedRegionMarket, AngelChest, ArmShopBridge, AutoShulker, BeastWithdraw, BetterRTP, BetterShulkerBoxes*, BetterSleeping4, BettingGames, ChestSort, Citizens, ClearLag, CMI, CMIEInjector*, CMILib, CoreProtect, CubCustomDrops, DailyBonus, DiscordSRV, Disenchantments, DualWield*, dynmap, FarmControl, FastAsyncWorldEdit (WorldEdit), FluffyMachines, GCoreLegacy, GoldenCrates, GriefPrevention, GuiRedeemMCMMO*, HeadDatabase, HolographicDisplays, KillerMoney*, LimitPillagers, LuckPerms, mcMMO, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, MyPet, MyPetGUI*, NexEngine, OpenInv, PlaceholderAPI, PlayerVaults, ProtocolLib, Quests, QuestsGUI, QuickShop, SelectionVisualizer, ShopGUIPlus, ShopGUIPlus-SellGUI, Shopkeepers, SilkSpawners, SimpleMaterialGenerators, Slimefun, TAB, TimeIsMoney, UltimateTimber, UltraCustomizer, Vault, VeinMiner, ViaBackwards, ViaVersion, Vouchers, WorldBorder, WorldGuard, WorldGuardExtraFlags

Hardware Info: I'm using pebblehost with 2 dedicated CPU cores(Intel i9-9900K), 10 GB ram, and NVMe SSD.

I've tried running the same setup on my local machine both in a docker and out. Same error.
8 GB RAM(given to the server) and ryzen 3600 with sata SSD.

I've tried running the same setup with 0 plugins. Same error.
If I reset the maps and everything I don't get the error so...

Also yes this error only started showing up when I updated to 1.17 & Java 16.

**Comment by h316098438** [comment]
> 你好，所以我之前已经报告过这个问题，但我再次这样做只是因为我可能有一些新信息。
> 
> 所以，这是我的服务器启动时遇到的错误：[https](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf) :
> [//paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf)
> 
> 只是为了让您知道我的服务器不会崩溃。
> 插件列表： 插件 (70)：AdvancedAchievements、AdvancedEnchantments、AdvancedRegionMarket、AngelChest、ArmShopBridge、AutoShulker、BeastWithdraw、BetterRTP、BetterShulkerBoxes*、BetterSleeping4、BettingGames、ChestSort、Citizens、ClearLag、CMI、CMIEInjector*、CustomPropectus、CLibubs DiscordSRV、Disenchantments、DualWield*、dynmap、FarmControl、FastAsyncWorldEdit (WorldEdit)、FluffyMachines、GCoreLegacy、GoldenCrates、GriefPrevention、GuiRedeemMCMMO*、HeadDatabase、HolographicDisplays、KillerMoney*、LimitPillagers、LuckPerms、mcMMO、Multiverse-In门户、MyCommand、MyPet、MyPetGUI*、NexEngine、OpenInv、PlaceholderAPI、PlayerVaults、ProtocolLib、Quests、QuestsGUI、QuickShop、SelectionVisualizer、ShopGUIPlus、ShopGUIPlus-SellGUI、Shopkeepers、SilkSpawners、SimpleMaterialGenerators、Slimefun, TAB, TimeIsMoney, UltimateTimber, UltraCustomizer, Vault, VeinMiner, ViaBackwards, ViaVersion, Vouchers, WorldBorder, WorldGuard, WorldGuardExtraFlags
> 
> 硬件信息：我使用的是带有 2 个专用 CPU 内核（Intel i9-9900K）、10 GB 内存和 NVMe SSD 的 pebblehost。
> 
> 我试过在我的本地机器上的 docker 和 out 上运行相同的设置。同样的错误。
> 8 GB RAM 和带有 sata SSD 的 ryzen 3600。
> 
> 我试过用 0 个插件运行相同的设置。同样的错误。
> 如果我重置地图和所有内容，我就不会收到错误信息，所以...



> 你好，所以我之前已经报告过问题，但我再次损坏只是因为我可能有一些新信息。
> 
> 所以，这是我的服务器启动时[](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf)[遇到](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf)的错误：[https](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf) :
> [//paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf](https://paste.gg/p/anonymous/1f653e04a28f49e4a28e88a7f7c554cf)
> 
> 只是为了让你知道我的服务器不会崩溃。
> 插件列表： 插件 (70)：AdvancedAchievements、AdvancedEnchantments、AdvancedRegionMarket、AngelChest、ArmShopBridge、AutoShulker、BeastWithdraw、BetterRTP、BetterShulkerBoxes*、BetterSleeping4、BettingGames、ChestSort、Citizens、ClearSRUBIENCHI、Citizens、ClearSRUBIENC、 *、dynmap、FarmControl、FastAsyncWorldEdit (WorldEdit)、FluffyMachines、GCoreLegacy、GoldenCrates、GriefPrevention、GuiRedeemMCMMO*、HeadDatabase、HolographicDisplays、KillerMoney*、LimitPillagers、LuckPerms、mcMMO、MyOpen、MyOpen、Commandverse-EnginePet、 、PlaceholderAPI、PlayerVaults、ProtocolLib、Quests、QuestsGUI、QuickShop、SelectionVisualizer、ShopGUIPlus、ShopGUIPlus-SellGUI、Shopkeepers、SilkSpawners、SimpleMaterialGenerators、Slimefun、TAB、TimeIsMoney、Quests、QuestsGUI、QuickShop、SelectionVisualizer、ShopGUIPlus、ShopGUIPlus-SellGUI、Shopkeepers、SilkSpawners、SimpleMaterialGenerators、Slimefun、TAB、TimeIsMoney、UltimateTimber、UltraCustomizer、Vault、ViaBorders、ViaMinwards、VainMinwards、WorldGuard, WorldGuardExtraFlags
> 
> 硬件信息：我使用的是带有2个专用CPU内核（Intel i9-9900K）、10 GB内存和NVMe SSD的pebblehost。
> 
> 我试过在我的本地机器上的 docker 和out 上运行相同的设置。同样的错误。
> 8 GB RAM 和附带 sata SSD 的 ryzen 3600。
> 
> 我过用 0 个插件运行相同的设置。同样的错误。
> 如果我有地图和所有内容，我就不会收到错误信息，所以...

Me, too. It has to do with loading chunk

**Comment by electronicboy** [comment]
Reverted, we lost a ticket or something and I'm far too tired to work out where it went

**Comment by h316098438** [comment]
Problem solved?

**Comment by tildearrow** [comment]
> Problem solved?

You need to confirm that by yourself. Download the latest Paper (186 as of this moment) and test.
If the crashes no longer occur (or if they do), please tell us your results.

**Comment by h316098438** [comment]
There are still occasional errors, but they don't crash anymore. The error may be caused by my insufficient hardware。The latest fix is working




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaperMC/Paper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 凌晨3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaperMC/Paper] chunk task prioritisation scheduling stall (#5980)





  
Problem solved?
  
You need to confirm that by yourself. Download the latest Paper (186 as of this moment) and test.
 If the crashes no longer occur (or if they do), please tell us your results.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
