### ISSUE TITLE
Update Notifications

### ISSUE THREAD

**Issue by josephjthomas** [PaperMC/Paper#5986]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

I often face scenarios where people claim they are running the "latest" version of Paper but experience an issue with <insert issue here>. If you look over their `version` output you see something like 200 versions behind.
How does that happen? Honestly, I have no idea. The download API v2 makes it very easy (at least for me) to grab a rundown about changes from version x to y and update on a frequent base, similar look over the commits if you have GitHub open.
A feature like many plugins and other software have it nowadays would be an update checker that prints an extra line at console leaving a notification that you are x builds behind and newer builds are available.
Of course such a feature would need to be toggleable and allow you to customize how many builds you are allowed to be out of date before a notification is printed, ~~so people can turn it off and live on with their outdated versions~~ so we can fine tune notifications matching our demand.
I would happily like to see such a feature added.
Kind regards

### Describe alternatives you've considered.

None

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Chew** [comment]
I like the concept, but I don't think it will be beneficial.
Who would this benefit? There are really 2 types of server owners, those who neglect to update and overall to take care of their server and hence peeking at the console for notices, and those who actively want to make sure everything is up to date. 
Obviously, the first group is our target. However, as mentioned, they won't benefit from it. They would not care; they would not look at the console and realize how far behind they are. This spills over to your plugin example, even I don't update as often as I should, and I often find update checkers annoying since I usually do a clean sweep of every single plugin and Paper because a lot of plugins don't have a checker. And, because of how often Paper updates, just a simple restart would essentially guarantee a "you're behind!" message compared to plugins which usually don't update for weeks or months on end. Regardless, it's added to my sweep so being outdated is irrelevant since it's going to get updated.
Paper already tells you if you haven't updated in a while (although this is based on days, not versions), and that alone already has no effect (see your "200 versions behind" thing, wouldn't they spot that and know to update?)

**Comment by josephjthomas** [comment]
The example I chose wasn't really suitable. The people who ignore updates wont start to update if someone shoves them build notifications up their face, but that wasn't my goal either.
If people don't like update notifications, they can turn them off like I mentioned previously.
It's more a handy notification letting you know about you being x versions behind, rather than an annoying message pestering you to update.
