### ISSUE TITLE
[1.17] Exception loading entity, Villagers are missing

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#6037]
### Expected behavior

Entities should be loaded, no exception in the console

### Observed/Actual behavior

Since upgrading to 1.17 i get a lot of these exceptions in the console. Several players complained about missing villagers.

https://cpaste.de/kizinaqazu.sql

### Steps/models to reproduce

Updating a server with an existing world from 1.16.5 in 1.17?

### Plugin list

[18:20:05 INFO]: Plugins (40): AddEveryoneToScoreboardTeam, ArmorStandTools, BCalculator, BrokkoCommandLogger, BrokkoSecurity, BungeeNCPNotify, CityBuilder2, CubesideEssentials, CubesideNMSUtils, CubesideSecurity, CubesideSettings, CubesideStatistics, CubesideUtils, CubesideVoteManager, Essentials, FakePlotMe, ForceSpawn, GamesInWorlds, GlobalAutoMessage, GlobalChat, GlobalClient, GlobalPort, LogBlock, LuckPerms, LWC, MyHelpPages, NoCheatPlus, OpenInv, PlayerStatistics, PlayerUUIDCache, ProtocolLib, ResourcePackUtils, VanishNoPacket, Vault, ViaBackwards, ViaVersion, WESV, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

[18:18:54 INFO]: This server is running Paper version git-Paper-"ba7ffd0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: ba7ffd0)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by switchbadger** [comment]
I too am getting this same bug and have a village in the Nether. I'm too scared to go to the overworld now because on reloading my village chunks I lose so many mobs. Sheep, bees, cows, and villagers.

In addition to the error message of failing to load some entities, it seems that there is a "randomly move mobs around to simulate time while you were away" algorithm. This is sometimes placing villagers outside of the boundary walls I've built, and a few times placed them inside walls where they suffocate. (See server log printout below) This may need to be logged as a separate bug tho.

`[16:02:45] [Server thread/INFO]: Villager EntityVillager['Villager'/4074, uuid='f1c31e5b-fccc-44c5-9a2c-18058511b412', l='ServerLevel[NewNerdCraft_nether]', x=-53.79, y=28.56, z=-63.35, cpos=[-4, -4], tl=322031, v=true, rR=null] died, message: 'Villager suffocated in a wall'`

The above villager was inside of a 2x3x2 room with no doors and no way out. Part of an iron golem farm.

**Comment by fluidsonic** [comment]
I've also noticed this when adding Paper 1.17 71 to my server:
> [19:36:28] [Server thread/INFO]: Villager EntityVillager['Villager'/39493, uuid='a45ee243-cb20-43c5-beeb-fa3f19c945e4', l='ServerLevel[world]', x=28.22, y=66.00, z=-154.22, cpos=[1, -10], tl=24210, v=true, rR=null] died, message: 'Villager suffocated in a wall'

At the location of death there's a fence. Above that is a block of air. Above that is a block of leaves.
Villagers often get stuck there but as far as I can recall it doesn't cause a death in vanilla Minecraft. I've only seen the suffocation after installing Paper.

Here I look at the problematic block:
![2021-07-06_19 51 56](https://user-images.githubusercontent.com/85242/124652260-1dd01880-dec6-11eb-843d-37abbfa22df9.png)

**Comment by Marcelo-Petrucelli** [comment]
Well, I don't know if this is happening because of #6168 but I'm also experiencing the same problem. Actually villagers are not only vanishing, they are actually dying. Note: I'm also on 1.17.1, running paper-100

It seems to occur only when we enter the world (loading chunks. Also, it seems to happen when NPC is in a place where it has a translucent block on it's head, or nearby in the same high as their head. I'm using Vanilla Tweaks datapack that broadcasts a message every time a villager dies. 

If I spawn far, and go flying, it may not happen, but spawning near this place seems have a high chance of killing many of them. This may even happen using a nether portal, but I'm not sure yet about this.

This is our log when loading our world:
![image](https://user-images.githubusercontent.com/293596/125619620-363fed21-5472-4225-ab1d-40bcabaddedb.png)

This is the place:
![image](https://user-images.githubusercontent.com/293596/125619689-1c7cc889-af34-424b-a790-524be0eba53f.png)

I'm not using any plugin, nor any server-side mod or anything like that. Only some datapacks of Vanilla Tweak and client-side mods.

**Comment by Marcelo-Petrucelli** [comment]
Can anyone check if this is solved by #6241? 
I think all my villagers in this kind of situations already died =(

**Comment by electronicboy** [comment]
6241 is likely irrelevant, there is a other patch we need to restore to resolve this vanilla issue

**Comment by EMach** [comment]
Hi, I am running papermc #388, but I am still experiencing lost villagers every month or so.  Trying to resolve. My question, should I add "use-optimized-ticklist: false" to fix this problem?  Or should have #6241 have fixed it?

**Comment by Warriorrrr** [comment]
I haven't seen anyone else with this exception on recent versions, so this issue is likely already fixed by vanilla. Looking at the code, it seems like it'll now log a warning instead of throwing like it did before.

People who experience villagers suddenly suffocating should open a new issue if still replicable, as that isn't really related to the original issue reported here.
