### ISSUE TITLE
Terminal+process detached+disowned on /restart

### ISSUE THREAD

**Issue by James-E-A** [PaperMC/Paper#608]
# Incompatibility (Bug)

### What behaviour is expected:
When the server is restarting, the new process should remain attached to the same tty / stdin+stdout (terminal).
### What behaviour is observed:
Running `/restart` _seems_ to exit the server. Once the shutdown procedure is completed, the Java process exits, returning 0.

(The server is restarted in the "background", with no way to access its console.)
### Steps/models to reproduce:
* `$ java -jar PaperSpigot-1.11.2-b1056.jar`
* `>restart`
* You are returned to the terminal; Java has exited. `jobs` returns nothing.

### Plugin list:
* Multiverse-Portals v2.5-b725
* Multiverse-Core v2.5-b719
* PerWorldInventory v1.9.1
* PermissionsEx v1.23.4

### Paper build number:
> Paper version `git-Paper-1056` (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Restart functionality is provided by the Watchdog thread, ultimately this report belongs upstream as it is [implemented there](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0042-Watchdog-Thread.patch#50-51,56,60,71,74,78-79,92,99,101,104,111,119).

I will leave this ticket open so that other members of the development team can chime in with their thoughts if they are interested in looking into it.

**Comment by Shevchik** [comment]
Use screen, problem solved.

**Comment by prplz** [comment]
Possible solution: run the server in a bash loop and just stop it when you wish to restart

**Comment by aikar** [comment]
Yes you will need to use a wrapper script.

The issue is that it spins off as a new parent so that the current process can then shut itself down.
When the process closes, the parent is shifted to 1.
See this for more details: https://unix.stackexchange.com/questions/193902/change-the-parent-process-of-a-process

**Comment by James-E-A** [comment]
Java has no `exec` à la `{ba,}sh`?
	~James

**Comment by James-E-A** [comment]
Even if I use a wrapper script, that still leaves the issue of how to differentiate between `/stop` and `/restart`.

As of now, `/restart` is basically useless. :confused: And upstream [has stated that they will not ever fix `/restart` functionality on their end](https://hub.spigotmc.org/jira/secure/QuickSearch.jspa?searchString=restart).

**Comment by aikar** [comment]
@JamesTheAwesomeDude that is doable

make your file look like:
```bash
pid="$$"
echo "$pid" > current_pid
while true
do
    screen -dmS minecraft java {flags} -jar paper.jar
    sleep 5
    if [ "$pid" == "$(cat current_pid)" ]; then
        echo "Server crashed, restarting"
   else
        exit 0
   fi
done
```
