### ISSUE TITLE
TNT Dupers randomly activating their tnt when not in use

### ISSUE THREAD

**Issue by stromne** [PaperMC/Paper#6128]
### Expected behavior

when the tnt duper is not being push/pulled by a stick piston, the tnt should remain as a block and not be lit.

### Observed/Actual behavior

After reloading the chunk the dupers are in either through relog or leaving the chunk and coming back without the duper running (being push/pulled), the tnt will ignite and not leave behind the tnt block 
![image](https://user-images.githubusercontent.com/86529380/125011479-2a6f8080-e02e-11eb-8949-e3da6c40430d.png)

### Steps/models to reproduce

Setup up tnt dupers in an area without running them (pushing/pulling them).  Leave the area or the server and come back.  The tnt will randomly ignite.  Appears to happen more frequently when using nether portals to leave/reenter the area.

### Plugin list

ChatColor21.11, EsentialsX-2.18.2, OpenIv, UltimateSHops, Vault

### Paper version

90

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
This issue has already been reported but given the fact that it's an unsupported option and there are much more important things we need to find time to work on already, this is likely a won't fix
PRs are welcome, I guess, but, not really something we're invested in diagnosing

**Comment by Chew** [comment]
Additionally, "90" is not a valid version. Please click to copy or manually copy the ENTIRE `/version` output.

**Comment by stromne** [comment]
This server is running Paper version git-Paper-90 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bb44da8)
You are 1 version(s) behind
Previous version: git-Paper-79 (MC: 1.17)

**Comment by stromne** [comment]
![image](https://user-images.githubusercontent.com/86529380/125012139-4cb5ce00-e02f-11eb-899a-1067838d3f96.png)
Why is this being labeled as unsupported?

**Comment by electronicboy** [comment]
Please see the pinned issues on our tracker, we do not put effort into maintaining bugs

**Comment by stromne** [comment]
Where can I find that?

**Comment by MiniDigger** [comment]
https://github.com/PaperMC/Paper/issues/3854

**Comment by Eagllus** [comment]
As I mentioned in https://github.com/PaperMC/Paper/issues/6094#issuecomment-878165847 I believe this is bigger than just the TNT duplicator. 

As @Proximyst mentioned `It's more likely that the entity ticks before its chunk does, which might very well be possible as entities and chunks are loaded separately now.`

Since I describe two different cases, one where TNT explodes without reason and one where everything is fine.
It seems we have an inconsistency in how chunks and entities are loaded.

**Comment by jkoenigschulte** [comment]
I think its very mean how you guys just say: naah, we wont fix that. Many people are dependend on your optimizations, and it would be unfair not to fix that bug, since it cleary is a bug, even though it may not be an intended setting. I can assure you that you are loosing many customers if you continue treating your clients like this! This is also the reson why for example many big servers like Hermitcraft dont use your software. Please reconsider!

**Comment by Chew** [comment]
It may seem rude or mean to you, but in reality all we are doing is sticking to our project goal, which includes fixing exploits or other gameplay inconsistencies, regardless of if Mojang thinks any particular concept is one or not.

You speak to us as if we're a cooperation. Users of Paper are not our "customers," we're not trying to save every customer we can; we're not obligated to try and save them for profits, nor are we "disappointed" if a big "client" such as Hermitcraft opts to not use our software.

If people want our optimizations, they will look past the fact we're trying to make a game more stable and free of exploits and inconsistencies, perhaps at the cost of fixing some exploits. If you cannot do that, then by all means you are free to choose something else.

I understand your disappointment, and it's okay to be, but we're not going to bend over backwards to support this kinda stuff. It goes against what we are for. The people who want it are a minority.

**Comment by jkoenigschulte** [comment]
Hmm, okay, I get that! It seemed like the bug was fixed anyway since it was not only limited on tnt duping. Still, I think that also the minority is a part of your community, and we are still only talking about a toggleable setting which is off by default, so it would hurt nobody and only make affected people happy. 

The only thing that I am asking for now is, if after this article #6241 the bug has been fixed. Is that true?
