### ISSUE TITLE
Option to remove npc collisions, currently setting max collisions to -1 breaks pushing carts and more

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#614]
I have tried using max-entity-collisions: -1 (or 0) to completely remove collisions for all mobs, but it does disable being able to push carts on rails and other things as well. Could an option be added to remove all npc collisions without breaking pushing around carts?

**Comment by zachbr** [comment]
Not without special casing minecarts and whatever else is "and more" so we'd need to know specifically what other entities need to be able to be pushed.

**Comment by BillyGalbreath** [comment]
This already exists on a per-entity basis.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#setCollidable-boolean-

**Comment by hurrgurl** [comment]
Turning off entity collisions gives a huge performance boost, somewhat mandatory in 1.13 for any survival server.

Would it be possible to give collision to entities ONLY when player attempts to push them, otherwise disable entity collision all together? 

Any other means to achieve similar effect would be helpful to overall server performance.
