### ISSUE TITLE
Packet constructors

### ISSUE THREAD

**Issue by 56738** [PaperMC/Paper#6166]
### Is your feature request related to a problem?

Some packet classes (like ClientboundAddMobPacket) only have constructors which take Entity or FriendlyByteBuf objects. There is no clean and fast way to create instances of those classes.

### Describe the solution you'd like.

All-argument constructors for all packets.

### Describe alternatives you've considered.

* Creating and passing a fake Entity object
* Encoding and passing a FriendlyByteBuf which contains all fields
* Using Objenesis and reflection to create and edit instances

All of those approaches have a significant overhead compared to simply calling a constructor.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

This would be a quite large patch - maybe only add constructors for commonly used packets?

**Comment by kennytv** [comment]
That's a pretty bad solution for that, even for an internal patch, based on how volatile it would be and how many viable alternatives you already have.

**Comment by MiniDigger** [comment]
maybe this patch could be automatically applied tho kenny, reducing the complexity on our side

**Comment by yannicklamprecht** [comment]
Disclaimer: Just ignore the rest of the patch.

Could be done similar to these marked line: https://github.com/WeepingMC/Weeper/blob/main/patches/server/0004-packet-support.patch#L656-L844

Adds:

1. Additional constructors with "raw" data passing, so no object needs to be instantiated to get the actual required data.
2.  EntityDataAccessor constants are exposed to the public -> no need to define some by index and look into protocol wiki. Should be done by using Access Transformers, done with patches because of the lack of AT for forks at that time.

**Comment by yannicklamprecht** [comment]
> maybe this patch could be automatically applied tho kenny, reducing the complexity on our side

Do it like your mob goal key generation test.
For each packet get all attributes and generate a constructor using these attributes.

EDIT: TextBlocks should fit it.

**Comment by kennytv** [comment]
Automation should actually be *automated*, not "here's all the things you have to change". But all things considered, as long as there doesn't have to be manual work done and noone actually expects this to work even between minor versions, I'll reopen again for further discussion
