### ISSUE TITLE
PlayerTeleportEvent firing twice?

### ISSUE THREAD

**Issue by Linebeck** [PaperMC/Paper#6174]
### Expected behavior

I was expecting to be able to use .getFrom(); and get the from location on a single teleport.

### Observed/Actual behavior

Whenever I would use "player.teleport(location);", there would be an inconsistent amount of times where PlayerTeleportEvent would be called twice instead of once per teleport. 

For testing purposes I wanted to see what each "Cause" was for it to trigger twice. So I printed .getCause(), and found that the first teleport is always "PLUGIN", but the duplicate is "UNKNOWN". Also in console it would print a warning that the player moved too quickly. In order for me to get around PlayerTeleportEvent firing twice I had to check if the teleport was coming from the plugin or "UNKNOWN". 

### Steps/models to reproduce

Make a simple command to teleport you to a location (player.teleport(location);). Then print the values of ".getFrom() and .getTo()" from the PlayerTeleportEvent.

### Plugin list

BackPlugin

### Paper version

[21:12:42 INFO]: This server is running Paper version git-Paper-781 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-780 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Is there anything specific about the teleport? I can't replicate it with a simple teleport up 5 blocks. I only get the one event with a PLUGIN cause. Is it interdimensional? a larger distance?

BTW, I am testing on 1.16.5 build 781 (that one build shouldnt matter, but I thought I'd let you know)

**Comment by Linebeck** [comment]
Nothing really specific. Same world. Distance does not matter. I just have the one plugin installed. I am using .teleport(location); My console is spammed with "[username] moved too quickly!"

**Comment by richardwhateverr** [comment]
I got the same problem with my back command. I put on every tp the old location into a Map and sometimes the teleport triggers twice and my back location is at the same as I teleported to.

**Comment by Thatsmusic99** [comment]
You're probably better off just making sure the teleportation cause isn't UNKNOWN at this rate, given your intentions with the plugin, since UNKNOWN teleport causes don't mean their causes are unnecessarily unknown, but just not covered by the enum used to distinguish between what caused the teleportation in the first place. Major examples (seem to, this is just from taking a quick glimpse at the server code) include leaving your bed, when you start riding an entity such as a horse and simply after you join the game. Which, obviously, cannot work with plugins that implement a /back command.

You mentioned the `[username] moved too quickly!` warning too, which also triggers the PlayerTeleportEvent with the UNKNOWN cause. 

It's of course down to the Paper team on whether they want to work around this or not and avoid calling the event when this occurs, but in the code itself (class: `net.minecraft.server.network.ServerGamePacketListenerImpl`), it looks like it could very well be intended design. 

Footnote: not sure if it made any difference that I'm checking the 1.17 code since I just noticed that... whoops. 

Edit: It did, I haven't been able to reproduce the behaviour on 1.17.1. Whilst the warning message gets printed when teleporting more than 10 blocks in the same world, the teleport event does not get called.

**Comment by Machine-Maker** [comment]
I still wasn't able to replicate it using the method you provided, but like Thatsmusic99 said, there are a bunch of weird UNKNOWN teleport causes. Sometimes it seems the event even fires on player's joining the server (with the UNKNOWN) cause. So I would just filter those out of your /back command logic.
