### ISSUE TITLE
Illegal dimension on create Custom World

### ISSUE THREAD

**Issue by gameusefly** [PaperMC/Paper#6188]
### Expected behavior

That i can create an custom world with bukkits WorldCreator.

### Observed/Actual behavior

Any Custom World and an excpetion on my console

### Steps/models to reproduce

Creator an World with environment Custom with bukkits WorldCreator

### Plugin list

Multiverse Core, all others are my plugins

### Paper version

This server is running Paper version git-Paper-104 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 377a60d)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
logs? info?

**Comment by Doc94** [comment]
I dont know if is the same "bug"

When try load a world with datapack using custom generation spigot throws a IllegalStateException for the dimension type.. like this.
![image](https://user-images.githubusercontent.com/3602279/125801599-63693dd0-2249-4ff5-af20-bd7416032a85.png)
If this is the error then is a issue with CraftBukkit when load the world (because they dont have support for custom worlds)

**Comment by gameusefly** [comment]
I'm very sorry i forgot to post the log
![image](https://user-images.githubusercontent.com/77025397/125832665-e4b27df9-105f-47cf-b7c5-904c430c9ec2.png)

**Comment by Machine-Maker** [comment]
craftbukkit doesn't support custom worlds. the WorldCreator you are using has the environment `CUSTOM` which is still unsupported. For the moment, you have to use `NORMAL`, `NETHER`, or `THE_END`.

**Comment by gameusefly** [comment]
Thats Okay, i will change it. Thanks for the Information
