### ISSUE TITLE
Issue with anti xray and worldedit brush

### ISSUE THREAD

**Issue by mcmatthevan** [PaperMC/Paper#6215]
### Expected behavior

With worldedit, applying a brush with the command "/br sphere air 5" should make an empty sphere when right-clicking with the brush tool.

### Observed/Actual behavior

The empty sphere is created but it lets appear the anti-xray fake ores around, instead of the correct blocks.

(tested with anti-xray engine-mode : 2)

### Steps/models to reproduce

Using paper anti xray engine-mode 2,
With worldedit-bukkit-7.2.6, apply a brush on a wooden pickaxe using "/br sphere air 5".
Right clicking on the ground should show the issue.
[click here to see the picture](https://mcmatthevan.github.io/axrayissue.png)

### Plugin list

WorldEdit (tested alone)

### Paper version

[20:30:26 INFO]: This server is running Paper version git-Paper-110 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b1cdc12)
You are running the latest version
Previous version: git-Paper-104 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

The issue is solved when the server restarts

**Comment by e-im** [comment]
This is a known issue, and Duplicate of #5157. However that has been closed with no real resolution- and I'm not sure that a proper fix for this will ever be implemented due to the reasons outlined on that issue.

Beyond restarting the server, relogging, or moving far away and back will also make these go away. You can also give users of your server with worldedit permission the [`paper.antixray.bypass`](https://paper.readthedocs.io/en/latest/server/configuration.html#anti-xray) permission in order to mitigate the issue.
