### ISSUE TITLE
Dynamic Per Player Mob Spawn Limits

### ISSUE THREAD

**Issue by Tencryn** [PaperMC/Paper#6237]
### Is your feature request related to a problem?

This feature request is not related to a problem, but is a quality of life improvement for both players and owners of a server.

### Describe the solution you'd like.

`per-player-mob-spawns` is a great configuration option that allows an even distribution of mobs among players, but there's two scenarios which are undesirable. One is that your spawn limits are set so low that players don't experience much in the way of mobs unless they reduce the spawn ranges, and the other being too many mobs.

What I thought about was dynamic per player spawn limits (`dynamic-player-mob-spawn-limits`). This would utilize Bukkit's spawn limits as the server limit. These spawn limits would then be divided by the number of online players (can be done during player login / logout), and act as the per player mob cap.

For example, if my hostile spawn limit was set to 300, but I had 10 players online, each player would get 30 hostile mobs (300 / 10). If that same limit was applied with two players online, each player would get 150 (300 / 2). There are three scenarios where this may be undesirable which I'll outline below.

**1**. 300 hostile mobs surrounding the only player that's online is a bit too much and would be incredibly difficult for an unequipped player to survive. This could be mitigated by having a `max-per-player-mob-spawn-limits` option. If this was set to 70 for hostile, they will get a maximum of 70 hostile mobs even if they're the only player online and the server spawn limits was 300.

**2**. What if the spawn limits was 30 hostile, but there was more than 30 players? Probably round up to 1. This would be more than the server spawn limits but then where they spawn is just down to chance, We could also have a `min-per-player-mob-spawn-limits` option that would become the players minimum and bypass the server spawn limits. A similar scenario is when a player joins while the server spawn limits are maxed, they would get no spawns but in this scenario, during a spawn attempt, it would use the minimum per player mob spawn limits for that player specifically until mobs are reduced through despawning or death. This may be difficult to implement though, it seems complex to me.

**3**. As the spawn limits are dynamic, it may be that there are too many or too little mobs within the specified spawn ranges. You could try and find a sweet spot where there may still be too many or too little but it wouldn't be polar opposites. Another option would be to also add dynamic mob spawn ranges with a minimum and maximum. As the spawn limits per player fluctuate, so could the spawn ranges. This should be also be a setting that you can disable because varying spawn ranges would break mob farms.

Personally, I don't know if this feature is possible to implement without performance hits. The whole idea behind it is just to have better survival experiences without too little or too many naturally spawning entities. You can find the right balance for your server hardware.

### Describe alternatives you've considered.

There are no alternatives that I'm aware of that do this sort of thing. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
managing all of the maths for this and all of the configuration and desires for features for this type of stuff often turns into a plugin in its own right, the API already exists for plugins to modify these limits

I think that there is a MASSIVE misunderstanding around how per-player works in general,

per player just adds an extra set of checks ontop of vanilla spawn logic to prevent mobs being crowded around one person, it does NOT change the number of mobs in the server, it does NOT modify the way that the global limits already work. the representation in the bukkit config is somewhat mis-represented and misunderstood before we go making much more of a mess in how all of the logic works there.

rewriting the entire mob spawning algo to be truly per player is already on my wishlist, but, it's completely undesirable to further mess with the mob spawning logic which is already a massively misunderstood mechanism in the server to add something which would likely require the turnaround times and dev velocity of a smaller plugin rather than a feature in the server itself, this would allow people more control over configuration options. The options stated here are practically not viable sanely without further bastardization of the existing spawn logic or just rewriting an alternative algo like I already desire to do so.
