### ISSUE TITLE
Error in the math for the ticking time

### ISSUE THREAD

**Issue by Williambraecky** [PaperMC/Paper#624]
**I recently discovered that the math used for ticking is incorrect.
Since this patch: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0020-Further-improve-server-tick-loop.patch paper has not been ticking every 50ms (if the server could actually make it in time) but 100ms then 0ms constantly.**

# Incompatibility (Bug)

### What behaviour is expected:
___spigot's normal ticking: http://prntscr.com/ei2o4n___
### What behaviour is observed:
___paperspigot ticking: http://prntscr.com/ei2onz___
### Steps/models to reproduce:
___Code used to test this: https://hastebin.com/awetuyarin.cpp___

### Plugin list:
___Test plugin containing code available above___

### Paper build number:
___git-Paper-1062 (MC: 1.11.2)___

Sorry if this issue report is incomplete, never done anything like this before.

**Comment by prplz** [comment]
~~What OS is your test server running?~~
Ok strike that i looked at the screenshots. Can you reproduce on linux? I believe this to be a bug with the sleep accuracy on windows

**Comment by Williambraecky** [comment]
Also works on linux, I mean also happens on linux*

**Comment by chickeneer** [comment]
Just looking at the maths. Looks like the issue is that we are not grabbing the new time after waiting on the Thread. I am a bit confused why the following line of code is there. 
if (catchupTime < 2E6) {
    wait += Math.abs(catchupTime);
}
It doesn't make any sense, I cannot think of a single good reason to throw the sign (positive/negative) away.

Below is my suggested fix (untested) with both aspects changed. Not sure which issue is causing the described behavior. Both are troubling from an analytical viewpoint.

https://gist.github.com/chickeneer/13b7521a3a65b6db0f2b73faf1c54d39/revisions?diff=unified

**Comment by aikar** [comment]
I am confused why I did the Math.abs, but that code for the 2E6 is to stop doing super tiny sleeps that are smaller than the inaccuracy window of sleeping to begin with.

The goal was that if we needed to sleep for say .1ms, we would skip the sleep, and let the earliness of our next tick be rolled into the delay of the next tick.

So if the tick is so close, that small delay rolls into the next ticks sleep, so if it comes up as 40ms needed, it becomes 40.01ms to sleep. so that the tick rate is consistent in the long run and we avoid the miniscule sleeps that are likely to be inaccurate anyways.

**Comment by aikar** [comment]
oh right, that code was trying to say "if were negative, add the overflow catch up to the wait"

that handles the cases of UNDER sleeping. Ie, we intended to sleep for 40, but server woke up at 39, we are now 1ms ahead.

This should cause catch up time to hit -1ms, which that < 2E6 was intended to account for negative and TINY amounts of under sleeping.

so say you have a tiny amount of under sleeping, and the next tick takes EXACTLY 49.999~ms, the <2E6 avoids sleeping for a miniscule amount and rolls it into the next sleep to make up for it.

**Comment by chickeneer** [comment]
I still think we need to update the current Time after waiting. 

But I think a better way to accomplish what you are describing would be to replace "if (wait > 0) {".
Just replace the zero with whatever that threshold value we think it is okay to go ahead and run the tick early. While still doing the calculations to aim for the actual time (0). Would want to implement that change in both places. (both the catchup calculations and the actual thread wait block). Probably just make it a constant field value.
That way we are always holding onto the precise values of time, but when the tick runs has a bit of flexibility in short but accurate in the long run.

**Comment by aikar** [comment]
@chickeneer  found the issue, it's now fixed in build 1063.
