### ISSUE TITLE
Furnace bug with MCMMO,issue with paper side

### ISSUE THREAD

**Issue by NightLife-SG** [PaperMC/Paper#6271]
### Expected behavior

When right clicking on furnace the GUI close automatically,when putting item in the item will loss.
Sometime when clicking too fast it also dupe the item out

https://github.com/mcMMO-Dev/mcMMO/issues/4583#issue-951806615 <---- this issue.

### Observed/Actual behavior

GUI closes when opening furnace,smoker when shift right clicking
Issue was fix in spigot and other fork

### Steps/models to reproduce

with mcmmo install right clicking furnace

### Plugin list

Mcmmo

### Paper version

1.17.1 lastest build

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
>1.17.1 lastest build

no. give us the output of `/version`

**Comment by NightLife-SG** [comment]
his server is running Paper version git-Paper-130 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2f1f1b7)

**Comment by JMCY26** [comment]
I've just switched to version 130 of paper and I've immediately had players saying furnaces are eating up their items they put in on shift click.

[Sun, 25. Jul 2021 18:45:15 GMT+01:00 INFO] Checking version, please wait...
[Sun, 25. Jul 2021 18:45:15 GMT+01:00 INFO] This server is running Paper version git-Paper-130 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2f1f1b7)
You are running the latest version
Previous version: git-Paper-123 (MC: 1.17.1)

**Comment by gecko10000** [comment]
Can confirm, reported this [here](https://github.com/PaperMC/Paper/pull/6245#issuecomment-886161013).

**Comment by DerFrZocker** [comment]
TLTR: Paper didn't apply the upstream comment correctly, your provided test code won't work on Spigot and Paper.

To hopefully bring some light to the issue.
The comment made for around 6 days on CraftBukkit / Spigot ([8d244b0b7e3](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8d244b0b7e35596b160452c1aa7ec4fc21de4d50)) contained a flaw. When a block is updated with the same type the tile entity would get removed but not re-set, this is because of Minecraft not setting a new tile entity in nms Chunk#setType(...) when the old and new block are from the same type. This causes that the block now didn't have a tile entity and therefore not an inventory. This causes the issue with the chest not being filled.

For two days a comment was made ([aa69d1cfb99](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/aa69d1cfb99f4784ed19b8918a7f5c1780b55fdb)) to fix this. Paper promptly updated but apparently didn't do it right, looking at the decompile code of Paper-130 it is still as before.
```
        if (this.getNMS().isTileEntity()) {
            if (this.world instanceof net.minecraft.world.level.World) {
                ((net.minecraft.world.level.World)this.world).removeTileEntity(this.position);
            }
            else {
                this.world.setTypeAndData(this.position, Blocks.a.getBlockData(), 0);
            }
        }
```

As with the provided test code, it won't work either on Spigot or on Paper. This is because `#getInventory()` returns the live inventory not the snapshot inventory by updating the block state you override the inventory you have set the items with the old empty one.
As to why your plugin did work again on Spigot is because in your actual plugin you call the update method before setting the items not afterwards (this makes a huge difference).
It worked again on Paper after removing the updated call because the chest has a valid tile entity since you set the block now only once and not twice.

**Comment by e-im** [comment]
Fixed in build 131.
