### ISSUE TITLE
Entity ID based wireless redstone doesn't work.

### ISSUE THREAD

**Issue by AvallonAB** [PaperMC/Paper#6277]
### Expected behavior

Wireless redstone device by 2no2name should work after activating transmitter.

### Observed/Actual behavior

Wireless redstone device doesn't work at all.

### Steps/models to reproduce

[WirelessReceiver20gt_hr-twzxs6FM.zip](https://github.com/PaperMC/Paper/files/6881328/WirelessReceiver20gt_hr-twzxs6FM.zip)
This is the wireless redstone device made by 2no2name. When started it doesn't work properly. It is important to note that it needs transmitter. The device and the transmitter are shown in this video. https://www.youtube.com/watch?v=hr-twzxs6FM

### Plugin list

ArmorStandTools, BanMenager*, BuyCraftX, Multiverse-Inventories, Multiverse-NetherPortals, CleanroomGenerator, Multiverse-Core, PersmissionsEx*, PlotSquared, Prism, ProtocolLib, VanishNoPacket, VoxelSniper*, WorldEdit, WorldGuard.

### Paper version

This server is running Paper version git-Paper-"5126bb3a5" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Paper-"0e420049c" (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

### Other

This video explains in detail how ID based wireless redstone work. https://www.youtube.com/watch?v=FLynwXDnETI

**Comment by NoahvdAa** [comment]
The wireless redstone breaking seems to be caused by these two patches: [(0012-Entity-Activation-Range.patch) (Spigot)](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0012-Entity-Activation-Range.patch?until=eac3cd963927641565f43f09f7a127cfeaa3447f&untilPath=CraftBukkit-Patches%2F0012-Entity-Activation-Range.patch#518) and [0359-Fix-items-not-falling-correctly.patch (Paper)](https://github.com/PaperMC/Paper/blob/321dd1d655f988f7c7764fd8e6c4fc026c2e7a9e/patches/server/0359-Fix-items-not-falling-correctly.patch). The Paper patch removes the item id offset for skipping every fourth tick, because Spigot implemented practically the same thing with their entity activation range patch. I'm able to get the wireless redstone machine to work, but only after removing the Paper patch and lines 386-388 from the Spigot patch.
