### ISSUE TITLE
[Suggestion] Optimize for stacked boat and minecart

### ISSUE THREAD

**Issue by HuJK** [PaperMC/Paper#6281]
### Is your feature request related to a problem?

We usually use stacked boat as elytra launcher, and use 24 minecart as mob grinder. 
But it cause huge lag on server.

We just need the acceleration and the suffocation damage. 
But it performs a lot of useless calculation on the server.

Elytra launcher:
https://www.youtube.com/watch?v=FQWF0HxxBEU

"Stack" means this(A lot of boat/minecart squashed in small space):
![image](https://user-images.githubusercontent.com/15907444/127228945-fb626b1b-92d4-41af-8616-bc0a5332c835.png)

**Not** this:
![image](https://user-images.githubusercontent.com/15907444/127228231-36b16d73-878a-4d8d-82b6-c3752c89918c.png)

### Describe the solution you'd like.

Is it a good idea to merge them into one entity in server, but keep it’s function?

The merged boat can accelerate entities that touching it to high speed based on how many boats it stacked, the merged minecart can cause suffocation damage to entities in it.

### Describe alternatives you've considered.

Find a plugin can do that? I didn't find yet...
Or just ban users who made this machine.

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by CDFN** [comment]
In my opinion that's not optimization but change of game behavior. Entity is entity, merging them is no-go for me.

**Comment by electronicboy** [comment]
The entire functionaily of this relies on the fact that they don't merge, merging them and retaining that behavior would be a great set of modifications in order to simulate this behavior, making cramming apply to carts is maybe something to consider, I already have a bit of code in a private plugin for a server to "suffocate" carts to reduce the performance impact of people doing this stuff, but, the nature of making the server "stack" entities which are not stackable in any form of sense outside of what plugins do, and having a bunch of behavioral changes to imitate the behavior that this causes is far out of scope imho

**Comment by Strahilchu** [comment]
The only other reason I've seen that many carts stacked is for a lag machine so I would definitely like an option for something that reduces this lag, currently I have them limited per-chunk with MobFarmManager but that prevents having more than 24 or so in a chunk. Ideally that limit could be removed while not compromising server performance at the same time. Good idea! I hope we can figure out an efficient way to add this in
