### ISSUE TITLE
View Distance API dont work

### ISSUE THREAD

**Issue by MrBretze** [PaperMC/Paper#630]
# Description of issue:
I use the player view distance API for a command to set the view distance for player 
Command in: https://gitlab.com/MrBretzel/KOTG/blob/master/src/main/java/fr/bretzel/kotg/command/CommandViewDistance.java

### Plugin list:
PermissionsEx, dynmap, WorldEdit, Essentials, VoxelSniper, BetterBrushes, MassiveCore, WorkdGuard, Factions, Dynmap-Faction, KOTG

### Other helpful links
Source code of KOTG plugin (my plugin): https://github.com/MrBretze/KOTG 

### Paper build number:
Paper version: git-Paper-1063

### Crash, Stacktrace
No crash

**Comment by zachbr** [comment]
Doesn't work when you set the view distance down? Or doesn't work when you increase the view distance?

When you set the view distance for a player down, the client will not unload those chunks locally, but the server still does. Only way to get the client to realize that is for the player to keep exploring or to force the client to refresh using the F3 menu.

**Comment by MrBretze** [comment]
Does not work correctly with any number, i tested to refresh using the F3 and its the same

**Comment by MrBretze** [comment]
Do you want to need this in my server ?

**Comment by zachbr** [comment]
No, it needs to be tested independently of your server to confirm it.

**Comment by connection-lost** [comment]
This is probably related to #539

I have recently noticed the issue has becoming significantly worse. In addition to #539, currently the bug is much more likely to happen even we are not trying to trigger it. Here is a chunk picture that indicates the chunk loading:
![p](http://i.imgur.com/WOiFhSP.png)
black - not loaded, white - loaded, red little dot = 1 chunk

This chunk visualization is about 4 minutes after I start my server. The server starts with 6 view distance and decrease by 1 every 1 minute until it reaches 3 (min value).

Full version of that previous picture: (please enlarge to view it)
![a](http://i.imgur.com/x8SMQTw.png)

**Comment by connection-lost** [comment]
Currently I am looking for a way to force unload those unnecessary chunks, since a high view-distance is a critical part in my server... Chunk#unload(boolean save, boolean safe) is not safe but I'll still try...?

**Comment by MrBretze** [comment]
Command links update to https://gitlab.com/MrBretzel/KOTG/blob/master/src/main/java/fr/bretzel/kotg/command/CommandViewDistance.java

**Comment by zachbr** [comment]
The only time I have ever been able to reproduce this is with negative values, and I just fixed that.
If you can still reproduce this after that change, and can provide some way to reproduce this, please let us know.
