### ISSUE TITLE
AuctionMaster and CrazyEnchantments

### ISSUE THREAD

**Issue by joaoespanhol** [PaperMC/Paper#6364]
### Expected behavior

plugin start no have error.

### Observed/Actual behavior

the server gives an error when connecting the plugins, so the plugin does not work.

### Steps/models to reproduce

https://mclo.gs/6DcB055

Install plugin folder plugins.
start server

### Plugin list

AuctionMaster and CrazyEnchantments: last version

### Paper version

paper-1.16.5-785.jar

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
AuctionMaster failed to load as you didn't have some script system available, the typical javascript engine is no longer bundled with java, the plugin would need to deal with this

CrazyEnchantments failed due to some error which likely induces that something else installed on the server improperly bundling some of the SilkSpawners classes

**Comment by joaoespanhol** [comment]
New error:
LOG: https://mclo.gs/TDuqCzN
Plugin: AuctionMaster
