### ISSUE TITLE
Suggestion: Deprecate / Refactor EntityRemoveFromWorldEvent

### ISSUE THREAD

**Issue by jaylawl** [PaperMC/Paper#6373]
### Is your feature request related to a problem?

The name of the event is misleading because it is firing both when:

1. An entity gets unloaded and is stored in the game's data until the chunk gets loaded again and thus will be respawned
2. An entity actually gets removed, be it by using the API call `entity.remove()` or just due to naturally despawning by nature of not being a persistent entity

This means either `EntityRemoveFromWorldEvent` or the method `entity.remove()` is mis-named.

### Describe the solution you'd like.

Deprecate `EntityRemoveFromWorldEvent` and introduce a new event called something more appropriate; maybe `EntityUnloadEvent`.

In the new event, a boolean could be call- and set-able along the lines of `EntityUnloadEvent#remove(boolean)` - controlling whether the entity will just despawn as opposed to being actually removed.

This would the code for the new event needs to hook somewhere else in the NMS code, because just calling `entity.remove()` in the current `EntityRemoveFromWorldEvent` causes a recursive server crash (as i have just experienced a few minutes ago).

### Describe alternatives you've considered.

I don't know i'm not that smart

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by lynxplay** [comment]
In my opinion, this event still makes sense. It is triggered when an Entity is removed from the world's tracker/ticklist and hence is no longer actively ticked by the world. Whether this was due to a chunk unloading the entity or the entity dying due to natural causes or API calls doesn't really make a difference there. 

If you want to differentiate between an entity being unloaded and an entity dying, you can check [Entity#isDead](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Entity.html#isDead()) on the entity that is being unloaded, as that will return true for entities that are unloaded due to death (e.g. [Entity#remove](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Entity.html#remove())).

Furthermore an event for the loading/unloading of entities from chunks is/has been (it seems rather stale rn 😕) in the works in a PR to upstream (found [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/pull-requests/637/overview)).

**Comment by Machine-Maker** [comment]
(see lynxplay's comment)
