### ISSUE TITLE
Server randomly crashing

### ISSUE THREAD

**Issue by IceString3** [PaperMC/Paper#644]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**

# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/eU3pQXcD

### Plugin list:
CoreProtect, BungeeSuiteWarps_1.9, antiraildupe, Skript, OpenInv, AntiAdvertiser, SkQuery, ConsoleSpamFix, SilkSpawners, ProtocolLib, Skellett, Hibernate, AAC, SkinsRestorer, skRayFall, FastAsyncWorldEdit, Reloader, MundoSK, BlocksHub, PermissionsEx, SafeArmorStands, MobSpawnLimiter, MelonDamageLib, Vault, ProtocolSupport, BungeeTabListPlus, EnjinMinecraftPlugin, WorldEdit, AuthMe, AntiCommandTab, TuSKe, LiteBans, SkStuff, DiscordSRV, AuthMeBridge, VoteLink, LimitedCreative, MyHome, GriefPrevention
### Actions to reproduce (if known):
Crashes appear to happen randomly

### Paper build number:
This server is running Paper version git-Paper-1076 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
based upon the crash, your issue is likely caused by a bad plugin that is modifying the EntityTracker in an asynchronous manner

**Comment by AlfieC** [comment]
I would disagree - the plugin is likely hiding or showing players asynchronously or something similar - I highly doubt any plugin has any use poking around the tracker.

**Comment by electronicboy** [comment]
Which is something that would trigger a modification of the EntityTracker, direct or indirect, something is likely triggering a modification of the tracker in a async manner...

I generally say that it's a bad manner to suggest particular actions that a plugin could take beyond the direct output as it only causes additional confusion towards people reporting issues.

especially when their likely response to a direct reply of "stupid plugin doing stupid shit" vs, "it's likely a plugin doing x async", (especially in cases where their reported plugin list is full of plugins known to break the server in various ways), you'll likely end up just with a reply of "I don't have any plugins doing that".

All of the methods that hide/show player would call that would trigger a CME appear to be captured by the async catcher, you'd also be surprised to see that some popular plugins do poke around the tracker and have been known to cause issues, e.g. MythicMobs as a popular example does this, wether that be direct or indirect of plugins interfacing with MM.

**Comment by Phreag** [comment]
I also got this Problem yesterday. It occured after i updated Paper itself, AAC and one of my selfmade-Plugins.

Maybe it can be an issue of AAC.
I Will post this there...

**Comment by agsosa** [comment]
I have the same error/crash. It happens when a player uses /home (or any teleport command) to an unloaded chunk with itemframes containing items with fake enchants or custom item meta.

Using latest paperspigot 1.8.8 build

Plugins:

Plugins (88): AAC (3.1.2), ActionBarAPI (1.5.2), AnimatedNames (5.16.0), AntiAura (10.88), AntiExpDropOnSpawnerPublico (1.0), ArenaFFA (1.0), BarAPI (3.5), BattleLevels (8.0), BedrockFix (1.0), BossShopPro (1.6.5), BuycraftX (10.2), ChatControl (5.4.3), ChestCommands (3.1.4), Citizens (2.0.16-SNAPSHOT (build 1267)), ClanTags (2.0), ClearLag (2.9.3), CoinFlipper (1.82), CombatTagPlus (1.2.3), ConsoleSpamFix (1.3.0), CrazyEnvoy (1.2.5), Detecciones (1.0), EndPortalRedirection (1.0), EndRandomTP (1.0), Essentials (TeamCity), EssentialsGUI (1.0.2), EssentialsProtect (TeamCity), EssentialsSpawn (TeamCity), ExtrasSK (1.1), FarmLimiter (1.2), FastAsyncWorldEdit (17.03.30-5c6a5c4-607-11.8.1), FBasics (2.1.8), FeatherBoard (3.17.2), GangsPlus (2.1.8), HeadDatabase (2.3.3), HolographicDisplays (2.2.5), InfoBook (2.2), InstantDamagePotNerf (1.0), ItemSlotMachine (1.3.3), Jefes (1.0), KeepItems (1.3.2), KillerMoney (3.4), KoTH (1.4.7), KothEventManager (1.0), LeaderHeads (2.8.0), LiteBans (2.1.23), MasterCrafter_Misiones (1.0), MergedMob (8.9.0), MinecraftMarket (2.1.5), MinePacks (1.16.6), Multiverse-Core (2.5.0-SNAPSHOT-b725), MythicLib (0.0.1-SNAPSHOT), MythicMobs (2.5.11), NoCheatPlus (3.15.0-SNAPSHOT-sMD5NET-b1075), NoPortalTraps (1.0), OX_EVENT (1.0), PayEvery30Minutes (1.0), PermissionsEx (1.23.4), PlaceholderAPI (2.6.0), PlayerPoints (2.1.5-SNAPSHOT), PlayerShops (1.1.2), PlugMan (2.1.1), PreciousStones (10.5.3), PreciousStonesAllowedBugFix (1.0), ProtocolLib (4.2.0), RandMan (2.5-SNAPSHOT-CUSTOM), RuletaMasterCrafter (1.0), SharpSK (1.6.0), ShopGUIPlus (1.6.0), SilkSpawners (3.8-SNAPSHOT-b397), SilkSpawnersPlayerPointsAddon (1.0), Skellett (1.6.9), SkinsRestorer (12.9.7), SkMorkaz (0.21), SkQuery (3.21.4), skRayFall (1.9.5), Skript (2.2-Fixes-V8), SQLibrary (7.1), SuperVanish (5.9.1), TitleAPI (1.7.4), TitleWelcomeMessage (4.0.0), TradeMe (5.0.0.3), Vault (1.5.6-b49), ViaVersion (1.0.4), VillagerFight (0.1), VIPSlots (1.0), WorldBorder (1.8.6), WorldEdit (6.1.3;7a097ca), WorldGuard (6.1.3-SNAPSHOT;c904242)

* The custom plugins are not the problem.

**Comment by electronicboy** [comment]
the nature of these types of crashes are pretty much always down to stupid plugins doing stupid stuff, your issue is likely a separate issue caused by whatever plugin you're using with the stuff you're specifying as causing the crash (e.g. the fake enchants)
