### ISSUE TITLE
Offline mode ban by UUID issues

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#645]
If on offline mode, then banned a player, he can still join in, because UUID is not right.

Version: latest version of PaperSpigot.

( This problem is very much like the problem of Whitelist's UUID. #79 )\

2017-04-01 18:24:06: If I manually modify the UUID for the correct, I will can not unban him...

**Comment by sgdc3** [comment]
1.8.8 is no longer supported, the problem have been fixed since 1.10

**Comment by ghost** [comment]
@sgdc3 I'm very sorry but I use 1.11.2-paperclip-1078...

**Comment by ghost** [comment]
@sgdc3 Hey you know me! I'm AuthMe!!! ( The man who consciously deleted his account...... ) ... I often change account......

**Comment by sgdc3** [comment]
Hey, how are you? ;) Sorry, PaperSpigot changed name after 1.8, not it's just Paper. It's strange, i never had such problem after the fix. Do you use bungeecord? If yes you have to set online-mode-bungee in paper.yml to false and delete the current ban list.

**Comment by ghost** [comment]
I'm sorry but I only using Paper ...

**Comment by electronicboy** [comment]
I tested this a few days ago but never had time to reply, so long as the users name is in the usercache (e.g. they've actually joined the server and there haven't been enough players to remove them from the cache), it works fine. you're using offline mode, so there is literally nothing stopping a player changing their name, which will cause them to have a new UUID anyways.

This could be fixed by making the usercache not look up the UUIDs of players when in offline mode without bungeecord, problem is that such a change would potentially break existing servers in certain edge cases...

**Comment by zachbr** [comment]
I don't see anyone messing with this. It seems prone to break existing behavior.

Given that banning players by UUID is next to useless on an offline mode server anyway, you should probably be banning by IP address.
