### ISSUE TITLE
Cancelling EntityDeathEvent makes item held by foxes disappear

### ISSUE THREAD

**Issue by NoahvdAa** [PaperMC/Paper#6477]
### Expected behavior

When cancelling the EntityDeathEvent for a fox, the item it's carrying should stay in its mouth.

### Observed/Actual behavior

When cancelling the EntityDeathEvent for a fox, the item it's carrying magically disappears.

### Steps/models to reproduce

1. Make a plugin that listens to the EntityDeathEvent and cancels it.
2. Kill a fox holding an item.
3. Observe. The item will have magically vanished.

### Plugin list

N/A

### Paper version

This server is running Paper version git-Paper-209 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 98fa136)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
After investigating further: it seems like this affects all entities wearing or holding something. For example, killing a zombie wearing armor (and cancelling the event) causes the armor to disappear

**Comment by lynxplay** [comment]
Yes, this issue is caused as `LivingEntity#dropCustomDeathLoot` is called prior to the entity death event in the `LivingEntity#dropAllDeathLoot(DamageSource)` method.

The item seems to disappear because the item is "supposedly" dropped in `Entity#spawnAtLocation(ItemStack, float)` while in reality it is added to the `drops` list (which is ignored as the event is cancelled).

**Comment by Machine-Maker** [comment]
At least from just one test with a zombie with a diamond chestplate that was given to it, and cancelling the EntityDeathEvent for it, it retained armor with #5740. This fixes another issue, but looks to fix this one as well, or at least part of it.

**Comment by lynxplay** [comment]
Tested a bit further, the fox issue was also fixed by your PR.
Zombies with swords also work fine on your PR.
Makes sense concerning that your PR prevents the clearing of the equipment slots.

Do you think it is safe to link this issue to the PR?

**Comment by Machine-Maker** [comment]
The items are still "wiped" later in the CraftEventFactory event method to prevent leaks. That's why there's that weird `Runnable` thing to run advancement triggers before the items are wiped. Since every item in a slot would be added to the drop list, and there aren't any clones in there, those itemstacks are still cleared, just a bit later.

Yeah, can go ahead and link that PR to this I think.
