### ISSUE TITLE
Unable to delete the world folder after unloading

### ISSUE THREAD

**Issue by Abcik** [PaperMC/Paper#6498]
### Expected behavior

I expected the method Bukkit#unloadWorld will completely unload the world and all cache it using, and I will be able to delete this world folder without any problem.

### Observed/Actual behavior

When you delete a folder of the additional world (after unloading this world), this folder is only partially deleted. The folders "entities" and "poi" which contain ".mca" files is remain.
They cannot be removed even manually(when server is running).
I also noticed that the ".mca" files disappear on their own some time later(about 2 hours).

If u create a new world with same name **before** ".mca" files will be removed, this will give a huge(5000 lines) crash in the console "Failed to read chunk [**x**, **z**]", "java.nio.file.AccessDeniedException: world2\entities\r.-1.0.mca".

### Steps/models to reproduce

A quick demonstration of the problem  - [here](https://youtu.be/5R4WQqB6Pk8)

1. Create an additional world. And teleport into it. (_Im using Bukkit WorldCreator_)
2. Summon any entity and wait for world-saving. (_or use /save-all command_)
3. Come back into main world.
4. Unload the additional world. (_im using Bukkit.unloadWorld("worldname", false);_)
5. Using any method, delete the folder with the additional world and all the files it contains.
6. Done. See that the folder is not completely deleted. It contains the "entities" folder, which contains ".mca" files.
7. Now, when creating and load a new world with the same name, you will get a huge error in the console.

### Plugin list

Does not matter. For demonstration, I only used **multiverse-core**.

### Paper version

This server is running Paper version git-Paper-219 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0a6d320)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

OS: Windows 10. (Everything is fine on Linux)
There is no such problem in 1.12.2. I tested 1.16.x and 1.17.x - there is a problem here.

**Comment by MiniDigger** [comment]
what OS? I would be this is a dum windows issue of not correctly freeing up the file references or smth.
I remember years ago, when I was working on stuff like this, it never worked locally but worked flawlessly on the deployed servers, cause they use linux...
edit: saw the video, its windows, do you have access to a server to try to repo on linux?

**Comment by Abcik** [comment]
> what OS? I would be this is a dum windows issue of not correctly freeing up the file references or smth.
> I remember years ago, when I was working on stuff like this, it never worked locally but worked flawlessly on the deployed servers, cause they use linux...
> edit: saw the video, its windows, do you have access to a server to try to repo on linux?

Yes you are right! On linux there is no this problem...
But I don't know whether this is good or bad, because it turns out that the bukkit still contains deleted files? Will there be memory leaks because of this? (Hundreds of world deletions are expected in 2 hours)

**Comment by MiniDigger** [comment]
I remember past me trying to track this down and failing, not sure I wanna go down that rabbit hole again.
I don't expect there to me memory leaks caused by this (somebody would have noticed in profilers by now), as long as no plugin is keeping references to entities or locations or whatever of unloaded worlds.
am also pretty sure this isn't a new phenomenon but always has been the case with bukkits world management on windows, not a recent regression.
if somebody wants to do a deep dive into file handling on the jvm/windows, be my guest, but since >90% of servers use linux and most likely the rest are just local dev servers, I would argue its not really worth spending time on.
what I always did is using javas deleteOnExit method, ontop of the delete, so it will be cleaned up eventually.

**Comment by electronicboy** [comment]
Does running a manual GC between unload and delete help? There is one thing I saw which offered a level of concern but some logic after that made it look potentially fine; all of the workers, etc, are flushed before unloading, so, my only guess here is that maybe some windows specific JVM quirk, as mini is leading to, but, it's not like mojangs data flow is complex and never really was designed to cater towards worlds unloading mid tick, and it's not something we're gonna butcher their hell of a system for

Windows is not an environment we generally care to put much effort towards outside of critical issues, and niche cases like this are not really deemed as a critical aspect as flows like this are generally not expected, generally, always create new folders for this stuff rather than trying to re-use the existing one, etc

**Comment by Abcik** [comment]
> Does running a manual GC between unload and delete help? There is one thing I saw which offered a level of concern but some logic after that made it look potentially fine; all of the workers, etc, are flushed before unloading, so, my only guess here is that maybe some windows specific JVM quirk, as mini is leading to, but, it's not like mojangs data flow is complex and never really was designed to cater towards worlds unloading mid tick, and it's not something we're gonna butcher their hell of a system for
> 
> Windows is not an environment we generally care to put much effort towards outside of critical issues, and niche cases like this are not really deemed as a critical aspect as flows like this are generally not expected, generally, always create new folders for this stuff rather than trying to re-use the existing one, etc

No, manual GC does not help.
When I wrote about this problem I didn't think the OS mattered. I do development on windows, and I test everything there. And it seemed to me that this is a task that is not so difficult to solve, but if this is not so, then I am ready to put up with it. Also, I cannot create folders with different names, since firstly this will constantly leave empty folders behind itself, and secondly, the folder name is the player's nickname.

**Comment by electronicboy** [comment]
Oh, wow, I missed some of the logic, so, upstream doesn't close the World when unloading them, their fix for this works as it explicitly calls to close the entity manager but doesn't actually close the level itself
