### ISSUE TITLE
Blocks being randomly restored

### ISSUE THREAD

**Issue by HyplexMC** [PaperMC/Paper#6560]
### Expected behavior

When you break blocks they stay broken...

### Observed/Actual behavior

I've had multiple players contact me and say that parts of things they have mined have been reversed, for example this one guy is digging a hole to bedrock and parts of his hole he had dug have re-appeared and when i check it with coreprotects inspect feature it says it was broke x time ago yet the blocks are still there. I've also had another person say part of there mine was regened and when i went and looked in spectator like a small chunk of the mine was restored which makes me think this cant be like a saving issue. If you have any thoughts do let me know thanks :)

### Steps/models to reproduce

not able to reproduce as this has only happened a few times and its completely random, having a hard time finding what could be causing the problem so cant attempt to recreate.

### Plugin list

Plugins (24): BlockQuest, Citizens, CMI, CMILib, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat, HeadDatabase, ItemJoin, LiveKit, Multiverse-Core, Multiverse-Inventories, PlaceholderAPI, Plan, ProtocolLib, RawMsg, SkQuery, Skript, UltraCustomizer, UltraPermissions, UltraPunishments, UltraRegions, Vault, WorldEdit

### Paper version

This server is running Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983)
You are running the latest version
Previous version: git-Paper-243 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
This was an issue that would have existed in builds 232-236 after the Tuinity merge, however at this point it should have been fixed. Are you still experiencing this now on the current version you are using?

**Comment by HyplexMC** [comment]
Ok so i just got a response from the players and the one who had mined part of a mountain off has told me that he mined it on 9/3/21 and on that date the server was running on build 243, and he noticed the blocks regened the following day. The server had only had 1 restart from the time of mine and the time of noticing the regen, and the server was still on build 243 on that following day 9/4/21. I've told them to keep a close eye out and if they see this happen again to notify me ASAP.

**Comment by HyplexMC** [comment]
Also ive checked and our server updated to build 236 on the day it was released (9/1/21)

**Comment by HyplexMC** [comment]
Hello this is still a major issue and needs to be looked at and addressed, i am at a total of 6 reports of peoples things being reverted.

**Comment by electronicboy** [comment]
version? do you have any means to reproduce it consistently? you are shutting down the server properly and it's not crashing, etc? Not heard of any reports of this in a little while

**Comment by HyplexMC** [comment]
i am on the latest version, my server auto updates to the latest version on restart. My server does daily restarts and hasn't crashed or been killed in months. I don't know how yall expect me to reproduce something that happens randomly cause its only happened to a few people not everyone.

I just get reports of people saying i did blank the other day and now that blank is gone and i check with core protect to see if blocks where edited and well an behold they did do blank and the blank is now missing/reverted  as if it never happened. I've contacted CoreProtect (first ones i contacted) and they stated that this couldn't be a issue with their plugin. 

This server is running Paper version git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)
You are running the latest version
Previous version: git-Paper-255 (MC: 1.17.1)

Plugins (24): BlockQuest, Citizens, CMI, CMILib, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat, HeadDatabase, ItemJoin, LiveKit, Multiverse-Core, Multiverse-Inventories, PlaceholderAPI, Plan, ProtocolLib, RawMsg, SkQuery, Skript, UltraCustomizer, UltraPermissions, UltraPunishments, UltraRegions, Vault, WorldEdit

Here is my latest log:
[2021-09-10-6.log](https://github.com/PaperMC/Paper/files/7147277/2021-09-10-6.log)

**Comment by HyplexMC** [comment]
I've got another report this is starting to get annoying and needs to be fixed or address ASAP. Yesterday i was editing a room and replacing lights in the floor with the new light block and i logged on today to see that half of the room was reverted back, also to note its not chunks based cause somethings in the chunk stay the same and other things in the chunk reverted. Here is a screenshot of the room
![2021-09-11_12 34 07](https://user-images.githubusercontent.com/66493095/132956554-7e212a4b-ccc8-4db1-b2cc-f2a1fb19a269.png)

I cant keep my server running knowing that my players things are of risk of being reverted. THIS NEEDS TO BE ADRESSED

Here are some of my latest logs:
[latest (3).log](https://github.com/PaperMC/Paper/files/7148267/latest.3.log)
[2021-09-11-3.log](https://github.com/PaperMC/Paper/files/7148268/2021-09-11-3.log)
[2021-09-11-2.log](https://github.com/PaperMC/Paper/files/7148270/2021-09-11-2.log)
[2021-09-11-1.log](https://github.com/PaperMC/Paper/files/7148271/2021-09-11-1.log)
[2021-09-10-6 (1).log](https://github.com/PaperMC/Paper/files/7148272/2021-09-10-6.1.log)
[2021-09-10-5.log](https://github.com/PaperMC/Paper/files/7148273/2021-09-10-5.log)
[2021-09-10-4.log](https://github.com/PaperMC/Paper/files/7148274/2021-09-10-4.log)

**Comment by PatiTati** [comment]
Same Problem since about 2 weeks on my Server. It happens on restart of Server with /stop and startup script. Chunks are randomly regenerated and all progress since the last 2-3 Hours are gone. See Screenshots (here was an entire farm placed), Entitys like Minecard are stay after reboot. Something must be wrong with the world saving or reading.

**Stopping Server with /stop Command**
https://pastebin.com/EceGjuAk

**Starting Server with Startup Script and Aikar Flags**
https://pastebin.com/RH616UN5

Plugins (15): CoreProtect, FarmControl, Harbor, HeadDatabase, InventoryRollbackPlus, LiveKit, LuckPerms, PlaceholderAPI, ProtocolLib, RHEasyCrops, ServerlistMOTD*, TAB, UltimateAutoRestart, WorldEdit, WorldGuard

This server is running Paper version git-Paper-325 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4a0d935)
You are running the latest version
Previous version: git-Paper-323 (MC: 1.17.1)

![2021-10-10_16 56 57](https://user-images.githubusercontent.com/71453983/136702544-760c5fcb-a244-41ed-8236-379b3662626b.png)

![2021-10-10_17 01 05](https://user-images.githubusercontent.com/71453983/136702552-c25fa560-f59c-44c2-9a81-5797b43c21b5.png)

**Comment by orang3i** [comment]
i had this problems a few times not in 1.18 but in 1.16.5

**Comment by aurorasmiles** [comment]
Looking at your logs, you both seem to have the datapack armor statues v2.8.1.zip, maybe that is the issue.
Anyway, since no one else reported anything similar and your logs don't really have any indication that points towards Paper, I'll be closing this for now. If this still happens with a current version please open a new issue.
