### ISSUE TITLE
Players can increase their player save file size above current max, making it impossible to join

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#671]
It is possible for players to (accidentally and intentionally) make their player save file too big, which kicks them from the server and makes it impossible to join. They will get this error message: 

http://i.imgur.com/A9u94eA.png

This is done by having too many shulker boxes with too many maxed out books inside them, inside either inventory or endchest. Having them in inventory causes the error message in picture above to happen instantly as the player connects.

paper 1090

can provide uuid.dats affected by this if needed

**Comment by 0-x-2-2** [comment]
this has nothing todo with paper this is a minecraft client bug with netty and has been already reported to mojang months ago

**Comment by aikar** [comment]
This isn't really a bug.
The client and server need reasonable safeguards on data size expectations to prevent loading huge nbt structures and causing lag pauses.

The issue here is that Mojang did not consider that Shulker Boxes can create a scenario where a single inventory has a ton of data, then multiple shulker boxes..

They really should of done something like limiting you to 1 per inventory or something.

But ultimately -- this isn't fixable outside of limiting a players gameplay to avoid them ever creating this scenario, and that kind of logic does not belong on the server.

**Comment by aikar** [comment]
Feel free to check JIRA for this being reported to Mojang, and file if not, but ultimately there is no clean solution here.

Servers can't control the client's limits, and we can't try to re-engineer how inventories are handled to the client.
