### ISSUE TITLE
Disable Player Collisions Not Working

### ISSUE THREAD

**Issue by MuddledGuy** [PaperMC/Paper#672]
paper.yml setting enable-player-collisions: false does not disable player collisions.

Have tried a few plugins to "fix" the issue, however it does not get fixed.

Not 100% sure how Paper works, however there is a scoreboard team called "NoCollide" with every player on the server in it. I set the collide option for that team to "never" and players still push eachother.

[21:27:53 INFO]: This server is running Paper version git-Paper-1090 (MC: 1.11.2
) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
That NoCollide team isn't Paper's.

To stop collisions the scoreboard must be used, and each player added to a team. In Paper, we add players that don't have a team to our default team which is named "collideRule_XYZ". Then all teams are forced to send the disable data on a packet level.

Because the system uses scoreboard teams though, it can be tempermental. For example, bungeecord won't forward teams that have the same name across multiple servers, which is why I said "collideRule_XYZ" above, because that XYZ is a string of random gibberish. It's also easy for plugins to interfere. There's not a ton we can do about either of these factors however, because of the way Mojang has written this on the client.

What I can tell you, is that it's working just fine for me locally, leading me to believe you have a plugin conflicting with our system somewhere. If you have any improvements you think you can make to the code, I'd be happy to look into your suggestions, but we are extremely limited by how this is handled on the client.

**Comment by MuddledGuy** [comment]
Is there a known list of plugins that do not work?

If not, I will unload every plugin and re-enable one by one. I will be able to test later today.

**Comment by mikroskeem** [comment]
Pretty much any scoreboard-related plugin causes issues with Paper no collide feature.

**Comment by MuddledGuy** [comment]
Only scoreboard I'm using is Featherboard.

**Comment by electronicboy** [comment]
as already noted by Z and mikroskeem, any plugin that creates or uses scoreboard in order to show information, e.g. scoreboards, tab lists, info above a players head, or even uses scoreboards/teams for functionality will cause that to not work, as it's only the internal team that is created with the flag.

It's up to plugin authors to modify their scoreboard support, in order to add the ability to specify whether or not to enable or disable collisions.

Might also be worthwhile to try a few more plugins to disable collisions as some handle this in different ways which work better for different plugins, I don't have time to look into this precisely right now, however; What we would need to happen for a more forceful fix of this, is to hook into team creation and ensure that the relevant info is set and sent to the client.

The question would be, can we implement this nicely, while ensuring that we don't break clients or plugins/servers by modifying the default behavior.

**Comment by MuddledGuy** [comment]
I do know there are "patches" that come with plugins that modify the paper/spigot jar. I haven't looked into these as from the sounds of it, it could be causing problems with plugins/clients.

I will close this issue for now and look into it some more and do some testing. This is a feature I would like added, possibly an option to force it, even though it may break things.

Thanks for the help, if I find anything new I will test and report.

**Comment by sgdc3** [comment]
Keep this issue open, as a reminder

**Comment by aikar** [comment]
@sgdc3 thats not how issue trackers work. Issues are open if they are fixable either by us or upstream.

This has to be fixed by a plugin, as the plugin is what's breaking the system.

Ultimately, it appears a plugin is either modifying the packet after we modify it and unsetting the flag, OR the plugin is sending raw custom packets that we can't intercept.
