### ISSUE TITLE
[Question] Snapshot builds of Paper for 1.12

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#673]
Spigot doesn't allow users to use there snapshot builds only for the offical release however bukkit used to release snapshot builds and i would like to use a snapshot build to test if my plugins need updating or not.

**Comment by Fonzee9** [comment]
Its also useful to give devs errors for 1.12 so they can fix it for the offical release

**Comment by zachbr** [comment]
Paper takes the Spigot source code and applies changes on top of it. Because Spigot does not release the source code of their snapshot builds, we cannot simply make a Paper build for snapshots.

In order to do so, we'd have to update CraftBukkit, Spigot, and finally Paper ourselves, duplicating effort and possibly introducing bugs (or fixes) that wouldn't exist in Spigot's official builds.

We simply don't have the manpower or the interest as of now in doing so.

It's also worth noting that Bukkit _has never_ released a snapshot build so Spigot isn't really breaking with any traditions here.
