### ISSUE TITLE
TPS loss since build 1064

### ISSUE THREAD

**Issue by mpivchev** [PaperMC/Paper#676]
I am not really sure what the problem is, but I am getting major TPS loss with b1064 onwards. It starts with 20 tps and then gradually goes down and usually stays at ~19.64 tps, with random spikes which lower it to around 15-16 tps, and then goes up.

I went ahead and removed all plugins and worlds, with a newly created default world, and the issue still persisted. I also reset all bukkit, paper and spigot configs but it did not help.

Any idea why this is happening?

**Comment by zachbr** [comment]
Timings reports would be helpful.

**Comment by mpivchev** [comment]
This is with all current plugins and b1064
https://timings.aikar.co/?id=9f2a92c7d7e04f759848e172adb70de8

**Comment by zachbr** [comment]
If b1064 doesn't lag than we don't need timings reports from it. Give us ones from the latest build.

**Comment by mpivchev** [comment]
b1064 (included) and onwards
I'm also going to post timings from the latest build in a few mins

**Comment by mpivchev** [comment]
Timings from latest build
https://timings.aikar.co/?id=cfbfb777a0ff40319edfb4be231f5f54

**Comment by zachbr** [comment]
We'll need timings from a period of active lag, that sample shows very little TPS loss and only for a short time. So we have no way to know if that's even related or what is responsible.

You're probably gonna have to run latest, tolerate some lag for a few hours, and then send us a new report.

**Comment by mpivchev** [comment]
Will do

**Comment by electronicboy** [comment]
To be honest, looking between the two sets of timings, beyond the initial TPS loss (which is likely a marginal artifact of what was being flagged up as a single tick in your timings for 1064), there is no actual difference, TPS is practically the same across the board beyond a slither which is somewhat dismissible overall (it's such a small difference to consider), GC is the only real noticible difference between the two in which it looks like it's potentially heading for over 2x the amount of collections... (which, with GCs behavior being somewhat unpredictible, along with your overall java flags potentially pushing what is also a somewhat weak GC system for the job, likely overall doesn't help)

https://mcflags.emc.gs/ < I recommend referring to that, a fair chunk of your java flags are useless, having been defaults for a fair while, while some of them are overall just outdated advice as well as bad (e.g. specifying levels for features such as SSE which are generally more than capable of selecting the right level for your CPU)

**Comment by mpivchev** [comment]
The server is hosted by BeastNode, so I don't have any access to custom flags.

**Comment by electronicboy** [comment]
In that case, your host is using bad flags that they've likely half-assed copied from some random website, likely not helping much in your performance.

Overall from the samples you've provided, I personally see no issues in them, it mostly just looks like you've misread the actual information in the timings and red-flagged at a reading that isn't really much of an issue and was actually reflected in your 1064 timings, however it was displayed differently in the UI due to changes to timings since then (note that timings flags Citizens in your first timings report and display it as part of the lag timings, however, doesn't do so in the second)

**Comment by mpivchev** [comment]
So the reason for the TPS loss and spikes is the bad flags? I will contact BN and see what I can do. I might have to stay with b1063 for the time being though (which works perfectly).

**Comment by electronicboy** [comment]
As I've said, between the two timings, they're both showing the exact same information within the expected tolerance, while the second set of timings may be displaying a TPS loss, there is no real difference between what is occurring in both 1064 and the latest build, it's just being presented differently towards you due to the updates that have occurred since 1064 and now.

if you look beyond the orange bar at the beginning (which, once again; the lag imposed by that is also seen in both sets of results, just presented differently due to changes), click the "all" view to display the actual timings result and not a snapshot of lag events, you'll notice that there is very little difference between the two, within the margin of performance deviation that you'd expect especially on a machine which you can't really see exactly what is going on due to others also using it.

**Comment by mpivchev** [comment]
In any case, here's a 10 hour timings report as you've requested https://timings.aikar.co/?id=c60761fd97f14e758240d48c52a2fe02

**Comment by electronicboy** [comment]
Your timings are overall showing no issues at all beyond a few plugins having lag spikes. I really don't see anything of concern on there, maybe other than HeadDatabase and HolographicDisplays having very few ticks where they actually caused an issue with lag.

**Comment by mpivchev** [comment]
Then the issue really must be something in the custom flags or Paper itself, since as I said above, I experience TPS loss with no plugins and just with the default world. Anything below 1064 works just fine.

**Comment by electronicboy** [comment]
Your original set of timings for 1064 showed issues within the small sample you provided (albeit, the sample was literally only running for ~10-15 minutes meaning it really provides hardly any information), with plugins. Your last set of timings shows trivial issues, which are with plugins, not with Paper itself.

Timings itself was modified in order to try and catch information more accurately, which is likely why you're seeing a discrepancy between both versions of paper.

I cannot see any issues imposed by Paper or minecraft itself, any lag you've had has been at the hand of plugins running on the server and nothing to do with the server itself. (and once again, timings is reporting that there have been hardly any issues where you've actually seen cases of a tick taking too long)

**Comment by jordanwilliams1** [comment]
Uh.. Not sure if coincidence or not a but i was happily sitting at 110 players and 18-20tps.. Now I'm struggling at 70... Here's my timings:
https://timings.aikar.co/?id=40725571713947ed8b4b0ecc6a6ea874

**Comment by aikar** [comment]
@jordanwilliams1 it appears you modified my flags and using less than 10G of memory.

please reset the G1Min and G1MaxNew sizes back to what I posted in https://mcflags.emc.gs

**Comment by aikar** [comment]
Note that 19.6 is not "TPS loss". It will never show "20" consistently. It's just how it works. 20 is the rounded up number.

Your timings show that everything is going great.

It only shows the head plugin is triggering network request to load the skin which is causing occasional spikes, but general runtime is great.

Anything GC related will also potentially cause spikes, which you would need to switch flags to solve, but you said you can't.

Ultimately, that 10 hour report confirms there is no performance problem in paper itself, and anything you are seeing with version numbers is purely placebo effect.
