### ISSUE TITLE
Disable or reduce Moved too quickly and Moved wrongly spam

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#677]
Would it be possible to add an option to disable these messages or reduce them? No matter what number I set either of those options to, I get insane spam in the console from it. I've had log files grow into nearly a gigabyte because of how much it's spammed.

Am I missing something, how is everyone dealing with this?

**Comment by electronicboy** [comment]
Those messages are triggered from players moving in a manner that the server isn't sure is actually legit; This generally falls down to plugins, bad performance (e.g. TPS drops) or players with hacked clients.

**Comment by ghost** [comment]
I know.

**Comment by electronicboy** [comment]
The part you're missing, is that people look into those 3 different potential issues and fix them.

It seems highly counterproductive for Paper to add a system to disable messages that are telling you that something is wrong, especially when the server has to take a set of actions that may actually impede the playability to players causing issues such as lagging back.

**Comment by ghost** [comment]
Because there is no lag, it's at solid 20.0* TPS, there is a relaxed anti cheat plugin. This happens for very few players and not everyone and there are no complaints from anyone about lag or rubberbanding. Those very few players it happens for just happen to spam the console so much it's unusable.

I don't see how an option to disable it for people that don't need it hurts

**Comment by electronicboy** [comment]
Because it's a message that is there for a reason, that only fires when the server takes an action to limit a players movement due to them making an invalid movement that could potentially crash the server. It's counterproductive to have a patch on the server in order to disable a message that indicates that a player is doing something that the server is having to take an action against in order to potentially keep your server running.

You're more than welcome to add such an option to your own server, or use a plugin/log4j configuration to filter the logs for such a message, however adding an option to disable warning messages of issues you should fix is counterproductive to server owners who should be fixing their servers to prevent the message from firing in the first place, as well as just creates another patch that needs to be maintained with no actual benefit to server owners most likely at the expense of us when we get hit with issues by people who are experiencing such cases, however aren't actually knowing it because they've disabled the messages.

**Comment by aikar** [comment]
we don't need to add a flag for something that only 1 person would likely use.

These messages do not "hurt".

If you want to get rid of them, you can configure the logger to ignore them.

There are plugins that can do this for you:
https://dev.bukkit.org/projects/consolefilter
https://dev.bukkit.org/projects/logfilter

**Comment by reverofevil** [comment]
@zetglob

![](http://i.imgur.com/c4jt321.png)

**Comment by suresttexas00** [comment]
`triggered from players moving in a manner that the server isn't sure is actually legit; ` @electronicboy I get these messages all the time when ever I execute a valid "tp \<player\> x, y, z".  Why doesn't the server know that the movement is from a command __it__ executed??

```
[18:13:38] [Server thread/INFO]: Teleported SurestTexas00 to 65.5, 69.0, -267.5
[18:13:38] [Server thread/WARN]: SurestTexas00 moved wrongly!
```

**Comment by electronicboy** [comment]
That's generally down to the player moving while being teleported and other various fun aspects of teleportation

**Comment by suresttexas00** [comment]
I TP myself from console (so I know my player client is not moving).. so Again; sounds like a bug.  This happens on my vanilla server - and I know this is probably the wrong place for it, but you guys were the only ones coming close to dealing with the issue at any level.

**Comment by aikar** [comment]
@suresttexas00 please report the concern to mojang. We are not in a position to rewrite that code.

If the log messages concern you, I linked some plugins that can filter the logs for you.

You can also just run a custom Log4J config thats configured to filter them too.

**Comment by suresttexas00** [comment]
Yea, sorry to barge in.  I really hate dealing with their (mojangs) bug report process.  Thanks!

**Comment by CosmicCatnap** [comment]
PaperMC: Lets make a custom minecraft server that offers something spigot and vanilla can't

User: Can you just turn off this annoying log message that we all know the meaning of and has been the pain point of log management on every minecraft server I have ever ran and by itself would give me a solid reason to use paperMC instead?

PaperMC: no, now go away and never speak of this again. 

To say that you can't fix how you wrap logging speaks volumes about either your initiative or the fragility of your implementation...

Seriously, my first thought after reading this was "This must be uncharacteristic of them, they must have been off that day or something" but no, I go to look for other related posts and very consistently you seem to find gray area where you can say "That is minecrafts fault" or "Its the fault of your plugins" or often times "we don't care, and if you do this again you are banned" without context but here is a **_perfect_** example of something your platform would be perfect for implementing, something that isn't even minecraft, it could be scripted easily and painlessly without a single line of java and something I was on the edge of my seat head over heels gitty to click on, something that was going to make me switch to this tonight...alas instead I will spend it writing my own wrapper to fix the logs, let me know if you want to pull it in, shouldn't take me more than a few hours -_-

**Comment by electronicboy** [comment]
That "annoying log message" indicates a potential state which can cause servers to crash, it would be highly counterproductive of us to remove logging messages which can lead us to these issues. it's easy to remove these messages, but at the same point, it makes the burden on us much harder when people start bringing logs to us with critical warnings like these disabled. You're more than welcome to filter out such messages, just do not expect support when you impede our ability to read what is going on in the server.

**Comment by CosmicCatnap** [comment]
Its amazing how you didn't read or care about anything we said.

I am an admin of minecraft servers and have been for far longer than this project, my use case is and has always been that I don't care if my server catches fire I just don't want to be bugged to rotate logs for things I already know.

Ghost was asking for a flag, an OPTIONAL flag for people like me of which there are many and who understand the ramifications of such a flag ENTIRELY. I agree it should be default on everywhere for most people...but not all and not overwelmingly all either.

At the moment plenty of people in my server are using ice blocks to boat long distances which is 100% valid and my server never skips a beat but what it does do is LOG THIS ALL DAY.

Its a valid need for a valid use case. If you don't want to fix it because you have something else to do or don't want to then so be it but don't tell me I don't understand why I want it or that my want isn't justified because you don't like the concept.

**Comment by Spottedleaf** [comment]
were there not solutions linked prior in this thread?

**Comment by electronicboy** [comment]
1) We've read what you're saying, however;

2) You never stated that there was a valid case in which the server starts printing these messages, just ranted about how we're refusing to disable messages which let us point out issues in peoples logs; Given that this is also a mojang message, have you filed an issue on mojangs issue tracker? It's now on our radar, however given my current health and other things I need to deal with on this project when I can, it's not exactly high priority.

3) as a public project, we're not going to start adding options to disable logging for things which allow us to help others when they ask for support, Yes; *you* might understand what that message means and might be able to say that in the current state, it's harmless; However, as a project, we do not want people blindly disabling things which only makes our life harder, existing solutions to filter those messages from the logs have already been provided, we do not, however, have the intent to provide a method to disable the logging of messages whose exclusion from the logs could make debugging server crashes/performance issues harder.

> that my want isn't justified because you don't like the concept.

As a project, we consider that the disabling of such messages is not justified given the implications, if you wanna disagree with us there, you're more than welcome to, this is an open source project and we even have tooling designed to make it easier for people to modify the software and maintain their changes ontop of paper. You're also more than welcome to submit a PR to attempt to fix the printing of these messages in *valid* cases, if vanilla lets you legally travel faster than one of vanillas checks, that should be addressed

**Comment by Cryptite** [comment]
> I am an admin of minecraft servers and have been for far longer than this project, my use case is and has always been that I don't care if my server catches fire I just don't want to be bugged to rotate logs for things I already know.

If you have been an admin of servers for longer than the existence of Paper, then you should have technical prowess to remove this unwanted log from your server on your own. This is not a debug that means "things are going just fine on the server".

Considering it's a common result of ice-boating, then that problem exists with Mojang. Because Paper has the _capability_ to exclude such things from the log doesn't mean it's required to. Paper is open-source for a reason, and those wishing to remove this log statement have been given a number of ways to handle it.

It is the experience of not only Paper-devs, but those of us who participate heavily in paper-dev support that people **will** turn off things "that annoy them", only for them to come back later and complain about things happening on the server that are a **direct result** of them turning off things they really shouldn't.

This fits under a problem with Minecraft, and not something Paper "should fix for me just because they can".

**Comment by aikar** [comment]
https://www.spigotmc.org/resources/consolefilter.38208/
We don't need this feature because a plugin can solve this, and plugins to do this already exists.

**Comment by JaegerDanger** [comment]
I know it's been a while since anyone commented on this, my apologies for all the notifications to the prior commenters.

Hi, sorry to be a pain but I recently discovered that a hacked client called liquid-bounce has found a use for the "player moved wrongly!" or "player moved too quickly!", it can exploit it so much over a small period of time that it crashes / lags the entire server massively, I'm not sure if the message spam is the cause of the crash or the invisible movements of the player. I have checked it against anticheats too and none of the ones I checked kick you fast enough / kick you at all.

The server is running 8gb ram and isn't overloaded in any shape way or form.

-Thought someone might be interested in this new information.

Cheers.

Please correct me if I am incorrect about anything or don't understand fully how this works


https://gyazo.com/cb7af626425059efb4765dfa3b635de5

https://gyazo.com/f12b6cc96b111be7286068414631f1df

**Comment by swim709** [comment]
I'd like to add that, similar to what others have said previously, I get this in my console logs CONSTANTLY, even when I am closely monitoring the TPS and it's steady 20. Most frequently it pops up when users are taking boats across ice highways. Funny enough I don't think I've ever seen it happening when we actually did have TPS drops.
Additionally we have some plugins that give users items to make them move faster, but even without those like I mentioned it's happening most frequently with vanilla behavior (boats on ice).

**Comment by Mastacate** [comment]
Did those Devs ever fix this stupid LOGGING of un-natural movement. Man paper is about as dumb as it gets. They add these amazing feature like *LOGGING* or /back... but they fail to realize that when players use minecraft mechanics as intended the damn file gets filled up with stupid logs of dumb stuff we dont care about. Its not hurting thousands of people so why the HECK did you ever add this stupid LOGGING feature to begin with. We DO NOT USE IT. IT IS SPAMMING OUR COMPUTERS FULL OF CRAP LOGS. Like many of the other profesionals have stated here but the Paper Devs are rude as FCK as always. Im sick of these NERDS bald headed idiots. STOP GETTING MAD AT EVERY FUCKING QUESTION OR REQUEST AND START LISTENING YOU FUCKING RETARDS.

**Comment by electronicboy** [comment]
We didn't add the log message, you are also welcome to disable the thing using log filtering. no need for the slurs or the attacks.

**Comment by wcdfilll** [comment]
Finally, there's the log filter, does it completely turn off that feature? It's funny, you guys use the excuse to blame, someone said "we can't rewrite that code". That's what we need to hear, and that's the real reason we ultimately want to know
