### ISSUE TITLE
#.getBasePotionData() called inside of a BrewEvent doesn't return the correct information

### ISSUE THREAD

**Issue by GavvyDizzle** [PaperMC/Paper#6828]
### Expected behavior

If you brew a water bottle into an akward potion you should receive an awkward potion from the method call #.getBasePotionData().getType().

### Observed/Actual behavior

Instead, you receive the information from the potion before it was converted, in this case the method call returns water.

### Steps/models to reproduce

Create a new BrewEvent
Check the value of the 3 potion output slots
Brew a potion in game and check the information of those items

### Plugin and Datapack List

Only the test plugin

### Paper version

This server is running Paper version git-Paper-351 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c66adfb)
You are running the latest version

### Other

If you create a delayed task inside of the BrewEvent listener the method will return the expected potion type. The delay of this task can even be 0.

**Comment by lynxplay** [comment]
This, at least by how spigot/bukkit defines this event is expected behaviour and not a bug. The event is called before any processing on the items inside the brewing stand is executed and hence the inventory you can access in your listener will contain the items prior to the actual brewing.

Changing this behaviour now is rather impossible without breaking compatibility with spigot and there is definitely merritt in knowing the state of the brewing stand before the changes of the brewing were applied.

If you want to fetch the brewing result, your described method of delaying the execution of your code through the bukkit scheduler works, however you could also request/maybe implement this in a new feature request/PR to paper that exposes the "resulting" state either in the `BrewEvent` or in some form of `PostBrewEvent`, however the `BrewEvent` might be more useful, as plugins could cancel the event based on the outcome.
