### ISSUE TITLE
Blocks with Physics dupe glitch

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#687]
https://hub.spigotmc.org/jira/browse/SPIGOT-1647

**Comment by reverofevil** [comment]
That's an issue in vanilla. Please, find a ticket in Mojang bugtracker. As it duplicates only falling blocks, it is not prioritized high.

**Comment by Cobwebster** [comment]
Alright, you can close this if you want. We resolved the issues for ourselves, just wanted to report for other server owners.

**Comment by reverofevil** [comment]
I'm not a contributor.

**Comment by zachbr** [comment]
Tracked upstream at [SPIGOT-1647](https://hub.spigotmc.org/jira/browse/SPIGOT-1647).
I believe there is also a private Mojang ticket for this item, but I am not privy to details on that tracker.

Any work towards fixing this should be sent upstream, or at the very least sent to us so we can send it upstream.

This is an old issue and one that is not always reproducible, especially in a perfect scenario with little lag or plugins, which is why it has sat for so long.
