### ISSUE TITLE
Server startup error 1.12 pre2

### ISSUE THREAD

**Issue by DarkFort** [PaperMC/Paper#696]
![aggoue1lbhy](https://cloud.githubusercontent.com/assets/25278617/26081274/b9d3a8fc-39d2-11e7-90b1-6a680bf45ed7.jpg)
PaperSpigot 1.12 pre2

**Comment by Black-Hole** [comment]
Please try running with "--nojline" as last argument of the command line.

**Comment by DarkFort** [comment]
Same error (

**Comment by zachbr** [comment]
Please provide information about your server environment.

**Comment by DarkFort** [comment]
Windows 7 Ultimate x86 SP1

**Comment by electronicboy** [comment]
Might need to install this: https://www.microsoft.com/en-gb/download/details.aspx?id=5582

**Comment by DarkFort** [comment]
Reinstalled, the problem did not dare

**Comment by andris155** [comment]
Same error
Windows 10 Creators Update x64

**Comment by electronicboy** [comment]
Could you try starting the server with this flag (place it somewhere before -jar)
` -Djline.terminal=jline.UnsupportedTerminal`
You won't have any color, but if my theory is correct, you'll have a working terminal and you should be able to run the server

**Comment by Postremus** [comment]
I found this comment in the bungeecord source:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L201
It may explain some of this weirdness on windows.

2017-05-16 11:40 GMT+02:00 Shane Freeder <notifications@github.com>:

**Comment by DarkFort** [comment]
The same error with the flag -Djline.terminal=jline.UnsupportedTerminal

**Comment by aikar** [comment]
Based on that Bungee comment, try adding:
`-Dlibrary.jansi.version=Paper`

**Comment by electronicboy** [comment]
Finally got a VM up and running that can replicate the issue (Instead of trying to take 20 shots of different angles), looks like paper is hitting the same issue as bungeecord was, windows 7 SP1 x86, as the creator of this ticket was using, was able to hit the same bug, and was fixed using the flag as above

**Comment by RikoDEV** [comment]
I have the same error. (Windows 10 Creators Update x64 Java 8)

**Comment by electronicboy** [comment]
Have you tried the flag that @Aikar has posted?

**Comment by RikoDEV** [comment]
Server start now, but a lot of errors.

**Comment by electronicboy** [comment]
if the errors are related to this issue itself, would be nice if you actually included a copy of the log so that we can see them.

**Comment by RikoDEV** [comment]
Now, all working fine. But he doubts that such things are good.

**Comment by DarkFort** [comment]
![image](https://cloud.githubusercontent.com/assets/25278617/26119213/2fd668c6-3a75-11e7-8fd3-42ef5af97c84.png)
@aikar, Error remained, but the server is now running

**Comment by RoyCurtis** [comment]
Had this same issue, and Aikar's suggestion fixed it. Thanks!

Since the OP is a screenshot rather than text, I couldn't find this on google and had to look here instead. To help others find this issue: `java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.WindowsAnsiOutputStream`

@Bogdan2402 : in your latest screenshot, I got that same error because I had `chcp 65001` set in the batch file I used to launch Paper. Fixed it by removing that line. What does the top of the log say?

**Comment by DarkFort** [comment]
Thanks @RoyCurtis, helped. But without the chcp 65001 does not appear russian text in the console.

**Comment by electronicboy** [comment]
That exception is actually fired because java itself doesn't support that codepage, 1251 is the one for russian which java does appear to handle fine, you should actually configure that in your comptuer settings, however I have no idea how windows handles that.

I can submit a PR that will fix the original issue shortly without needing the flag, beyond that it's a system environment issue, you'll see the exact issue in any java application that tries to ask java to fetch the proper CharSet for the console in such cases. (e.g. CraftBukkit, Spigot...)

**Comment by andris155** [comment]
-Dlibrary.jansi.version=Paper fixed this bug.

**Comment by zachbr** [comment]
Workaround added ca6254067f57b240206c9d6ac1fde56db6786eb6
