### ISSUE TITLE
TileEntityChest cannot be cast

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#712]
Paper Build: 1102 
Minecraft version 1.11.2

Crash report: https://hastebin.com/efacururum.sm
Log: https://hastebin.com/huqeguzuve.vbs

**Comment by electronicboy** [comment]
no idea how the heck you managed to pull that one off, but you have a block with the meta of a chest identifying as a banner....

**Comment by SecretlyJealous** [comment]
How can I fix it? Server crashed again with the same message.

**Comment by electronicboy** [comment]
Not entirely sure how you've managed to do it, but I'd feel safe to say that it's likely due to some plugin doing something stupid with modifying the world in an unsafe manner, or somebody has modified the world manually using a program that has now broken the world.

Not entirely too sure what to suggest, I was under the assumption that the server tried to validate stuff like that upon loading, but apparently not... My only real suggestion would be to either attempt to modify the world manually and locate the issue or accept that the map is somewhat rip... The only other alternative would be for some failsafe to be added to the server, which for something that is highly unlikely to occur in 99.9999999999% of users cases, and would likely be a pain in the ass to handle for cases where something actually is doing something stupid at runtime seems somewhat unviable.
