### ISSUE TITLE
FurnitureLib ClassNotFound w/ JLine InputStreamReader

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#733]
Paper 1120 breaks furniture lib error: https://pastebin.com/db35Vf2v

**Comment by Fonzee9** [comment]
going to recheck on this soon.

**Comment by Fonzee9** [comment]
This is a Paper problem i am downgrading to build 1111 until this is fixed.

**Comment by zachbr** [comment]
It broke because it's using internal craftbukkit code from the logging library that we just replaced because it sucked.

We need a link to where we can get the plugin please. We'll evaluate options after that.

**Comment by Fonzee9** [comment]
You need

https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/

also

https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/

also http://ci.dmulloy2.net/job/ProtocolLib/

and you can test it.

**Comment by zachbr** [comment]
Bukkit 1.12 removed a specific input stream API that author used, so instead of fixing their code to use one of the others, they substituted in the logging library's from the CraftBukkit implementation code. Plugins should not be depending on internal logging libraries from CraftBukkit.

This is absolutely 110% a plugin issue and needs to be reported to the author.

We'll see what we can do in the meantime.

**Comment by zachbr** [comment]
Plugin author has fixed the issue in their plugin, long term we're working on a better solution to alert server admins and plugin devs about this issue.
