### ISSUE TITLE
Custom log4j2.xml fails to load server

### ISSUE THREAD

**Issue by ryans1230** [PaperMC/Paper#741]
As of build 1113, custom log4j2.xml are preventing the server from starting up. After being initially loaded, "Loading libraries, please wait", it just quits. Previous builds work just fine when using a custom log4j2.xml file. 

I believe this has to do with PR #728

**Comment by electronicboy** [comment]
Existing log4j configuration files will need to be updated in order to reflect the changes made;
https://github.com/PaperMC/Paper/commit/de2af506f35c415345189814a08f867a70f76a4b#diff-1166d249a557cdb64102129faccaf406R594

**Comment by stephan-gh** [comment]
You can still use custom `log4j2.xml` configurations, but you need to make a few changes to make it work on newer Paper builds. You need to change your configuration similar to the changes that were made in Paper: https://gist.github.com/Minecrell/e85abdaf419fa3636c55848cf0ca2e1b/revisions#diff-54adcee425bf63410fea5d7351813e2d

Explanation of the changes:
- You can usually safely delete `packages="..."` from `<Configuration>`. It doesn't break anything if you keep it, but will delay the server start.
- `<TerminalConsole>` is used instead of `<Queue>`
- `%highlightError{...}` will color errors and warnings red/yellow in your console. If you don't want it, you can just leave it out.

    - Make sure to wrap the entire message in `%highlightError{...}`. If your layout previously ended with `%n`, it should be entirely within`%highlightError{...}` and you need to add `%xEx` at the end of it to make sure the exceptions are colored as well.
- `%minecraftFormatting{%msg}` translates the Minecraft color codes to console colors. If you don't want them (e.g. in the log file), you can strip them using `%minecraftFormatting{%msg}{strip}`
    - `%minecraftFormatting{%msg}{strip}` is a more efficient way to implement something like `%replace{%msg}{(?i)\u00A7[0-9A-FK-OR]}{}`, so you can replace these with the new one

- `WINDOWS_COMPAT` is unneeded in newer Log4J versions and can be removed entirely.
