### ISSUE TITLE
AsyncChatEvent#renderer() swallows exceptions thrown inside it

### ISSUE THREAD

**Issue by AnttiMK** [PaperMC/Paper#7466]
### Expected behavior

Exceptions thrown inside `renderer()` call to be logged.

### Observed/Actual behavior

The exception is being swallowed somewhere, nothing was logged.

### Steps/models to reproduce

1. Throw an exception inside `AsyncChatEvent#renderer()`:
```java
@EventHandler
public void onAsyncChat(AsyncChatEvent event) {
    event.renderer((source, sourceDisplayName, message, viewer) -> {
        throw new IllegalArgumentException();
    });
}
```
2. Send a chat message in-game, observe nothing being logged.

### Plugin and Datapack List

Test plugin only

### Paper version

[02:47:56 INFO]: Checking version, please wait...
[02:47:57 INFO]: This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are running the latest version

**Comment by lynxplay** [comment]
Replicable :+1: 
Caused due to the fact that, while 
https://github.com/PaperMC/Paper/blob/0cc2503b88343c4d10d9e6ecf7592d56762b4cae/patches/server/0417-Deobfuscate-stacktraces-in-log-messages-crash-report.patch#L562
does register an UncaughtExceptionHandler for the ThreadPool, the chat submits the runnable instead of calling `execute`, resulting in the exception being caught in the created future and dying there without the handler ever picking it up.
