### ISSUE TITLE
Suggestion - Add Version info to pom.xml or Repo

### ISSUE THREAD

**Issue by tmfksoft** [PaperMC/Paper#747]
This is purely a suggestion for the benefit of PaperBot and anyone else wanting to get the latest supported Paper version.

It'd be nice to somehow retrieve the supported Minecraft version from the repo.
I dont currently see a way.

Maybe by adding it to the pom.xml as a variable people can parse out.
That way apis could retrieve the latest Jenkins build and then based on its commit retrieve the version of Minecraft the build supports.

**Comment by tmfksoft** [comment]
One way as suggested by Aikar is this:
https://ci.destroystokyo.com/job/PaperSpigot/1124/com.destroystokyo.paper$paper/api/json

Although thats not exactly a intended feature it it should work and be reliable.

**Comment by aikar** [comment]
Since it would be no different than reading the other line in the POM file, this wouldn't accomplish anything.

That API will let you obtain it w/o downloading the POM, so it accomplishes the need.

This verisoning format has been stable for years and no reason to change, so just extract it from the artifact version.
