### ISSUE TITLE
Crash OutOfMemoryError (with solution)

### ISSUE THREAD

**Issue by lokha** [PaperMC/Paper#754]
player.getTargetBlock((HashSet<Byte>) null, 0) - If you specify 0, then the method will go into recursion and it will be OutOfMemoryError

**Comment by lokha** [comment]
Paper version git-Paper-1123 (MC: 1.12)

**Comment by zachbr** [comment]
This uses BlockIterators internally, and is constructed similarly.

BlockIterators have an explicit contract to allow this sort of behavior. We have to assume that because of the design similarity and the fact that they are used internally, that this functionality is intentional.

Like BlockIterators, it is up to the plugins using this API to handle this feature safely. If that is not possible, they should not be using it.

Take it up with whatever plugin is doing this or remove the offending plugin.
EDIT: or take it up the chain to Spigot to get them to make this _breaking_ API change.
