### ISSUE TITLE
1.8.8 Fix-Cannons sand stacking

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#777]
Hello! I am using 1.8.8 PaperSpigot. I made fix-cannons to true, made falling blocks, tnt, enderpearls true on load chunks. Max-tnt-per-stick is 3000. But still ,when I shot with cannon sand goes wrong and just stacks 1 sand. Am I doing something wrong?

**Comment by MiniDigger** [comment]
1.8.8 isn't supported anymore

**Comment by ghost** [comment]
But could you maybe help me, please :(?

**Comment by electronicboy** [comment]
Well, the issue is either a bug in paper (in which case, you'd have to fork and fix it yourself, however I somewhat doubt that that is the case), an issue with your config (No idea, what you've said would sounds right but remembering stuff that was only relevant a few years ago....), or an issue with your plugins.

Beyond that, the ticket system is for reporting bugs, which unless you can prove that there is actually a bug and it's not caused by your own setup, this isn't the place to report it. (ignoring the fact that we no longer support/accept bugs for 1.8)
