### ISSUE TITLE
Server stopped responding (did not crash)

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#779]
paper dumps thread traces when server stops responding
in this case it did not crash, just became unresponsive
what sorcery happened here?

https://pastebin.com/YicjgBxn

no notable plugins, paper 1139

**Comment by electronicboy** [comment]
in the event that a tick takes too long to complete, as is the behavior in spigot, The watchdog will print the stack trace and then mark the server for shutdown once the tick has finished,modification in paper is that: in the event that the server hasn't entered a state where it is shutting down in 10 seconds, we will forcefully kill the server assuming that it's deadlocked.

I do not exactly understand what this ticket is trying to say, however?

if your issue is that it stopped responding, you either had item entity that moved too fast, or something earlier in the tick loop took too long, such as a plugin

**Comment by hurrgurl** [comment]
thanks

doesn't sound like something easily checked
