### ISSUE TITLE
Tabing commands is broken on latest Paper Build

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#788]
Build 1147

When i use for example a plugin like essentials and do /msg and press tab it doesn't tab there name 

When i used furniturelib and used /furniture give tab it doesn't tab the furniture..

Definitely a paper issue multiple plugins that use tab are affected

**Comment by Fonzee9** [comment]
I am not sure now tab works when you are opped and use /msg for essentials and so does furniturelib..

**Comment by electronicboy** [comment]
Test it in Spigot, paper does nothing that would affect tabbing that I'm aware of without looking around patches, but fairly sure that the default behavior was changed in 1.12 for tabbing to not just spew out names by default from what I properly recall, EssentialsX has patched this themselves so that it will tab complete if you have permissions to actually use the command.

**Comment by Fonzee9** [comment]
Seems problem is also in spigot.

**Comment by Fonzee9** [comment]
Also yes they have the perms in essentials and furniturelib

**Comment by Black-Hole** [comment]
This is a Paper feature:
https://github.com/PaperMC/Paper/commit/90b2d020918a1d18df950e360edf70d62c131b6e

There is also a config option in paper.yml: suggest-player-names-when-null-tab-completions

**Comment by electronicboy** [comment]
that option is what what you linked as a commit, and the default behavior doesn't have any change, it just allows for plugins to return null to not suggest names instead of the default behavior to just send every name on null.

several plugins noticed a behavior change with spigot around the time, leading to plugins such as EssentialsX making changes to their plugin to suggest names and stuff, hence why the creator of the ticket is also seeing the issue in Spigot.
