### ISSUE TITLE
Whitelist always looks up online mode UUIDs, even in offline mode

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#79]
I set online-mode=false, and now is offline mode, but whitelist always get online mode's player UUID.

For example:
Set to offline mode, and add a player to whitelist, name is Apple, his offline UUID is 5862580e-aa1b-3ba2-82db-40e501c08259, but in whitelist.yml, his UUID is 3c7db14d-ac4b-4e35-b2c6-3b2237f382be(online mode's UUID)...

So on offline mode, player Apple can not join server because UUID is not true. I must manually modify his UUID, change that to offline UUID in whitelist.yml, then he can join in.

Sorry for my bad English, and this is a bug or... Thanks!

**Comment by Techcable** [comment]
This is because whitelists look up onlije mode uuids even in offline mode.

**Comment by ghost** [comment]
But Paper 1.7.10 no this problem...

**Comment by zachbr** [comment]
The reason it worked in 1.7.10 was because it used all of the Bukkit duplicate commands, not the vanilla ones. In 1.8, the Bukkit duplicate commands were removed and the vanilla ones used.

We can investigate fixing this ourselves in the vanilla command, or just being lazy and re-adding the Bukkit command as an option
