### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#791]
It`s continually displayed.

![screenshot_3](https://user-images.githubusercontent.com/29000881/28281391-1ad29e92-6b51-11e7-8aa3-43bde3386496.png)

Server stopped.

![66](https://user-images.githubusercontent.com/29000881/28281479-718ed480-6b51-11e7-8a6c-81f9e03faac3.png)

Paperspigot 1150

**Comment by Black-Hole** [comment]
You could set "remove-corrupt-tile-entities" to "true" in the "paper.yml" file.

**Comment by zachbr** [comment]
World corruption is best corruption.

**Comment by enlyow** [comment]
"remove-corrupt-tile-entities" to "true" already set, but its gone again.

**Comment by electronicboy** [comment]
the state of your world is inconsistent, from the trace you gave us, you have a furnace where you have a block that should contain a shulker. I've not seen exactly how this can happen in the server beyond plugins modifying the server in an unsafe way.

not exactly too sure what the best way to fix this would be, I don't think that that setting actually catches the issue as I don't think it really considers that such a state is possible (the TE attached to the block being the wrong type), nor am I exactly aware of the best solution to tackle this, however, it's not something I really looked too deep into given the loose nature of the cause.

**Comment by enlyow** [comment]
Wipe was made 2 days ago. Will it help now?

**Comment by electronicboy** [comment]
if your world is only 2 days old, you have something horrible that is drastically breaking the state of the world and you should probably attempt to work out exactly what is triggering it.

**Comment by enlyow** [comment]
Could this be due to the fact that the world was downloaded with WorldDownloader and pasted into the world. The size of pasted map was more than 30 million.

**Comment by MiniDigger** [comment]
depends on how you pasted it, but if you did that with worldedit than yes, this could be the cause of breakage. I would recommend doing such large actions via mcedit.

**Comment by FunnyCraft** [comment]
тут только фаник механик сможет помочь

**Comment by enlyow** [comment]
Какого хуя здесь фаник механик забыл?

**Comment by Leymooo** [comment]
теперь это Русский чат)

**Comment by Savvy0787** [comment]
Пожалуйста, напишите ответы на английском языке, спасибо вам.

**Comment by MiniDigger** [comment]
guys, could we keep this in english please?

before anyone else wastes time translating: the last 4 messages:
```
Here only a mechanic will be able to help

What the fuck did the mechanic forget?

Now it's Russian chat)

Please write the answers in English, thank you.
```

**Comment by reverofevil** [comment]
The last one was actually "please, write down [some] answers in English, thank you" which sounded kinda weird.

**Comment by Leymooo** [comment]
Hm... Now i also have this crash.
https://pastebin.com/uuqKvUdR

**Comment by enlyow** [comment]
I no longer received this error after the wipe.

**Comment by Black-Hole** [comment]
Please use the setting mentioned before:
You could set "remove-corrupt-tile-entities" to "true" in the "paper.yml" file.

**Comment by Dimatert9** [comment]
It is already set to true

**Comment by Leymooo** [comment]
@Black-Hole  This setting doesn't help. When this crash happened - remove-corrupt-tile-entities was true

**Comment by electronicboy** [comment]
after looking over this properly and scratching my head as to "how the heck can this happen" the answer is beyond a case that spigot has missed (... cannot be cast to TileEntityShulkerBox; which I might have fixed on my own fork of paper while going over this, which should be on my CI server, [backup your world, or just don't run this... I'll consider cleaning it up and PR'ing later if wanted, this also isn't really the fix for your issues]), from what I can see, there is fundamentally no way that this can happen without a plugin modifying the world in a completely unsafe manner.

the process for getTE is that it will get the TE from the world, and then checks the block type and the compares it against the type of TE that it's expected to be. In the event that it doesn't match up, the server will log a warning and create a new TE.

beyond an oversight due to tiredness, I really do not see how this issue can occur without a plugin doing something horrible. that setting, remove-corrupt-tile-entities is only used when loading chunks from my recollection

**Comment by electronicboy** [comment]
looks like I derp'd pushed an older messed up version of that patch, if you were using it, try https://atlas.valaria.pw/jenkins/job/paper-self/37/ instead of 36 (and reminder, I did say use backups if it broke anything!!); however: this is still likely not the fix to whatever is causing your issues, (but should help correct any damage done once you remove what is causing it)
