### ISSUE TITLE
How to use paperclip.jar?

### ISSUE THREAD

**Issue by lyfer233** [PaperMC/Paper#792]
When i run it show it "Downloading original jar..." 
Then a new folder was created “cache” and New file "mojang_1.12.jar"
The "paperclip.jar"  to need compilation?

**Comment by electronicboy** [comment]
When you run paperclip it will download the vanilla server jar and then patch it, after the patching process has finished paperclip will run the paper jar; Just a case of being patient while it patches, shouldn't take too long depending on your connection and computer speed.

**Comment by lyfer233** [comment]
thank you very much. I think I understand.
Yes, for me the network is a problem.
Can i go directly to download "mojang_1.12.jar" ?

**Comment by electronicboy** [comment]
yes, you can download the server jar off the minecraft website and place it in the cache folder manually (make sure that the name is set to mojang_1.12 otherwise paperclip won't recognise it)
This issue tracker really isn't for support, if you have any further questions feel free to drop onto the webchat: http://hansel.spi.gt/iris/?channels=paper

**Comment by lyfer233** [comment]
oh~ Follow your method. 
my question has been solved.
Orz thank you ~
