### ISSUE TITLE
Couldn't load advancement console warning at start-up when using custom advancement pack with vanilla MC advancements.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#796]
Paper dev 1153

Using custom advancements that load vanilla MC advancements causes quite the output uproar at start-up.
http://paste.ubuntu.com/25139388/

Is this something that could be suppressed or fixed? The pack requires loading the vanilla MC advancements in addition to the custom ones so tabs aren't duplicated.

**Comment by electronicboy** [comment]
there is nothing here to fix other than the pack you're using, you're causing an error by causing duplicate advancements to be defined, which is an error. suppressing errors caused by something doing something stupid is counter productive and is a patch we'd have to maintain just because people want to use badly defined advancement files which also causes additional issues for us when people are not only ignoring the messages in their log file should they file an issue, but blatantly hiding them from even being logged.

You could probably look into replacing the advancements in the server jar manually, you'd basically have to run paperclip every update and replace the advancements file in the patched jar and upload it to the server.

**Comment by mibby** [comment]
As far as I know, you can't add custom advancements without it creating a new tab in the client GUI. So if you wanted to add onto the vanilla list under the same type of advancement category, i.e. 'end' or 'nether', it requires the vanilla advancements to be force not to be loaded, then loaded as a new file under a custom advancement. This is why I was wondering if it was possible to fix or suppress the output when it is loaded again to force it disabled.

**Comment by mibby** [comment]
Found an alternative way to get this to function. Can disable the vanilla advancements via spigot config and then load the custom ones.

**Comment by PrinceAkaid** [comment]
I have the same error

`[20:07:00 ERROR]: Couldn't load advancements: [minecraft:wander_add_map, minecraft:give_quest_trader_trade]`

**Comment by electronicboy** [comment]
Please don't bump better part of a decade issues, that is likely down to those advancements no longer existing
