### ISSUE TITLE
Disconnect packets not properly sent before server terminates in some instances

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#8]
![link](http://i.imgur.com/HeqexEB.png)

Updated BungeeCord and PaperSpigot recently and noticed a new disconnect message being outputted to the client when the server (PaperSpigot) restarts. Doesn't occur to everyone on the restart, only to about 1/2 of the players when there are a lot of players on the server. The other half get the standard shutdown message set in the config.

I restart my server with the full shutdown command (/stop), then do a fresh start-up. It is suppose to send the shutdown-message set in the bukkit.yml to all clients.

In contrast, this is what the old io exception looked like when the disconnect message (packet) is not sent to the client in time. Assuming the bump to compile with java 8 changed the io exception string.
![link2](http://i.imgur.com/wkiwkhw.png)

**Comment by zachbr** [comment]
This issue is just another varation of
https://hub.spigotmc.org/jira/browse/SPIGOT-625 and
https://hub.spigotmc.org/jira/browse/SPIGOT-638

The issue being that all the disconnect packets are not properly sent before the server terminates when there are larger numbers of players. A workaround was introduced here
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c3730616ee72b4e6e6b4f59654519d653791bc34
that did not completely resolve the issue.
However, a more proper fix would be implementing a cleaner way to shutdown the server so all packets flush before terminating the thread. This has been discussed upstream but never seemed to come to fruition.

Reformatting issue to focus around that, rather than this exception.

**Comment by mibby** [comment]
This also seems to occur with a low player count. Had it happen on server shutdown with just me and another player. Me being the one to receive the IOException instead of shutdown message.

**Comment by mibby** [comment]
Bumpity bump.

**Comment by zachbr** [comment]
Seems like SportBukkit may have fixed this? Needs testing.
https://github.com/OvercastNetwork/SportBukkit/commit/4113f51bd89ff55b02670423f263093482252df0

**Comment by zachbr** [comment]
Should be fixed, Use build 671 or newer.

**Comment by mibby** [comment]
Thanks @Zbob750 and @jedediah! From my quick testing, it finally seems to be resolved. :)
