### ISSUE TITLE
Serious bug

### ISSUE THREAD

**Issue by VoidAngel** [PaperMC/Paper#800]
Sorry, I'm about to be annoying :3

I guess word travels fast xD
If #799 is about what i think it is, it has already reached my medium sized server.

I'm not demanding a fix, I know some things take time. I would just like to know if I should spend the next few hours/days looking for a way to prevent this while you guys work on it, or if a fix/patch is almost here?

Any info would be very much appreciated <3

**Comment by itsaphel** [comment]
#799 is reproducible in all versions of 1.12 Minecraft. In short, it's because Mojang goofed up again and have some stupid old inventory mechanics. Every time they add something new, it breaks and instead of fixing the core issue, they add some code on top to fix it for one specific instance.

For now, you can apply a patch to Paper to cancel auto recipe crafting. This will fix the duplication glitch on your server.

See: https://gist.github.com/LordRobust/1575b3d19c32e9f209dbdf24a05190f3

Instructions for use are in the comments. It will serve as a temporary fix until Mojang get their shit together, release a patch and it's merged in from upstream versions.

**Comment by VoidAngel** [comment]
Thanks for the info LordRobust c:

**Comment by EmotionalLove** [comment]
https://www.spigotmc.org/resources/recipe-book-dupe-patch.44413/ It now seems as if this has been patched via plugin.

**Comment by zachbr** [comment]
Update your servers, skip the plugin.
