### ISSUE TITLE
Attempted to place TileEntity where there was no entity tile

### ISSUE THREAD

**Issue by adam-silvester** [PaperMC/Paper#803]
Just received this console errors a few times now
https://hastebin.com/togesabiri.md

**Comment by 0-x-2-2** [comment]
was the world a worlddownload?

**Comment by adam-silvester** [comment]
Nope it wasn't its a survival server

**Comment by zachbr** [comment]
So here is what is happening, as part of the chunk load process, entities and tile entities are loaded and registered to the chunk and then to the world itself. Within this registration process, there is some basic validation to make sure that there is at least a semblance of the correct block at the location where the tile entity gets registered.

In this case, the server is appropriately warning you that there are multiple locations where a chest tile entity is supposed to be but there is no chest block present there.

There are numerous ways this sort of thing could happen, 

- In past versions, a plugin altering a block in the world did not necessarily handle cleaning up any tile entity data stored there. Which makes this sort of thing not entirely uncommon in older worlds
- Plugins may be doing things outside the API, both safe and unsafe, that could cause this
- Out of game world editors could create this by not cleaning up data properly
- Other world corruption issues could also be at play as well

By default, Paper will only notify you in the server log when it comes across them. However you can also configure Paper to automatically remove these as it comes across them by setting the `remove-corrupt-tile-entities` configuration option to `true` within paper.yml.

This will still result in a server log message, however it will only happen the one time in order to notify you that we are removing it. Once it is removed, you will no longer see that message for that specific tile entity.

Alternatively, you could investigate handling this on your own using a plugin to re-set the appropriate block at the location and hoping it re-registers properly, but I do not believe you'd be able to recover  the data via this method. You'd likely need to investigate an out-of-game editor for that.
