### ISSUE TITLE
Paper generator settings generate structures over existing chunk terrain.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#807]
Paper dev 1162

Vanilla ocean monuments are spawning inside custom generated terrain, even after the world had been pre-generated without structures enabled.

![link3](http://i.imgur.com/ytX8iLE.png)
![link](http://i.imgur.com/GAyqOVI.png)
![link2](http://i.imgur.com/pIL0eCx.png)

Paper.yml
```
world-settings:
  default:
    generator-settings:
      monument: false
```

I pre-generated a custom world using a custom plugin generator (OpenTerrainGenerator) and noticed vanilla monuments intersected in-between the the custom terrain. So I pre-generated another world with the monuments setting disabled to get the world without random structure holes. Upon re-enabling the monuments setting after the world had been pre-generated, all of the structures re-generated in the vanilla default seed location of where it would be in that world. Shouldn't monuments only create themselves in new chunks?

Another issue I noticed is with the generator monuments setting disabled, all guardians in existing monuments stop spawning. Breaking pre-existing monuments in old worlds or vanilla monuments in new worlds with the setting disabled. Shouldn't it only prevent the creation of monuments, not existing monuments from loading and handling guardian spawns?

**Comment by zachbr** [comment]
In regards to ocean monuments generating in existing terrain: that is vanilla behavior and considered a feature.

See http://minecraft.gamepedia.com/Ocean_monument#Generation

**Comment by mibby** [comment]
What a terrible vanilla feature. It generates them in every single location of where it would be in default seed too, not just the chunk you are near. I guess I'll continue to keep the setting disabled to avoid chunks from being destroyed then.

How about the generator setting being disabled preventing guardian spawns in existing monuments from working?

**Comment by zachbr** [comment]
Whatever plugin you’re using to do world generation should just handle that by itself. You need to just leave it enabled rather than switching back to the vanilla chunk gen system.

That’ll avoid the entire category of problems.



I have not looked into Guardians not spawning with ocean monument generation disabled, will do so soon.

**Comment by mibby** [comment]
That's what I thought too. I figured the custom generator would override vanilla structure placement and create custom monument defined locations, but it only seems to override everything _but_ monuments. Both generators I tested (TerrainControl & OpenTerrainGenerator) have the vanilla monuments spawning within the custom terrain, so I figured it was a bug in spigot/paper since the plugins claim to be updated for 1.11 with monuments added to the game in 1.8. It is probably just the vanilla minecraft feature force re-creating monuments in all valid default seed locations throughout the entire world at once since the chunks inhabited timer is less than 3 minutes for the newly created terrain. 

I'll just keep the paper monument generator setting disabled to avoid problems.

> I have not looked into Guardians not spawning with ocean monument generation disabled,

My guess would be with the generation setting disabled, it ignores the monuments.dat file if one is valid.

**Comment by zachbr** [comment]
It looks like the actual data registration for structures occurs in the same places that handle creating them. In order to separate the two, we'd need to do a significant amount of decoupling that is just not going to be maintainable, and I have no interest in adding some massive patch to do so just to drop it in the next major version when all this changes anyway.

As far as I'm aware there is also no tangible reason a custom world generation plugin shouldn't be able to remove and even replace the structure generators. Which would be a requirement for many since they so dramatically alter vanilla world gen. Removing the vanilla feature that allows ocean monuments to spawn in old uninhabited chunks would likely only cause more confusion, and I see little incentive to add a toggle for this one very specific feature.

This is a solid wontfix from me.

That being said, if you can recursively iterate chunks to increase the chunkInhabited timer to more than 3 minutes, you should be able to prevent ocean monuments from spawning in existing chunks.
You can so by altering their NBT representation (stored as a long value) or by altering the field directly as the server runs using reflection. In CB's barbaric mappings this is currently ` net/minecraft/server/Chunk/w`.

That will allow you to workaround this problem until a better option reveals itself.
