### ISSUE TITLE
Minecraft Scheduler (SELF) lag

### ISSUE THREAD

**Issue by farprima** [PaperMC/Paper#813]
**Description:**
Server runs fine on 80-90 players, but starts lagging when it reaches 100+ players.

Server that runs on the same machine is just bungeecord and test server. How can i optimize it except the mobs? (i tried tons of solution for the mobs, but still its just reduce it, not removing it at all)

**Server specs:**
Processor: Intel i7-7700K - 4c/8t - 4.2GHz /4.5GHz
RAM: 64GB DDR4 2400 MHz
Disks: SoftRaid 2x450GB NVMe
Traffic: 5TB traffic

From OVH MC-64 SGP

**Timings:**
https://timings.aikar.co/?id=65636d707a594954a08d47083d4dad9f

**bukkit.yml:** https://pastebin.com/4TZybwFf
**spigot.yml:** https://pastebin.com/DkXR5jp7
**paper.yml:** https://pastebin.com/pTyUzXT1
**server.properties:** https://pastebin.com/b2r7RiK6

**Version:**
git-Paper-916.2 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Plugin list:**
http://prntscr.com/g1qm2z

Thank you 👍

**Comment by electronicboy** [comment]
This issue tracker is for reporting issues, not for support; We also don't support outdated software nor servers running plugins such as MassiveLag that break timings ability to report accurate information.

**Comment by farprima** [comment]
So where can i get support for Paper? as spigotmc is for "Spigot".

And how exactly MassiveLag can break timings? i use that plugin for the accuracy on /tps and /ping feature

**Comment by MiniDigger** [comment]
> So where can i get support for Paper?  

generally in irc (#paper on irc.spi.gt, webchat here http://irc.spi.gt/iris/?channels=paper ) or on the forums https://aquifermc.org/forums/#paper.3 (those are kinda ded), but since you use an outdated server you will not receive support.

**Comment by electronicboy** [comment]
there is the aquifer forums or the IRC channel; http://irc.spi.gt/iris/?channels=paper We don't provide support on the github issue tracker because it needlessly spams all of the contributors with emails.

We also don't provide much support for outdated versions of our software, however, so your mileage may vary.

MassiveLag and co plugins are known to hijack timings in order to register their own handlers, sometimes causing information to not be displayed in timings or for issues in the performance of their own plugin to show as an issue for other plugins. We cannot provide any form of support in any capacity when there is a plugin hijacking and likely causing issues with the information we're supposed to be able to look at in order to provide any form of support.
