### ISSUE TITLE
error announce-player-achievements

### ISSUE THREAD

**Issue by ProDash1998** [PaperMC/Paper#835]
announce-player-Achievements
Disappears from server.properties when the server is started.

and not work /gamerule announceAdvancements false
Version: PaperSpigot-1.12.1-b1172.jar

**Comment by electronicboy** [comment]
please see #725, or #798; and in the future, please search before creating an issue. You have to run the gamerule command on all of the worlds in order to disable it.

**Comment by ProDash1998** [comment]
#725 Sorry I can not compile

**Comment by electronicboy** [comment]
there is nothing to compile, it's more the notation that, the config option you're talking about has been removed from minecraft itself, as such is no longer in paper, the gamerule that has been added needs to be set in every world in order to disable it. This issue has been reported several times, and a quick search of the issues tracker or a google search could of likely landed you with the exact same information.

**Comment by ProDash1998** [comment]
I have another problem with the operation
spawn-monsters=false
and 
spawn-animals=false

Once turned on, they still appear

**Comment by zachbr** [comment]
Only stops new spawns, does not stop the world from loading mobs already saved in chunks.
