### ISSUE TITLE
Is it possible to set view distance per world?

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#859]
I was wondering if it was possible to set view distance range per world. Ideally I would like to have my arena void world with a view distance of 10 for greater battlefield view while keeping a default player view distance of 6/8 in my primary overworld / nether / end for the vast majority of players for lag reasons.

If it is possible, a concern I have is players being set to 10 view distance upon entry of the larger view world and not getting set back down when leaving that world.

**Comment by MiniDigger** [comment]
just listen to world switch and join events and set the distance with the api?

**Comment by electronicboy** [comment]
see spigot.yml, view-distance is configurable per-world, the 'default' "world" applies to all worlds without an entry in there. so, basically, copy default, rename it, modify view-distance

**Comment by mibby** [comment]
Huh, I guess it is possible. Never knew. 

@electronicboy Would I have to rename the 'default' settings to a world and copy it for all other existing worlds or would a custom world setting override the defaults? i.e. leaving default at 8 view distance for all worlds and simply just appending this below default;

```
world-settings:
  default:
    various-settings-blablabla
  void:
    view-distance: 10
```

**Comment by electronicboy** [comment]
~if a world is defined in the config, it will use its own settings, otherwise it will use the settings under defaults; it will not, however, read missing settings under a world in the config from the default group~

I was apparently brain-dead while writing this, this is actually wrong, the config will read the default world settings

**Comment by mibby** [comment]
So then if I'd like to increase the view distance to 10, I'd also have to copy _every_ ```default:``` world settings as well for those default settings to still work in the world? Bit odd that it wouldn't just override settings defined and use missing settings from default.

**Comment by electronicboy** [comment]
Yes, you would have to copy everything from default that you wish to keep set in the new world entry, otherwise it will not be applied. The whole applying missing stuff to worlds from the default section really isn't nice to do with the current config mechanism, otherwise, we'd cause issues trying to read the config in the first place.
