### ISSUE TITLE
suggestion: prevent fireworks from loading chunks

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#860]
https://gyazo.com/b836ee9e66ffdc898cb3f9a3aa81c2d6

somehow on my creative server fireworks are loading chunks, i think it happens if they have a unlimited travel length

**Comment by Laarryy** [comment]
I am unable to reproduce on 1.19.1, not sure why because I don't see much changed, but nothing I can do (including sending a whole bunch of fireworks off into the unloaded distance) is getting me a timings report like the one here. Perhaps fireworks have been more flushed out as entities? 

Regardless, I will close this for now. If you or anyone else can manage to reproduce this, PhanaticD, please open a new issue with steps to reproduce on 1.19.1 and mention this one in it. Thanks!

**Comment by PhanaticD** [comment]
Bit late, five years ago I found out they were nbt edited to have infinite duration and blocked them through other means.
