### ISSUE TITLE
PeperSpigot Crash on creative server

### ISSUE THREAD

**Issue by Malachiel87** [PaperMC/Paper#874]
My creative server randomly crash without reason in really rare cases only using PAPER, with spigot never crash, i got the same issue also by using 1.8.9
# Crash, Stacktrace
https://hastebin.com/ivoregagey.hs
There is also the log before the crash
https://hastebin.com/uxezolezus.sql

### Plugin list:
Plugins (20): BannerMaker, BetterChairs, ChatControl, FastAsyncWorldEdit, FixHackedItems, iConomy, LibsDisguises, LuckPerms, MarriageMaster, MiniaturePets, Nicky, PlotSquared, ProtocolLib, ProtocolSupport, SimpleTPA, Skript, TitleManager, TrollandiaCore, Vault, WorldEdit> 
### Actions to reproduce (if known):
none

### Paper build number:
This server is running Paper version git-Paper-1196 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)>

**Comment by zachbr** [comment]
Your world has some pretty bad corruption issues. Specifically around tile entities. We could band-aid Timings to use a method more friendly to these sorts of corruption issues, however it wouldn't fix it when other plugins attempt to use it.

There's nothing here for us to fix, the issue is your world. I don't know if any of your current plugins are responsible or if this is just old damage.

**Comment by Malachiel87** [comment]
and how i suppose to fix this? It happen rarely but is pretty anoying to make the server crash,  but is pretty anoying, and this happen only with paperspigot.
