### ISSUE TITLE
/minecraft:reload does not reload loot tables, advancements, and functions

### ISSUE THREAD

**Issue by malonnnn** [PaperMC/Paper#878]
In Spigot, /minecraft:reload performs the vanilla reload command, updating loot tables, advancements and functions. In Paper, nothing happens when I run that command.

Verision of paper:
This server is running Paper version git-Paper-1201 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by electronicboy** [comment]
Because I have very little (i.e. none) experience with creating advancement packs, I grabbed this: https://www.planetminecraft.com/project/blazeandcave-s-advancements-pack-1-12/ and ran the command on the server and got this pretty output:
https://i.valaria.pw/170907171534.png

is there any feedback from the command whatsoever? Are you sure that you've put your files in the correct place? can you replicate this without plugins?

**Comment by malonnnn** [comment]
@electronicboy 

Well, actually, I haven't started writing functions yet, but I did back to back testing on the latest version of spigot vs paper.

In spigot, when doing /minecraft:reload (no plugins, no functions written) a message pops up saying "reloading loot tables, advancements and functions"

In paper, when doing /minecraft:reload (no plugins, no functions written) no message occurs, making it seem broken.

**Comment by MatrixTunnel** [comment]
If it's not a fresh world, make sure you have the gamerule sendCommandFeedback set to true. It should still display in the console regardless of that setting

**Comment by malonnnn** [comment]
@MatrixTunnel 

Ahhhhhh holy shit that was it. I have this "test" server i use with no plugins, but I did not generate a fresh world. Thank you!
