### ISSUE TITLE
Console badly support for chinese input/output ?

### ISSUE THREAD

**Issue by collller** [PaperMC/Paper#879]
sorry for bother you

first i use windows server2012 x64

after i update paper form #1104 to 1.12.1(#1179),
all the chinese input/output become **Disorderly code **! just like "ÎÒ´òµÄ¾ÍÊÇÂÒÂë"

then i use "-nojline" in start.bat but no more color and dose not support chinese input.

yestoday i update my system form server2012 to win10,

![issue](https://user-images.githubusercontent.com/8498136/30236768-4597a19a-9554-11e7-8148-d5042920b9c0.jpg)

still have problem...

input chinese sometimes will make console stop responding and crash.
![tim 20170909114917](https://user-images.githubusercontent.com/8498136/30236800-04e6dbe2-9555-11e7-930d-04a157f26e17.png)

so i was wonder is there any way to rollback jline to old vision some thing like ".patch" i can do it my self or it's really is a bug and you can fix it easily？

thanks :3

**Comment by electronicboy** [comment]
Would be nice to see the full crash report as opposed to a snippet that just says that it actually crashed, just took a look over at the jline repo and looks like they might have actually fixed within the past few days caused by some oddities in how windows handles stuff across languages.... (thanks microsoft....) might also be worth executing: chcp 65001   in your bat file before starting java in order to try and convince windows to try and deal with it properly, however windows has a few bugs with that but it shouldn't cause any issues for the current needs

looks like it should just be a case of updating jline looking at the commits, @Minecrell any comments?

**Comment by collller** [comment]
thanks for response

i already try chcp 65001/chcp 1251/-Dfile.encoding=CP866/chcp 855/-Dfile.encoding=UTF-8

but nothing change or worse.

i think the crash is because of the console is stuck when i type some chinese，console will not output any information anymore. and i have to type some command just like "who/lag/tps",console stop stuck anymore , but all the players lost connection.

type chinese -> sometimes console stuck -> server stop running -> type "lag" command ->server work again -> console show all players lost connection msg.




log here =>[log.txt](https://github.com/PaperMC/Paper/files/1289559/log.txt)

**Comment by stephan-gh** [comment]
Might be related to https://github.com/jline/jline3/issues/164, apparently there are some problems with the UTF-8 code page and Chinese characters. The solution for that issue is to revert back to pre-3.4.0 behaviour (use the Windows default code page), which would bring #736 back. Hooray.

**Comment by zachbr** [comment]
Paper will update to the next version of jline as soon as it is released which should fix this issue, whether that be 3.4.1 or 3.5.0.

Revert this change to get things back to the way there were before in the meantime: 9f3f6e02a6f803094be005a672fe5d5d6698a4d2

**Comment by stephan-gh** [comment]
@Zbob750 We can't just upgrade to the newer JLine version (at least without setting the UTF-8 code page manually), because then we bring #736 back. Right now we'd need to choose which one of the two issues we'd like to fix...

When I have time I'll try to find a better fix for this, however, I was not yet able to reproduce the issue. Apparently, the English Windows version doesn't come with any Chinese support on the command line. I just get `???` on the UTF-8 code page, and the Chinese code page isn't even installed.

**Comment by zachbr** [comment]
I was under the impression they didn’t regress on the last one. Must’ve misread their ticket.

**Comment by stephan-gh** [comment]
Well, the reason it's not directly a regression is that you can now manually set a code page. The default behavior is again the one from before 3.4.0 (where Chinese characters appear to work but Cyrillic characters are broken) and you can manually change it to what 3.4.0 does (where Cyrillic characters work but Chinese characters are broken).

**Comment by stephan-gh** [comment]
Should be fixed properly with https://github.com/jline/jline3/pull/168

**Comment by stephan-gh** [comment]
It's now fixed in JLine, we just need to wait until they make a new release.

**Comment by collller** [comment]
@Minecrell
thanks for your hard work!  :-D

![1](https://user-images.githubusercontent.com/8498136/30789381-c0791616-a1d7-11e7-8a67-f82cbc097fe1.jpg)
