### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SeruhioX** [PaperMC/Paper#882]
For some reason since I updated to 1.12.1, this error occurs, I have no idea why, in the log there are no more errors

https://pastebin.com/Enb0baxL

### Plugin list:
https://i.gyazo.com/8ed4710621ec3ed21ace697f9f1ba665.png

### Paper build number:
1202

**Comment by zachbr** [comment]
Your server was lagging significantly enough that it was stopped completely.
In this case it was probably because of a Firework. There is nothing here for us to fix.

We have seen cases where people/plugins make fireworks move very quickly causing excess lag, pushing a server beyond the point of no return. There's no conclusive evidence here that that is the case, but it's something to keep in mind.
