### ISSUE TITLE
No longer possible to Iterate over ServerListPingEvent

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paper#884]
c86f61f8afd3b99d490e11690091aca5731d28b0 broke plugins that iterate over the event to remove players from the list (and thus the player count that appears). 

This is how EssentialsX has worked around the issue.
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsServerListener.java

An attempt at compatibility should be made in the implementation, and the API added in that commit should be properly documented.

**Comment by electronicboy** [comment]
I was deliberating over this other and (and totally remembered to comment) it basically falls down to several things:

fire our own event after the initial event in order to accommodate this without touching the original event... (means that we're firing two events instead of one, which isn't really all that ideal but is cleaner to existing plugins that aren't using these changes)

The major downfall here falls into play with the fact that we can have entries which aren't players, the Iterator on the event has to drop Player objects out of it, which is where the major issues for compat come, we basically have two options here:

attempt to return Player's in the iterator, creating our own objects when needed in order to accommodate this, this has the downfall that it will break any plugins that actually care about the player beyond UUID/Name, and will likely cause issues with permissions on players due to how permission plugins generally handle this.

attempt to filter out entries so that we only return a Player when there is a Player in the list, this one I'm not entirely sure how it would be implemented at this moment, but would provide a bridge that is more transparent to plugins and doesn't break any form of existing behavior, however it is the one that is more messy to implement and does leave plugins potentially blind to what is in there.

Overall, I feel that the first option is the cleanest of them, and:

```
[20:17:39] minecrell:	Z750 + anyone else: Would you accept a PR that extends ServerListPingEvent with all the bad stuff like protocol version, MC version name etc (just like Bungee has all of that). I was thinking that it would be nice if ServerListPlus could work on Paper without ProtocolLib, but it needs all the advanced stuff
[20:28:10] minecrell:	Question is if you want to expose an implementation detail like protocol versions to the API
```
I would say option one plus ^ would make a great `excuse` for a paper specific event for this

**Comment by stephan-gh** [comment]
I personally think the actual issue here is that it's a plain list of strings instead of also tracking the UUID of the players. Yes, all plugins that "abuse" the player list to display a custom hover message usually just set a dummy or random UUID, but the Vanilla Minecraft server sets the real UUIDs of the players.

Currently, this is just ignored in the Vanilla client, but that doesn't mean this won't change in the future or that some custom clients may depend on it. As an example, it would be possible to write a client mod that uses the UUID to display a tiny image of the player skin (e.g. the face) next to the player name. Even without a single plugin using this event, Paper now replaces all UUIDs with random UUIDs, breaking this feature.

#### Possible solution when UUIDs are preserved
Plugins can use the player iterator to ensure certain (e.g. vanished) players are not displayed in the server list. Removing a player using the iterator removes it from the sample list and decrements the online player count.

If we keep the UUIDs, this can be implemented quite easily: We only return the entries that refer to an online player. This can be implemented with a simple lookup of the UUIDs in the list.

As an example, let's say the player sample is a `List<Map.Entry<UUID, String>>`. The optimal solution would be a list of game profiles, but we need #828 for that. The player iterator can then be implemented like this:

<details>
<summary><code>PlayerIterator.java</code>  (click me)</summary>
<br>

```java
public class PlayerIterator implements Iterator<Player> {

    private final Iterator<Map.Entry<UUID, String>> iterator;
    @Nullable private Player currentPlayer;

    public PlayerIterator(Iterator<Map.Entry<UUID, String>> iterator) {
        this.iterator = iterator;
    }

    @Override
    public boolean hasNext() {
        while (this.currentPlayer == null && this.iterator.hasNext()) {
            this.currentPlayer = Bukkit.getPlayer(this.iterator.next().getKey());
        }
        return this.currentPlayer != null;
    }

    @Override
    public Player next() {
        if (!hasNext()) {
            throw new NoSuchElementException();
        }

        try {
            return this.currentPlayer;
        } finally {
            this.currentPlayer = null;
        }
    }

    @Override
    public void remove() {
        this.iterator.remove();
        // TODO: Decrement online player count
    }

}
```

</details><br>

This will also work if a plugin only changes the format of the player names (e.g. replacing the names with the display name). The UUID would still match in this case.

**Comment by electronicboy** [comment]
So, option three, it still has the implications that stuff can be in there that won't be seen by other plugins, but when I was going over the options it felt the cleanest in terms of overall behavior, duplicate events are just annoying...

I was actually thinking that this would be a good candidate for the game profile API, now that I have free time I just basically need to sit down and get to it and speak to everybody involved, that would however push this back to at least 1.13, but the usage of GameProfiles for this was the original idea, which might be more ideal in the long run, doesn't solve anything in the shortrun, might be more ideal at this point as a stopgap between then and now to only set the sample text manually if it's been modified in the event itself....

**Comment by stephan-gh** [comment]
> it still has the implications that stuff can be in there that won't be seen by other plugins

Normally yes, but in my opinion that's exactly how it's supposed to work according to the Javadocs:

> Displayed players can be checked and removed by iterating over this event.

> Calling the `Iterator#remove()` method will force that particular player to not be displayed on the player list, decrease the size returned by `getNumPlayers()`, and will not be reutnred again by any new iterator.

Since a message doesn't refer to a particular player, the iterator works exactly as expected (and _should_ work fine for plugins like Essentials).

> I was actually thinking that this would be a good candidate for the game profile API

You could start pretty simple for this event: In terms of the server list, a `GameProfile` is just an UUID combined with a name. Properties are more complex but they could still be added later on.

**Comment by aikar** [comment]
The simplest option be to keep it using real UUID's UNLESS a plugin changes it.

So if nothing writes custom text (in which they would be responsible for vanish checks to begin with), then keep vanilla behavior.

**Comment by stephan-gh** [comment]
> The simplest option be to keep it using real UUID's UNLESS a plugin changes it.

That would be fine as a temporary solution, but I don't see any reason to not expose the UUID as soon as we have a `GameProfile` API. Plugins should be able to re-create the player list with a specific formatting (e.g. display names) without causing the player UUIDs to get lost.

**Comment by electronicboy** [comment]
it sounds crass and it is, but until we have the API, it would potentially make more sense to just add a boolean inside the event that is set in order to tell it to use the sample list when it's been modified/accessed (as it's not an immutable or copy of a list that is returned, we can't see if any modifications have been made), it's not ideal, but it would allow us to retain existing behavior of bukkit but allow for the new methods to be used.  not ideal, but it "would work"
