### ISSUE TITLE
Paper not start Java 9 Ubuntu 16

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#905]
```
06.10 08:05:19 [Multicraft] Loaded config for "Paper 1.12.2 (Java 9)"
06.10 08:05:19 [Server] INFO WARNING: Java 9 currently causes significant issues for a lot of Bukkit plugins due to new ClassLoading semantics.
06.10 08:05:19 [Server] INFO WARNING: For the time being, it is recommended to stick with Java 8 until plugins are updated.
06.10 08:05:19 [Server] INFO Exception in thread "main" java.lang.NullPointerException
06.10 08:05:19 [Server] INFO at com.destroystokyo.paperclip.Agent.addClassPath(Agent.java:17)
06.10 08:05:19 [Server] INFO at com.destroystokyo.paperclip.Utils.invoke(Utils.java:54)
06.10 08:05:19 [Server] INFO at com.destroystokyo.paperclip.Paperclip.run(Paperclip.java:155)
06.10 08:05:19 [Server] INFO at com.destroystokyo.paperclip.Main.main(Main.java:9)
06.10 08:05:19 [Multicraft] Server shut down (starting)
```

`This server is running Paper version git-Paper-1233 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

`Plugins (0): `

OS: Ubuntu 16.04.3 LTS

**Comment by electronicboy** [comment]
that would seem to potentially imply that there as an issue starting the instrumentation, especially considering that it works on java 9 perfectly fine outside. Any idea what the java arguments that multicraft uses, could be that they're doing something which conflicts with the loading of the agent that is required in java 9 to be able to launch without requiring manual patching.

The best option is to just stick to java 8, there is no real major reason for servers to switch at this current point, especially with the compatability issues, beyond that, we'd need to look into what multicraft is doing and if it is infact causing the breakage. paperclip will also dump the patched jar in the cache folder when it's ran, it's not as clean as you'd need to run paperclip every update and then run that jar, but would work.

**Comment by DenWav** [comment]
I don't see how that could be null unless the server is intentionally being run in some way to prevent instrumentation from running. When that happens, my fix will only be to print a clearer error message, rather than failing hard. Multicraft needs to stop doing whatever it's doing to cause instrumentation to fail.

Is there any way we can get the full command Multicraft used to start the server by any chance?

**Comment by andris155** [comment]
Start command
```
[start]
command = "/usr/lib/jvm/java-9-openjdk-amd64/bin/java" -Xmx{MAX_MEMORY}M -Djline.terminal=jline.UnsupportedTerminal -jar "{JAR}" nogui
```

**Comment by andris155** [comment]
Waterfall works perfectly with java 9 on Multicraft.

**Comment by electronicboy** [comment]
Try using oracles JDK/JRE instead of openJDK, it appears that openJDK isn't loading the agent, whereas oracle java does. Not sure if there is anything here for us to fix as much as openjdk just won't load the required agent.

Waterfall working on j9 is a mute point, it doesn't require instrumentation in order to allow us to run the jar, whereas paperclip does. If you was to run a compiled or the patched jar in the cache folder, it will work fine as it doesn't need to use this agent in order to load paper.

**Comment by andris155** [comment]
I copy patched jar from my PC and not work. :/

**Comment by electronicboy** [comment]
"not work" doesn't provide much info, if you got the exact same exception that means that you started paperclip and not the patched jar.

**Comment by andris155** [comment]
I'll test it at home.

**Comment by andris155** [comment]
Please wait.

**Comment by andris155** [comment]
Works perfectly with patched jar.

**Comment by andris155** [comment]
I installed Java 9 JDK and fixed this bug.
