### ISSUE TITLE
"Server has stopped responding."

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#906]
###  Timings or Profile link:
Probably 20 TPS. No players were online before the issue occured.

### Description of issue:
Server crash when player trying to connect.

### Plugin list:
AsyncWorldEditInjector v3.4.9, AsyncWorldEdit v3.4.10, Essentials v2.0.1-b530, EasyBackup v2.3.3, EssentialsSpawn v2.0.1-b530, ProtocolLib v4.3.0, WorldEdit v6.1.8-SNAPSHOT;cd4729f, ChatControl v7.5.8, AntiAura v11.1, LiteBans v2.2.4, WorldGuard v6.2.1;84bc322, React v5.3.8, GriefPrevention v16.7.1

### bukkit.yml, spigot.yml, paper.yml, server.properties
Default

### Paper build number:
git-Paper-1217 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### What behaviour is observed:
Red error text in console and server shutting down as usual.
### Steps/models to reproduce:
Maybe leave server running for a while.

### Link/paste of stack trace
https://pastebin.com/DDEZL07j

**Comment by electronicboy** [comment]
can't really say much from that report, your server lagged out for some reason, slow disk, maybe? (or just horribly slow plugins or something). watchdog reports are mostly useless, they say what your server was doing after x amount of time of a tick starting, generally a minute, your server was in the middle of saving the file of a player who was disconnecting.

Unlikely to be the cause, but if it is, your disk is too slow, otherwise, this is more than likely an issue with a plugin, not much we can do with this.

**Comment by ghost** [comment]
I'm using a 3200MB/s SSD for my minecraft server. Could not be that..
I will investigate if it's a plugin that causes this.

My report can be archived now, since we won't come any further.
