### ISSUE TITLE
Light Chunk timings

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#916]
I recently updated my PaperSpigot version to "git-Paper-1238" and started to notice some lag spikes on my server. I turned on timings to see if it would show anything: https://timings.aikar.co/?id=510907069a7347e081d2ed05556cb472 - For some reason "Light Chunk" is extremely high. Looking at the recent changes, build #1237 mentions some changes about lighting. I'm assuming this change may be the cause of this issue?

**Comment by electronicboy** [comment]
We recently dropped a few patches from Spigot that cause various issues regarding the state and consistency of the server, and could even potentially in some cases end up with chunks without having had their lightmap calculated what so ever, which is basically what you've configured the server to do from your spigot config.

There is no real issue here, now that those patches have been removed, your server should actually be calculating the light properly on the server instead of leaving them in an inconsistent state, and so as chunks are loaded from a server that was configured to leave the map in such a state, this has to be corrected by calculating the lightmaps for these chunks there where left in such a manner, I would suggest referring to https://github.com/PaperMC/Paper/pull/904 and the patches involved for more information on them and why they where pulled.

Paper provides an option that allows you to queue light updates, I would suggest enabling that while we work on #903 as it would try to limit the amount of work done in a single tick for light calculations

**Comment by SecretlyJealous** [comment]
Okay, I think the timings are worse: https://timings.aikar.co/?id=61919301566a455e9816b4505ba24a6c because of the queue light updates setting but I guess this is something that I'll only have to deal with temporarily until everything has been corrected or when the new patch comes out.

**Comment by SecretlyJealous** [comment]
Recently got this crash, just leaving it here in case it is related: https://pastebin.com/44i29xEh
I've reverted to an older paperspigot for now since the process of correcting the lightmaps is causing lag spikes/crashes even with the "queue light updates" option.

**Comment by electronicboy** [comment]
Closing, final crash report has nothing to do with this (looks like somebody moving too fast in the world), I'd suggest following #920, spigot breaking the server by default really doesn't help for stuff like this when the bad decision is rectified later on.
