### ISSUE TITLE
1249 or 1250 crashes when player joins on mobile

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#932]
# Crash 

### Description of issue:
Server automatically updated to 1250 last night and today the server would crash anytime someone used PickaxeChat or Minechat to connect. Not sure if build 1249 or 1250 caused the issue because we jumped straight to 1250.

Issue is resolved by using build 1248 instead.

### Log:
Here is a log from startup to crash: https://pastebin.com/KTBL2cPE

### Plugins:
Note: Issue was still present WITHOUT viaversion!
https://imgur.com/KHVHK67

**Comment by electronicboy** [comment]
Crash is caused due to EssentialsX relying on library internal. 1249 saw Spigot updating SnakeYaml to 1.19 from 1.18, which means that EssX reflecting into snakeyaml now fails, what happens is EssX creates a lock on its data source, and because it doesn't expect or deal with the exception, it causes the lock to remain, thus preventing access to the config and blocking the main thread.

https://github.com/drtshock/Essentials/issues/1631
