### ISSUE TITLE
Penned Animals Despawn

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#943]
**Update**: Confirmed that this doesn’t not require the plugin AAC to occur. It may have simply been exacerbated by AAC.

### Description
- Farm Mobs (cows, pigs, sheep, etc) that can be bred will despawn in mass after a **Command Block** teleport.
- This only occurs on Paper 1.12.2, not Spigot, so it has something to do with how Paper uniquely handles cached mobs that were recently bred (that's my theory).
- ~~This only occurs because of what AAC(by @konsolas) has to do to prevent teleport exploits/bugs, but AAC does not despawn mobs and it doesn't happen on Spigot...so the report belongs here.~~
- The issue stops ~~if I remove AAC or~~ if I remove PaperSpigot.

**Update/Edit:** Mobs that are named or tamed have the same issue. So it seems any metadata on a mob will trigger the despawn under the circumstances. Generic spawned mobs will not despawn.

My hopes are that something was overlooked on Paper's side as it relates to cached mobs containing metadata and how unloaded chunks save said mobs... 🤷‍♂️ 

### Replicate (not sure how to replicate without AAC)
- 1.12.2 PaperSpigot + AAC plugin(latest builds)
1. Make small pen of 2+ animals (I reproduced religiously with cows).
2. Breed/feed all the animals
3. Unload the chunks by leaving area _Edit: (chunks being unloaded may not be required)_
4. Use a command block to teleport a few thousand blocks away to a random, unloaded location
5. Return to animal pen
6. Find no animals

### Error/Stacktrace
None

### bukkit.yml, spigot.yml, paper.yml, server.properties
Tested on default mob despawn distances and all default Spigot spawning ranges.

### Paper build number:
Occurred as early as 1251 (based on player report timeline).

**Comment by electronicboy** [comment]
There really isn't much we can do in cases like this, we don't own a copy of AAC nor even if we did would we be able to see what it's actually doing without much work. I'm also really not aware of any changes we've got which could affect this.

Also, how are you unloading the chunks? You mean the chunks of where you're teleporting to or?

**Comment by CeIebrimbor** [comment]
The chunks are unloaded by any means: walking, teleporting by means other than Command Block (including Plugin Teleports).

It is possible that it could occur without unloading the chunks w/ the animals. I simply reported what I did to get it to occur at a 100% rate.

> There really isn't much we can do in cases like this, we don't own a copy of AAC nor even if we did would we be able to see what it's actually doing without much work. I'm also really not aware of any changes we've got which could affect this.

I was hoping there was something unique that a Paper dev could stab in the dark to pin down something related to cached mobs and how bred mobs are treated in Paper and nowhere else. Hopefully, that is still the case...regardless of what AAC does to trigger that bug. Since AAC doesn't despawn mobs or tell the server how to handle cows...it seems tied to Paper.

Edit: It's as if PaperSpigot lumps _specifically_ bred mobs into the same category as hostile mobs after this unique event.

**Comment by CeIebrimbor** [comment]
**Update:** Mobs that are named or tamed have the same issue(reportedly). So it seems any meta data causes this.

**Comment by CeIebrimbor** [comment]
I will try to put some video together, but maybe that is not helpful? I will see if the AAC dev will comment... @konsolas

**Comment by electronicboy** [comment]
I'll try and find some time to look into this, the problem here is that we don't know how AAC is interacting with the server and the assumptions it's making. it wouldn't be the first time that a plugin like AAC has caused issues due to assumptions it's made on the CB platform or "it's not causing any issues here".

**Comment by Brokkonaut** [comment]
I can confirm this without AAC, we often have disappearing mobs in a similar situation but do not run AAC. Since I never found a way to reproduce it, I did not report it (and I don't even know if it happens on Spigot too or is some plugin caused problem)

**Comment by CeIebrimbor** [comment]
**Update**: Confirmed that this doesn’t not require the plugin AAC in order to occur. It may have simply been exacerbated by AAC. My players are still reporting it...

Hopefully this issue is upgraded to a critical status 😞

**Comment by zachbr** [comment]
The issue I'm running into is how inconsistent this issue seems to be.

I am unable to reproduce this, but I went digging through the code and found myself looking through the despawn code. There is some intended randomness in how entity despawns are handled, but even after removing it I cannot reproduce it, nor would that explain your cases of it occurring when chunks are unloaded.

I will try to make time to look at it more in the following days, but given the time of year I can't promise anything.

**Comment by Brokkonaut** [comment]
I'm not sure if they despawn at all. Maybe the are just not saved/loaded or saved/loaded/teleported at the wrong location or not added to the world or something like that. because it also happens to animals that are invulnerable and not despawning (Invulnearable and PersistenceRequired set to 1)

**Comment by CeIebrimbor** [comment]
Downgraded to the Paper version that introduced anti X-ray, still happening. :(

**Comment by CeIebrimbor** [comment]
@zachbr Please try to implement whatever you think was the random and unintended despawning. This is starting to do damage...

Players with named, tamed and saddled animals are reporting mass despawns, as if it’s happening in waves at their location (all their animals despawn, not just a few at a time).

**Comment by electronicboy** [comment]
as stated, We've still yet been able to replicate this issue, which means that we're unable to find out what is actually going on or even begin to properly pin the issue in a corner. The code he's referring to is likely the chance system in which mobs in varying radiuses of the player are potentially despawned (there was some general % of mobs that should be removed further the player moves around them until all mobs ready to be killed are gone) and isn't going to be the actual cause of this.

If you have a way that we can replicate this properly without any plugins, feel free to inform us, but as it stands, this cause of this issue is as it stands, unknown. As much as we love to fix issues, we can't fix what we're not able to reproduce or triangulate

**Comment by CeIebrimbor** [comment]
Hmm, no longer being reported. I update to latest Paper recently and _seems_ like it's gone??? 🤷‍♂️ 

I will re-open if I get it to happen again or if someone else who had similar issues reports more findings. This has been an odd one...
