### ISSUE TITLE
Allow sending plugin messages to empty servers [Feature]

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#947]
it would be nice if it was possible to send plugin messages from/to bungee and servers that have 0 players connected

(sorry if im posting this in the wrong place)

**Comment by pkt77** [comment]
That'd be something a plugin would do and would have to be put on both bungee and minecraft servers.

**Comment by MiniDigger** [comment]
you can't send plugin messages if no players are online since plugin messages are relayed thru players. if there is no player, then you can't use its connection to send additional data.
instead you should open your own connection between the servers with a message queue (redis p/s, rabbitmq) or raw tcp with something like netty

**Comment by 0-x-2-2** [comment]
https://www.spigotmc.org/resources/api-socket4mc.15938/

**Comment by hurrgurl** [comment]
Thanks.
