### ISSUE TITLE
touching end portal makes you invincible

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#96]
touching end portal makes you invincible. In my case the end is disabled, but just touching the portal makes you unable to take any damage

**Comment by hurrgurl** [comment]
I had similar issue, only happens if end portal teleport is disabled in paper yml.

**Comment by zachbr** [comment]
That is not a config value. Are you referring to the disable-end-credits feature?

**Comment by hurrgurl** [comment]
Yeah that one.

**Comment by zachbr** [comment]
@hurrgurl do you also have the end disabled?

**Comment by hurrgurl** [comment]
Yep, end-credits disabled, not the world itself. Everything works fine when end credits are enabled.

**Comment by PhanaticD** [comment]
i have tried with and without the end world disabled, did not try the credit settings though

**Comment by zachbr** [comment]
The end credit disable toggle is unrelated to this issue. The issue is that the player is given temporary invulnerability on dimension change, that is then unset when the server receives a packet from the client after the teleport is successful.

When the end is disabled, it's set but the server never receives that teleport success packet because the player never actually switches dimensions. So their invulnerability is never removed. The same thing should occur when the nether is disabled but I haven't checked that case specifically.

**Comment by zachbr** [comment]
It seems safe to only do this when the player goes to the end, so I think we'll try that and see how it goes

**Comment by zachbr** [comment]
Looks like I missed the original end case in that last closing fix. Such is life.
