### ISSUE TITLE
NBT Crash 1.12.2

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#960]
Paper version: git-Paper-1286 (MC: 1.12.2)
Crash report: https://pastebin.com/8HTPHnt7

Mentions something about NBT? Not quite sure why that would lead to a crash though.

**Comment by electronicboy** [comment]
Watchdog reports are pretty useless in most cases, more than likely your issue is due to a lag spike caused by something else and watchdog just happened to stick there, the report indicates that your server is still ticking fine, even if it has gone over the allowed time for a tick. I'd suggest keeping your eyes on timing reports to locate any signs of plugins that are potentially going to cause a spike during events such as players logging out.
