### ISSUE TITLE
Chunks not unloading correctly. 

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#97]
Caused by this commit? https://github.com/PaperMC/Paper/commit/e546c55b6efdd083afd5a9d20f9dd99deec5d32f

I don't think chunks are unloading correctly with Paper 518. I've got 20k chunks loaded, 24k entities, and 27k tiles with a view distance of 10 with only 16 players on. If my calculations are correct, view distance of 10 = 441 chunks per player. So at most, I should only have ~7k chunks loaded?

Downgrading to Paper 502, things are much more reasonable and to expected levels. (~6k chunks loaded) Something is definitely broken in the newer commits. :(

**Comment by aikar** [comment]
found issue. Fixed in build 521

**Comment by ghost** [comment]
Do your chunks unload correctly with Paper 502? I use the 502 build but with 175 players online and view-distance 5 there are 30k chunks loaded (max.: 11 \* 11 \* 175=21175). Will this issue also be fixed with the new commit @aikar ?

Edit: Same with the newest build on my testserver. With view-distance = 10 there are constantly 445-455 chunks loaded. If I'm not wrong that could be at most 441 chunks.

**Comment by aikar** [comment]
521 is fixed. It'll never be exact as chunks constantly load and unload on the edges, as well as spawn chunks.
