### ISSUE TITLE
Custom NMS Entities make server warn on PreCreatureSpawnEvent

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#986]
22.01 00:41:33 [Server] WARN Warning, could not find EntityType for be.isach.ultracosmetics.v1_12_R1.customentities.Pumpling contains: no - Please report this to Paper at https://github.com/PaperMC/Paper/issues
22.01 00:42:02 [Server] WARN Warning, could not find EntityType for be.isach.ultracosmetics.v1_12_R1.customentities.Pumpling contains: no - Please report this to Paper at https://github.com/PaperMC/Paper/issues
22.01 00:42:13 [Server] WARN Warning, could not find EntityType for be.isach.ultracosmetics.v1_12_R1.customentities.CustomSlime contains: no - Please report this to Paper at https://github.com/PaperMC/Paper/issues
22.01 00:42:17 [Server] WARN Warning, could not find EntityType for be.isach.ultracosmetics.v1_12_R1.customentities.RideableSpider contains: no - Please report this to Paper at https://github.com/PaperMC/Paper/issues
22.01 00:42:20 [Server] INFO TPS from last 1m, 5m, 15m: 19.98, 19.98, 19.9
22.01 00:42:23 [Server] WARN Warning, could not find EntityType for be.isach.ultracosmetics.v1_12_R1.customentities.RideableSpider contains: no - Please report this to Paper at https://github.com/PaperMC/Paper/issues
22.01 00:42:40 [Server] WARN Warning, could not find EntityType for be.isach.ultracosmetics.v1_12_R1.customentities.Pumpling contains: no - Please report this to Paper at https://github.com/PaperMC/Paper/issues

Since its asking to report, here it is :)

**Comment by RoboMWM** [comment]
[21:49:35] electroniccat: in part the "report to paper" is also somewhat dumb, because it kinda goes off on the fact that that error can only be triggered if paper/upstream has done something stupid

---
I'd delete this but then the comments regarding this message would seem rather silly or something so uh w/e ¯\\\_(ツ)_/¯

**Comment by electronicboy** [comment]
I'm on the verge of not having a brain, so my comment above might sound a bit discombobulated, looking at ultracosmetics, it looks like they've registered the entities in the server, but not inside bukkit. Think this needs to be resolved by using the servers entity -> type list, maybe falling back to bukkits before screaming

The message itself I'm not entirely fond of, but somewhat potentially spammy in some cases, but not really something we wanna skip.

**Comment by electronicboy** [comment]
Actually looking at this closer, looks like this needs to technically be fixed by the plugin by registering the entities types inside bukkit before registering them inside the server, paper caches the entity type for all entities so that information can be used for the prespawn events (which can be used by plugins to avoid creating entities for them to be immediately removed due to the spawn event being cancelled).

Might wanna speak about the nature of the message, from a message I saw on IRC when I said some things about this issue, I don't believe it should only been shown once, as that could make it easier to miss entities which haven't been registered in the server, some part of me wants to say, once per entity (and should be registered as an unknown entity when that occurs)

nor am I still entirely sure about the event not firing at all in such cases, even if we do suggest to listen to the standard event, there might be cases where listening to the event might be ideal, even if we can't get a proper pick on the entity by using the UNKNOWN entity type.

**Comment by aikar** [comment]
@electronicboy I added that because I wanted to learn what sources trigger this case so we can see if we can improve the patch to support it.

**Comment by aikar** [comment]
code in question: https://github.com/iSach/UltraCosmetics/blob/master/v1_12_R1/src/main/java/be/isach/ultracosmetics/v1_12_R1/customentities/CustomEntities.java#L76

**Comment by aikar** [comment]
Removed the warning in 9b1ada78
