### ISSUE TITLE
TippedArrow cant be detected in PlayerDeathEvent 

### ISSUE THREAD

**Issue by Doc94** [PaperMC/Paper#999]
# issue

###  Timings or Profile link:
https://timings.aikar.co/?id=0ae5b7640a0c4c3385c70a17778c909d

### Description of issue:
i use the PlayerDeathEvent for change messages, and for any reason i cant use the event for get if death its o not by TippedArrow.

The deaths by TippedArrow (for example TippedArrow of INSTANT_DAMAGE) have the cause of MAGIC, but the DamageCause its not instance of EntityDamageByEntityEvent then dont form to know this dead.

In EntityDamageByEntityEvent only check the damages by arrow, the potion effect for arrow its no trigger.

I´m not secure if this its a issue with bukkit/spigot or paper...

### Other helpful links
The same report in spigot (not secure where report...) https://hub.spigotmc.org/jira/browse/SPIGOT-3799

### Paper build number:
Paper version git-Paper-1322 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
Sorry for the delay, however, the issue here is purely down to how arrows work in the server, i.e. magical effects are applied last, and as such are the last cause of damage. Your best option here is going to be to track that information yourself, any fix on our side would break the existing behavior of either the server or the API.
